### ISSUE TITLE
Add limit characters on Wysiwyg

### ISSUE THREAD

**Issue by akididou** [AdvancedCustomFields/acf#1]
Hi, 

Is it possible to add a limit characters on Wysiwyg same as on the text area ?

So very nice job for this plugin ;)

Peace

**Comment by elliotcondon** [comment]
Hi @akididou 

Thanks for the question.
We don't have built in solution for this, but it should be easy enough to customize the tinymce settings.

Here's a thread discussing the tinymce JS to add a character count:
https://amystechnotes.com/2015/05/06/tinymce-add-character-count/

And here's some documentation on how to customize the WYSIWYG field tinymce instance:
https://www.advancedcustomfields.com/resources/adding-custom-javascript-fields/
- scroll down this page to the 'wysiwyg_tinymce_init' action

Good luck!

**Comment by Wheels00** [comment]
+1  i'd love an example of doing this

**Comment by fhauck** [comment]
Here is a solution for a little Word/Character Counter on the WYSIWYG Editor:

Put this in your functions.php:

```
function my_acf_input_admin_footer() {
	
?>
<script type="text/javascript">
(function($) {
	
acf.add_action('wysiwyg_tinymce_init', function( ed, id, mceInit, $field ){
	$('#wp-'+id+'-editor-container .mce-statusbar').append('<div class="acfcounter" style="background-color: #f7f7f7; color: #444; padding: 2px 10px; font-size: 12px; border-top: 1px solid #e5e5e5;"><span class="words" style="font-size: 12px; padding-right: 30px;"></span><span class="chars" style="font-size: 12px;"></span></div>');
	counter = function() {
	    var value = $('#'+id).val();
	
	    if (value.length == 0) {
	        $('#wp-'+id+'-editor-container .mce-statusbar .acfcounter .words').html('Word Count: 0');
	        $('#wp-'+id+'-editor-container .mce-statusbar .acfcounter .chars').html('Characters: 0');
	        return;
	    }
	
	    var regex = /\s+/gi;
	    var wordCount = value.trim().replace(regex, ' ').split(' ').length;
	    var totalChars = value.length;

	    $('#wp-'+id+'-editor-container .mce-statusbar .acfcounter .words').html('Word Count: '+wordCount);
	    $('#wp-'+id+'-editor-container .mce-statusbar .acfcounter .chars').html('Characters: '+totalChars);

	};
	
    $('#wp-'+id+'-editor-container .mce-statusbar .acfcounter .words').html('Word Count: 0');
    $('#wp-'+id+'-editor-container .mce-statusbar .acfcounter .chars').html('Characters: 0');
	        
    $('#'+id).change(counter);
    $('#'+id).keydown(counter);
    $('#'+id).keypress(counter);
    $('#'+id).keyup(counter);
	$('#'+id).blur(counter);
    $('#'+id).focus(counter);

	
});

})(jQuery);	
</script>
<?php
		
}

add_action('acf/input/admin_footer', 'my_acf_input_admin_footer');
```

**Comment by Wayne-FlapJack** [comment]
I ran into an error while running the code above. Here is an improved version of the code.

Key Improvements:
**TinyMCE API:** The counter now uses TinyMCE’s getContent({ format: 'text' }) to properly handle text inside the editor.
**Correct Event Handling:** Using TinyMCE's internal keyup and change events ensures the content is tracked accurately.
**Word Splitting and Character Count:** The word count now filters out empty spaces properly, ensuring an accurate count.

```
function my_acf_input_admin_footer() {
?>
<script type="text/javascript">
(function($) {

    acf.add_action('wysiwyg_tinymce_init', function(ed, id, mceInit, $field) {
        // Append counter to TinyMCE status bar
        var $editorContainer = $('#wp-' + id + '-editor-container .mce-statusbar');
        if ($editorContainer.length > 0 && $editorContainer.find('.acfcounter').length === 0) {
            $editorContainer.append(
                '<div class="acfcounter" style="background-color: #f7f7f7; color: #444; padding: 2px 10px; font-size: 12px; border-top: 1px solid #e5e5e5;">' +
                '<span class="words" style="font-size: 12px; padding-right: 30px;"></span>' +
                '<span class="chars" style="font-size: 12px;"></span>' +
                '</div>'
            );
        }

        // Counter function
        const updateCounter = function() {
            var content = tinymce.get(id).getContent({ format: 'text' }); // Get content as plain text
            var wordCount = content.trim().split(/\s+/).filter(Boolean).length; // Word count
            var totalChars = content.length; // Character count

            // Update the status bar counters
            $editorContainer.find('.acfcounter .words').html('Words: ' + wordCount);
            $editorContainer.find('.acfcounter .chars').html('Characters: ' + totalChars);
        };

        // Trigger counter on initialization and content changes
        updateCounter(); // Initial count
        tinymce.get(id).on('keyup change', updateCounter); // Bind to keyup and change events
    });

})(jQuery);
</script>
<?php
}

add_action('acf/input/admin_footer', 'my_acf_input_admin_footer');
```

**Comment by ShaneMuir** [comment]
> I ran into an error while running the code above. Here is an improved version of the code.
> 
> Key Improvements: **TinyMCE API:** The counter now uses TinyMCE’s getContent({ format: 'text' }) to properly handle text inside the editor. **Correct Event Handling:** Using TinyMCE's internal keyup and change events ensures the content is tracked accurately. **Word Splitting and Character Count:** The word count now filters out empty spaces properly, ensuring an accurate count.
> 
> ```
> function my_acf_input_admin_footer() {
> ?>
> <script type="text/javascript">
> (function($) {
> 
>     acf.add_action('wysiwyg_tinymce_init', function(ed, id, mceInit, $field) {
>         // Append counter to TinyMCE status bar
>         var $editorContainer = $('#wp-' + id + '-editor-container .mce-statusbar');
>         if ($editorContainer.length > 0 && $editorContainer.find('.acfcounter').length === 0) {
>             $editorContainer.append(
>                 '<div class="acfcounter" style="background-color: #f7f7f7; color: #444; padding: 2px 10px; font-size: 12px; border-top: 1px solid #e5e5e5;">' +
>                 '<span class="words" style="font-size: 12px; padding-right: 30px;"></span>' +
>                 '<span class="chars" style="font-size: 12px;"></span>' +
>                 '</div>'
>             );
>         }
> 
>         // Counter function
>         const updateCounter = function() {
>             var content = tinymce.get(id).getContent({ format: 'text' }); // Get content as plain text
>             var wordCount = content.trim().split(/\s+/).filter(Boolean).length; // Word count
>             var totalChars = content.length; // Character count
> 
>             // Update the status bar counters
>             $editorContainer.find('.acfcounter .words').html('Words: ' + wordCount);
>             $editorContainer.find('.acfcounter .chars').html('Characters: ' + totalChars);
>         };
> 
>         // Trigger counter on initialization and content changes
>         updateCounter(); // Initial count
>         tinymce.get(id).on('keyup change', updateCounter); // Bind to keyup and change events
>     });
> 
> })(jQuery);
> </script>
> <?php
> }
> 
> add_action('acf/input/admin_footer', 'my_acf_input_admin_footer');
> ```

Nice one solid solution... I further made some edit as I wanted to implement a limit and stop the cursor going back to the start...

```
function my_acf_input_admin_footer() {
    ?>
    <script type="text/javascript">
        (function($) {

            acf.add_action('wysiwyg_tinymce_init', function(ed, id, mceInit, $field) {
                // Append counter to TinyMCE status bar
                var $editorContainer = $('#wp-' + id + '-editor-container .mce-statusbar');
                if ($editorContainer.length > 0 && $editorContainer.find('.acfcounter').length === 0) {
                    $editorContainer.append(
                        '<div class="acfcounter" style="background-color: #f7f7f7; color: #444; padding: 2px 10px; font-size: 12px; border-top: 1px solid #e5e5e5;">' +
                        '<span class="chars" style="font-size: 12px;"></span>' +
                        '<span class="error-message" style="color: red; font-size: 12px; display: none; margin-left: 10px;">Character Limit Reached!</span>' + // Add error message span
                        '</div>'
                    );
                }

                // Max character limit
                const maxChars = 1000;

                // Counter function
                const updateCounter = function() {
                    let content = tinymce.get(id).getContent({ format: 'html' }); // Get content in HTML format (preserves line breaks)
                    let plainTextContent = content.replace(/<[^>]+>/g, ''); // Remove HTML tags to get plain text

                    let totalChars = plainTextContent.length; // Character count (excluding HTML tags)

                    // Update the status bar counters (showing characters left)
                    let charsLeft = maxChars - totalChars;
                    if (charsLeft < 0) {
                        charsLeft = 0; // Prevent negative value for characters left
                    }
                    $editorContainer.find('.acfcounter .chars').html('Characters Left: ' + charsLeft);

                    // If character count exceeds maxChars
                    if (totalChars > maxChars) {
                        // Show the error message
                        $editorContainer.find('.acfcounter .error-message').show();

                        let limitedContent = plainTextContent.slice(0, maxChars);

                        tinymce.get(id).setContent(limitedContent); // Set the content to the first 1000 characters

                        // Make sure the cursor is at the end of the text
                        let selection = tinymce.get(id).selection.getRng();
                        selection.setStart(selection.endContainer, selection.endContainer.length);
                        tinymce.get(id).selection.setRng(selection);
                    }
                };

                // Trigger counter on initialization and content changes
                updateCounter(); // Initial count
                tinymce.get(id).on('keyup change', updateCounter); // Bind to keyup and change events
            });

        })(jQuery);
    </script>
    <?php
}

add_action('acf/input/admin_footer', 'my_acf_input_admin_footer');
```

I've also gone a little further and made this more dynamic so we can target specific wysiwug as for my use case I just wanted to restrict one wysiwug from the flexible layout system.
