### ISSUE TITLE
Revert PHP export

### ISSUE THREAD

**Issue by ruizfrontend** [AdvancedCustomFields/acf#10]
Hi!
I trusted your advice and moved my acf configuration to a functions.php file.
I still agree that it's a good idea, but I miss a way to edit them again without going through the craziness of manual editing that array.
Have you think of any way to solve this problem?

Thanks

**Comment by elliotcondon** [comment]
Hi @ruizfrontend 

Please make all questions via support tickets here: http://support.advancedcustomfields.com/new-ticket/

This github repo is used for code related issues only.

To answer your question. No, there is no way to edit the PHP registered fields via a wp-admin interface. The reason for using PHP registered fields is to have full programmable control over the fields without any way to edit them via UI.
