### ISSUE TITLE
PHP Warning: undefined index pagenow in login-popup when network-activated

### ISSUE THREAD

**Issue by mcguffin** [AdvancedCustomFields/acf#104]
## Steps to reproduce:
 - WP-Multisite 
 - Network activated ACF
 - Use something different than en_US as an Admin language.
 - Logged into wp-admin 
 - When the please-login window pops up a PHP . (You can either delete user session in the database and wait a few seconds, or just navigate to `http://localhost/wp-login.php?interim-login=1&wp_lang=de_DE` ;) ... )
 - A PHP warning occurs saying: `Notice: Undefined index: pagenow in /path/to/wp/wp-includes/l10n.php on line 141
W `

![image](https://user-images.githubusercontent.com/402988/50054693-c5d53900-0144-11e9-9660-be2d9d3089de.png)

## Cause
 - WP first loads mu- and network-activated plugins, _before_ the $pagenow is set in `wp-includes/vars.php`.
 - ACF calls `__()` during plugin inclusion...
 - ... which calls `determine_locale()` in `wp-includes/l10n.php` at some point ...
 - ... which makes use of the `$GLOBALS['pagenow']` in line 141.

## Core Ticket
There is a ticket on wp core trac on this issue https://core.trac.wordpress.org/ticket/42656, which was closed, saying such problems should be fixed in the plugin (and which I just reopened). 
Not quite sure where this one should fixed...

**Comment by mcguffin** [comment]
Just in case it might be helpful to others: For a temporary workaround see this gist: https://gist.github.com/mcguffin/641dfa2cdff36357e714a21fb045267f

**Comment by elliotcondon** [comment]
@mcguffin Thanks for the bug report. Can you please provide some more info about the following:
"ACF calls __() during plugin inclusion..."

When does this occur?

**Comment by mcguffin** [comment]
@elliotcondon I was referring to this line: https://github.com/AdvancedCustomFields/acf/blob/2de647eff6e641bbf42a21fd38a793b7c259a90e/acf.php#L80

**Comment by elliotcondon** [comment]
Hi @mcguffin 

Thanks for the info. Now I am understanding the full issue.
I will consider changing the ACF core code, but do believe this is a bug in core.

The ticket you linked to is indeed the same issue, but doesn't mention the `__()` function. I suspect that once this is clearly explained, the WP core team will be more interested in fixing the problem.

Would you mind opening a new ticked with WP with a more similar wording to this GitHub issue? I'm sure that ACF is not the only plugin using `__()` within the plugin initialization.

**Comment by mcguffin** [comment]
Hi @elliotcondon 
I was just about to write the ticket when I noticed, that the issue has just been fixed a couple of hours ago in trunk: https://core.trac.wordpress.org/changeset/44317/trunk/src/wp-includes/l10n.php

Anyway, Thank you very much for the response!

**Comment by elliotcondon** [comment]
Hi @mcguffin 

Well that was good timing!
