### ISSUE TITLE
Add Image button click firing multiple times

### ISSUE THREAD

**Issue by webbudesign** [AdvancedCustomFields/acf#109]
Hello, I am using the latest version of ACF and I have a few Image Fields on my custom post type. When I click to Add Image button, I see 3 media uploader windows. I have to close two of them to select one image and apply. I think this is a kind of bug. Can you help me in this case?

**Comment by elliotcondon** [comment]
Hi @webbudesign 

Thanks for the bug report. 

I'm looking forward to testing/fixing this issue, but please note this is not the place for support. 
When possible, can you please open a support ticket here: https://www.advancedcustomfields.com/contact/ with as much information as possible.

Thanks
Elliot
