### ISSUE TITLE
Gutenberg sidebar settings do not display if block selected when opening sidebar

### ISSUE THREAD

**Issue by NewJenk** [AdvancedCustomFields/acf#120]
If block is selected when the sidebar is opened, the settings don't display. You have to click a different block, and then click the block again for the settings to display. Here's a video showing the behaviour: https://www.useloom.com/share/9b8a0c16ecd5475d985267cda78ac6a6

**Comment by NewJenk** [comment]
Great, thanks @elliotcondon. Have you got an eta for 5.8.0?

**Comment by elliotcondon** [comment]
This issue should be solved in 5.8.0-beta4.
Please let me know if you are able to test out the latest beta.
