### ISSUE TITLE
Text field Character Limit should validate like min/max values in number field

### ISSUE THREAD

**Issue by mcguffin** [AdvancedCustomFields/acf#122]
The absence of a validation might lead to some odd behaviour:

Reproduction:
 - Create a text field (no Character Limit so far)
 - Edit a post and enter a long text (like 10 chars) into the field
 - Edit the text field and choose a character limit now. (e.g. 5)
 - Edit the Post again and save it. You won't get an error message event though the character limit is exceeded. (Theoretically the browser should validate against the `maxlenth` attribute, but neither Firefox nor Chrome do)

I'll craft a PR adressing this issue soon.

Kind Regards

**Comment by elliotcondon** [comment]
Hi @mcguffin 

Thanks for the bug report and PR.
I'll add this to my to-do list, perform some testing and add it in :)

**Comment by elliotcondon** [comment]
@mcguffin I've just added this into 5.7.11. Thank again for your help

**Comment by mcguffin** [comment]
@elliotcondon Thanks to you!
