### ISSUE TITLE
Elementor dynamic fields not available in ACF PRO 5.7.11

### ISSUE THREAD

**Issue by gahawkey** [AdvancedCustomFields/acf#126]
Hi Eliot and crew 👋
I noticed following the update from ACF PRO 5.7.10 to 5.7.11 that the ACF field select list in Elementor dynamic fields were no longer populated. Upon downgrading back to 5.7.10 it all worked again straight away. This is also with Elementor Pro 2.4.4.

Working:
![correct-ui](https://user-images.githubusercontent.com/10040554/52611352-f7624a80-2ed0-11e9-9149-f42ce0cab5ba.png)
Not working:
![incorrect-ui](https://user-images.githubusercontent.com/10040554/52611353-f7fae100-2ed0-11e9-8e15-1301f00d324f.png)
Working code:
![correct-code](https://user-images.githubusercontent.com/10040554/52611356-f7fae100-2ed0-11e9-83d5-4ab437892cb1.png)
Not working code:
![incorrect-code](https://user-images.githubusercontent.com/10040554/52611354-f7fae100-2ed0-11e9-8c44-e19aae9632a4.png)

Thanks for all your awesome work guys!

**Comment by elliotcondon** [comment]
Hi @gahawkey 

My apologies for the issues in version 5.7.11.
I am confident we have found and fixed the issue.

Can you please re-download the ACF PRO plugin files and test the issue?

An easy way to re-download is to edit the main acf.php plugin file and change the version number '5.7.11' down to '5.7.10'
- please note the version number appears twice in this file and both will need to be changed
- after this change is made, please update the plugin as per normal and it will update to 5.7.11 (including the new fix)

**Comment by gahawkey** [comment]
Thanks @elliotcondon 

Sorry I haven't replied sooner! My bad.

I just found this again when searching for a solution to the exact same problem again recently. I'm running ACF Pro 5.8.1 on WP 5.2.2 with Elementor 2.5.16 and Elementor Pro 2.5.11 (all the latest versions). 

Not sure what's changed, but Robey was finding the same issue too. (Welcome to QLD by the way!)

Cheers.
Grant

**Comment by elliotcondon** [comment]
Hi @gahawkey 

Thanks mate. Sorry to hear the issue has crept back up. Whilst I unpack and re-assemble the office here, can you please get in touch with the Elementor developers and ask them about the issue?

Keep me posted.
