### ISSUE TITLE
Wrong maxlength validation in text field and textarea

### ISSUE THREAD

**Issue by pinheiroalexandre2** [AdvancedCustomFields/acf#128]
Hello, 

I've just upgraded my websites to the latest version of ACF pro and detected a bug in the max length verification. 

I have this text: `Golegã. Ministério Público pensou "acusar" Igreja` (with 49 chars) and one field with
`maxlenth=50` but the validation fails on `class-acf-field-text.php:180` (the same happens on
`class-acf-field-textarea.php:212`). 

I think there were two errors in this function: 

1. count maxlength with special characters quoted 
2. use strlen with UTF-8 chars . 

You can see this behavior in attached screenshot. 
![screenshot from 2019-02-12 12-16-59](https://user-images.githubusercontent.com/3235813/52635611-389f2e00-2ec2-11e9-9a7a-342dab24b304.png)

Best regards, 
Alexandre Pinheiro

**Comment by elliotcondon** [comment]
Hi @pinheiroalexandre2 

Thanks for the bug report and info.
I've just performed some testing and believe I have found a fix.
Can you please edit the code in question and change `strlen()` to `mb_strlen()`.
This change should correctly count special characters.

**Comment by pinheiroalexandre2** [comment]
Problem solved! 
thank you :)
