### ISSUE TITLE
editor role not able to save html tags in multisite since acf pro 5.7.8

### ISSUE THREAD

**Issue by matthiaswagnerwy** [AdvancedCustomFields/acf#130]
hy elliot,

i just ran into an issue where html-tags were stripped from textarea fields in a multisite environment. i could test it with the editor and super-admin role, where the issue only appeared for the editor. in the acf pro changelog i found the following line for the 5.7.8 version:

> Fix - Fixed vulnerability allowing author role to save unfiltered HTML values.

after switching back to 5.7.7 the issue disappeared in my environment. i could also reproduce it in two different multisite installations.

could it be that something has gone weird for multisite with version 5.7.8? i tried newer versions in a single site and was able to save html tags in the textarea field there with an editor role.

thanks for your feedback and great work,
matt

**Comment by elliotcondon** [comment]
@matthiaswagnerwy 

Thanks for the question.

The issue you are experiencing is most likely related to the changelog item you have referenced.
When working on a multisite, only network admins have the "unfiltered_html" capability:
https://codex.wordpress.org/Roles_and_Capabilities#unfiltered_html

If you wish for your admins or other user roles to save HTML, please look into role modification to add the "unfiltered_html" capability to your users.

**Comment by matthiaswagnerwy** [comment]
hy ellitot, thank you for your quick response. i was not aware of that capability :)
