### ISSUE TITLE
if parent page use this template

### ISSUE THREAD

**Issue by aftarfadilah** [AdvancedCustomFields/acf#131]
- [x] Feature Request

I think it will be helpful if I can apply acf to child pages that use **this** template for the parent page so I don't need to apply the template to every child pages but instead just apply it once on the parent.

**Comment by elliotcondon** [comment]
@aftarfadilah 

Thanks for the feature request.
It should be quite easy to create a "Child of template" location rule, but we won't be able to action this for some time.

For now, please consider creating such a location rule for yourself:
https://www.advancedcustomfields.com/resources/custom-location-rules/
