### ISSUE TITLE
Is there an acction that is triggered when a field's value is changed?

### ISSUE THREAD

**Issue by wujekbogdan** [AdvancedCustomFields/acf#135]
I'm looking at [actions section](https://www.advancedcustomfields.com/resources/javascript-api/#actions) in the docs, I see there are several actions there related to field's "lifecycle": `prepare_field `, `ready_field`, `load_field`, `append_field `, `remove_field`, but none of these seem to be triggered when a value of a field is changed.

I'd like to read the EXIF data from an image field after its value is changed. In the old version of ACF I used to do it using the `acf.add_action('change')` filter, so I expected to find `field_change` action in the documentation, but such an action doesn't exist.

Is there any way to do it in the new version of ACF?

---
**UPDATE**

OK, I found it:

``` javascript
const field = acf.getField('field_56d99d7de115e');
field.on('change', 'input', (e) => {
    // Do something
});
```

BTW, it's weird that `.on` event requires the second parameter which is a selector. IMO the event should be raised when a value of the model is changed, no matter what the HTML structure of the rendered field is. We can always access DOM using the `field.$el` reference.

**Comment by elliotcondon** [comment]
@wujekbogdan 

Thanks for the question and updated info.
Similar to the [jQuery on function](http://api.jquery.com/on/), the `Field.on()` function applies the event listener to the "field element", not the "input element". This is why the second parameter is needed to specify the "selector".

**Comment by wujekbogdan** [comment]
Thanks. Got it.

How about adding `field_change` action? Is there any reason why such an action does not exist?

**Comment by elliotcondon** [comment]
I decided to remove the "change_field" action for performance reasons.

Having this action meant needing to perform extra jQuery selecting during the editing of a post which I deemed unnecessary.

I'm happy to consider adding this back in, but would like to push for jQuery to be used instead.

**Comment by wujekbogdan** [comment]
Thanks for the explanation, let's close this ticket then.
