### ISSUE TITLE
[docs] Document model.getValue() method

### ISSUE THREAD

**Issue by wujekbogdan** [AdvancedCustomFields/acf#136]
I was trying to get the value of a field when it's value is changed.

I did:

``` javascript
const myField = acf.getField('field_key');

myField.on('change', 'input', () => {
    const value = myField.$el.find('input').val();
});
```

But I didn't like the idea that I have a model but I still need DOM traversing to get the value. It simpy seemed wrong. So I started to dig into the source code and found that there's a undocumented  `.getValue()` method, so I can do the following:

``` javascript
const myField = acf.getField('field_key');

myField.on('change', 'input', () => {
    const value = fields.image.getValue();
});
```

Which is much more elegant solution.

What is the reason why this method is not documented? Is it just an oversight, or is it an internal method that's not a part of the official API?

**Comment by elliotcondon** [comment]
@wujekbogdan 

Thanks for the question.

The `Field.on()` function privides similar functionality to the `jQuery.on()` function but with some extra sugar on top.

The callback function will receive 2 parameters:
1. The event object
2. The jQuery element that triggered the event.

So, you can do something like this:
```
const myField = acf.getField('field_key');

myField.on('change', 'input', ( e, $el ) => {
    const value = $el.val()
});
```

**Comment by wujekbogdan** [comment]
@wujekbogdan 

Thanks for the answer. the `fields.image.getValue()` the method still seems more appropriate to me because relying on model sounds better than relying on DOM. Can I use it safely? It's not documented, so I'm afraid it might change in the future.

**Comment by elliotcondon** [comment]
@wujekbogdan 

Good point. Using the field's api is always a better idea than relying on jQuery / selectors.

Yes, the `Field.getValue()` function is safe, but there is a better function.

Please instead use `Field.val()` to load the val.
This function will call either getValue() or setValue() depending on if you provided a parameter :)

**Comment by wujekbogdan** [comment]
Thanks.
