### ISSUE TITLE
Gallery Field

### ISSUE THREAD

**Issue by glauberm** [AdvancedCustomFields/acf#138]
As I understand it, the `gallery` field is a pro-only feature now, right? I think [this page](https://www.advancedcustomfields.com/resources/gallery/) should be removed then, as is misleading.

**Comment by elliotcondon** [comment]
@glauberm Thanks. I think these documentation pages require a note that this is a premium feature.

**Comment by glauberm** [comment]
Let me know if there's anything I can do to help.
