### ISSUE TITLE
ACF 5.8.0-beta3 Custom Gutenberg Icons?

### ISSUE THREAD

**Issue by mitchkramez** [AdvancedCustomFields/acf#142]
More of a question here, but I'm finding "dashicons" incredibly limiting for icon usage. The Gut docs refer to being able to specify an svg path for a custom icon, but that doesn't appear to translate to the `acf_register_block`. Are there plans to support custom Icons, or am I overlooking something relatively simple here?

I did run across this in the forums regarding this, but I wonder if this is the preferred approach? https://support.advancedcustomfields.com/forums/topic/gutenberg-block-custom-svg-icon-not-displaying/

Thanks!

**Comment by elliotcondon** [comment]
Hi @mitchkramez 

Good news. I have recently added support for custom HTML SVG in the 'icon' setting.
This will be included in the enxt beta version 5.8.0-beta4 due for release in the next few days!
