### ISSUE TITLE
ACF 5.8.0-beta4: Link field without value saving as "false"

### ISSUE THREAD

**Issue by NewJenk** [AdvancedCustomFields/acf#147]
When saving an ACF Gutenberg block with a link field with no value, a URL value of http://false is added.

**Comment by elliotcondon** [comment]
Hi @NewJenk 

Interesting. I'll test it out.

**Comment by elliotcondon** [comment]
Just found and fixed the issue :)

**Comment by NewJenk** [comment]
@elliotcondon, thanks for fixing. When can we expect beta 5?

**Comment by elliotcondon** [comment]
Aiming for today!
