### ISSUE TITLE
Code Standards

### ISSUE THREAD

**Issue by GaryJones** [AdvancedCustomFields/acf#15]
As you may be aware, [WordPress core now mostly conforms to WPCS](https://make.wordpress.org/core/2017/11/30/wordpress-php-now-mostly-conforms-to-wordpress-coding-standards/) (with an ongoing project to address the remaining violations), so getting prominent plugins to adhere to them as well not only helps the authors and contributors of those plugins, but ensures that the community as a whole benefits from code following the same code style conventions and best practices.

Would there be any interest in adding code standards checking for this repo? [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) plus [WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards)?

I'd propose to add:
- an `.editorconfig` file ([example](https://github.com/GaryJones/plugin-boilerplate/blob/f067080a02c3c411769a75b2c21aa4f3d613f581/.editorconfig)) so supporting IDEs follow the basics code style consistently.
- a basic `composer.json` so that [dependencies are explicitly declared and isolated](https://12factor.net/dependencies) via the `require-dev` section ([example](https://github.com/GaryJones/plugin-boilerplate/blob/f067080a02c3c411769a75b2c21aa4f3d613f581/composer.json#L37-L47), though this includes extra dependencies not needed for this repo); PHPCS, WPCS, PHPCompatibility and VariableAnalysis packages.
- a `.phpcs.xml.dist` file ([example](https://github.com/GaryJones/plugin-boilerplate/blob/f067080a02c3c411769a75b2c21aa4f3d613f581/phpcs.xml.dist) though this would be customised for ACF) so that checks are run consistently and easily.

Initially, there will be lots of CS violations (warnings and errors), and these can be addressed over time, or through a concerted effort to fix groups of files. Later, exclusions could be added to the config file, or at the per-line level, though adding exclusions typically means not conforming in the long term.

The benefit of fixing the low-level stuff (typically whitespace or optional braces, missing periods in documentation and comments, etc.), is that more important issues are easier to see (output not escaped, deprecated functions being used, syntax used that doesn't match up with lowest supported version of PHP etc.)

If there is interest, then I'm happy to do the PR for the above proposed items (not the actual CS fixes, initially).

**Comment by elliotcondon** [comment]
Hi Gary

Thanks for the topic.
In short, yes, this is definitely something that I am interested in.

I have already begun work on "standardizing" the ACF plugin code after some conversations with WP VIP this year. I made some good progress, but still have much to do.

Leave this with me for 2018 and I'll continue to pick away at the code. 

Thanks
Elliot

**Comment by lgladdy** [comment]
Closing this legacy issue.

We've made huge steps towards WPCS code standards in the last couple of minor releases, and will continue to do so as we modify and write new code.

**Comment by GaryJones** [comment]
Are development files held on a branch that is not `master`, or elsewhere?

Looking at https://github.com/AdvancedCustomFields/acf I see no `.editorconfig`, no `composer.json` with which to define development dependencies, and no `.phpcs.xml.dist` to define the coding standard.

The lack of these in this repo / branch make it harder for folks to contribute.

There are a bunch of other items I would expect to see for a WordPress plugin that was allowing contributions as well. See https://github.com/Parsely/wp-parsely/ for some examples.
