### ISSUE TITLE
Repeater fields added to top level

### ISSUE THREAD

**Issue by guillaumepn** [AdvancedCustomFields/acf#154]
Whenever I add a Repeater field to a field group, any subfields in the repeater is moved to top level of the field group after saving :

![image](https://user-images.githubusercontent.com/10799586/54528086-28281a80-497c-11e9-8d5d-2613dffc0a00.png)

and after saving :  

![image](https://user-images.githubusercontent.com/10799586/54528101-32e2af80-497c-11e9-8ca4-35b05024a3bf.png)

and the repeater field is empty :  

![image](https://user-images.githubusercontent.com/10799586/54528113-468e1600-497c-11e9-9a75-742d2bc90915.png)

Thanks for your help

**Comment by elliotcondon** [comment]
Hi @guillaumepn 

This suggests there is a conflict somewhere preventing/modifying the "parent" value for each field.
Perhaps you have a plugin installed that is modifying the post.post_parent value?

If it's not too much to ask, can you please spin up a fresh WP site in "Local by Flywheel" and try to replicate the issue?
Please keep the default theme active and edit the functions.php file with any extra logic needed.​

​​If you can replicate the issue, please export the site (from flywheel app, right click the site and click "export") and attach to your next reply.
​I'll import this and get to work replicating / testing the issue :)

**Comment by guillaumepn** [comment]
Sorry for the late reply, the project I was working on had an old ACF Pro version, updating the plugin solved the problem

**Comment by elliotcondon** [comment]
Thanks for the reply, glad to hear things are working!
