### ISSUE TITLE
5.8.0-beta4 preview not updating when switching between edit mode

### ISSUE THREAD

**Issue by leeroyrose** [AdvancedCustomFields/acf#166]
I have created a simple block with a text field, which is being registered and rendered using the following code:

```add_action('acf/init', function() {
  acf_register_block([
    'name' => 'block-editing',
    'title' => 'Test',
    'render_callback' => function($data) {
      echo get_field('test_block_editing');
    },
  ]);
});
```

When I add the block, add some text: 

<img width="278" alt="click edit" src="https://user-images.githubusercontent.com/3706842/55194431-8dacb000-51a1-11e9-96e6-16ac1be1f469.png">

Toggle edit mode and change the text: 

<img width="305" alt="Screenshot 2019-03-28 at 21 33 37" src="https://user-images.githubusercontent.com/3706842/55194468-b16ff600-51a1-11e9-8e9e-45f460dd844c.png">

switching back to preview mode does not trigger the update:

<img width="279" alt="Screenshot 2019-03-28 at 21 33 42" src="https://user-images.githubusercontent.com/3706842/55194483-b9c83100-51a1-11e9-81b1-4bb6a97fe5fc.png">

However, it does update in the settings panel on the right. If I update the text there, the preview updates as expected.

<img width="279" alt="Screenshot 2019-03-28 at 21 33 53" src="https://user-images.githubusercontent.com/3706842/55194533-e67c4880-51a1-11e9-9cb6-e8ce85fa157f.png">

<img width="219" alt="Screenshot 2019-03-28 at 21 33 57" src="https://user-images.githubusercontent.com/3706842/55194538-ea0fcf80-51a1-11e9-8b46-e3fc613d80da.png">

Am I doing something wrong?

**Comment by elliotcondon** [comment]
Hi @leeroyrose 

This issue should be fixed in 5.8.0-beta4.1.
Can you please update and let me know if this solves the issue?

**Comment by leeroyrose** [comment]
Hi @elliotcondon 

Yep that fixes it - I didn't realise there was an update! Thanks for your help

**Comment by leeroyrose** [comment]
I have just noticed that using the "Move up" & "Move down" arrows are not triggering the ajax preview request either. Should I open a new ticket for that?

**Comment by leeroyrose** [comment]
Hi @elliotcondon 

For our specific use case of ACF blocks, we render each preview in an iframe that is populated with html and stylesheet and script links. This is due to certain limitations of the asset build we have in place. Because of this, when react mounts/unmounts the preview element from the dom, the dynamic content in the iframe disappears. What I need to work around this is a way to trigger the preview ajax for a particular block. Is there any possibility of an action being added somewhere that can facilitate this? It would have to be on a block by block basis.

**Comment by elliotcondon** [comment]
@leeroyrose 

Good question. I have anticipated such a scenario, and built in an action that you can use.
Please us the JS action "render_block_preview" to update the block element after its component has changed (remounted, etc).

```
acf.addAction('render_block_preview', function( $el, props ){
    
});
```

Let me know if this helps.

**Comment by leeroyrose** [comment]
Hey @elliotcondon 

That is certainly handy, I found that loading the iframe content using javascript caused too many problems, so I changed the approach and it's playing nicely. Thanks for your help!
