### ISSUE TITLE
Button to prefill on the counterpart of relations

### ISSUE THREAD

**Issue by pretzlaw** [AdvancedCustomFields/acf#167]
Currently it is possible to setup relations, custom links and custom buttons.
But there is no thing like an action/button that prefills the fields it is pointed to.
Please add a button type that allows to configure values for all the fields on the other side.

Example:

* Edit the fields of the "doctors" post type 
* Add a new field
* Type ist "Prefill button"
* Name this button "Add feedback"
* Set the related post type to "feedbacks"
* The fields of the others post type occur (e.g. Date, Doctor, Text)
* Enter `{{ ID }}` in the field for "Doctor"
* Save and edit a doctor

Now there should be a button named "Add feedback" in the "doctors" edit screen.
Clicking on it creates a new "feedback". But the field "doctor" (of the post-type "feedback") already has the correct value.

Also please think of more fields besides `{{ ID }}` like `{{ address.ID }}` to access data of related post types too. Example: The doctor has an "address" (as separate post-type) and clicking "Write letter" transports the address ID into the correct field of the "letter" post-type.

**Comment by elliotcondon** [comment]
Hi @pretzlaw 

Thanks for the feedback. This sounds a tad too complex to make it into the core plugin, but perhaps is something you would like to investigate as an add-on?

**Comment by pretzlaw** [comment]
We would just do it without open an issue if we would have the developer and the skill to do so.

What exactly is complex about a string that replaces "template-vars" with actual values?
And adding value=... to your already existing input templates prefilled with what comes via $_GET (secured via nonce) ?
We hoped that ACF is modular and extensible enough to have this covered.

**Comment by elliotcondon** [comment]
Hi @pretzlaw 

Thanks for the reply. I'm finding it difficult to understand your last reply. Can you please be sure to clearly explain your points, and include relevant screenshots/code examples to help.

**Comment by pretzlaw** [comment]
This was total theory without any code references. Are you the developer of ACF? 

Imagine a doctor post-type and an appointment post-type. The appointment has a reference-field to the doctor. The goal is that "post-new.php?post_type=appointment&doc=123" will prefill the doctor field with the doc 123.

Would that be possible?

Also there is already a thing like a button. Place it in the edit-screen of the doctor post-type named "Add appointment". The button points to the URL "post-new.php?post_type=appointment&doc={{ ID }}" . But ACF is clever: When the button is rendered it replaces the placeholder with the actual ID of the doctor.

This is the easy one. Also possible, right?

This would be the beginning. Afterwards there could be "{{ doctor.ID }}" for a "Create invoice" button in the edit screen of the appointment because ... well, you surely see where this can go.

**Comment by elliotcondon** [comment]
Hi @pretzlaw 

> Imagine a doctor post-type and an appointment post-type. The appointment has a reference-field to the doctor. The goal is that "post-new.php?post_type=appointment&doc=123" will prefill the doctor field with the doc 123.

Yes, this would be possible by hooking into the [acf/load_value](https://www.advancedcustomfields.com/resources/acf-load_value/) filter. This filter allows you to customize the value of a field. In this filter callback, you could look at the `$_GET` parameters sent and return that custom value.

> Also there is already a thing like a button. Place it in the edit-screen of the doctor post-type named "Add appointment". The button points to the URL "post-new.php?post_type=appointment&doc={{ ID }}" . But ACF is clever: When the button is rendered it replaces the placeholder with the actual ID of the doctor.

The button field allows you to select a value, similar to the radio input field. This is not a field type for actually "clicking" and navigating to a URL.

If you wish to customize the admin edit screen with extra HTML, I suggest hooking into the "acf/render_field" action and adding this HTML after/before a specific field.

Another idea would be to add a WP metabox with your custom HTML.

Good luck!

**Comment by pretzlaw** [comment]
And now imagine this build in into ACF so that ACF together with WordPress becomes a very mighty tool for creating intranet communication, crms, simple data management and more. But you insist  that we should get lost with this. Okay. Bye.
