### ISSUE TITLE
Auto-update children number on duplicate

### ISSUE THREAD

**Issue by jimmyadaro** [AdvancedCustomFields/acf#169]
When the user duplicates any field, ACF detects that field has a consecutive numeral as label and name, and then sums _1_ to the previous number. That's great, and I guess we all love it.  

But if that field has any children with the same consecutive naming (`level_3`,`level_4`...), like _repeaters_ or _groups_, those **sub-fields will keep the previous parent number**. 

It would be great to auto-detect the consecutive numbers in the same way for the sub-fields.

**Comment by elliotcondon** [comment]
Hi @jimmyadaro 

Thanks for the support and idea!
Would you mind putting together some screenshots to demonstrate this scenario?

**Comment by jimmyadaro** [comment]
@elliotcondon Sure thing! Here is the field group with the first level with a group inside of it:

![Field group Level 1](https://i.imgur.com/gx4yVj3.png)

After duplicate that field group, here's the automatic update, where the children elements of the group keep the number from the original that was duplicated from.

![Field group Level 2 after duplicate](https://i.imgur.com/7f63CRg.png)

**Comment by elliotcondon** [comment]
Thanks @jimmyadaro 

This makes it much easier to understand.

Do you normally name your sub fields using a prefix of the parent?
This is not something that we recommend, as the meta_key saved into your DB would become "level_1_x_level_1_image".

We recommend that you leave your sub field named "image" and then allow the meta_key to be saved as "level_1_x_image".

**Comment by jimmyadaro** [comment]
Oh, okay, I understand what you're talking about. That seems fair to me!
