### ISSUE TITLE
Add local json folder to wp_uploads_dir()

### ISSUE THREAD

**Issue by inetbiz** [AdvancedCustomFields/acf#17]
Just create a folder within wp_uploads and that should solve everyone's problem with setting local json folder to save & load json files.

**Comment by elliotcondon** [comment]
Hi @inetbiz 

What is the issue everyone is having with the local json feature?
Please note this github repo is for code related bug reports only, not feature requests or support.

**Comment by inetbiz** [comment]
@elliotcondon alright. I have a support ticket opened as customer. I had googled it. Several hits to unable to make it work. Adding it into the core and in the uploads dir would solve alot.

**Comment by elliotcondon** [comment]
Hi @inetbiz 

Thanks for the reply. Just to confirm, did you open a support ticket or a forum topic?
I would like to know more about this issue, but will require you to submit a full support ticket with a clearer explanation of the issue.

**Comment by inetbiz** [comment]
@elliotcondon "James replied. Sent him my file.

**Comment by elliotcondon** [comment]
Awesome, thanks.
