### ISSUE TITLE
ACF 5.8 RC2 Bugs and Feature Requests.

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#170]
Hi Elliot,

This is continuation from https://github.com/AdvancedCustomFields/acf/issues/159 Sorry for the delay, the past 2.5 weeks I've been out of town with a family emergency... going home tomorrow...

Summary:

Bugs (and fixed bugs):
1. Advenced CSS
2. Columns - Duplication issues - did not exist in beta3
3. Save twice - some blocks like sections - HAPPENS ONLY IN EDIT MODE ! - did not exist in beta3
4. defaults work only after changing a value. - Fixed (Hooray!)

Feature Requests: (non show stopping if these won't happen)
5. Inner Blocks - Using tiny and shortcodes instead 
6. Reusable inspector settings - to be auto. displayed on all blocks, ACF or not.

I'm sure my summary notes mean very little to you, so I have a detailed video explaining all my issues, suggestion... https://www.youtube.com/watch?v=S0f-jOxnw74&feature=youtu.be

Thanks again !!!

**Comment by nick6352683** [comment]
I have some supplementation info for issue #3 from above (getting not saved message).

- It does happen only if you edit a text or numeric fields. The message does NOT show up when making changes to WYSIWYG, select, color etc... fields.

- Another way to avoid the message while in edit, change to preview and back to edit mode and then save. This is besides the other 2 ways to avoid it as I described in the video - save the page twice, or save the page while the edited block is in preview mode, and not in edit mode.

- A last way to avoid this of course to use the auto mode for the blocks. This sounded awesome initially, but  while testing blocks with many settings, font sizes, colors, font-awesome, adding shadows, etc... creates a more time wasting and frustrating environment, as you have to constantly change modes from edit to preview just to see and precisely adjust your settings. The auto mode would be perfect for simple blocks like you have in your RC2 blog video, but for blocks with many settings, the auto mode is cumbersome at best.

Thanks, let ,e know if you want me to create a very short (2 minute video) describing any of the new supplemental information I just provided you.

Thanks as usual,
Nick.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the issue report and video recording.
I've got this on my to-do and will be in touch with my findings.

Feel free to create another short video for the new info, that would be great :)

**Comment by nick6352683** [comment]
Will do tomorrow... thanks.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Just checking in on this ticket.

I've made some progress with issue 2 (Columns - Duplication issues).
This is now fixed, and I will include in the next release.

I'm not sure that I understood your issues 1 and 3. Can you please provide some more detail about how to replicate these issues?

**Comment by nick6352683** [comment]
Sorry for the delay, I had to do further testing to definitely give you precise answer.

1. This one is easy to explain...  On the right side, in the inspector, the very last tab, Gutenberg inserts the "Advanced" tab, where inside it there is a text box labeled "Additional CSS Class". This by default exists for all blocks, ACF or not. With our ACF blocks, thanks to you we can turn this off, but when on, whatever CSS class we put there, it does not work. The CSS class name is not displayed on the front end.

3. It took me 2-3 days to fully figure this out... Not Saving Message issue. This does not happen with beta 3, but surfaced with RC1, and still exists with RC2. This is how to replicate.

- This happens ONLY with Text fields, that I know of. I'm positive that it does not happen with the color picker filed, or a select field etc... (not sure about the TextArea field...).
- If you edit a Text field, and immediately click on the update button to update the post, and then click on the view to see the post, you will get the message. Even though Gutenberg will let you know that things are not saved, if you view the page, your changes are actually saved, so it's a false alarm. 
- How to avoid it. After editing a Text field, click on another field or another block or even a white area on the screen, in other words clicking yourself out of the text field, and then save the post. 

I hope things are more clear now, otherwise I can make 2 VERY short videos.
I'm ecstatic that the Duplication issue inside the Gut, columns got fixed. Thanks again Elliot, and I can't wait for ACF 5.8...

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the reply.

1. Advanced CSS. This setting is working well, and the value for custom class is found in the `$block['className']` property. Please see the documentation on this page for a working example: https://www.advancedcustomfields.com/resources/blocks/

2. This is called an "Unload Prompt" and the issue will be fixed in the 5.8 full release :)

**Comment by nick6352683** [comment]
Aha ! I had missed that page entirely, and I was also assuming that Gutenberg or ACF would automatically create a div around my block with the custom class name (issue number 1). 

I'm also glad that the "unload Prompt" issue will be fixed too, it was driving me nuts!

I was initially surprised that the Blocks would be included in the free version, but i totally understand why it will included in the Pro version only. As an unlimited licence owner, it's almost not a big issue for me. 

Thanks a million Elliot.
