### ISSUE TITLE
5.8.0-RC2 Gutenberg blocks edit occurs within the block now instead of the sidebar

### ISSUE THREAD

**Issue by mitchkramez** [AdvancedCustomFields/acf#176]
Elliott,
We just updated to the RC2, and we're seeing that the editing tools moved from the sidebar to the blocks themselves making it a little less visual, albeit with more room to breathe. Is there a way to configure this behavior so the edit stays in the sidebar for live updating?

**Comment by elliotcondon** [comment]
Hi @mitchkramez 

In RC2 we changed the default "mode" from "preview" to "auto".
You can set this back to "preview" when registering the block, and I'm also open to your feedback on which should be the default mode.

**Comment by mitchkramez** [comment]
Ah - that makes sense, just didn't see any documentation on it. I think it's fine, but it was surprising! Thanks!
