### ISSUE TITLE
Anchor field data is not saved - ACF 5.8 RC2

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#177]
Two things:

1. I created a test block, and successfully managed to activate the anchor for it with the "support" parameter. The anchor field is displayed for the block, I can insert a value in the anchor field, but when I  view the post and go back in the editor, the anchor field is blank. I know you had said that in beta 4 the anchor was working, but it seems that in my case with RC 2, it is not.

2. I can't find any docs on this on your site - how do we get the anchor name? I know for the custom Class Name it is $block['className'], but I have no idea how to get the anchor. and since I can't save the data in the anchor field, I can't test it for $block['anchorName'], or $block['anchor'], etc...

Note: The anchor is not a big deal for me, it would be nice if it works, that's all.
Thanks,
Nick.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the questions. This issue has recently been fixed:
https://github.com/elliotcondon/acf/issues/768

You can find an example of how to load the "anchor" value here:
https://www.advancedcustomfields.com/resources/blocks/

**Comment by nick6352683** [comment]
Thanks again !

**Comment by willrowe** [comment]
Is #567 related to what you are describing?

**Comment by isagomezgalvez-hub** [comment]
Hi Willrowe, yes It is the same, 
thank you

**Comment by hannahmwool** [comment]
Hey, Also experiencing this in the last few days with WP5.9 and ACF Pro 5.11.4

**Comment by lgladdy** [comment]
@hannahmwool This issue has been resolved in ACF 5.12-RC1 which is available in your account.

We're aiming to have the final release out this week.
