### ISSUE TITLE
ACF 5.8-RC2: Enqueue Assets are loading only in footer

### ISSUE THREAD

**Issue by carfis** [AdvancedCustomFields/acf#178]
Hi Elliot,

I'm using the new `$settings` variable `enqueue_assets` from `acf_register_block()`.
And there isn't possible to enqueue css or js in the `<head>`. Always the css and script are placed in the footer.

Here is the code:
```php
'enqueue_assets'  => function() {
	wp_enqueue_style(
		'block-slick',
		FUNCTIONALITY_URL . 'css/slick.css',
		array(),
		FUNCTIONALITY_VERSION
	);
	wp_enqueue_script(
		'block-slick',
		FUNCTIONALITY_URL . 'js/lib/slick.min.js',
		array( 'jquery' ),
		FUNCTIONALITY_VERSION,
		true
	);
},
```
The `$in_footer` variable doesn't work in the `wp_enqueue_script` function
`wp_enqueue_script( $handle, $src = '', $deps = array(), $ver = false, $in_footer = false )`

I tried the `'enqueue_style'   => FUNCTIONALITY_URL . 'css/slick.css',`
and the css is placed on the footer as well.

Carlos

**Comment by elliotcondon** [comment]
Hi @carfis 

Thanks for the question. Yes, the `enqueue_assets` callback is called during the rendering of your block type. This is how ACF is able to enqueue only when your block type exists on the page.

This is a different story to the back-end, which can enqueue all block styles during the "enqueue_block_editor_assets" action.

I hope this info helps answer your question. In short, it is not possible for the `enqueue_assets` callback to run during the `<head>` tag. To do this, I suggest using the `wp_enqueue_style()` outside of the `enqueue_assets` setting.

**Comment by carfis** [comment]
Hi Elliot,

Thanks for the aswer. I will use the `wp_enqueue_style()` outsite of the enqueue_assets.

**Comment by isaumya** [comment]
Hey @elliotcondon,
Can you share an example code of how you are suggesting to handle the situation? I didn't get what you mean by do it outside enque_assets.

If you could share an example code of doing this, that would be really helpful.

Cause the enqueue_assets is a key of the array. What do you mean by calling outside it? I'm just confused reading your reply. An example code snippet would be really helpful. Thanks.

**Comment by elliotcondon** [comment]
Hi @isaumya 

Absolutely. It's quite easy to enqueue scripts & styles in WordPress. For reference, please read over the [Including CSS & JavaScript](https://developer.wordpress.org/themes/basics/including-css-javascript/) documentation found on the WordPress.org website.

An example snippet that will enqueue a style in both the admin and front-end could look like this:
```php
<?php
function add_theme_scripts() {
  wp_enqueue_style( 'slider', get_template_directory_uri() . '/css/slider.css', array(), '1.1');
}
add_action( 'wp_enqueue_scripts', 'add_theme_scripts' );
add_action( 'admin_enqueue_scripts', 'add_theme_scripts' );
```

**Comment by isaumya** [comment]
Thanks a ton @elliotcondon for the further explanation. I totally misunderstood your first reply thinking you are asking to load the `wp_enqueue_style()` without `wp_enqueue_scripts` action in some special way.

BTW, I think the above snippet can be further optimized to ensure the script only loaded when the block is present in the content by loading it the following way:

```php
/**
 * Register the styles (CSS) for the blocks outside
 * acf_register_block_type() as loading styles
 * using acf_register_block_type() will load the
 * styles in the footer and not in <head> causing
 * CLS issues 
 */
add_action( 'wp_enqueue_scripts', 'register_acf_block_styles' );
add_action( 'admin_enqueue_scripts', 'register_acf_block_styles' );

function register_acf_block_styles() : void {
  if( has_block( 'acf/some-custom-block' ) ) {
    wp_enqueue_style( 'block-some-custom-block', get_theme_file_uri( 'path/to/the/css/file.min.css' ), array(), wp_get_theme()?->get( 'Version' ) );
  }
}
```

Thanks again for your response on this. 🙏
