### ISSUE TITLE
ACF 5.8-RC2: Side option not working for position

### ISSUE THREAD

**Issue by Jorenm** [AdvancedCustomFields/acf#180]
After updating from 5.8 beta3 my ACF block fields are replacing the block contents when editing. Setting the position to "side" has no effect.

**Comment by Jorenm** [comment]
I tried installing RC1 and that also ignores the position setting, but renders to the side.

**Comment by elliotcondon** [comment]
Hi @Jorenm 

Please review the `acf_register_block_type()` documentation and take a look at the "mode" setting.
As for 5.8.0-beta2, this setting defaults to "auto". You may wish to set this to "preview".
https://www.advancedcustomfields.com/resources/acf_register_block_type/

**Comment by Jorenm** [comment]
This looks like what I needed. What is the position setting in the field editor meant to do?

**Comment by elliotcondon** [comment]
This setting defines the metabox position in the "classic editor".

Now that we are transitioning to a "block based editor", I will be reviewing the old field group settings during the year :)
