### ISSUE TITLE
ACF 5.7.13: Field changes aren't shown after clicking "Preview changes"

### ISSUE THREAD

**Issue by mattdinthehouse** [AdvancedCustomFields/acf#184]
If I make changes to ACF fields when editing a Page and click "Preview Changes" I'd expect to see those changes reflected on the frontend but that's not happening.

I had a look over how Wordpress handles previews and it hooks into 'the_preview' to replace only the post_title, post_content, post_excerpt, post_format taxonomy, and thumbnail_id meta.

ACF doesn't hook into 'the_preview' and WP doesn't change the post's ID to the revision's meaning ACF seems to be fetching data for the post and not the revision when previewing changes.

**Comment by elliotcondon** [comment]
Hi @mattdinthehouse 

Thanks for the bug report.
I'll close this ticket in favor of an existing one here:
https://github.com/AdvancedCustomFields/acf/issues/186

I'll perform some testing with "previews" in Gutenberg during the week and will be in touch :)
