### ISSUE TITLE
Extending Core Gutenberg Blocks with ACF?

### ISSUE THREAD

**Issue by mathewjordan** [AdvancedCustomFields/acf#185]
Hey @elliotcondon,

I am hoping to be able to add an ACF field to the core Columns block. My goal would be a an array of options that allowed users to set a styling options that might control column widths, bordering options or background colors. This is just one example.

Perhaps there is a feature in place that already does this so please let me know if so. If not, is there any plan to do so?

**Comment by elliotcondon** [comment]
Hi @mathewjordan 

Thanks for the question, but unfortunately, this is not possible with the ACF plugin.
