### ISSUE TITLE
Inner Blocks... a different direction...

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#188]
Hi Elliot,

This is in case you did not know already:

 WPBakery has a Gutenberg module. Basically it gets a whole instance of Gutenberg editor, and just the editor part, not including the inspector sidebar and the rest..., and inserts it in a WPBakery Column.

Maybe, one solution for ACF is to do something similar. Just like we have the WYSIWYG field, we can have a Gutenberg field, and around that field, we can build our containers and sections, etc... Right now I'm doing something similar, where I include a WYSIWYG field, and use the editor's toolbar to generate the shortcodes. Even though not ideal, it works for me, as all of my 40+ ACF Blocks are conversions from existing shortcodes.

This is how WPBakery handles Gutenberg:  
https://www.youtube.com/watch?v=CExmpgrg31U&feature=youtu.be

On the other hand, by the time we (you) can figure this thing out, Gutenberg could have a solution for containers, as they started the "Group" block, but it's not very good, and many features are still missing. It took them more than a year to make the "Columns" block usable, and it still has some important features missing compared to most page builders...

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the link. This is an interesting implementation of the Gutenberg editor within an existing interface, but this will not be possible within an ACF block.

We'll be investigating innerBlocks during the year, but would like to first focus on some other "non gutenberg" sides of our plugin :)

**Comment by nick6352683** [comment]
Thanks Elliot.
