### ISSUE TITLE
5.8.1 - Breaks "seamless" style

### ISSUE THREAD

**Issue by nomadpete** [AdvancedCustomFields/acf#193]
It seems the latest update has broken the styling for "seamless" - everything appears in metaboxes whatever the setting.

**Comment by elliotcondon** [comment]
Hi @nomadpete 

Can you please let me know if this issue appears in the Classic or Gutenberg edit screen.

**Comment by nomadpete** [comment]
Yep sorry, forgot to specify.

This is in Classic editor, using the latest WP.

**Comment by elliotcondon** [comment]
Thanks. I'll perform some testing and will be in touch.

**Comment by christophery** [comment]
This issue also seems to effect the Gutenberg edit screen as-well.

**ACF Pro 5.8**
![Screen Shot 2019-06-13 at 10 23 47 AM](https://user-images.githubusercontent.com/1683361/59441005-e0bbf980-8dc5-11e9-8717-e3b8aea1a39c.png)

**ACF Pro 5.8.1**
![Screen Shot 2019-06-13 at 10 24 37 AM](https://user-images.githubusercontent.com/1683361/59441023-e87b9e00-8dc5-11e9-8a89-7e1857013d6b.png)

**Comment by elliotcondon** [comment]
Hi @christophery 

Thanks for the screenshot. This looks like it was taken from the Gutenberg editor, which makes sense. In our latest release, we removed the "seamless" styling from the Gutenberg editor due to styling conflicts / UX issues.
