### ISSUE TITLE
Feature request: Show private fields when WP-DEBUG is true.

### ISSUE THREAD

**Issue by MarcZijderveld** [AdvancedCustomFields/acf#204]
Would it be an idea to show acf-fields in the backend when the wp-debug flag in the wp-config is set to true, even if the "private" field is set to true in the .json file. This way we can hide the fields on acceptance and production sites for our clients but still use the flexibility of the field editor in local development. Can provide a pull request if requested!

**Comment by elliotcondon** [comment]
Hi @MarcZijderveld 

Thanks for the email,
Elliot here - ACF dev​​​.

I like the idea behind this request, but am not sure that using the `WP_DEBUG` constant should be used like this.

I agree that on most local/dev sites, the WP_DEBUG constant is set to true, however, this constant is specific in it's nature; To show debugging errors/information.

Can you help me better understand the scenario where you are creating "private" .json field groups, but wan't them available for "sync" in the local site?

**Comment by MarcZijderveld** [comment]
Hi @elliotcondon,

Thanks for the quick reply!
I can't disagree with your philosophy regarding the WP_DEBUG constant, thus we also included a way to set a new constant through a filter as proposed in the pull request my colleague @menno-ll has made.

We sync ACF fields in local dev environments during development of new projects, but also while maintaining older projects that require new features or tweaks. In our experience opening up the ACF fields on a production environment to clients and developers gives them unwanted control of content that we purposely setup a specific way. The .json field groups are leading as they are a part of our theme in GitHub, removing them from the database for more control. If they are visible on production sites and someone syncs them, the database becomes leading. From that moment on, you need to sync the fields on production every time for every change made in the json files, which is an unwanted situation. That's why we would like to only hide field groups on production environments, but have them visible locally.

**Comment by elliotcondon** [comment]
Thanks for the reply.

This is a great explanation of when that filter/functionality is needed. I wonder if there is a way to add this in using the current filters...

So there is a filter called "acf/load_field_group" which you can use to hook in and customize each `$field_group` array. In theory, you should be able to hook into this and modify the `$field_group['local']` setting when on a dev environment. For example:
```
// Only run on dev environment.
if( is_dev() ) {
	add_filter('acf/load_field_group', function( $field_group ){
		
		// Remove the private setting on all field groups.
		unset( $field_group['private'] );
		return $field_group;
	});
}
```

Note: The code above is untested, but should work in theory :)
