### ISSUE TITLE
Polish translation 5.8.2

### ISSUE THREAD

**Issue by tomektomczuk** [AdvancedCustomFields/acf#206]
"Minimalna liczba wierszy" is duplicated. Second line should be "Maksymalna liczba wierszy".
<img width="1646" alt="Screenshot 2019-07-28 at 12 53 06" src="https://user-images.githubusercontent.com/40096666/62005656-ad93b680-b136-11e9-9923-b4b8eb6c80e9.png">

**Comment by elliotcondon** [comment]
Hi @tomektomczuk 

Thanks for the bug report. Can you please let me know which setting this is for?

**Comment by tomektomczuk** [comment]
all of them Elliot

**Comment by elliotcondon** [comment]
Hi @tomektomczuk 

Thanks for the reply. Now I understand. I've fixed the issue and will include in the next release :)
