### ISSUE TITLE
Feature Request: Serving Gutenberg Templates

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#208]
Hi Elliot,

Many page builders have the ability to install pre-made blocks and pre-made pages, sections etc... This feature is now starting to appear in some of the Gutenberg block bundles, like Kadence blocks as an example. When you select to insert a Kadence row for example, you have the choice to select how many columns, or select a pre-made block/page... my guess is that these are simple reusable blocks, stored in json format. So, I'm going to TRY to convince you that this is something ACF needs desperately.

If not out of line, (and I'm almost certain I'm exactly on the line by now), I have 2 suggestions of how to approach this.

1. Have a new ACF Field type, call it Templates, etc..., and have one crucial setting in it... a url of a folder. In this folder, somewhere on the internet, or locally in a plugin or theme, we can store our json files, and with the same json filenames, their corresponding thumbnail images.

2. Again, have a new ACF Field type, and make it a repeatable field, where we can set the json and thumbnail locations per row... 

I prefer the first option with the folder solution, (less work in setting the templates).

Once things are setup, we should have a new ACF block called Templates, etc..., where it will load the premaid templates (json files with the thumbnail images), so we can choose which one to load into the Gutenberg editor. 

Right now the only way for us to do it, is to manually have our customers import the reusable blocks into their websites. Automating things, will make things more professional and much easier to constantly push new templates...

I'm sure you are shaking your head on this one already... sorry!
Nick.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the topic. Premade templates/parts/blocks are definitely an important piece of the "block editing" puzzle. 

The team behind [Envato Elements](https://wordpress.org/plugins/envato-elements/) are doing a great job in this space.

I'm definitely interested in allowing ACF Blocks to work with premade content, but am not sure I understand the workflow you described. Perhaps instead of focusing on the "technical side" of how it would work, let's talk about how a typical user would use it.

For example, a user creates a page/post, and clicks the "+" button to add a new block. The block selector popup appears, and then...

**Comment by nick6352683** [comment]
... "For example, a user creates a page/post, and clicks the "+" button to add a new block. The block selector popup appears, and then..."...,

You would select an ACF created block called "Templates, etc...", and select one to insert it in the page. These templates can be complete pages or parts of a page (a mere collection of blocks), obviously stored in json format that we can easily make with Gutenberg - called Reusable Blocks...

Check this video how Kadence blocks does this very nicely.

https://www.youtube.com/watch?v=G7_EizOAOYs&feature=youtu.be

Once you understand what I'm proposing, we can discuss the technical stuff again...

Thanks a million Elliot.

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the reply, screen-recoding and info.

I'm a big fan of what Kadence blocks and Elementor are doing with pre-made content. This solves a number of issues from onboarding new clients to helping users add more exciting content to their websites.

I believe that the need for these "layouts" transcends any single plugin such as ACF, and as such, don't believe this is something we will look into at the moment.

I'm curious to hear if WP or any other developers are creating a "block library" or "template library" for use across any site...

**Comment by nick6352683** [comment]
Hi Elliot,

I had to try, knowing that most probably you would not go for it... maybe sometime further down the line...

WP (the core) is building a "block library", but this is not what we are talking about here. This is going to be strictly a block library and not a template/content directory. For example when inserting a new blog in a page, and search for a "slider" block to insert, and if your website has not registered a slider block, it will then automatically search in this block directory and if a slider block is found, it will display it as a result of the search. Now, if you click to insert the slider block, Gutenberg will automatically download, install, activate and insert the slider block into the page you are editing. Needless to say that the block directory will be for individual blocks, and not a whole library of them like Kadence, etc... In the hands of a responsive person, this can be time saving, but in the hands of an idiot (mainly my customers), this might blow up the website,... I can see my customers searching and downloading 300+ blocks with this... The other thing that worries me a bit, is the quality and the number of similar blocks in this directory, similar to the plugins directory. For example, probably when all is said and done, we could end up with 20 slider blocks, some good and some rubbish. We will have to figure out, which slider is good to use, and which is a total waste of time. I am almost certain, in Gutenberg we won't be able to see reviews, update frequency, number of installations, etc..., to help us out to decide which one to use...

ACF has 2-3 good competitors right now in terms of building blocks without React, and the rest of the garbage, and the competition will only increase in numbers and quality with time. Having the ability to also serve content (templates/reusable blocks), would keep all the others light years behind... I'm sure sooner or later somebody is going to make a tool for us theme/plugin developers to use to easily push our content to our customers...

Once again,
Thanks for everything Elliot.

**Comment by elliotcondon** [comment]
Thanks @nick6352683 

I'm loving your energy behind this idea, and agree with you fully.

This is a solid idea, but it is also a BIG idea. One thing we have not touched on is the reality of maintaining a template library for ACF Blocks.

Not only would this require some infrastructure to the core plugin, but the templates themselves would need to be designed, built and tested to run on all popular themes.

This would require too much work, and steer ACF's roadmap away from its core ideals.

For now, I would like to focus on core ACF development, and allow WP to pave the path for Gutenberg, instead of the other way around :)
