### ISSUE TITLE
Field groups can be saved with empty order

### ISSUE THREAD

**Issue by jmstopper** [AdvancedCustomFields/acf#209]
WordPress: 5.2.2
ACF Pro: 5.8.2
Theme: Twenty Nineteen

When using local-json, It is possible to save a field group with an empty string for order. When this happens, the empty order takes precedence over field groups with any integer for order. This results in an inability to hide default WordPress inputs.

**Comment by elliotcondon** [comment]
Hi @jmstopper 

Thanks for the bug report.

I'm not sure I fully understand the issue yet, so could you please attach some screenshots / .json files to help me replicate the problem?

**Comment by jmstopper** [comment]
Hey Elliot

Turns out it was a little more nuanced than I originally thought. I cant attach JSON files so have renamed them as txt files. It could just be my thought on what should happen, but field group group_5d487a4827529 with an order of 0, which has been told to hide the_content field doesn't apply because field group group_5d487d603a6ef with an empty order is selected as the first field group applied to that context.

Environment
- WP 5.2.2
- ACF 5.8.2
- Classic Editor installed and active with the classic editor option selected

Steps
1. Create field group 1 - call it "Order - A"
2. Set Order No to be empty
3. Save the field group
4. The JSON file associated with field group a should be saved with a menu_order of ""
5. Create field group 2 - call it "Order - B"
6. Set Order No to be 0 (the default value)
7. Hide the content editor
8. Save the field group
9 The JSON file associated with field group b should be saved with a menu_order of 0

In theory, if it works out the same for you as it has for me, the field group A "hide on screen" settings are applied. For me it's confusing but maybe this is expected. 

What made it confusing maybe is that when editing the field groups again, the file saved with an empty order is shown with an order of 0. If the menu order was validated as an integer, and set to 0 before saving, the loading of "hide on screen" settings would make more sense.

Happy to jump on a Skype call if that makes it easier...

[group_5d487a4827529.txt](https://github.com/AdvancedCustomFields/acf/files/3469376/group_5d487a4827529.txt)
[group_5d487d603a6ef.txt](https://github.com/AdvancedCustomFields/acf/files/3469377/group_5d487d603a6ef.txt)

**Comment by jmstopper** [comment]
https://github.com/AdvancedCustomFields/acf/blob/f745d197118d1396a45084ddad6299abdf78d72d/includes/acf-field-group-functions.php#L517

If you cast $field_group['menu_order'] as an integer when integer its no longer possible to save a field group with an empty menu_order

**Comment by elliotcondon** [comment]
Hi @jmstopper 

Thanks for your patience whilst I got around to this issue.
I've just performed some testing and can confirm the problem has now been fixed :)

I'll include this fix in the next release.
