### ISSUE TITLE
CodeMirror Syntax Highlighting Wordpress Core

### ISSUE THREAD

**Issue by mediengestalter2** [AdvancedCustomFields/acf#21]
Hey there,

would be very nice to implement the new Wordpress Core Editor for WYSIWYG-Fields.
CodeMirror was implemented with Wordpress 4.9

Is that a plan?

**Comment by elliotcondon** [comment]
Hi @mediengestalter2 

Thanks for the request.
The WYSIWYG field received an update in ACF5 to correctly match the native editor.

Having the 'Visual / Text' tabs will allow for HTML editing, but this is not integrated with CodeMirror.

Thanks
Elliot
