### ISSUE TITLE
acf_form() argument 'uploader' always outputting the basic uploader

### ISSUE THREAD

**Issue by abetoots** [AdvancedCustomFields/acf#213]
### Steps to Reproduce 
*Notes: 
- acf_form_head(); is called correctly and before get_header()

1.  acf_form() was working initially
```
$id = get_current_user_id();
$author_id = 'user_' . $id;
$key= 'some key';

acf_form(array(
                        'post_id'                   => $author_id,
                        'field_groups'              => array($key),
                        'form_attributes'           => array(
                            'class'     => 'Edit__form'
                        ),
                    ));
```
2.  I tried experimenting with supplying argument of 'uploader' => 'basic'
3. Tried reverting back by removing uploader argument , it still outputs the basic uploader
4. Explicitly passing 'uploader' => 'wp' does not work either
5. All ACF uploader buttons are now basic, even those not being output by acf_form()
6. Strangely, only the admin's acf uploader buttons are still handled by wp media uploader. All other roles I have now have basic uploaders, acf_form() or not;

Any ideas?

**Comment by elliotcondon** [comment]
Hi @abetoots 

Thanks for the email,
Elliot here - ACF dev​​​.

This is expected behavior, as the "wp" uploader requires certain user privileges to operate. The WP media library will only be enqueued if the current user condition `current_user_can('upload_files')` is met.

**Comment by abetoots** [comment]
@elliotcondon that makes sense, thanks for clarifying.
