### ISSUE TITLE
ACF block disappears from editor view after editing

### ISSUE THREAD

**Issue by ooksanen** [AdvancedCustomFields/acf#214]
I have (relatively) a simple ACF block that displays an image slider (Slick slider) based on a Post Object field. Everything works nicely when I first insert the block, but if I click the block open for editing and then click outside the block to exit editing, the block disappears from editor view. It will be visible again on page reload though.

Getting following error in console:
TypeError: "e.$slides is null" (react-dom.min.fa9ca8c8.js:117:150)

WP 5.2.2
ACF Pro 5.8.3
Gutenberg 6.3.0

**Comment by elliotcondon** [comment]
Hi @ooksanen 

The issue here is that your block's HTML is most likely hidden (via JS or CSS).
Please inspect the block DOM elements to confirm.

Your error suggest that there is a JS related problem. Please confirm that your HTML contains the correct markup from your slickslider.

**Comment by ooksanen** [comment]
Thanks for your quick reply @elliotcondon !

Yep, some sort of JS problem definitely, but doesn't seem like a problem with Slick, the block template or related files to me. The whole dom tree goes empty from (and including) `div.acf-block-component.acf-block-body` down as soon as the block loses focus.

I think I'll do some more debugging in the morning.

**Comment by ooksanen** [comment]
Just realized you had written a blog post on creating a Slick slider block! The problem I had was missing `window.acf.addAction( 'render_block_preview/type=slider', initializeBlock );`

So if someone is struggling with a similar problem, check out Elliots great post on the subject at https://www.advancedcustomfields.com/blog/building-a-custom-slider-block-in-30-minutes-with-acf/
