### ISSUE TITLE
acf_register_block() parameter icon is mandatory

### ISSUE THREAD

**Issue by crtl** [AdvancedCustomFields/acf#215]
After updating the Gutenberg plugin to 6.3.0 blocks were not working in Gutenberg anymore but still recognized by acf.

ACF Version: 5.8.3
Gutenberg Version: 6.3.0

The js console displays:
```
The icon passed is invalid. The icon should be a string, an element, a function, or an object following the specifications documented in (url to docs)
```

The error can be fixed by providing an `icon` option to `acf_register_block()`.

**Comment by elliotcondon** [comment]
Hi @crtl 

Thanks for the bug report. It sounds like some changes in the Gutenberg block API are tripping over the default icon value for an ACF block.

I'll perform some testing with this and will be in touch shortly.

**Comment by elliotcondon** [comment]
Thanks again for the bug report. I've just patched the issue and will include in the next release.
Duplicate: https://github.com/AdvancedCustomFields/acf/issues/202
