### ISSUE TITLE
enqueue_assets and alternative no longer work

### ISSUE THREAD

**Issue by jfreed295** [AdvancedCustomFields/acf#221]
Apologies in advance if this isn't an issue. My experience in this area is limited.

When registering a block, I'm using enqueue_style. In the editor on the backend, the css file is loaded and applied correctly. On the frontend, the css file is never loaded. This issue applies to enqueue_script and enqueue_assets as well. I've attempted to get this working in the current version of WordPress as well as a few of the previous ones with no success.

From what I can tell, acf_enqueue_block_type_assets() is called when rendering the backend but not the frontend. If I'm understanding it correctly, the register_block_type() function call inside of acf_register_block_type() never uses the acf_rendered_block() callback function, so the assets are never enqueued.

I assume my understanding is incorrect, but I can't tell if I'm making a mistake or if this is a bug. The following is an example of the code I'm using:

```php
add_action('acf/init', 'my_register_blocks');
function my_register_blocks() {

    if( function_exists('acf_register_block_type') ) {

        acf_register_block_type(array(
            'name'              => 'test-name',
            'title'             => __( 'Test Title' ),
            'description'       => __( 'A custom test block.' ),
            'render_template'   => get_template_directory() . '/blocks/test_name/test_name.php',
            'enqueue_style'     => get_template_directory_uri() . '/blocks/test_name/test_name.css',
            'category'          => 'formatting',
        ));
    }
}
```

As a side question, is there a difference between enqueuing the styles in the acf_register_block_type() function versus enqueuing the styles directly after calling acf_register_block_type()?

**Comment by elliotcondon** [comment]
Hi @jfreed295 

Each time the block is rendered on the front end, the `acf_render_block()` callback is called, which then calls`acf_enqueue_block_type_assets()`. This function thenenqueues your styles and scripts.

If you are experiencing any issues, can you please spin up a fresh WP site in "Local by Flywheel" and try to replicate the issue? Please keep the default theme active and edit the functions.php file with any extra logic needed.​

​​If you can replicate the issue, please export the site (from flywheel app, right click the site and click "export") and attach to your next reply. ​I'll import this and get to work replicating / testing the issue :)

**Comment by jfreed295** [comment]
Nevermind. I followed your suggestion and spun up a new site with the default theme, and it worked just fine. I eventually figured out that the wp_footer() call had somehow gotten removed from my theme's footer.php file. Adding it back in fixed the issue. Sorry for the inconvenience.
