### ISSUE TITLE
Stop limiting `$block['keywords']` to only three items

### ISSUE THREAD

**Issue by hacknug** [AdvancedCustomFields/acf#227]
Gutenberg's core used to limit the number of keywords to three and, to prevent JS issues with that, you were slicing `$block['keywords']` to only get the first three items.

This limitation doesn't exist anymore and should be removed so things work as expected. Lines 190–192 in `pro/blocks.php`.

**Comment by elliotcondon** [comment]
Hi @hacknug 

Thanks for the topic.
Do you know which version of WP introduced the change?

**Comment by hacknug** [comment]
It was [this PR](https://github.com/WordPress/gutenberg/pull/13848) which was assigned to the 5.1 milestone.

**Comment by elliotcondon** [comment]
Thanks @hacknug 

I'll add this to my to-do list.

**Comment by elliotcondon** [comment]
@hacknug I have implemented a fix for this issue and will include it in the next release.
