### ISSUE TITLE
Select input automatically converted to text

### ISSUE THREAD

**Issue by lewebsimple** [AdvancedCustomFields/acf#229]
I'm having a strange bug when modifying an existing select field : the field type is automatically set to "text" when loading the field settings.

~~Upon investigation, it seems the culprit is `acf_walk_select_input` incorrectly setting the value in the 2nd level `optgroup` options.~~

This is very annoying when editing large field groups, please fix !

**Comment by elliotcondon** [comment]
Hi @lewebsimple 

Thanks for the email,
Elliot here - ACF dev​​​.

Is this occurring when editing the first field within a group in combination with Firefox 69.0?
If so, please take a look over this thread + solution: https://github.com/AdvancedCustomFields/acf/issues/219
