### ISSUE TITLE
acf acf/load_field/key=field_5d9a14bff4145  filter not working

### ISSUE THREAD

**Issue by iranimij** [AdvancedCustomFields/acf#232]
in functions.php

  `var_dump(has_filter('acf/load_field/name=field_5d9a14bff4145'));` ==> return false
     

      add_filter('acf/load_field/key=field_5d9a14bff4145', function ($field) {

	$field['choices'] = array(
		'custom' => 'My Custom Choice'
	);

	return $field;
       

});
![Screenshot_2019-10-13 Edit Field Group ‹ My Great Blog — WordPress](https://user-images.githubusercontent.com/31434218/66717330-b6666100-ede4-11e9-9252-6bfa10a0428c.png)
this  filter in functions.php not working  and wordpress not defined this filter , i have this field key in acf menu

**Comment by elliotcondon** [comment]
Hi @iranimij 

Were you able to figure this out?
