### ISSUE TITLE
conflict in load_json and load/field hooks

### ISSUE THREAD

**Issue by iranimij** [AdvancedCustomFields/acf#233]
i use load json and read all field from json
when i want to create custom choices for my checkboxes, in the theme option page , show choices from json file and in acf admin page, show my custom choices created by acf/load/field ,
can i show my custom choices that created by acf/load/field in theme option ?

**Comment by elliotcondon** [comment]
Hi @iranimij 

Thanks for your questions, but I'm finding your wording difficult to understand.
Can you please attach some screenshots and a more descriptive explanation of the issue?
