### ISSUE TITLE
how to use acf/load_field dynamically

### ISSUE THREAD

**Issue by iranimij** [AdvancedCustomFields/acf#235]
for using this filter we have two ways : 
1_using this filter in plugin : 
we have a custom taxonomy that we want to use it in filter . 
because our taxonomy should be registered with init action (init action run after loading plugins)
so we have no access to custom taxonomy . what should we do for both using this filter in plugin and access to custom taxonomy? 

2_ using this filter in functions.php
in this case filter works . But only in ACF admin .filter add taxonomies to choice field of ACF admin,while we want to use our taxonomies in type of checkbox fields in our custom theme options,

How can I do it?

**Comment by elliotcondon** [comment]
Hi @iranimij 

The "acf/load_field" filter is applied each time a field is loaded from the database. There are a few different times when a field is loaded, but the most common are when editing a post, or when loading a value.

In theory, both of these events should occur after the "init" action. Can you help me understand why the "acf/load_field" filter is being triggered earlier?

I'm quite confused about your other questions here. I suspect they are related to your other GitHub issues. Please don't open up any more issues - let's discuss them here using comments.

The English barrier is making this a little difficult for me, so to help, can you please take some screenshots to help identify the problem. Perhaps you can annotate what in the screenshot is wrong, and what you would like to change.

**Comment by iranimij** [comment]
using this filter in theme functions.php when parent theme is active : 
![1](https://user-images.githubusercontent.com/31434218/66800455-10207580-ef22-11e9-8461-b190f29c705b.jpg)

in theme option we don't see any changes : 
where parent theme or child theme is active 
![2](https://user-images.githubusercontent.com/31434218/66800501-3b0ac980-ef22-11e9-8229-c2d749121bde.jpg)

and in acf admin (where parent theme is active) 
![3](https://user-images.githubusercontent.com/31434218/66800641-d13eef80-ef22-11e9-81a7-5b1c43401216.jpg)

and in acf admin (when child theme is active ) : 
![4](https://user-images.githubusercontent.com/31434218/66800696-16fbb800-ef23-11e9-9445-1684d1613586.jpg)

i wants to : 
1_show this filter results in my theme option that created by ACF when child theme and parent theme is active.
2_show this filter results in ACF admin when child theme is active

this is problem occur when we use this filter in functions.php

**Comment by iranimij** [comment]
when we use this filter in plugin : 
![11](https://user-images.githubusercontent.com/31434218/66801261-57f4cc00-ef25-11e9-92d1-b02292c8d95d.jpg)

we don't have any response in both of ACF admin and theme option
![33](https://user-images.githubusercontent.com/31434218/66801433-ea956b00-ef25-11e9-8e37-df91e84ef9eb.jpg)

![44](https://user-images.githubusercontent.com/31434218/66801449-f6812d00-ef25-11e9-8cf3-f2aecffcc58f.jpg)


because : 
![22](https://user-images.githubusercontent.com/31434218/66801499-23cddb00-ef26-11e9-8bd5-141970b00ba4.jpg)

and my taxonomy registered in init action in function.php

when i set a test value for this filter

![55](https://user-images.githubusercontent.com/31434218/66801815-4f9d9080-ef27-11e9-9591-28c3de67b66a.jpg)

we have response for both ACF admin and theme option

**Comment by elliotcondon** [comment]
Hi @iranimij 

Thanks for the screenshots, these are great.

It sounds like the "acf/load_field" filter is being run before the "init" action (where your taxonomy is registered). I'm not sure why this is happening. There should be no need for the field to be loaded so early.

Is it possible that you have some code in your theme/plugin that is loading field values earlier than the "init" action?

Try adding some debugging code to both your "Register taxonomy code" and also the "add_listing_default_cities_options" function. In what order do the functions get called?

**Comment by iranimij** [comment]
> 
> 
> Hi @iranimij
> 
> Thanks for the screenshots, these are great.
> 
> It sounds like the "acf/load_field" filter is being run before the "init" action (where your taxonomy is registered). I'm not sure why this is happening. There should be no need for the field to be loaded so early.
> 
> Is it possible that you have some code in your theme/plugin that is loading field values earlier than the "init" action?
> 
> Try adding some debugging code to both your "Register taxonomy code" and also the "add_listing_default_cities_options" function. In what order do the functions get called?

This is for the case where the code is in the plugin. 
What do you think about when the code is in functions.php?

**Comment by elliotcondon** [comment]
Hi @iranimij 

Plugins are loaded before the theme functions.php file.

In theory, there should be no difference unless one of your plugins is loading a field value before the "init" action.

You mentioned that "this is the case". Can you please be more descriptive?

**Comment by iranimij** [comment]
> 
> 
> Hi @iranimij
> 
> Plugins are loaded before the theme functions.php file.
> 
> In theory, there should be no difference unless one of your plugins is loading a field value before the "init" action.
> 
> You mentioned that "this is the case". Can you please be more descriptive?

problem resolved by using acf/prepare_field filter . tnx

**Comment by marcwieland95** [comment]
Amazing. Using `acf/prepare_field` instead of `acf/load_field` also solved my issue immediately

**Comment by andrewreal** [comment]
Using `acf/prepare_field` also fixed an issue I had where `acf/load_field` was not being fired on the Options Edit screen in admin.

@elliotcondon This thread took me a while to find, it would be really useful to add a link or mention of this on the documentation at https://www.advancedcustomfields.com/resources/dynamically-populate-a-select-fields-choices/
