### ISSUE TITLE
Function acf_get_form() doesn't return data

### ISSUE THREAD

**Issue by ovdienko** [AdvancedCustomFields/acf#237]
Function is a wrapper for acf()->form_front->get_form( $id ). But acf_get_form() hasn't return.

It is:

function acf_get_form( $id = '' ) {
	acf()->form_front->get_form( $id );
}

It should be:

function acf_get_form( $id = '' ) {
	return acf()->form_front->get_form( $id );
}

**Comment by elliotcondon** [comment]
Thanks @ovdienko 

I'll have this fixed in the next version.
