### ISSUE TITLE
Error loading in Customizer with ACF Pro

### ISSUE THREAD

**Issue by khanhtd1108** [AdvancedCustomFields/acf#24]
I use ACF Pro to create some form for widgets and when go to Customizer screen, the page still keep loading infinitely.
Can you fix this soon?

**Comment by elliotcondon** [comment]
Hi @khanhtd1108 

Please submit a support ticket with a full description of the issue including screenshots, steps to replicate and any other relevant information:
http://support.advancedcustomfields.com/new-ticket/

Thanks
Elliot
