### ISSUE TITLE
Breaking ACF block editor styles since 5.8.6

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#241]
Hey Elliot,

after updating to ACF 5.8.6 the ACF field styles are broken inside the block editor sidebar like this example:

<img width="345" alt="Bildschirmfoto 2019-10-26 um 16 14 31" src="https://user-images.githubusercontent.com/31563167/67620851-b5cdc180-f80b-11e9-8690-b86d7043af00.png">

Currently the margin around the fields breaks the design. Do you can confirm this?

This issue comes from `margin: 0 -16px -16px;` of the following style block:

```
.acf-block-panel .acf-block-fields {
    border: none;
    border-top: #e2e4e7 solid 1px;
    margin: 0 -16px -16px;
    padding: 0;
}
```

**Comment by elliotcondon** [comment]
@CreativeDive 

Thanks for the bug report. We haven't made any specific CSS changes in 5.8.6 but I'll be sure to investigate this today. Perhaps the style changes are from a newer version of WP/Gutenberg?

**Comment by CreativeDive** [comment]
@elliotcondon maybe, I've tested with Gutenberg 6.7.0.

**Comment by elliotcondon** [comment]
@CreativeDive - I've just tested out the latest WP 5.3-RC2, but was unable to replicate the issue.

**Comment by CreativeDive** [comment]
@elliotcondon You are sure? I've tested again with Gutenberg 6.8 RC1 + WP 5.3 RC2 + ACF 5.8.6 + Twenty Nineteen Theme.

![Oct-29-2019 08-30-05](https://user-images.githubusercontent.com/31563167/67746231-5c8daa00-fa26-11e9-8905-0c7b1017de82.gif)

It does not look good. Very strange, where is the mistake?

**Comment by elliotcondon** [comment]
Perhaps the issue is specific to the fields. Can you please share with me an export of your field group? I'll add this to a block and test it out.

**Comment by CreativeDive** [comment]
@elliotcondon ... ok, now more information about this issue. This happens to all of my field groups.

CASE 1: WP 5.3 RC2 + ACF 5.8.6 + Twenty Nineteen Theme
--> Everything looks good.

CASE 2: Gutenberg 6.8 RC1 Plugin + WP 5.3 RC2 + ACF 5.8.6 + Twenty Nineteen Theme
--> Field design is broken.

This is solving the issue for me:

![Oct-29-2019 09-14-38](https://user-images.githubusercontent.com/31563167/67749286-230c6d00-fa2d-11e9-8396-65ba6be2e131.gif)

So, please test with the installed Gutenberg plugin. But I don't know which of both cases is the release case :-/

**Comment by elliotcondon** [comment]
Thanks @CreativeDive 

Looks like the Gutenberg plugin is introducing some different styling into the admin.
I'll have a look into this as either it will affect the 5.3 release, or a future one.

**Comment by eballeste** [comment]
confirming the negative margins are affecting the panels since I installed 6.8.0, was using the core version before that.

**Comment by elliotcondon** [comment]
The good new is that I can confirm this CSS issue does not yet exist in the latest WP 5.3-RC4 build.
Looks to be isolated to the Gutenberg plugin, which may introduce itself into the next minor version of WordPress. I'll keep an eye out for this, but will leave it for now.

**Comment by eballeste** [comment]
makes total sense, for now I'm setting the `mode` parameter to `auto` so that it can go into edit mode when a user clicks on an acf-block. Now I'm not relying on the sidebar, especially if it's hidden

**Comment by roryashfordbentley** [comment]
I'm seeing the same issue in the sidebar running WP 5.4.1 and ACF 5.8.9. I'm not using the Gutenberg plugin its using the native WP gutenberg.

A short term fix is to enque a stylesheet for the backend:

```
wp_enqueue_style('my-gutenberg-admin-css', get_stylesheet_directory_uri() . '/gutenberg.css', array(), '1.0.0');
```
That contains the following:
```
.acf-block-panel .acf-block-fields {
    margin: 0 !important;
}
```

**Comment by elliotcondon** [comment]
Hi @roryashfordbentley 

Thanks for the comment. I'm not seeing this "margin" CSS issue on our local sites. Can you please attach some screenshots to demonstrate the issue?

**Comment by roryashfordbentley** [comment]
Hey Elliot, thanks for the reply! I'm happy to report that its actually working correctly in 5.8.9, I must have goofed while updating from 5.8.8 via composer yesterday and didn't actually update. It looks perfect now in 5.8.9 :)
