### ISSUE TITLE
BUG: Google Maps not refreshing map after map marker was changed in block editor

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#242]
Hey Elliot,

tested with ACF 5.8.6. If I use the google maps field inside a ACF block, the map doesn't refresh after map marker was changed. In other cases outside the block editor, this is working well.

Currently the only way to refresh the map after changing the map marker inside the block editor, is to change an other field from this field group.

You can see it here:

![Oct-27-2019 10-46-17](https://user-images.githubusercontent.com/31563167/67632699-152cdf80-f8a7-11e9-96fb-6295496c3950.gif)

Do you can confirm this?

**Comment by CreativeDive** [comment]
@elliotcondon By the way there is a litte typo on your documentation example: https://www.advancedcustomfields.com/resources/google-map/

```
function initMarker( $marker, map ) {

    // Get position from marker.
    var lat = $marker.data('lat');
    var lng = $marker.data('lng');
    var latLng = {
        lat: parseFloat( lat ),
        lng: parseFloat( lng )
    };

    // Create marker instance.
    var marker = new google.maps.Marker({
        position : latlng,
        map: map
    });
```

You should change `position : latlng,` to `position : latLng,`. :-D

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Thanks for the bug reports.

I suspect the Block refresh issue is due to a missing "change" event triggered on the Google Map field input. I'll perform some testing shortly and report back with my findings.

**Comment by elliotcondon** [comment]
Update: I was able to replicate and fix the issue today. 

I've updated the ACF PRO plugin files online - can you please download the latest build from your account online (https://www.advancedcustomfields.com/my-account) and copy accross the `assets/js` folder?

Please let me know how you go.

**Comment by CreativeDive** [comment]
@elliotcondon Thank you. It works very well again!
