### ISSUE TITLE
ACF block and custom style via wp.blocks.registerBlockStyle deletes block

### ISSUE THREAD

**Issue by mtruitt** [AdvancedCustomFields/acf#246]
While running into this issue I ran across this post that already detailed the issue. 

There is a bug in the ACF PRO Version 5.8.3 with Gutenberg (WordPress 5.2.2) that wasn’t there in beta (Version 5.8.0-beta4.1).

When you add styles to the block via wp.blocks.registerBlockStyle, the preview/edit functionality doesn’t work: the edit UI doesn’t load after switching styles and previewing block.

For full description - https://support.advancedcustomfields.com/forums/topic/acf-block-and-custom-style-added-via-wp-blocks-registerblockstyle/

**Comment by elliotcondon** [comment]
Thanks @mtruitt 

I'll take a look into this today.

**Comment by elliotcondon** [comment]
@mtruitt I have implemented a fix for this issue and will include it in the next release.

**Comment by elliotcondon** [comment]
Hi @mtruitt 

Please disregard my previous reply (now hidden) - I had mistaken this thread for another.
I am interested in testing out this issue, but am not yet able to replicate the issue.

I have tested block styles via two methods, and each seem to be working well.

**1. Pure Javascript:**
The following JS adds a style to a block named "testimonial". No issues detected.
```
wp.domReady( function() {
		wp.blocks.registerBlockStyle( 'acf/testimonial', {
		    name: 'fancy-quote',
		    label: 'Fancy Quote'
		});
	});
```

**2. Pure PHP:**
Styles can also be registered with the `acf_register_block_type()` function args. The following adds two styles to a block type. No issues detected.
```
'styles' => array(
				array( 'name' => 'normal', 'label' => __( 'Normal', 'my-acf' ), 'isDefault' => true ),
				array( 'name' => 'fancy', 'label' => __( 'Fancy', 'my-acf' ) ),
			),
```

Please let me know how I am able to replicate the issue. Looking forward to your reply.

**Comment by mtruitt** [comment]
Looks like we are good now after updating. Other than updating ACF no other code was changed so not sure what fixed it but not going to complain either. Going to go ahead and close it.
