### ISSUE TITLE
gutenberg core/editor deprecated

### ISSUE THREAD

**Issue by eballeste** [AdvancedCustomFields/acf#247]
Just started to work with gutenberg / acf-blocks and after installing the gutenberg plugin in order to get the new breadcrumbs feature that rolled out in 6.8.0, I started to get a bunch of warnings in the console about `core/editor` being deprecated to be replaced by `core/block-editor`. After clearing them all up, I noticed that the remaining 3 were coming from `assets/js/acf-pro-blocks.min.js`:

```
`wp.data.select( 'core/editor' ).getBlocks` is deprecated. Please use `wp.data.select( 'core/block-editor' ).getBlocks` instead.
wp.editor.BlockControls is deprecated. Please use wp.blockEditor.BlockControls instead.
wp.editor.InspectorControls is deprecated. Please use wp.blockEditor.InspectorControls instead.
```

**Comment by elliotcondon** [comment]
Hi @eballeste 

Thanks for the info. I'm all for changing this, but we need to consider the backwards compatibility implications this would have on previous versions of WordPress.

 I'll need to think about what the best solution is for avoiding "deprecated warnings" for modern versions, but still allowing functionality for previous ones.

**Comment by eballeste** [comment]
That makes absolute sense to me, I guess it should only be a problem if it finally does get deprecated and but it's still in use in the core. Thanks for you response.
