### ISSUE TITLE
Instruction placement doesn't apply to the group field

### ISSUE THREAD

**Issue by rahulnever2far** [AdvancedCustomFields/acf#25]
If the _Instruction placement_ is set to _Below fields_ in Field Group settings, instructions in the group field are still displayed below labels.

**Comment by elliotcondon** [comment]
Hi @rahulnever2far 

Please submit any issues you find as support tickets here:
http://support.advancedcustomfields.com/new-ticket/

Please be sure to specify your ACF (or ACF PRO) version, and also steps to replicate the issue. I can assure you this setting does work, so perhaps it is only on a specific form?
