### ISSUE TITLE
Flexible Layouts: Compatible with 5.3 + Classic Editor?

### ISSUE THREAD

**Issue by rabbithops** [AdvancedCustomFields/acf#251]
We're seeing the very powerful flexible layout field getting blown up by the 5.3 update, which significantly overhauled the WordPress UI with Classic Editor enabled. 

Before:
![Screen Shot 2019-11-13 at 11 29 35 AM](https://user-images.githubusercontent.com/10162762/68783774-825fa500-0609-11ea-8e41-ada6f41e0d0f.png)

After:
![Screen Shot 2019-11-13 at 11 29 01 AM](https://user-images.githubusercontent.com/10162762/68783773-825fa500-0609-11ea-875a-a749d7f53627.png)

**Comment by elliotcondon** [comment]
Hi @rabbithops 

This looks very strange indeed. The layout element itself contains the correct styling, but the inner fields are missing all "ACF field" styles. I'm not able to replicate this on my end, can you please inspect the DOM and check if anything looks obviously wrong?

**Comment by rabbithops** [comment]
Thanks for your response! We used a custom theme internally that we believe may be causing the issues.
