### ISSUE TITLE
ACF Pro field time are not taking timezone

### ISSUE THREAD

**Issue by d3tr1tus** [AdvancedCustomFields/acf#252]
In WP Admin i am setting for example 7:00 am but in database is set 6:00 am. My timezone is Europe/Berlin. I checked server und there is no problem, also WP admin has set this timezone and in functions.php i am setting `date_default_timezone_set('Europe/Berlin');`. In versions before Wordpress 5.3 working all fine.

Can you repair that please?

**Comment by ArthurShlain** [comment]
I have similar problem with Date field. When i save any date, it's represents as "-1 day". I detect, that it's causes by timezone GMT-05.

**Comment by elliotcondon** [comment]
Hi all,

Thanks for the bug report. I am currently reviewing similar tickets both on our helpdesk and the WordPress trac. This issue looks to be related to the use of `date_default_timezone_set()` within WordPress 5.3, and is not specific to ACF, but will also affect other parts of WP such as "scheduled posts'.

Please read this reply from one of the WordPress moderators: https://wordpress.org/support/topic/read-this-first-wordpress-5-3-master-list/#post-12124062

@d3tr1tus - You mentioned that the value saved into the DB is different to the one selected. Can you please confirm this by inspecting your wp_postmeta table? If my prediction is correct, the value saved in the DB should be correct. The problem occurs only when loading the value via `get_field()` which will "format" the value via the `date_i18n()` function.

@ArthurShlain - Can you please confirm the same?

**Comment by ArthurShlain** [comment]
@elliotcondon You right, i see correct value in database

**Comment by corydhmiller** [comment]
As long as `date_default_timezone_set` has been removed from any instances on the pages, `get_field` behaves properly to create a new `DateTime` object:

```
$date_time = get_field("date_time");
$date_time_eastern = new DateTime($date_time, new DateTimeZone('America/New_York'));
```

The only thing that might be a hassle (and I may doing it wrong) is having to set the origin timezone into a new DateTime object every time I want to convert it.

```
$date_time_pacific = new DateTime($date_time, new DateTimeZone('America/New_York'));
$date_time_pacific->setTimezone(new DateTimeZone('America/Los_Angeles'));
```

It might be helpful to allow the option to set the timezone from the custom field itself, which would need to return an object instead of a string.

**Comment by elliotcondon** [comment]
@corydhmiller - Thanks for the reply. 

I don't have much experience using timezones in WP projects, so can you help me understand why this timezone setting is needed in your project? Are you wanting the displayed "date value" to be modified based on the difference in timezones? If not, perhaps these timezone parameters/settings are not needed.

**Comment by corydhmiller** [comment]
@elliotcondon Sure thing. I prefer to convert the string into a DateTime object so that more can be done with it. In our case we have custom post types for webinars/workshops, which need to display dates in Eastern and Pacific time (and if I get around to it, "Your local time" as well). We also use it to determine timeframes for bonuses, expirations, and countdowns (to name just a few). That's where having the DateTime object is preferable because you can just do more stuff with it.

If you're only using the string in a single output case, then certainly you wouldn't need to set timezones since the timezone could be inferred in the copy or whatever, but anything beyond that needs a bit more work within the theme.

That being said, if someone _wants_ to create a DateTime object from a Date Picker custom field, it defaults to UTC and would need to be modified to the correct timezone to display properly anyways. 

`get_field('date_time')` might return something like `11/20/2019 4:00 pm`, but if you try and make a new DateTime object from that point, it's 4pm UTC, no matter what your intention was for the actual time. In fact when we upgraded to 5.3, my colleague was confused as to why the WordPress timezone we set in the admin panel was Los Angeles but the Date Picker seemed to be doing its own thing (the culprit really was `date_default_timezone_set()`). 

In any case, the solution may not necessarily be to add dependencies to the returned string itself, but having the option to return a DateTime object on `get_field('date_time')` could be really handy for people wanting to do more with the date than just display a string.

Hope this helps! 😊

**Comment by majidgh72** [comment]
To resolve this problem manually until new version release you can do this:

Edit file : **"includes/api/api-helpers.php"**.

find this code:
```php
date_i18n($format, $unixtimestamp)
```

And replace it with:
```php
wp_date($format, $unixtimestamp)
```

**Comment by Sam-Pryor** [comment]
Instead of editing the api-helpers.php file you can change your code like this.
Add 'false' add a second parameter to 'get_field', so acf will not format the date.
Then do your own wp_date function:
`$date = get_field('date', false);
$date = wp_date('F jS', strtotime($date));`

**Comment by elliotcondon** [comment]
@Sam-Pryor Good solution. Just a minor clarification: The `$format_value` parameter is actually the 3rd param, not the 2nd: https://www.advancedcustomfields.com/resources/get_field/

**Comment by jimmyadaro** [comment]
The third parameter works as expected.

```php
get_field('some-hour-value', $my_post_id, false);
```

**Comment by ronnaph** [comment]
Right now this problem still occurs. I have resoled it by add action.

add_filter('date_i18n', function ($date, $format, $timestamp, $gmt) {
      return wp_date($format, $timestamp);
}, 99, 4);

**Comment by wlarch** [comment]
I encounter the same problem. The timezone is set to UTC-4 in my Wordpress general settings. On the front end, when displaying the date, it is displayed correctly using `get_field('date_start', $post_id, false);` although, in the administration part where the datepicker is displayed, the date displays using UTC timezone. How can I make sure my client see the right datetime and not the UTC ?

**Comment by Soben** [comment]
I am having the same issue as @wlarch 

Client has Los Angeles set, and throughout the front-end of the site date/time usage is correct. Saving the field based on the user's selection appears to be saving it correctly, however, the data renders in UTC in the admin panel.

This confused the client and is a poor author experience. @ronnaph's solution worked for me.

**Comment by rAthusFr** [comment]
The issue stip persists as of today.

To sum it up, a date or a datetime is always saved as a numeric timestamp in the database, which is a universal value that can then be read in any timezone. 

The issue with ACF is that they use the PHP function `date_i18n()` when returning the value in the format you chose in the field's settings, and this function doesn't take timezone into account unless you pass it a time offset, which ACF doesn't do.

This isn't an issue for 99.9% of people who's server date is set on their own timezone and they don't need to get dates in any other timezone, but it becomes an issue for the few who don't have their server's date set in their own timezone and/or wish to change it using PHP's function `date_default_timezone_set()`, ACF doesn't take it into account.

The fix suggested by @ronnaph solves the issue, as it forces the function `date_i18n()` to take the timezone set by the Wordpress into account, and by extention the timezone you set using the function `date_default_timezone_set()` if you use it.

You just need to add that code into your child theme's _function.php_:

`add_filter('date_i18n', function ($date, $format, $timestamp, $gmt) { return wp_date($format, $timestamp); }, 99, 4);`

I will set the correct date and time both frontend and backend in the WP-admin.

I hope ACF will address this issue someday, but for now, this seems to be the best solution we have.

**Comment by only-cliches** [comment]
I got you fam.  Hacked this together in a few hours, works fine for my client but would love for some one to polish it up.

![ACF Date and Time picker V2](https://i.imgur.com/hnnpAJ1.png "Date/Time Picker V2")

Source Code: https://gist.github.com/only-cliches/f41e0aad1bcd043292a2705216a785d5

How is this different from the built in date/time picker?
- All date/time operations are purely javascript, the time WILL adjust automatically with the user's timezone.
- The field saves a javascript timestamp (milliseconds since epoch).  Can be read in PHP by first dividing it by 1,000.
- If an admin in US Pacific Time Zone sets something to 3 PM using ACF with this field, it will show as 6 PM when an admin in the Eastern Time Zone looks at it.
- When you render the time on the front end USE JAVASCRIPT and the timezone will automamagically adjust for you. Example in the readme at the top of the gist above.

**Comment by rAthusFr** [comment]
@only-cliches there's a massive issue with your solution, which is having to add some files into the plugin's directory.

Each time the plugin will update, your file will be lost.

You should seek for a way of making your hack indepentend so it doesn't have to be reapplied each time the ACF plugin update.

**Comment by only-cliches** [comment]
> @only-cliches there's a massive issue with your solution, which is having to add some files into the plugin's directory.
> 
> Each time the plugin will update, your file will be lost.
> 
> You should seek for a way of making your hack indepentend so it doesn't have to be reapplied each time the ACF plugin update.

Agreed, until I can turn this into a PR the ACF folks will accept, it's a bit of manual work after each update.  For me, it's worth it.  If it's worth it for you too, great.  That's what open source is all about. :)

If someone had already made this file before me, I'd happily put it in place and just take note to re apply the patch after each update.  Takes like 20 seconds.

**Comment by rAthusFr** [comment]
@only-cliches but how is your complex solution better that the one-line hack in _functions.php_, posted just above, that perfectly fixes the issue while keeping the normal ACF datetime picker?

**Comment by only-cliches** [comment]
> @only-cliches but how is your complex solution better that the one-line hack in _functions.php_, posted just above, that perfectly fixes the issue while keeping the normal ACF datetime picker?

Apologies, I thought I was clear in my first post, I'll try to be more detailed in this response.

The original Date/Time picker suffers from two issues in my opinion:
1. The timezone on the picker in the ACF panel (inside Wordpres admin) is fixed based on the server/wordpress configuration.  The "fix" so far in this thread is to try to lock it to the desired timezone of the Date/Time picker to the one set in the Wordpress settings.  In my mind, this is still wrong.  Very few users are sophisticated enough to check or know what timezone their environment is in before setting something.  They always assume it's their timezone! (I've been through this situation personally dozens of times with my clients).  So unless *everyone* who *ever* works with your site will always be in the same timezone forever, the original Date/Time picker is leaving open a massive door for human error.  The new Date/Time picker is not fixed to the server or Wordpress, but the *user*.  Whichever timezone their phone/computer/browser is set to is the timezone the Date/Time picker is using.
2. Similar issue for rendering the Date/Time.  I'm sure there are some cases where you just want to naively render the Date/Time on the frontend according to the timezone of the server/wordpress install.  But the default settings don't even give you an option to display a timezone! https://i.imgur.com/nuBJ0js.png.  What the heck is a user of your website supposed to do when they see "2pm"? 2pm WHEN?  How many people have this field displaying on their site with just "2pm" and no more information!?  For me, this is a big problem for usability. In a majority of cases I've encountered my clients want the time to appear according to the user's timezone, and if not we should explicitly display the timezone for the times being shown.  So I think it's *VERY* important that developers think about if they're rendering the time statically based on server/Wordpress timezone or based on the user's device timezone.   So the formatting options are gone, do the formatting in PHP or JS and think about what kind of experience you want to create.

**Comment by rAthusFr** [comment]
I believe all your issues come from a wrong approach of internationalizing a website.

A website is either local (specific to a timezone) or international.

In the case of a local website, the question of a flexible timezone doesn't exist as it's unique and forced.

In the case of a flexible timezone, it's the developper's job to have the timezone set automatically depending on each user, using IP geolocation, JavaScript detection, asking the user, etc, any method you prefer, and then set the timezone for this specific user using `date_default_timezone_set()`.

From there you don't have to make any odd hacks or anything, as the dates are stored in the database using either timestamp or UTC time, and the display date functions will adapt to the user's timezone.

Our agency has been working with two methods to achive that, giving a lot of importance to cleanness, stability and performance as we're working on high trafic international websites (over a million single visitors per day):

1. Using JavaScript to determine the user's timezone based on his browser, saving it as a $_SESSION variable and use it to set the PHP timezone in _functions.php_, it works like a charm and is completely free, but can require refreshing the page to benefit from the timezone depending on how the website has been built.
2. Using an IP geolocation service to get the user's timezone on first load, saving it as a $_SESSION variable and use it to set the PHP timezone in _functions.php_, it's generally faster and better for the UX and SEO, but can have a cost for a good IP geolocation service depending on the number of visitors.

Having the whole PHP engine working in the right timezone you want it to work is the right way to go, and if a developper don't understand what I'm saying here then no disrespect but he/she should learn more before working on internationalizing a WordPress.

Your hack can be an interesting solution for a lazy developper who wants to make ACF datetime fields work with users' timezones and don't have the knowledge to properly do it, but it really is a wrong way to go imo, it's heavy, bulky, hazardous, unclean, unstable and way too specific (eg it won't display a post's publish date `get_the_date()` in the right timezone, etc) :/

**Comment by only-cliches** [comment]
I'm not even sure where to start.... I think we're going to have to agree to disagree.  You asked me why I built a new solution, and I explained it.  Good luck out there.

**Comment by Youdaman** [comment]
> Right now this problem still occurs. I have resoled it by add a filter.
> 
> add_filter('date_i18n', function ($date, $format, $timestamp, $gmt) { return wp_date($format, $timestamp); }, 99, 4);

I encountered the same issue today. WP timezone is set to Perth Australia, and selecting from the datetime picker with time of 6pm was showing 10am in the form field and elsewhere after saving. It was saved correctly in the database as `2023-08-13 18:00:00` so thank you @ronnaph :)

**Comment by Joram-Helium** [comment]
Hello, I was using ronnaph hack until today when I realised that the post's publish date is not right when I edit it as rAthusFr mentionned. Back to square one for me. I'm going to use an extend of DateTime class "WPDateTime" which will set automatically the timezone in DateTime object.

**Comment by Hnnx** [comment]
I've been banging my head against this bug for hours now and I see the posts are still relatively recent. Switched themes not long ago and noticed 2 hour discrepancy between my WordPress timezone and whatever ACF was returning. I've never seen this bug before but the add filter solution fixed it for me - switched to @ekazda fix so it doesn't affect admin view.

Any official response from ACF?

**Comment by Yasp0** [comment]
This still seems to be an issue?
