### ISSUE TITLE
No clear way to add examples to block inserter

### ISSUE THREAD

**Issue by mattbeck** [AdvancedCustomFields/acf#264]
All of our ACF powered blocks show up as No Preview Available.

These previews appear to be referred to as examples in the core blocks.
ref: https://github.com/WordPress/gutenberg/pull/17493/files

It'd be great if that example content could be exposed as an arg in acf_register_block_type().

**Comment by mattbeck** [comment]
<img width="650" alt="Screen Shot 2020-01-07 at 11 46 02 AM" src="https://user-images.githubusercontent.com/2372870/71927566-98da3680-314a-11ea-9634-6868dae52389.png">

**Comment by elliotcondon** [comment]
Hi @mattbeck 

Thanks for the topic,
Elliot here - ACF dev​​​.

I believe it will be possible to add previews to an ACF Block by implementing the "example" setting like so:
```php
acf_register_block_type(array(
	'name' => 'testimonial',
	...
	'example' => array(
		'attributes' => array(
			'data' => array(
				'testimonial' => 'This is an example!',
				'name' => 'Elliot'
			),
		)
	)
));
```

I'll need to perform some more testing to be absolutely sure, but please test this out and let me know if you have any luck.

**Comment by mattbeck** [comment]
Hey @elliotcondon - thanks.  That almost works, but not in a useful way.

I tried it with our heading block, because it's about the simplest we have:

Populating the example data based on what is saved in wp_posts.post_content gets something to render, but it generates a preview of the admin UI.
 
<img width="200" alt="Screen Shot 2020-01-07 at 4 25 18 PM" src="https://user-images.githubusercontent.com/2372870/71940266-84a63180-316a-11ea-9201-69a78744bca0.png">

**Comment by mattbeck** [comment]
`	'example' => array(
		'attributes' => array(
			'data' => array(
				'type' => 'h3',
				'style' => 'default',
				'heading' => 'This is a heading'
			),
		)
	)`

**Comment by mattbeck** [comment]
passing an empty array renders the admin UI there as well, but with no values selected

**Comment by elliotcondon** [comment]
This might be a result of the block type's "mode" setting. Try this:
```php
'example' => array(
	'attributes' => array(
		'mode' => 'preview',
		'data' => array(
			'type' => 'h3',
			'style' => 'default',
			'heading' => 'This is a heading'
		),
	)
)
```

**Comment by mattbeck** [comment]
@elliotcondon - that works. 

We don't have preview mode enabled on our custom blocks because our CMS is decoupled from the front-end, but we can work with that, and at least get something rendering in that space using the callback. 

Cheers, hope you guys are safe from the fires.

**Comment by ovincent3012** [comment]
Hi Guys,
Managed to get it working with just 

```
'example' => array(
            'attributes' => array(
                'mode' => 'preview',
                
            )
        )
```

Anyone able to explain what the 		`'data' => array()` does as I tried it and it doesn't seem to do anything?

Thanks :)

**Comment by elliotcondon** [comment]
@ollievincent The `'data'` attribute holds the custom field values you would like to be displayed within the block preview.

For example, if your block contains a field called "background_color", you could define this within the `example.attributes.data` array. The block `render_callback` or `render_template` will then be able to access this value via the `get_field()` function.

**Comment by ollievincent** [comment]
@elliotcondon Thanks, so what do the individual `attributes` do within the `data` array?

Where would your `background_color` field go within the code?

**Comment by elliotcondon** [comment]
Similar to the previous example code I posted:
```
'example' => array(
	'attributes' => array(
		'mode' => 'preview',
		'data' => array(
			'background_color' => '#ff0000',
			'other_custom_field' => 'xxx',
		),
	)
)
```

**Comment by ollievincent** [comment]
@elliotcondon  Ah I see. That makes sense. Thanks very much for all your hard work :)

**Comment by fcharrasse** [comment]
Hello @elliotcondon ,
I'm trying to get the examples above to work, but I only get a preview of the edit mode of the block. I would like to display the rendering of the preview mode instead.

![image](https://user-images.githubusercontent.com/46343634/78237821-1f00e180-74dc-11ea-893e-f22206e9f1b7.png)

acf_register_block args : 

```
$acf_block_args = array(
    'name' => 'text',
    'title' => 'Texte',
    'description' => '',
    'render_callback' => 'setAcfBlocksRenderForGutenberg',
    'category' => 'hwc',
    'icon' => 'text',
    'keywords' => array(),
    'mode' => 'edit',
    'post_types' => array(),
    'supports' => array(
        'align' => false,
        'mode' => true,
        'multiple' => true
    ),
    'enqueue_assets' => 'setAcfBlocksEnqueueAssetsForGutenberg'
);
$acf_block_args['example'] = array(
    'attributes' => array(
        'mode' => 'preview'
    )
);
acf_register_block($acf_block_args);
```

Adding data array under attributes does nothing. 

$acf_block_args ['mode'] = 'preview' : 

![image](https://user-images.githubusercontent.com/46343634/78239640-435dbd80-74de-11ea-9c69-5221cf31fbb4.png)

Again, thanks for your fantastic work !

**Comment by elliotcondon** [comment]
Hi @fcharrasse 

Please ensure your "reference values" match the correct field keys.
In your code example, the following data is incorrect: `'_text' => 'Exemple',`.

**Comment by fcharrasse** [comment]
@elliotcondon  Thank you for your reply. No change by deleting "_test" and leaving "test". I had put the two values, as they are entered in the two ways in the database.

**Comment by ollievincent** [comment]
@fcharrasse , I am assuming you are using the name of your fields, not your block? I only ask because in your example above your block  is called 'test'

**Comment by fcharrasse** [comment]
Oops, sorry, typo. I mean "text" not "test".
"text" is the block name.

**Comment by palmiak** [comment]
Hi

I tried this example without luck. I using WP 5.4.1, ACF 5.8.9 and TwentyTwenty theme

```php
function owl_blocks() {
	if ( function_exists('acf_register_block') ) {
		acf_register_block(
			[
				'name'            => 'owl_link',
				'title'           => 'Link',
				'description'     => 'Link do artykułu',
				'render_template'   => 'test.php',
				'category'        => 'layout',
				'icon'            => 'menu',
				'keywords'        => [ 'link', 'linki' ],
				'example' 		=> array(
					'attributes' => array(
						'mode' => 'preview',
						'data' => array(
							'opis' => 'preview example text',
						),
					),
				),
			]
		);
	}
}
add_action('acf/init', 'owl_blocks');
```

and the test.php is:
```php
<?php 
echo 'Echo test';
echo get_field( 'opis' );
```

The preview only shows "Echo test" - https://share.getcloudapp.com/mXuB2KXq

I also did some test using `render_callback` but it didn't worked either.

**Comment by elliotcondon** [comment]
Hi @palmiak 

Thanks for the comment. We have recently identified a bug that is preventing the "data" attribute to be predefined in both block examples and post type templates. 

We have a fix for this, and will release it shortly in 5.8.10 (early next week). Sorry for the inconvenience.

**Comment by palmiak** [comment]
Thanks 😀

pt., 8 maj 2020, 02:53 użytkownik Elliot Condon <notifications@github.com>
napisał:

**Comment by palmiak** [comment]
@elliotcondon Example are working correctly - I implemented them in my plugin for Timber and ACF Blocks - https://palmiak.github.io/timber-acf-wp-blocks/#/using-example :) 

Just noticed one thing - `get_fields` doesn't get the data passed in Example array.

**Comment by elliotcondon** [comment]
Thanks for the confirmation @palmiak.

The problem with `get_fields()` is that it requires the field reference values to exist. One solution is to use the field_key instead of field_name in the "example" array. For example:

Change:
```
'data' => array(
    'my_field' => 'Some value',
),
```

To:
```
'data' => array(
    'field_123abc' => 'Some value',
),
```

We'll be working on a more intuitive solution shortly :)

**Comment by palmiak** [comment]
I saw that the example data is stored in $block[data] so if I see that
get_fields is empty I try to override with that. So it's not a big deal -
just wanted you to know 😀

Thanks again for all the hard work.

sob., 16 maj 2020, 02:19 użytkownik Elliot Condon <notifications@github.com>
napisał:

**Comment by anybodesign** [comment]
Hello :)
I can't figure it out. I still got no preview with all your examples.
I just want to show a picture as preview.
Here is my code, I should be wrong somewhere…

`add_action('acf/init', 'adblocks_posts_block_init');
function adblocks_posts_block_init() {
	if( function_exists('acf_register_block') ) {
		
		// Posts
		
		acf_register_block(array(
			'name'				=> 	'posts',
			'title'				=> 	__('Posts', 'adblocks'),
			'description'		=> 	__('Insert one or many posts or custom posts.', 'adblocks'),
			'category'			=> 	'ad-blocks',
			'icon'				=> 	'<svg width="100%" height="100%" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve" xmlns:serif="http://www.serif.com/" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;"><g><path d="M12,0l0,2l-9.2,0c-0.442,0 -0.8,0.359 -0.8,0.8l0,18.4c0,0.442 0.358,0.8 0.8,0.8l18.4,0c0.442,0 0.8,-0.358 0.8,-0.8l0,-9.2l2,0l0,10.08c0,1.06 -0.86,1.92 -1.92,1.92l-20.16,0c-1.06,0 -1.92,-0.86 -1.92,-1.92l0,-20.16c0,-1.06 0.86,-1.92 1.92,-1.92l10.08,0Z" style="fill:#555d66;"/><path d="M18.018,9.97l-0.997,0.748c-0.997,0.997 -1.246,2.741 -0.498,3.988l-1.994,1.994l-2.742,-2.742l-3.24,3.24c-0.499,0.498 -3.988,3.24 -4.487,2.742c-0.498,-0.499 2.244,-3.988 2.742,-4.487l3.24,-3.24l-2.742,-2.742l1.994,-1.994c1.247,0.748 2.991,0.748 3.988,-0.498l0.748,-0.748c1.246,-1.246 1.246,-2.991 0.499,-4.237l1.994,-1.994l7.477,7.228l-1.994,1.994c-1.191,-0.476 -2.837,-0.497 -3.988,0.748Z" style="fill:#555d66;"/></g></svg>',
			'mode'				=> 	'auto',
			'supports'			=> 	array( 'align' => array( 'wide', 'full' ), 'mode' => false),
			'keywords'			=>	array( 'post', 'publication' ),
			'render_template'   =>	ADBLOCKS__PLUGIN_PATH . '/blocks/block-posts/templates/block-posts-template.php',
			'enqueue_assets'	=>	function() {wp_enqueue_style( 'block-posts', ADBLOCKS__PLUGIN_URL . '/blocks/block-posts/css/block-posts.css' );},
			'example' => array(
				'attributes'		=> array(
					'mode'			=> 'preview',
					'data'			=> array(
						'content' 	=> __('<img src="https://via.placeholder.com/680x720">'),
					),
				)
			),
		));
	}
}
require_once( ADBLOCKS__PLUGIN_PATH . '/global-fields/columns-fields.php' );
require_once( ADBLOCKS__PLUGIN_PATH . '/blocks/block-posts/block-posts-fields.php' );
require_once( ADBLOCKS__PLUGIN_PATH . '/global-fields/background-fields.php' );`

**Comment by elliotcondon** [comment]
_Replying to https://github.com/AdvancedCustomFields/acf/issues/264#issuecomment-632533752 by @anybodesign_

The block example HTML shown will all depend on your render_template code. May I suggest that you open up a fresh GitHub ticket and include all the necessary code so that I may setup the exact block that you are creating? I can then help identify any problems and get your block running smoothly.

**Comment by anybodesign** [comment]
Ok thanks @elliotcondon :)
I’ll open a new ticket with a whole block

**Comment by anybodesign** [comment]
Hello @elliotcondon it's done, I've just opened a new ticket: [https://github.com/AdvancedCustomFields/acf/issues/302](https://github.com/AdvancedCustomFields/acf/issues/302)
