### ISSUE TITLE
Options Pages in WP 5.4

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#272]
I just installed WP 5.4 beta 1, and without really inspecting how my ACF blocks really work with it (they seem fine at first glance), the ACF Option pages are little bit messed up but not a total loss - it will be just confusing for some.

1. The Screen even though by default to 2 Columns, it displays only 1 column, and in this state there is no way to save your options.

2. Also, the meta boxes widths are now dynamic, the width will be adjusted by the content on the meta boxes.

2. Changing the screen from 2 columns to 1 column, you NOW get 2 columns actually, and finally we see the save button... 

So, setting the screen to 2 columns, you get 1 column, and setting the screen to 2 columns, you actually get one - without the save button !

Here is a short video of the mess this geniuses managed to make - https://www.youtube.com/watch?v=L_BtNb1sZm8&feature=youtu.be

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the bug report. It looks like WP 5.4 is introducing some changes to how custom admin pages / metaboxes are rendered. I'll be sure to investigate this shortly.

Thanks
Elliot

**Comment by elliotcondon** [comment]
Update. WP Ticket created: https://core.trac.wordpress.org/ticket/49424#ticket

**Comment by nick6352683** [comment]
Thanks Elliot, I hope they can resolve this by the end of March...

**Comment by nick6352683** [comment]
Looks like WP 5.4 RC1 fixes this issue... I guess your ticket 49424 greased the wheels over there !

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks again for raising the issue. Please let me know if you come across any other WP 5.4 conflicts.
