### ISSUE TITLE
Adding Fields to Menus in WP 5.4 bug...

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#273]
Fresh WP 5.4 beta 1 - I have added 2 fields to the WP menu structure to add a font awesome icon to a menu item. One field is for the FA name, the other a message and a link to open the available FA icons to use.

With WP 5.3.2 (and below), all is fine.

With WP 5.4 beta 1, the field group is duplicated, using the first instance of the field group does nothing, using the second instance works, and also automatically updates the first instance of the field group.

Here is a short video, first demonstrating how it should  work with WP 5.3.2, and then the mess created by WP 5.4 beta 1 - https://www.youtube.com/watch?v=8PgQ6rYR0CQ&feature=youtu.be

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the bug report.

The issue here appears to be a double render of the ACF fields. This is most likely due to a duplicate action call which I will need to investigate.

Thanks
Elliot

**Comment by elliotcondon** [comment]
Update. I've reviewed some changes found in WP 5.4-beta1 and discovered that WP core have introduced an action called "wp_nav_menu_item_custom_fields" within the `Walker_Nav_Menu_Edit` class.

Until now, this action has been something that plugin/theme developers have implemented within their own plugins.

With WP 5.4 + ACF 5.8.7, custom fields will be displayed twice.

I'll be sure to release an update shortly to fix the problem :)

**Comment by nick6352683** [comment]
As some say "you da man !"

Thanks once again Elliot.

**Comment by baloran** [comment]
Hey 👋

Same problem here, wp 5.4.1 and acf 5.8.3, did you know if they are something we can do to handle the problem awaiting the fix ?

**Comment by nick6352683** [comment]
The fix was completed months ago... get the latest version of ACF (and possibly you need to clear your cache), and you will be set.

**Comment by baloran** [comment]
@nick6352683 Thanks !
