### ISSUE TITLE
Another possible ACF Pro and WP 5.4 beta 1 conflict.

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#274]
Hi Elliot,

I reported the following bug, which I think either you have to fix this, or have it fixed in the core...

My last comment in the report explains all the situations I encountered the issue...

https://core.trac.wordpress.org/ticket/49425

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks mate. I think we'll need to see some screenshots / screen recordings to better understand this one. Is the issue occurring on the front-end, or the back-end?

If on the back-end when editing a post, I suspect the issue will be related to metaboxes appearing on the screen.

**Comment by nick6352683** [comment]
Hi @elliotcondon ,

Only on the front end... I will make a short video for you tomorrow on this, as it is 12:30 am here...

**Comment by nick6352683** [comment]
@elliotcondon , I had a long day yesterday, so I missed something obvious with this bug (I apoogoze). So let me clear things up in the simplest way...

If ACF Pro is active there is no scrollbar on screens smaller than 781px. This happens for any theme. I also made this clarification in Trac, so it's up to you and the core developers to decide who should fix this issue...

**Comment by elliotcondon** [comment]
Hi @nick6352683 

For this to be true, ACF PRO must be modifying some of the HTML rendered on the front-end. 
The confusing part here is that by default, ACF does not make any changes to a website's HTML.

Can you please activate ACF PRO and copy/save the HTML of your page to a file.
Then, deactivate ACF PRO and again copy/save the HTML of your page to another file.

Please attach both files so we can debug the difference.

If you are also able to provide a staging/test site online where I can inspect the issue myself, that would be great :)

**Comment by nick6352683** [comment]
No need... My version of ACF Pro uses options screen that embeds/enables other plugins. I am embarrassed to assume that it was ACF Pro causing this issue. In fact it was not. The plugin that is causing this is the "Simply Gallery Plugin", which I verified by installing it directly into the site...
![options](https://user-images.githubusercontent.com/5131681/74497420-7c8c9080-4e92-11ea-9a4c-63c035a29e5c.JPG)
