### ISSUE TITLE
All fields reset to type "text" and rules set to "show on post"

### ISSUE THREAD

**Issue by Terrorpixel1991** [AdvancedCustomFields/acf#276]
I can't say what happend, but every field on my website changed the type to "text" and every rule set to "show if its a post"... description and field names are working but all other information is lost.

WP: 5.3.2
PHP: 7.2.26
ACF: 5.8.8 (also in 5.8.7)

**Comment by elliotcondon** [comment]
Hi @Terrorpixel1991 

Sorry to hear about the issue. This GitHub repo is reserved for code specific related issues and fixes. For general support and bug reporting, please contact our support team from here: https://www.advancedcustomfields.com/contact/

The symptoms you are experiencing suggest some sort of "corrupt" field and field-group data causing the objects to load default settings.

**Comment by elliotcondon** [comment]
Hi @Terrorpixel1991 

Were you able to solve the issue?

**Comment by Terrorpixel1991** [comment]
> Hi @Terrorpixel1991
> 
> Were you able to solve the issue?

Hi. No, i‘ve closed the Ticket because you said its only for code issues ^^ i‘ve wrote a ticket :)
