### ISSUE TITLE
ACF Value always returning null / nothing

### ISSUE THREAD

**Issue by PascalKu** [AdvancedCustomFields/acf#277]
Hi I installed the ACF plugin using the Wordpress plugin "market".  I got the menu section and created my first group called "Front page". In this i got a field called "test".

I can find the field editing in my admin panel page configuration and if I implement the following code on my custom front-page.php site, I get nothing... Also the get_field method with my header group is not working.

Any ideas?

```
<?php get_header();

echo the_field('test');

$header = get_field('header');
if ($header) : ?>
    <header>
        <div class="m-header bg-darkBlue">
            <div class="container py-5">
                <div class="py-5"><span class="m-header__lead"><?php echo $header['slogan']; ?></span>
                    <h1 class="m-header__headline"><?php echo $header['headline']; ?></h1>
                    <p class="m-header__paragraph"><?php echo $header['paragraph']; ?></p>
                    <a class="m-header__button btn btn-primary mt-3 py-2" href="#">Jetzt
                        loslegen!</a>
                </div>
            </div>
        </div>
    </header>
<?php endif; ?>```

**Comment by elliotcondon** [comment]
Hi @PascalKu 

This GitHub repo is reserved for code specific related issues and fixes. For general support and bug reporting, please contact our support team from here: https://www.advancedcustomfields.com/contact/

Also, we have extensive documentation on our site covering all the basics of ACF usage which you can find here: https://www.advancedcustomfields.com/resources/

**Comment by PascalKu** [comment]
Isn't it a code question?

**Comment by elliotcondon** [comment]
Hi @PascalKu 

Your question does indeed relate to code, however, this is the custom code within your theme.

This GitHub repo is reserved for issues and fixes that relate directly to the ACF codebase. For example, if you were to identify a bug in the internal `acf_add_local_field()` function, this would be the correct place to raise an issue.

I highly recommended that you contact our support team via the contact link mentioned previously. Our team will be able to help advice on a solution, and work with you to diagnose the issue.

Looking at your code, I can see that you are loading a field value before the "the loop". If you are viewing a non single page (home, archive, etc), ACF won't know where to load the "test" field from.

When running into any kind of problem where "code doesn't behave as it should", I always recommended that you spend some time debugging your code.

**Comment by PascalKu** [comment]
fixed; https://stackoverflow.com/questions/24887158/wordpress-acf-get-field-not-returning-value
