### ISSUE TITLE
Confusing translations - Field group: Locations - nl(_NL)

### ISSUE THREAD

**Issue by mathiasdb** [AdvancedCustomFields/acf#279]
Hi

When creating a Field Group, you'll need to define one or more Field Group - Locations.
If you select "page_type", you have the following options ( incl. the dutch translations )

front_page  : Hoofdpagina
posts_page : Berichten pagina
top_level      : Hoofdpagina (geen hoofd)
parent          : Hoofdpagina (bevat subitems)
child             : Subpagina

The choices "front_page", "top level" and "parent" all seem alike.
Each individual translation seems, to my opinion, correct, but when they are next to each other eg. the Page Type choices dropdown. It seems confusion.

I suggest the following translation(s)

front_page : Homepagina => not the best translation, but the same translation WordPress uses in the Settings > Reading screen a.k.a. page_on_front label.
posts_page : Berichten pagina => ok, WordPress uses "Berichtpagina", close enough :)
top_level      : Bovenliggend (hoogste niveau) => translates as "top, parent of the highest level"
parent          : Bovenliggend => translates as "top, parent"
child             : Subpagina => ok

Thanks

**Comment by elliotcondon** [comment]
Hi @mathiasdb 

Thanks for the recommendations. I've added this to out to-do list, and will hope to add these into the next release :)
