### ISSUE TITLE
Date/time showing in UTC instead of WordPress locale

### ISSUE THREAD

**Issue by aeivete** [AdvancedCustomFields/acf#280]
I've googled and read through several similar reports and have found no solution or answer in the docs, so I'm opening a ticket.

I am testing in a brand new WP 5.3.2 install with ACF 5.8.7 and no other plugins, no custom code, and no themes.

The only instances of the `date_default_timezone_set()` method in my environment are in core as you can see:

```
root@889642ee686f:/var/www/html# grep -rn 'date_default_timezone_set' .
./wp-admin/includes/class-wp-site-health.php:1048:					/* translators: %s: date_default_timezone_set() */
./wp-admin/includes/class-wp-site-health.php:1050:					'<code>date_default_timezone_set()</code>'
./wp-settings.php:58:date_default_timezone_set( 'UTC' );
./wp-includes/class-phpmailer.php:3297:        date_default_timezone_set(@date_default_timezone_get());
```

I have set my WP locale to New York, and all core date/time fields show the local time, like so:
```
                   ID: 16
          post_author: 1
            post_date: 2020-03-23 15:08:17
        post_date_gmt: 2020-03-23 19:08:17
```

![Screenshot 2020-03-23 15 39 46](https://user-images.githubusercontent.com/54189440/77356472-c2076d80-6d1c-11ea-920c-cca58e88244c.png)

However, for ACF date/time fields, the UI displays in UTC:

```
   meta_id: 38
   post_id: 20
  meta_key: something_0_date
meta_value: 2020-03-26 06:00:00

   meta_id: 44
   post_id: 20
  meta_key: plain_date_field
meta_value: 2020-03-24 03:03:00
```
![Screenshot 2020-03-23 15 42 20](https://user-images.githubusercontent.com/54189440/77356585-ff6bfb00-6d1c-11ea-87f1-9a4a1ba5f444.png)

The question is: **Shouldn't the UI for ACF date/time fields match the timezone of WP core date/time fields?**

**Comment by elliotcondon** [comment]
Hi @aeivete 

Thanks for the question.

ACF save's date and date_time values timezone agnostic. Meaning, the value saved "2020-03-24 03:03:00" is exactly as it is displayed "03/24/2020 3:03 am".

**Comment by aeivete** [comment]
@elliotcondon thanks for the answer, although "timezone agnostic" is not literally true since it's in GMT, which is, itself, a time zone.

Do you have plans to make the ACF date/time fields match the behavior of WP core fields?

**Comment by elliotcondon** [comment]
Hi @aeivete 

No plans at the moment for this, however, it should be possible to implement through filters that already exist. Using the "acf/update_value" and "acf/load_value" filters, you can hook in and modify the value when it is saved and loaded. You could use this to offset the value forwards / backwards using the site's timezone setting.

**Comment by agencekonig** [comment]
in class-acf-field-time-picker.php

`// vars
  103: 		$g_i_a = date('g:i a');
  104: 		$H_i_s = date('H:i:s');`

date should be replaced with wp_date to have the correct timezone.

Please check : https://make.wordpress.org/core/2019/09/23/date-time-improvements-wp-5-3/

**Comment by elliotcondon** [comment]
Hi @agencekonig 

Thanks for your comment.

I agree, the field settings should show the current local time. I'll add this to my to-do list for our next release :)

**Comment by elliotcondon** [comment]
Can confirm this has been fixed and will be included within the next release.

**Comment by aeivete** [comment]
@elliotcondon after upgrading to the latest version, the behavior remains the same. 

The UI value continued to match the db value in GMT.

Testing on an empty WP install with ACF Pro 5.8.11 installed on 5.4.1:

![image](https://user-images.githubusercontent.com/54189440/82924718-bf0e4080-9f4a-11ea-9c69-95e0f0a520c4.png)

```
meta_id: 78
post_id: 27
meta_key: something_0_date
meta_value: 2020-03-26 00:00:00
```

I tested changing the `acf_format_date` method's `date_i18n` to `wp_date` and that changed the UI to display in the current timezone, but the value shown in the picker is still what is saved to the DB, so that is not the correct solution, either. I'm not familiar enough with your plugin to debug this efficiently...

**Comment by elliotcondon** [comment]
Hi @aeivete.

I believe you may have miss-interpenetrated the previously discussed improvement.

The change mentioned in this comment ( https://github.com/AdvancedCustomFields/acf/issues/280#issuecomment-614087410 ) is with regards to the Date Picker settings, not the value.

As mentioned, ACF save's date and date_time values timezone agnostic. Meaning, the value saved "2020-03-24 03:03:00" is exactly as it is displayed "03/24/2020 3:03 am".
