### ISSUE TITLE
Validation failed. 1 field requires attention

### ISSUE THREAD

**Issue by advaitn** [AdvancedCustomFields/acf#281]
Hi,

I have tried posting this on ACF Support Forum but couldn't get any help.
Please help me in this particular issue, it is quite an urgent task for me right now.

System Status:
Advanced Custom Fields Version 5.8.7
WordPress Version 5.3.2
Theme Kunco

I am having too many fields on the product page so I have used ACF to create all the fields and mapped them on the frontend, however I am not able to publish my product in a particular case wherein the error shows up, but in some other case the product gets published. I have attached both the cases screenshots.

Extremely long screenshots – so providing links instead of posting images*

This is the case where it works extremely fine: https://i.stack.imgur.com/6GJ61.jpg

This is another case where it doesn’t get published: https://i.stack.imgur.com/wvVXF.jpg

Awaiting response,
Advait Nandeshwar.

Also here is my json file for the same: 
[acf-export-2020-03-27.txt](https://github.com/AdvancedCustomFields/acf/files/4394232/acf-export-2020-03-27.txt)

**Comment by elliotcondon** [comment]
Hi @advaitn 

Thanks for the email,
Elliot here - ACF dev​​​.

Please note this GitHub repo is not intended for ACF support. If you are looking for assistance to write some custom functionality, please be sure to contact our support team here: https://www.advancedcustomfields.com/contact/

My advice would be to viewing the validation AJAX response from the browser's console log. Does the JSON response return any field errors? This information will be helpful to the support team.

Wishing you all the best 👍

**Comment by advaitn** [comment]
Hi @elliotcondon 

Thank you so much for your response.

Here is the console log:
![image](https://user-images.githubusercontent.com/29460487/77832248-a8ba5300-715a-11ea-821b-586d725bb8cf.png)

I know not the right repo, I will post this on the forums too.

Thank you very much.

**Comment by elliotcondon** [comment]
Hi @advaitn 

Thanks for the reply.

Be sure to check the validation AJAX response from the browser's console log. When updating the page/post, an AJAX request will be made to validate the fields. It is this data that will be important to debug, not the entire page load warnings/errors.

Also worth noting, please use the contact link mentioned above to discuss the issue with our support team. Posting on the community forums will not guarantee a reply as this is a space to discuss ideas with fellow developers.

**Comment by advaitn** [comment]
Hi @elliotcondon 

Thank you my error is resolved.
