### ISSUE TITLE
Old ACF (5 beta) and new WordPress compatibality

### ISSUE THREAD

**Issue by kuraga** [AdvancedCustomFields/acf#285]
Good day, @elliotcondon !

I use ACF 5 Beta. See the last paragraph as a note.

I've updated my WordPress and links "Edit" link, "Add a field" button, etc. became silently... After experiments I saw `acf.field_group.init()` hasn't start. And starting it manually I get some errors about namespaces... But links start to work!

Soo seems like I ran into https://github.com/WordPress/gutenberg/issues/6091 . First of all, **thank you** about your attempt to get it right!

I'd be **very pleased** about some questions:
1. What should I change these lines https://github.com/toddsby/acf5-beta/blob/master/js/input.js#L914-L976 to get it working? (BTW I've tried some code but...)
2. Which version of WordPress became uncompatible?
3. (a rhetorical) Why WordPress hooks are discussed by developers in editor (Gutenberg)'s repository, hm......

(I use ACF 5 Beta. Seems like https://github.com/toddsby/acf5-beta but I remember I cloned it from your repository several years ago. I see "License: GPL" so I think, it's legal. I do want to buy PRO for my organization but only feature we need is (as I remember) is The Repeater Field, so... Also I fear about data migration from unreleased beta...)

Thanks!

**Comment by elliotcondon** [comment]
Hi @kuraga 

Thanks for the topic.

Please note that this 5.0 beta version you are referring to is over 6 years old. The `wp.hooks` issue that have referenced is something that we have fixed, although I can't remember the exact version number of the top of my head.

I can't recommend enough that you stop using a 6+ year outdated version of our software. This is not a responsible practice for your projects or clients.

If you are looking to purchase an ACF PRO license and gain access to our regular updates, please be sure to visit our PRO page here: https://www.advancedcustomfields.com/pro

Wishing you all the best.
