### ISSUE TITLE
acf_register_block_type did not show up in frontpage 

### ISSUE THREAD

**Issue by Abdelmonem-BEN-NACEUR** [AdvancedCustomFields/acf#287]
Hello!

I recently created a custom block type with acf like mentioned in the doc, it works just fine in the edit interface in the back-office, but in the front I did not get anything, and when i inspect the html code i get the content commented like this:

`<!-- /wp:heading -->`
``

Any ideas please ! ?

**Comment by elliotcondon** [comment]
Hi @Abdelmonem-BEN-NACEUR 

Can you please confirm that your block is being registered during the `"acf/init"` action, and is not blocked by any conditional logic such as `if( is_admin() ):`?

Thanks
Elliot

**Comment by Abdelmonem-BEN-NACEUR** [comment]
Hello @elliotcondon !

Thank you for your response!

here is my code :

`add_filter( 'block_categories', function ( $categories ) {
  $categories[] = [
    'slug'  => 'MyNewTheme',
    'title' => 'MyNewTheme',
    'icon'  => null
  ];

  return $categories;
} );


if ( function_exists( 'acf_register_block_type' ) ) {
  add_action( 'acf/init', function () {
    acf_register_block_type( [
      'name'            => 'highlighted_posts',
      'title'           => __( 'articles mis en avant', 'VoxEurop' ),
      'render_template' => 'blocs/advertising_area.php',
      'category'        => 'MyNewTheme'
    ] );
  } );
}
`
Even if i debug the object post in front i get the content commented out .
![image](https://user-images.githubusercontent.com/30234640/79400239-8e1b1300-7f7d-11ea-9529-a6e73e432c8a.png)

All kind of block works fine except for my custom ones.

I tried with 
`      'render_callback' => function() {
      echo "Hello world";
      },
`
I got my block in Gutenberg but not in front :/

![image](https://user-images.githubusercontent.com/30234640/79400458-329d5500-7f7e-11ea-8a3d-ecfb69b0916c.png)

**Comment by elliotcondon** [comment]
Thanks for the reply.

Can you confirm that your page/post content is being output by the traditional "WP loop" including the `the_content()` function? If your block is being registered within the functions.php file for both front-end and back-end, the problem may be that the template displaying the post content (single.php or similar) is not allowing the value to be formatted by dynamic block callbacks.

**Comment by Abdelmonem-BEN-NACEUR** [comment]
Exactly! 

Thx a lot!

And sorry for my noob question.

:)

**Comment by FalkoJoseph** [comment]
> Thanks for the reply.
> 
> Can you confirm that your page/post content is being output by the traditional "WP loop" including the `the_content()` function? If your block is being registered within the functions.php file for both front-end and back-end, the problem may be that the template displaying the post content (single.php or similar) is not allowing the value to be formatted by dynamic block callbacks.

Just wanted to say: this solved it for me as well (if anyone is experiencing a similar issue).

**Comment by Abdelmonem-BEN-NACEUR** [comment]
That was my mistake , and it's a tricky one :)

**Comment by elliotcondon** [comment]
Happy to help :)

Also worth checking out the `do_blocks()` function for direct post_content rendering:
https://developer.wordpress.org/reference/functions/do_blocks/

**Comment by Abdelmonem-BEN-NACEUR** [comment]
I think that the new registered bloc type is not aware about required attribute of the related ACF field.
I'm not missing anything here? 

Thank you for your help in advance.

**Comment by elliotcondon** [comment]
Hi @Abdelmonem-BEN-NACEUR. If you are referring to required field validation, then yes, this is not yet supported in our plugin. We are currently awaiting an official API from WP for providing block validation.
