### ISSUE TITLE
Unable to Use ACF

### ISSUE THREAD

**Issue by EwanKirkywood** [AdvancedCustomFields/acf#293]
I have installed all ACF addons to my computer. The only way I am able to use "acf menu" tool is by joining a certain server, but when on the server I try to pick a gun and theres no image. even when I spawn it, its not there but it shows in my recent spawns. 
It does say the version they use is 246 but mine is 245, I use SVN update/ checkout but still no luck,
Am I missing some addons? Did I download from the right link?
If anyone could help me, Please do. thank you.

**Comment by elliotcondon** [comment]
Hi @EwanKirkywood 

I think you might have the wrong GitHub repo here. I don't understand a lot of what you are saying. Servers, guns, 246, SVN... this does not sound like a WordPress plugin question.

**Comment by EwanKirkywood** [comment]
Im unsure if I have the wrong download, I installed this one into addons, If I could add a Picture on this it would be much easier to explain. 
I join a server called AWM builders. when I join it it says because ive installed SVN. "Your addons are out of date"
Nothing shows, I have no tools linking to ACF addons. If theres an email I could send it that would help. 
Sorry im just really confused by this. 
If you have a link to the Right Repo I could download that. its just confusing.

**Comment by elliotcondon** [comment]
Hi @EwanKirkywood 

GitHub allows comments to include images. Can you please take a moment to attach some screenshots along with a clearer explanation of your issue?

**Comment by EwanKirkywood** [comment]
![gm_flatgrass0000](https://user-images.githubusercontent.com/64892244/81158554-01fa7b00-8f80-11ea-80e5-671106dc797f.jpg)
![gm_buttes20001](https://user-images.githubusercontent.com/64892244/81158561-03c43e80-8f80-11ea-98a0-339dd73061f8.jpg)
![gm_buttes20002](https://user-images.githubusercontent.com/64892244/81158565-045cd500-8f80-11ea-94b7-e996418af182.jpg)

Hi, On the flatfgrass in me on a solo session. I look on my tools and there is no ACF menu.

On the Online server, Unsure of the map name though. There is a ACF menu, when I click on it. It says "ACF menu is out of date". Thats why I downloaded SVN from a youtube tutorial which said would help but didnt.
When I click on any weapon, on the image I use HMG. but there is no image that shows what it looks like.
When I try to spawn it, It shows its there in my utilities but I can not see it personaly.

**Comment by elliotcondon** [comment]
Hi @EwanKirkywood 

Thanks for the screenshots. This is 100% not ACF. I can't help you with this issue.
