### ISSUE TITLE
Fields don't stay hidden when using screen options

### ISSUE THREAD

**Issue by rmens** [AdvancedCustomFields/acf#295]
Hey guys,

I may have found a bug or edge case.

WordPress has baked in option called Screen Options. This gives users the possibility to hide certain fields in their interface. It's documented [here](https://make.wordpress.org/support/user-manual/getting-to-know-wordpress/screen-options/).

ACF Fields show up in these 'Screen Options' and can be hidden that way, but it only works one time. When you refresh the page. It shows all the ACF Fields again, even if you hid them with the WordPress Screen Options.

How to reproduce:

- Install the latest WordPress with the latest ACF Pro
- Add a custom field and let it show up on posts
- Make a new post and hide the field with the Screen Options preferences in WordPress. Now it's hidden.
- Refresh the page: the field will show up again.

**Comment by elliotcondon** [comment]
Hi @rmens 

Thanks for the bug report. Can you confirm if this issue occurs on the Gutenberg edit screen or the classic edit screen? Or both?

**Comment by rmens** [comment]
@elliotcondon This is while using the classic editor. I have never used the Gutenberg Editor and the Classic Editor plugin is set to always show the classic editor.

**Comment by elliotcondon** [comment]
Thanks for the confirmation. I'll add this to out to-do list and perform some testing shortly.

**Comment by rmens** [comment]
Great! Thanks for the quick response @elliotcondon.

**Comment by monojp** [comment]
Hi there, I don't want to be rude but are there updates on this?

**Comment by elliotcondon** [comment]
Hi @monojp - Thanks for the prompt. This bug seems to have slipped through the cracks during 5.9 development.
I'll make sure we address this for 5.10

**Comment by rmens** [comment]
After about a year I'm curious if this is still on the roadmap for 5.10 that seems to be around the corner now 5.9.9 is out.

**Comment by mattgrshaw** [comment]
Sorry about that and thanks for the heads up @rmens. Yep, this one unfortunately did fall through the cracks for the 5.10 release.

I've tested and was able to replicate the issue with the Classic Editor plugin enabled. It should hopefully be a pretty simple fix, so I've triaged that for 5.11.

**Comment by mattgrshaw** [comment]
@rmens @herndlm Just to follow up - we've completed the work for this and it's currently available in the 5.11 release candidate, which can be downloaded from the "[My Account](https://www.advancedcustomfields.com/my-account/)" section of our site.

We're anticipating that this will be officially released for both free and pro sometime next week.

**Comment by rmens** [comment]
Confirming that this works as expected in the 5.11 release candidate @mattgrshaw.
