### ISSUE TITLE
Forum topic disappeared

### ISSUE THREAD

**Issue by kuraga** [AdvancedCustomFields/acf#296]
Good day!

I've had a question. Created a topic: https://support.advancedcustomfields.com/forums/topic/avoiding-admin-editors-tags-strip/ . Now I see: It's accessible under my account only and "topic not found" else.

Seems like a forum engine bug. I've filled a support ticket but didn't get a reply.

![image](https://user-images.githubusercontent.com/1063219/82114805-94143780-9767-11ea-9b94-6d25dbbfe61d.png)

So I would "restore" the topic and get a help :)

Thanks!

**Comment by elliotcondon** [comment]
Hi @kuraga 

Your forum topic was incorrectly marked as spam. I've fixed the status, and it is now publicly visible.

**Comment by kuraga** [comment]
Hello @elliotcondon !

Sorry to bother you. Could you remove that topic, please?

I haven't know about spam detection and thought it's a problem with my text's closing tags. And created three replies to my post. So topic is trash and marked as "Solving". Maybe that's why I haven't got an answer :smile: .

I'd re-create it. (If it won't marked as a spam :smile: ). Thanks!

**Comment by elliotcondon** [comment]
Hi @kuraga 

I'll go ahead and remove the duplicate replies, but please note that our Community Forums are not an official support offering. Instead, this is a place for the greater community to connect with thousands of ACF developers & users worldwide to discuss unique issues, share code snippets and solve problems together. 

Please checkout our options for support from this page: https://www.advancedcustomfields.com/support/

**Comment by kuraga** [comment]
Thanks! Very much!

I wrote here after I've not gotten a reply there.
