### ISSUE TITLE
5.9 beta - InnerBlocks not showing on frontend view

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#297]
Hey Elliot,

thanks for you great work and the new possibility to add inner blocks. I've tested this new feature. The inner blocks are visible in the backend view inside the gutenberg editor, but not included in the frontend view. My ACF blocks are still empty without inner block in the frontend view.

**Comment by CreativeDive** [comment]
Ok more details about this issue. This happens if the gutenberg version 8.1.0 is installed. This breaks the output of the inner blocks in the frontend view. With the latest release of WordPress (without the latest gutenberg plugin), the inner blocks are included in the frontend view.

**Comment by CreativeDive** [comment]
The constant changes from the gutenberg team are horror for every developer who works with this new editor.

**Comment by nick6352683** [comment]
Thank you CreativeDive, you saved me from throwing my expensive laptop in the pool ! I can confirm that Gutenberg 8.1 is the reason why the inner blocks not showing up on the front end.

**Comment by elliotcondon** [comment]
@CreativeDive @nick6352683 Thanks for the bug report. I recall a similar issue being reported in the past where the Gutenberg plugin uses different parameters than WP core when calling a block's dynamic render callback function.

**Comment by nick6352683** [comment]
Hi Elliot,

Without adding any additional pressure on you, is there any way for us to get a beta2 version soon that will work with Gutenberg 8.1? Testing things without  the latest Gut. version is almost waste of time...

**Comment by elliotcondon** [comment]
Hi @nick6352683 I've got this on my list for beta2

**Comment by noknokcody** [comment]
As of version 5.9-beta4 you will also get this issue if you mis-capitalize the "InnerBlocks" element in your block renderer.

For me using "<Innerblocks  />" allows rendering on the backend and produces this bug on the frontend 
when using "<InnerBlocks  />"  (B is capitalized) everything works as normal.

Just thought I'd put this here incase anyone else runs into the same bug on newer versions and is confused.

**Comment by elliotcondon** [comment]
@noknokcody Yes. This JSX component is Case sensitive.
