### ISSUE TITLE
Group Field Color Picker z-index Problems

### ISSUE THREAD

**Issue by mrwweb** [AdvancedCustomFields/acf#3]
Using ACF 5.6.2 and WP 4.8.2, I'm seeing the following with the Color Picker in a Group Field:

![image](https://user-images.githubusercontent.com/1238696/30933222-d0b9d74c-a37e-11e7-9dfc-e6a49e23c04a.png)
_Using the Block layout, the popup is underneath the sidebar elements_

![image](https://user-images.githubusercontent.com/1238696/30933225-d4965732-a37e-11e7-9e4d-434ac2e3f7d3.png)
_When in the group field, a color picker with a set width may have the group field dividers appear over the popup._

I haven't done enough testing to determine if this is a universal color picker issue or just one with the group field.

Regardless, the popup picker should obviously appear above all other page elements.

**Comment by elliotcondon** [comment]
Hi @mrwweb 

Thanks for the bug report.
Can you please attach a .json export of your field group for me to test?
I've just tried to replicate this issue but found the popup displayed over the top of other elements.
- i found this strange anyway because there is no z-index given to the color picker popup...

**Comment by mrwweb** [comment]
I think a lack of z-index is exactly the problem! Putting even `z-index: 1;` on `.acf-field-color-picker` fixes the issue. That may not be the best solution, but it did fix what I was seeing.

Here's the JSON export saved as TXT (to let me upload it right here):

[acf-export-2017-09-28.txt](https://github.com/AdvancedCustomFields/acf/files/1342242/acf-export-2017-09-28.txt)

Not there was some template logic on the field you'll have to remove to see it.

It's also worth noting that the sidebar issue in particular is only visible on narrower screens.

**Comment by elliotcondon** [comment]
Hi @mrwweb 

Thanks for the .json - made it very easy to replicate the issue.
I've just fixed the problem by adding a z-index style to the 'active' color picker. Easy

**Comment by mrwweb** [comment]
Great! Glad to get that fixed :)
