### ISSUE TITLE
Version 5.6.9. has compatibility issue with Location "Nav Menu" add-on

### ISSUE THREAD

**Issue by nickw1984** [AdvancedCustomFields/acf#30]
Was updating wordpress plugin to version 5.6.9. and this broke my staging site. Seems to be not compatible with Location "Nav Menu" Version 1.1

**Comment by elliotcondon** [comment]
Hi @nickw1984 

Thanks for the issue.
Can you please submit a support ticket with a more detailed explanation of the issue?
http://support.advancedcustomfields.com/new-ticket/

This GitHub repo is not for plugin compatibility support.
