### ISSUE TITLE
ACF fields not showing in custom post type when giving multiple rules.

### ISSUE THREAD

**Issue by swamiv1984** [AdvancedCustomFields/acf#303]
I have a custom post type 'post a job' created with CPT UI plugin. I have created ACF fields and set the location rules as follows, Post type is equals to 'post a job' and user role is equals to 'Administrator'. I didn't see my ACF fields in the custom post type(post a job). Note: I changed user roles to 'All' as well as other options but nothing works. I want to show ACF fields for custom post type and for specific user roles only. How can I solve this issue?
![ACF bug](https://user-images.githubusercontent.com/52122346/82951138-44820700-9fc4-11ea-8b54-79031cb2ab1b.PNG)

**Comment by elliotcondon** [comment]
Hi @swamiv1984 

Thanks for the question. The location rule "User Role" refers to the actual User form, not the current user's role. 

Please use the location rule "Current User Role" instead.
