### ISSUE TITLE
`wp.hooks` implementation overridden by AFC PRO

### ISSUE THREAD

**Issue by gziolo** [AdvancedCustomFields/acf#31]
I was able to reproduce the bug filed in the Gutenberg repository https://github.com/WordPress/gutenberg/issues/5860 by installing ACF Pro (v5.6.9).

> 

This issue is caused by the ACF implementation in `assets/js/acf-input.js` file, lines 8-250:
```js
var EventManager = function() {
    ...
};

window.wp = window.wp || {};
window.wp.hooks = new EventManager();
```

Putting this into words, ACF reimplements `wp.hooks` instead of using the already present module registered under `wp-hooks` name. My understanding is that it removes some of the filters registered previously causing the issue.

`Hooks` library which is developed under https://github.com/WordPress/packages/tree/master/packages/hooks and published to npm as https://www.npmjs.com/package/@wordpress/hooks is planned to be included under `wp.hooks` namespace in WordPress core in the 5.0 release. To avoid that kind of conflicts it might be a good idea to detect if `wp.hooks` is already defined and provide your implementation only when it is missing.

**Comment by elliotcondon** [comment]
Hi @gziolo 

Thanks for the bug report.

Yes, it looks like the wp.hooks library I use does not check for an existing instance.
I'll have this fixed in the next version.

**Comment by elliotcondon** [comment]
Hi @gziolo 

This has been fixed in ACF PRO 5.6.10. When you have a chance, can you please update and test it out? If the problem persists, please let me know and I'll continue to investigate.

**Comment by gziolo** [comment]
@elliotcondon, thanks for quick fix. I will let you know once it is confirmed by users who filed this issue 👍

**Comment by mejta** [comment]
Hi, thank you for fixing that. But update introduced new bug:

This is how it looks with ACF Pro 5.6.10 deactivated:

![image](https://user-images.githubusercontent.com/498441/38268130-a1b5b766-377d-11e8-9f63-30707b3196e8.png)

And this is with ACF Pro 5.6.10 activated:

![image](https://user-images.githubusercontent.com/498441/38268217-d2356bf2-377d-11e8-925a-e987ba850d2a.png)

`The hook name can only contain numbers, letters, dashes, periods and underscores.`

**Comment by elliotcondon** [comment]
Hi @mejta 

Hmmm.. looks like WP is requiring strict usage rules for the wp.hooks library.
I'm currently using a '/' in the action names as a namespace, but will need to change this to a '_' to avoid the errors.

Thanks for letting me know, I'll add this change to my to-do list.

**Comment by Rekenna** [comment]
Has this been fixed yet? I'm currently having this issue still :/

**Comment by Rekenna** [comment]
Awesome! Thanks for your hard work :D

**Comment by 681consulting** [comment]
Thanks for the updates on this one everyone. Had a client just upgrade to WP v5 and date fields stopped working. Easy fix by upgrading to the latest and greatest :) Also bought a developer subscription so that future updates are easier to manage for all clients. Love your work.
