### ISSUE TITLE
acf_register_block_type - post_types restriction not working

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#310]
Hey Elliot,

I run into this issue that the `'post_types' => array('recipe')` property of the **acf_register_block_type** function is not working. In my case I have a ACF block which should be only selectable for the "recipe" post type. But if I add this restriction, the block is not available for the recipe post type. I get this message inside the block container: _Your site doesn’t include support for the "acf/recipe-card" block. You can leave this block intact or remove it entirely._

I know this works in the past, but currently there is something wrong.

Do you can confirm this issue?

**Comment by elliotcondon** [comment]
Hi @CreativeDive. Does this issue appear in the latest stable or beta version of ACF PRO?

**Comment by CreativeDive** [comment]
@elliotcondon This works fine with ACF 5.8.11. With the latest 5.9 beta I can't select a restricted block in the allowed post type.

**Comment by elliotcondon** [comment]
Thanks @CreativeDive. I've just tested the issue and have identified the problem. Will have this fixed shortly 👍.

**Comment by elliotcondon** [comment]
Good news. I've found and fixed the issue 🙌.

You can pull down the latest code from ACF PRO repository, or await the 5.9.0-beta2 release later this week.

**Comment by CreativeDive** [comment]
@elliotcondon I've downloaded the 5.9 branch again, but I can't see any changes to this issue. The restricted post type block is still not selectable. Also I've refreshed the browser cache.

**Comment by elliotcondon** [comment]
That's odd. I can confirm this issue appears fixed on my end (tested with and without the Gutenberg plugin activated). Can you please provide an example block registration code for me to test?

**Comment by CreativeDive** [comment]
@elliotcondon This is my block registration code:

```
acf_register_block_type(
			array(
				'name' => 'recipe-card',
				'title' => __('Recipe Card', 'wphave'),
				'description' => __('...', 'wphave'),
				'icon' => array(
					'background' => $block_background,
					'foreground' => $block_foreground,
					'src' => 'carrot',
				),
				'category' => 'theme-recipes',
				'keywords' => array( 'recipe', 'card' ),
				'mode' => 'preview',
				'post_types' => array('recipe'), // <-- This block is only visible for recipe post type
				'supports' => array(
					'align' => array( 'wide', 'full' ),
					'mode' => true,
					'multiple' => true,
				),
				'render_template' => wphave_dir( 'inc/acf-blocks/recipe-card/recipe-card.php' ),
			)
		);
```

I will test it again if the beta 2 is released.

**Comment by elliotcondon** [comment]
Thanks @CreativeDive. I've just tested this code, swapping "recipe" for "post" (and also a CPT), but am not able to replicate the issue. 

Can you please confirm that the ACF PRO version being used contains this commit:
https://github.com/AdvancedCustomFields/acf-pro/commit/22e0093347c8ff2bf249ae632606cf29a00d5549
