### ISSUE TITLE
5.9 beta - Menu location field groups missing

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#312]
Hey @elliotcondon,

I've found a new issue with field groups at the menu location while working with 5.9 beta. All my field groups are missing and not visible at Appearance > Menus. If I downgrade to ACF 5.8.11 my field groups are visible again.

Do you confirm this bug?

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Thanks for the bug report. I've just tested this, but can't replicate the issue using the latest 5.9 branch. Can you please enable DEBUG_MODE and check for any PHP errors that could suggest an issue?

**Comment by CreativeDive** [comment]
@elliotcondon the DEBUG_MODE is always on :-) There are no PHP or JS errors. I've downloaded the latest branch again and the issue is still there. The fields are not visible at Appearance > Menus. If I downgrade to ACF 5.8.11 my field groups are visible again.

Here is the setup for the fields:

<img width="1042" alt="Bildschirmfoto 2020-06-05 um 07 07 27" src="https://user-images.githubusercontent.com/31563167/83839057-3b4b1580-a6fb-11ea-8a3f-70095e1a5197.png">

Do you can test this case please. It's very strange, that it's working fine with ACF 5.8.11, but not with 5.9 beta.

**Comment by CreativeDive** [comment]
@elliotcondon Here are more details:

Location: Menu > is equal to > All = Fields are there
Location: Menu > is equal to > Menu Locations > Primary Menu = **Fields are missing** !!!
Location: Menu > is equal to > Menus > My Menu Name = Fields are there

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Thanks for the bug report. I've found and fixed the issue 🙌

**Comment by elliotcondon** [comment]
Nice custom admin styling by the way. Is that from another plugin / theme or something you maintain yourself?

**Comment by elliotcondon** [comment]
Hi Martin. I just purchased a copy 🙌. Looks great so far - well done.

I noticed that the new ACF toolbar in version 5.9 doesn't quite connect to the sidebar. Is that something that can fixed from your end, or from mine?

**Comment by CreativeDive** [comment]
Yes, it is not easy to design an admin theme for WordPress that works very well with all plugins. Basically, this only works if you stick to the basic structure of the WordPress backend and make only minimal changes. It's also difficult because many plugin authors don't stick to WordPress design and always have to invent something new. Fortunately, this is not the case with ACF. :-)

The admin theme uses a little more padding on the left. I will improve this and add an exception for ACF :-) It's just a negative margin from 40px instead of 20px.

You could solve it by yourself at the moment and add a custom CSS line to the custom CSS field of the admin theme settings page, like:

```
.wpat #wpcontent .acf-admin-navigation {
margin-left: -40px;
}
```
