### ISSUE TITLE
PHP Notices: Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#313]
Hey @elliotcondon,

on another WordPress installation I get this PHP notices "**Trying to access array offset on value of type bool**" while editing a post or page with the Gutenberg editor:

<img width="1266" alt="Bildschirmfoto 2020-06-05 um 09 19 22" src="https://user-images.githubusercontent.com/31563167/83848129-aef61e00-a70d-11ea-8096-f8c9736c7e9f.png">

```
wp-admin/includes/template.php:1079
add_meta_box()
wp-admin/includes/template.php:1256
do_meta_boxes()
wp-content/plugins/wphave/inc/acf/includes/forms/form-post.php:182
ACF_Form_Post->edit_form_after_title()
wp-content/plugins/wphave/inc/acf/includes/forms/form-gutenberg.php:84
ACF_Form_Gutenberg->block_editor_meta_box_hidden_fields()
wp-includes/class-wp-hook.php:287
do_action('block_editor_meta_box_hidden_fields')
wp-admin/includes/post.php:2443
the_block_editor_meta_box_post_form_hidden_fields()
wp-admin/includes/post.php:2270
the_block_editor_meta_boxes()
wp-admin/edit-form-blocks.php:427
```

Do you have any idea what's going wrong here? Tested with latest WP, Gutenberg 8.2.1 and ACF 5.9 beta.

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Thanks for the bug report. I suspect this issue will exist outside of the current ACF beta version. Are you able to test with the latest stable version - 5.8.11?

If you have the chance, can you also debug the line in question found in WP core?
wp-admin/includes/template.php:1079

```
$title         = $wp_meta_boxes[ $page ][ $a_context ][ $a_priority ][ $id ]['title'];
```

**Comment by CreativeDive** [comment]
@elliotcondon yes this issue is also there with ACF 5.8.11 and latest WP (also without the latest Gutenberg plugin).

I've found a similar issue here: [https://wordpress.org/support/topic/error-trying-to-access-array-offset-on-value-of-type-bool-in-block-php-line-297/](https://wordpress.org/support/topic/error-trying-to-access-array-offset-on-value-of-type-bool-in-block-php-line-297/)

<img width="1310" alt="Bildschirmfoto 2020-06-08 um 10 16 21" src="https://user-images.githubusercontent.com/31563167/84007819-3d1e0e80-a971-11ea-89dc-8d998542ef34.png">

I get this notice also if ACF is disabled. It seems this is a core issue.

**Comment by elliotcondon** [comment]
Thanks for the info. I'll close this for now, but please let me know if we should re-open it.
