### ISSUE TITLE
5.9 beta - Gallery field not working

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#314]
Hey @elliotcondon,

are there any changes with the gallery field type in 5.9 beta? I've a gallery field with return format: "Image ID". But after adding some images, I get nothing. Normally this should output an array of image IDs. This works fine with ACF 5.8.11. With 5.9 beta I can't get any results.

Do you can confirm this issue?

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

I've just tested this on my end, but can't replicate any issues when loading the value of a Gallery field. All three return types appear to be working well.

**Comment by CreativeDive** [comment]
@elliotcondon I've tested more deeper.

1. I can confirm this works, if I use the gallery field in a metabox for posts. 

2. But, if I use the gallery field included in a ACF block. The return value is nothing. After switching back to ACF 5.8.11 it works fine. In 5.9 beta the output is empty.

Do you can test this case please?

**Comment by CreativeDive** [comment]
And here more details:

After adding some images to the gallery field, I can see them included in the field:

<img width="339" alt="Bildschirmfoto 2020-06-09 um 08 41 30" src="https://user-images.githubusercontent.com/31563167/84114741-2c32d300-aa2d-11ea-9b6e-ae66ec1e83ae.png">

BUT, after saving and refreshing the editor, the selected images are missing.

<img width="340" alt="Bildschirmfoto 2020-06-09 um 08 43 29" src="https://user-images.githubusercontent.com/31563167/84114832-4e2c5580-aa2d-11ea-918b-18df4b907b8f.png">

It seems there is an issue with the save operation?

**Comment by elliotcondon** [comment]
Thanks for the update. I've just attempted to replicate this on my local site, but still am not having any luck.

If it's not too much to ask, can you please spin up a fresh WP site in "Local by Flywheel" and try to replicate the issue? Please keep the default theme active and edit the functions.php file with any extra logic needed.​

​​If you can replicate the issue, please export the site (from flywheel app, right click the site and click "export") and attach to your next reply. ​I'll import this and get to work replicating / testing the issue :)

**Comment by CreativeDive** [comment]
@elliotcondon It's definitely a bug. I've created a very very simple theme to replicate this issue.

Unfortunately I don't have "Local by Flywheel". I have created a [Duplicator](https://de.wordpress.org/plugins/duplicator/) installation. 
I think that's enough, right?

You can download it here for testing:

https://www.creative-dive-de/themes/acf_test.zip

You should see this after installing this duplication:

<img width="728" alt="Bildschirmfoto 2020-06-10 um 09 28 09" src="https://user-images.githubusercontent.com/31563167/84239448-ca419e80-aafc-11ea-9b6b-23a222261e49.png">

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Thank you very much for the duplicator export and test site. This was extremely useful in tracking down the issue - which was a really tricky one to find!

I'll have more information to share as the day progresses, but will have a fix shortly :)

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Good news. I've applied an initial fix for the problem, and have updated the 5-9 branch. Can you check it out when you next get the chance?

**Comment by CreativeDive** [comment]
@elliotcondon It works. Thank you!
