### ISSUE TITLE
Didn't get replies on support queries

### ISSUE THREAD

**Issue by kuraga** [AdvancedCustomFields/acf#318]
Hello!

Unfortunately, can't get a help on my issue - https://support.advancedcustomfields.com/forums/topic/avoiding-admin-editors-tags-strip/ .

Note I've been opening a support ticket (name: Alexander Kurakin, e-mail: kuraga333@mail.ru), but got no reply.

Help, please! Thanks.

**Comment by elliotcondon** [comment]
Hi @kuraga 

Thanks for the post,
Elliot here - ACF dev​​​.

We offer a variety of ways to get help with ACF. Please be aware that the forum you have posted on is a place to connect with the greater community, and is not a place for official support from the ACF help team.

If you are looking for official support, please post a ticked via this form: https://www.advancedcustomfields.com/contact/

I've just searched our support tickets for the email provided, but can't find any. Do you have an ACF store account? If so, you can login and view your tickets online via the following link: https://www.advancedcustomfields.com/my-account. If you are able to find your ticket, please share with me the ticket ID.

And just to let you know, this GitHub repository is used only for technical bug reports and pull requests.

Thanks
Elliot

**Comment by kuraga** [comment]
Eliot,

thanks very much about replies!

> If you are looking for official support, please post a ticked via this form: https://www.advancedcustomfields.com/contact/

Yes, I posted there exactly. Maybe, my e-mail is in spam-list, too? :smile:
