### ISSUE TITLE
ACF Pro 5.9 beta2 bug - allowed file types for the Image field

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#319]
I do believe this bug also existed in beta 1 as well...

In an image field if I set any allowed file types, the Add Image button stops working (tested in a block and not in a meta box).

By removing the file types limitation setting, the Image button functions again.

**Comment by elliotcondon** [comment]
Thanks @nick6352683 

I've tracked it down, fixed the issue and pushed an update to the 5-9 feature branch 🙌.
The issue was due to changed action names within the ACF_Assets class. I've also added a to-do for us to review these changes and test for similar bugs.
