### ISSUE TITLE
5.9 beta - Stripping/modifying style attribute

### ISSUE THREAD

**Issue by JiveDig** [AdvancedCustomFields/acf#322]
Many of my ACF blocks use CSS variables passed via the style attribute of the wrapper, like this super basic example:
```
<div style="--custom-color">
```

Then my CSS is:
```
.my-block {
    color: var(--custom-color);
}
```

This is working really well with existing ACF blocks, but when trying to allow innerBlocks, these are getting stripped or modified. Either they get removed completely, or the output is changed (spaces or more values added). It's very strange.

Here is a simplified test:
```
add_action( 'acf/init', function() {
	if ( ! function_exists( 'acf_register_block_type' ) ) {
		return;
	}

	acf_register_block_type(
		[
			'name'            => 'mai-test-block',
			'title'           => __( 'Mai Test Block', 'textdomain' ),
			'description'     => __( 'A test block block.', 'textdomain' ),
			'render_callback' => 'mai_do_test_block',
			'supports'        => [
				'align'              => true,
				'mode'               => false,
				'__experimental_jsx' => true,
			],
		]
	);
});

function mai_do_test_block( $block, $content = '', $is_preview = false, $post_id = 0 ) {
	echo '<div class="mai-test-block" style="--my-custom-property:4;">';
		echo '<h2>This is the test block block</h2>';
	echo '</div>';
}
```

If you inspect the HTML, the `--my-custom-property` is missing.

Change `__experimental_jsx` to false, and it works correctly.

**Comment by elliotcondon** [comment]
Thanks @JiveDig 

I'll add this to our testing list 👍

**Comment by elliotcondon** [comment]
@JiveDig Good news. I've found and fixed the issue, and will include in the next release 🙌

**Comment by JiveDig** [comment]
👊🍻💰

**Comment by JiveDig** [comment]
Beta 3 fixes this. Thanks!
