### ISSUE TITLE
Image field frontend with Elmentor problem

### ISSUE THREAD

**Issue by codeorlov** [AdvancedCustomFields/acf#327]
Hi, i'm new here, i have already sent the problem to the support elementor, and will also post it for you. I can not derive the image from the profile using the dynamic image in the elementor. I wrote a short video for you. Look please. I use the latest versions of acf pro and elementor pro plugins.
[video.zip](https://github.com/AdvancedCustomFields/acf/files/4859371/video.zip)

**Comment by elliotcondon** [comment]
Hi @codeorlov 

Thanks for the conversation,
Elliot here - ACF dev​​​.

Your video shows an Image field being added to the User form, but doesn't show any issues related to outputting that image into your theme via Elementor. If you are looking for help on how to display custom field values using Elementor, I suggest reading up on their documentation and watching some online tutorials before contacting support 👍

**Comment by codeorlov** [comment]
@elliotcondon Hello!  Thank you for responding so quickly.  Perhaps you didn’t understand it, I select the widget elementor called the image, I can insert it on absolutely any page and point it to a dynamic value from an arbitrary field.  The documentation states that this should work, what am I doing wrong?

**Comment by elliotcondon** [comment]
@codeorlov Thanks for the reply and updated screen-recording.

This now clearly demonstrates an Elementor image widget attempting to load the dynamic value from a user's custom field.
Firstly, let's check with the Elementor developers that this is possible.

I know that Elementor works great by loading custom field values from the current Post/Page, but I'm not so sure if it is possible to load a custom field value that is saved to a specific user. Can you please present this question to the Elementor team and let me know what information they provide?

**Comment by codeorlov** [comment]
@elliotcondon, I opened a request more than 8 days ago in Elementor support. Unfortunately, no answer until today. This is something terrible.

**Comment by elliotcondon** [comment]
Hi @codeorlov 

What did the Elementor team reply with? If you were unsatisfied with their reply, please be sure to follow up with them. We're all in this together, and everyone want's the best for you 👍

**Comment by codeorlov** [comment]
@elliotcondon
that's just the point, nothing, 8 days have passed :) the delay of the Elementor is not particularly responsive.

**Comment by elliotcondon** [comment]
Sorry to hear that. I'm sure there is a good reason for the delay, but it may be worth submitting another ticket from a different email address just in case the initial ticket got lost.

**Comment by codeorlov** [comment]
Elementor team answer:
It's a pleasure to get to you.

First of all, I would like to offer you a sincere apology on behalf of all Elementors' team. We strive to reply to each ticket as soon as possible, with a goal of first response within 24 hours. However, in the midst of the COVID crisis, we have been experiencing a higher than usual volume of tickets whereby delivering responses has been taking us some more time.

The image filed is added to a user profile and not on a single post / page, thus it will not working like that. In this case, it's like a relationship and that is not supported yet with elementor. If you need to add user profile image the dynamic content should be > Author > User Profile Picture / Author profile picture.

The image comes from Gravatar but, If you want to keep your gravatar locally, head over to Dashboard -> Plugins -> Search for an Avatar plugin such as 'WP User Avatar'. Install and activate the plugin.

After activating the WP User Avatar plugin, please go back to Dashboard -> Users -> All Users -> Choose the specific user and hit Edit and scroll down to Avatar. You would see the additional options added by the plugin.

**Comment by mathiasdb** [comment]
Hi

Just jumping in, may this helps out =>
You could bypass your problem by creating your own custom DynamicTag => [https://developers.elementor.com/mini-tutorial-custom-dynamic-tag/](https://developers.elementor.com/mini-tutorial-custom-dynamic-tag/)

Add one or two control fields:

- field for the user-ID: use a number-field or fetch dynamically using get_queried_object() -> only works on author / user pages.
- field for the ACF field-name: optional text-field, but useful if you want to fetch more than one custom field, or skip the field and hardcode the field-name you've used for your image field.

Might be useful ( this is not mentioned in the tutorial ): an Elementor Image requires an array() with two key-paired values:
`return array(
  'id' => $attachment_id,
  'url' => wp_get_attachment_url( $attachment_id, 'full' )
)`

Kind regards
Matt
