### ISSUE TITLE
Issue with syncing field groups in Beta 3 + huge Kudos to you guys

### ISSUE THREAD

**Issue by gaz-think3** [AdvancedCustomFields/acf#328]
Firstly, you guys are fucking great. I'm mean amazing... InnerBlocks will revolutionise and reduce time developing in our process. This is going to be massive. I've been playing around with the Beta - there are so many creative uses for this feature. Huge kudos to the ACF Team and @elliotcondon!

Anyhow, I did stumble on a bug I wanted to report. When I go to sync field groups there is no option to bulk sync, so you have to sync each group individual. When you click 'Import' to sync the field group it says 'Field group synchronised.' but the group **does NOT** sync!

P.S. is there a release date for ACF 5.9? We have an upcoming starting project next week which would be perfect for this.

**Comment by elliotcondon** [comment]
Hi @gaz-think3 

Thanks mate!! You're too kind, but yeah, we're feeling pretty excited about releasing support for InnerBlocks 🎉.

I'll add this to our to-do list and will have a fix to share with you shortly.

**Comment by elliotcondon** [comment]
I've just spent some time testing out this bug report, but am not having any luck replicating it on my end.

I'll attach some screenshots to show the bulk "Sync  changes" drop-down option. This action seems to be working fine too.

![Screenshot_2020-07-13 Field Groups ‹ acf5 — WordPress](https://user-images.githubusercontent.com/2296425/87259261-50327a00-c4ed-11ea-8ffb-1f27c06e5fdc.png)

![Screenshot_2020-07-13 Field Groups ‹ acf5 — WordPress(1)](https://user-images.githubusercontent.com/2296425/87259263-532d6a80-c4ed-11ea-9b4a-dde11b303366.png)

**Comment by gaz-think3** [comment]
I've just retried seems to be working fine, it could have been an issue from my side! Not too sure.

**Comment by jtwee** [comment]
@gaz-think3 do you know what may have caused your issue? I'm having this now with 4 devs using 5.9.0-beta5. Our only workaround is to import each file from acf-json manually.

**Comment by gaz-think3** [comment]
@jtwee I'm not too sure how the issue was caused. We were trying to import a 5.8 version of json into the 5.9 beta 3 but there was an issue syncing it. We ended up upgrading to beta 4 and it fixed the issue not too sure what the cause was!

**Comment by jtwee** [comment]
Thanks for the info. I'll keep digging to see if I can work out where it's silently borking.

**Comment by jtwee** [comment]
Not sure what happened originally, but this was fixed in the 5.9.0 release. So even more huge kudos to you guys!
