### ISSUE TITLE
React warning triggered when using <InnerBlock /> feature in 5.9.0-beta3

### ISSUE THREAD

**Issue by shulard** [AdvancedCustomFields/acf#330]
Hello !

I'm currently playing with Gutenberg blocks inside a new project and it's awesome to have a PHP API to handle all the block creation. After the latest 5.9.0 beta release, I tried to implement `<InnerBlock />` and encounter some issues.

When I'm on the post edit screen, and I add a new bloc (which use the `InnerBlock` feature) I got the following React warning :

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in e (created by e)
    in div (created by e)
    in S (created by C)
    in C (created by InspectorControlsFill)
    in InspectorControlsFill (created by Ke) react_devtools_backend.js:6:7472
    r moz-extension://49878343-df0b-154d-a1d6-3c4d60da6705/build/react_devtools_backend.js:6
    warningWithoutStack http://lesbellesjournees.localhost/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:539
    warnAboutUpdateOnUnmountedFiberInDEV http://lesbellesjournees.localhost/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:23315
    scheduleUpdateOnFiber http://lesbellesjournees.localhost/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:21532
    enqueueSetState http://lesbellesjournees.localhost/wordpress/wp-includes/js/dist/vendor/react-dom.js?ver=16.9.0:13238
    setState http://lesbellesjournees.localhost/wordpress/wp-includes/js/dist/vendor/react.js?ver=16.9.0:413
    t http://lesbellesjournees.localhost/mu-plugins/advanced-custom-fields-pro/pro/assets/js/acf-pro-blocks.min.js?ver=5.9.0-beta3:1
    e http://lesbellesjournees.localhost/mu-plugins/advanced-custom-fields-pro/pro/assets/js/acf-pro-blocks.min.js?ver=5.9.0-beta3:1
    t http://lesbellesjournees.localhost/mu-plugins/advanced-custom-fields-pro/pro/assets/js/acf-pro-blocks.min.js?ver=5.9.0-beta3:1
```

I'm using WordPress 5.4.2 and found some details in the Gutenberg project related to this warning (https://github.com/WordPress/gutenberg/releases/tag/v8.5.0, https://github.com/WordPress/gutenberg/pull/23365). It seems that they fixed one of the possible cases in the v8.5.0 but I still encounter the warning with that version.

If I save the page and refresh the browser, everything works fine, the warning is triggered only when a new block with innerblock is added in the Gutenberg editor.

Is it a known issue ? Do I need to add some specific details/configuration in my bloc declaration ?

**Comment by elliotcondon** [comment]
Hi @shulard 

Thanks for the bug report.
I have been seeing this error also, but it's great to have more clarity on "when" it occurs. I'll be sure to test this out during our work on beta4 and hope to have a solution for your shortly 👍

**Comment by elliotcondon** [comment]
Note: I've already got a feeling that I know what is causing the issue. This is tied to another bug that is causing duplicate AJAX calls.

**Comment by elliotcondon** [comment]
@shulard Good news. Since some recent JS enhancements, I'm no longer able to trigger this error!

We have the next beta version scheduled for release this Friday, but wonder if you would like to join our ACF PRO private repo to help test sooner?

**Comment by shulard** [comment]
🎉 

I'll be glad to test the release ASAP 😄.

**Comment by elliotcondon** [comment]
@shulard Fantastic! I've just sent you an invite to the ACF PRO private repository. Here you will find the latest ACF PRO development code. We are currently working in the `feature/release-5-9` branch, so please pull down from there and let me know how you go!

**Comment by shulard** [comment]
Hello @elliotcondon and thank you for the invite.

I've just made different tests and the issue seems fixed on the `feature/release-5-9` branch.

I close this issue since it's fixed in the code and I'll try with the new beta when it'll be released.

**Comment by elliotcondon** [comment]
@shulard Fantastic news!
