### ISSUE TITLE
InnerBlocks 5.9.0-beta3 templateLock not working

### ISSUE THREAD

**Issue by Brandoning** [AdvancedCustomFields/acf#331]
I have this block:

```
<?php
$blocksTemplate = [
        ['core/heading', [ 'content' => '<strong>CTA Title</strong> - Title of the block', 'level' => 4 ]],
        ['core/paragraph', [ 'content' => 'CTA Text' ]]
];
?>

<InnerBlocks
                   template="<?php echo esc_attr( wp_json_encode( $blocksTemplate ) ); ?>"
                   templateLock="all"
                />
```

It renders okay and everything works other than template locking. I've checked the admin-ajax request and it has the attribute in the block preview's InnerBlocks tag so it should be working however I'm still able to add blocks to the area.

**Comment by Brandoning** [comment]
Side issue: Do not have line breaks in the InnerBlocks tag like I have above. It can work fine on the back-end but it'll prevent the content of the InnerBlocks loading on the front-end.

**Comment by elliotcondon** [comment]
Thanks @Brandoning. I'll test this out today 👍

**Comment by elliotcondon** [comment]
Good news. This is easily fixed and will be included in today's 5.9.0-beta4 release 🎉

**Comment by Brandoning** [comment]
Good stuff, thanks @elliotcondon :)

**Comment by Brandoning** [comment]
Works fine now in beta4, closing
