### ISSUE TITLE
Additional CSS class ajax calls

### ISSUE THREAD

**Issue by Zealth57** [AdvancedCustomFields/acf#332]
When you add in additional CSS classes via the built-in Gutenberg panel (Advanced -> Additional CSS Class(es) ACF runs an ajax call for every single character typed with the action acf/ajax/fetch-block. If I type in the css class "my-css-class" I get 12 ajax calls ran against admin-ajax in rapid succession. When I'm typing into a block field created via ACF such as a WYSIWYG or a text field, there is some sort of delay that waits until I stop typing, then runs the ajax call so that it is way better for performance. Can the same logic be applied to other fields?

**Comment by elliotcondon** [comment]
Hi @Zealth57 

Thanks for the bug report. I'll add this to our to-do list for 5.9.0-RC1 and aim to have an optimization for you shortly :)

**Comment by elliotcondon** [comment]
@Zealth57 Happy to report this has been fixed, and will be implemented in the next release - either 5.9.0-beta5 or 5.9.0-RC1

**Comment by Zealth57** [comment]
Awesome thanks for your quick work with that, just another reason your plugin is my all time favorite.

**Comment by Zealth57** [comment]
I can confirm in beta5 the additional css classes field performance is vastly improved, it only rechecks the admin-ajax after I've stopped typing. Great work!
