### ISSUE TITLE
InnerBlocks Content Issue

### ISSUE THREAD

**Issue by brockcataldi** [AdvancedCustomFields/acf#337]
So a summary of the problem, we love to use the new Gutenberg ACF Blocks, but I found an issue where if you have an InnerBlock and there is a dollar amount in the content the it'll lose the first half of the value. For example "$100,000" will become "0,000." After a short while diagnosed the issue with the plugin and here is at least a functional fix. 

Within the `acf_rendered_block` function in `advanced-custom-fields-pro/pro/block.php` there is this conditional.
```php
    if( preg_match('/<InnerBlocks(.*?)\/>/', $html, $matches) ) {
	 $html = preg_replace( '/<InnerBlocks(.*?)\/>/', $content, $html );
    }
```
But the problem with preg_replace, is the replacement parameter can take a $nth style references, so all you'll need to do if escape the `$`.  My quick solution would be to simply add a `$content = str_replace('$', '\$', $content);`, below is that working solution.

```php
    if( preg_match('/<InnerBlocks(.*?)\/>/', $html, $matches) ) {
         $content = str_replace('$', '\$', $content);
	 $html = preg_replace( '/<InnerBlocks(.*?)\/>/', $content, $html );
    }
```
Thanks, Keep up the good work.

**Comment by elliotcondon** [comment]
Hi @brockcataldi 

Thanks for the bug report. I can confirm the `$` characters is acting as a "capture group", and that escaping the character works well. We actually got this same issue reported by another developer and pushed a fix yesterday. We'll include the fix within the next beta version, expected in the next day or two!
