### ISSUE TITLE
ACF for Gutenberg Block Settings?

### ISSUE THREAD

**Issue by kanlukasz** [AdvancedCustomFields/acf#338]
Hello

There is such a future request at the ACF forum:
https://support.advancedcustomfields.com/forums/topic/acf-for-gutenberg-block-settings/

There is a lot +1 so i decided to make FR at github

Do you have any plans to implement something like this?
Is it in ACF scope?

Best regards,
Lukas

**Comment by elliotcondon** [comment]
Hi @kanlukasz 

As we see it, this request is currently outside the scope of ACF.

**Comment by kanlukasz** [comment]
Ok, thank you for the quick reply

**Comment by donohoe** [comment]
@elliotcondon I understand this is closed, but wondering if you could provide more context as to why it is out of scope.

ACF-based blocks solve a problem in that WP's block system is a mess. ACF also extends existing Post Types in WordPress. I can see why it would be natural for folks (myself included) to see huge benefits if ACF could also extend pre-existing Blocks like it does Post Types.

I would love to know more on why this is out-of-scope? 

From a demand and product perspective I think it would be a huge deal. Is it technical or resource hurdles?

**Comment by mklasen** [comment]
Hey @mattgrshaw - I'm wondering if there's any change of plans or if you're able to provide some more context these days

**Comment by lgladdy** [comment]
Could you give us some more info on how you would imagine ACF would extend default core blocks?

Because all the results of block output for core blocks is React/JS native, I'm not sure how we could code anything here that would let users do anything meaningful with ACF adding settings to a block.

**Comment by FalkoJoseph** [comment]
> Could you give us some more info on how you would imagine ACF would extend default core blocks?
> 
> Because all the results of block output for core blocks is React/JS native, I'm not sure how we could code anything here that would let users do anything meaningful with ACF adding settings to a block.

Hi thanks for following up @lgladdy. You're totally right, you can't edit the React blocks with ACF. I didn't realize that. 🤦‍♂️

**Comment by kaelansmith** [comment]
> Could you give us some more info on how you would imagine ACF would extend default core blocks?
> 
> Because all the results of block output for core blocks is React/JS native, I'm not sure how we could code anything here that would let users do anything meaningful with ACF adding settings to a block.

@lgladdy It would be hugely beneficial for headless WP sites that are truly decoupled -- i.e. where blocks (even core ones) just produce JSON (not HTML), consumed via REST api or GraphQL, and rendered by the user in some decoupled application using their own rendering method. I realize the ACF team probably only cares about developing features that work for native/traditional WP sites... but just thought I'd share that there is a very real use case over in headless WP land. If you don't think it'll ever become an internal priority, could you help point me in the direction of what it might take to build this? Specifically what sort of ACF internals a plugin for this might need to interface with?
