### ISSUE TITLE
PHP error with WordPress 5.5 and ACF 5.9-beta 4 wp_make_content_images_responsive

### ISSUE THREAD

**Issue by Zealth57** [AdvancedCustomFields/acf#339]
I'm running ACF Version 5.9.0-beta4 and WordPress 5.5-beta3-48630 (latest nightly as of 7/27). When I use a WYSIWYG field as part of my field group, I get the following deprecated PHP warning: "wp_make_content_images_responsive is deprecated since version 5.5.0! Use wp_filter_content_tags() instead." My field groups are part of an ACF block integration, here is the complete stack trace of the error:

wp-includes/functions.php:4773
wp_make_content_images_responsive()
wp-includes/class-wp-hook.php:287
apply_filters('acf_the_content')
wp-content/plugins/advanced-custom-fields-pro/includes/fields/class-acf-field-wysiwyg.php:471
acf_field_wysiwyg->format_value()
wp-includes/class-wp-hook.php:287
apply_filters_ref_array('acf/format_value/type=wysiwyg')
wp-content/plugins/advanced-custom-fields-pro/includes/acf-hook-functions.php:101
_acf_apply_hook_variations()
wp-includes/class-wp-hook.php:287
apply_filters('acf/format_value')
wp-content/plugins/advanced-custom-fields-pro/includes/acf-value-functions.php:141
acf_format_value()
wp-content/plugins/advanced-custom-fields-pro/pro/fields/class-acf-field-repeater.php:602
acf_field_repeater->format_value()
wp-includes/class-wp-hook.php:287
apply_filters_ref_array('acf/format_value/type=repeater')
wp-content/plugins/advanced-custom-fields-pro/includes/acf-hook-functions.php:101
_acf_apply_hook_variations()
wp-includes/class-wp-hook.php:287
apply_filters('acf/format_value')
wp-content/plugins/advanced-custom-fields-pro/includes/acf-value-functions.php:141
acf_format_value()
wp-content/plugins/advanced-custom-fields-pro/includes/api/api-template.php:342
get_field_objects()
wp-content/plugins/advanced-custom-fields-pro/includes/api/api-template.php:269
get_fields()
wp-content/mu-plugins/Maeve/MaeveBlocks/render/index.php:6
acf_render_block()
wp-content/plugins/advanced-custom-fields-pro/pro/blocks.php:292
acf_rendered_block()
wp-includes/class-wp-block.php:217
WP_Block->render()
wp-includes/blocks.php:720
render_block()
wp-includes/blocks.php:758
do_blocks()
wp-includes/class-wp-hook.php:287
apply_filters('the_content')
wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:1683
WP_REST_Posts_Controller->prepare_item_for_response()
wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php:505
WP_REST_Posts_Controller->get_item()
wp-includes/rest-api/class-wp-rest-server.php:1050
WP_REST_Server->dispatch()
wp-includes/rest-api.php:463
rest_do_request()
wp-includes/rest-api.php:1983
rest_preload_api_request()
Unknown location
array_reduce()
wp-admin/edit-form-blocks.php:77

**Comment by elliotcondon** [comment]
Thanks @Zealth57. We've got this bug fixed already and will include in the upcoming beta5 release 👍

**Comment by Zealth57** [comment]
Perfect! Any ETA on the next beta?

**Comment by elliotcondon** [comment]
Beta5 will be released later today!

**Comment by Zealth57** [comment]
Running the latest WP nightly and beta5 the deprecation error is gone, and my OCD of php errors during dev has been satisfied. Thanks again!
