### ISSUE TITLE
Feature Requests: Option Pages.

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#346]
1. Have the ability to place the Option Pages anywhere we want in the Dashboard's menu. Frankly I wanted to move the Option page higher up above the Appearance menu, but I don't think that's possible... or is it?

2. Ability to export the Option pages data and import it to another website, or simply export the data as a backup. If the Options were registered as a cpt, the Tools -> Import/Export was going to take care of it... In the meantime I'll have a look where and how the data is stored in the database and maybe do the import/exports with sql commands...

**Comment by elliotcondon** [comment]
Hi @nick6352683 

Thanks for the feature requests.

1. This should be possible using the "position" setting as described here: https://www.advancedcustomfields.com/resources/acf_add_options_page/

2. Great idea. I'll add this to the to-do list.

**Comment by nick6352683** [comment]
1. Well that was embarrassing ! I was looking at this page https://www.advancedcustomfields.com/resources/options-page/ and I thought that was it... I had tried "menu_position" which is used for CPT, but of course did not work.

Thanks for pointing me in the right direction, all is sorted out now... Because of issue 2, I'll leave it up to you to close this or not...
