### ISSUE TITLE
BUG: "Post Object" fields can not be cleared

### ISSUE THREAD

**Issue by yaquawa** [AdvancedCustomFields/acf#350]
Hi there, I found a bug that "Post Object" fields have no way to be cleared once they are set, can we fix this in the next version? Thanks!

**Comment by elliotcondon** [comment]
Hi @yaquawa 

Can you please check the field settings and ensure "Allow Null" is enabled?

**Comment by yaquawa** [comment]
@elliotcondon Thanks! Works!!
