### ISSUE TITLE
Postbox headers visible when group style set to seamless (As of WP 5.5)

### ISSUE THREAD

**Issue by strive-phil** [AdvancedCustomFields/acf#354]
WP 5.5 added a wrapping div around the postbox handles that were previously hidden by ACF when the group style is set to seamless.

Tested in classic editor / Not tested with gutenberg

See changeset: https://github.com/WordPress/WordPress/commit/22d0cd6c963d4ac0e203f7423294c15fb2e5d45a#diff-3240dc6a0be56a00a16bd3b294a1d398

![image](https://user-images.githubusercontent.com/18400737/90023128-4302d980-dcab-11ea-8855-d392fe905036.png)

https://github.com/AdvancedCustomFields/acf/blob/eef8fda7e3cdd7d27ec2c7c9649d73a916e79a83/assets/build/css/_fields.scss#L453-L457

![image](https://user-images.githubusercontent.com/18400737/90023717-f5d33780-dcab-11ea-9cb3-46443321b1c8.png)

**Comment by elliotcondon** [comment]
Hi @strive-phil 

Thanks for the bug report,
Elliot here - ACF dev.

I've got this issue on my to-do for today and will hope to release an update shortly :)

**Comment by elliotcondon** [comment]
Update: We have released a 5.8.14 update to take care of this bug - thanks again for your help!​​

**Comment by strive-phil** [comment]
Fix looks good to me. Thanks!
