### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by wackywired135** [AdvancedCustomFields/acf#36]
Looks like your local .gitignore file doesn't exclude macOS created `.DS_Store` files. You'll probably want these in your global gitignore since it looks like you're using macOS:
```
.DS_Store
.DS_Store?
._*
.Spotlight-V100
.Trashes
```

**Comment by elliotcondon** [comment]
Thanks @wackywired135 

`.DS_Store` is already ignored, but it's possible that previous hidden files have not been deleted from the repo.
