### ISSUE TITLE
Align argument for acf_register_block_type has no effect

### ISSUE THREAD

**Issue by noknokcody** [AdvancedCustomFields/acf#360]
Trying to build a few custom blocks with ACF PRO but I can't seem to get the align argument working. The block I'm currently building requires either the 'full' or 'wide' layouts but neither layout works when I set the alignment flag. I've attempted rebuilding the block on a new page and even tried creating a brand new block entirely. I've also tried downgrading my ACF version to the last version I can remember this working for me for. I've also read the documentation carefully to try to figure out what's wrong here and still can't figure it out.

Screenshot: Register Call
![code](https://user-images.githubusercontent.com/56014932/90348007-2aae0880-e077-11ea-903c-49f4e6bad2f4.png)

Screenshot: Block
![Capture](https://user-images.githubusercontent.com/56014932/90348005-297cdb80-e077-11ea-9c64-dc1311c05427.PNG)

Any help would be greatly appreciated

**Comment by elliotcondon** [comment]
Hi @noknokcody 

Thanks for the question.

1. To customize the available "align" options, please use the 'supports' setting to specify the 'align' options like so:
```
'supports' => array(
    'align' => array( 'full', 'wide' ),
)
```

2. To specify the initial alignment value, do as you already are - setting the "align" setting value to "full".
It may be possible that the reason why this is not working is due to a bug that we recently fixed in version 5.9. Can you please update to 5.9 when next possible and test again?

**Comment by noknokcody** [comment]
Hi @elliotcondon

Thanks for your quick reply. 

I've updated to ACF to the latest version (Excited for innerblocks btw) 

Sadly after making the changes you suggested I no longer seem to have the option for alignment.

Here's my environment info / plugin list

- WordPress 5.4.2
- ACF 5.9
- ACF Extended 0.8.6.3
- Max Mega Menu 2.8
- Woocommerce 4.2.2
- Query Monitor 3.6.0

Things I've tried:
- Disabling all plugins except acf
- Checked block is registered on 'acf/init' hook
- Different variations of the align and supports property

```
 
    function init_block() {
        if( !function_exists( 'acf_register_block_type' ) ) {
            return;
        }

        acf_register_block_type([
            'name'            => $this->blok_id,
            'title'           => __( 'Triple Feature' ),
            'description'     => __( '' ),
            'category'        => 'nokbloks-prefabs',
            'mode'            => 'preview',
            'align'           => 'full',
            'render_callback' => 'npb_render',
            'supports' => [
                'align' => [ 'full', 'wide' ],
            ]
        ]);
    }
```
Output:
![image](https://user-images.githubusercontent.com/56014932/90454858-bbe4b400-e137-11ea-9948-2caf78b940b1.png)

Normally I'd attempt to track these issues further but in all honesty, the realm of React/Guttenberg integration in WordPress scares me a little haha

**Comment by elliotcondon** [comment]
@noknokcody Thanks for the code snippet and screenshot. I've just tested this, but am seeing a different result. I've tweaked your code example ever so slightly, and attached a screenshot of the result - which does show the "align" toolbar with appropriate settings.

```php
acf_register_block_type([
            'name'            => 'triple',
            'title'           => __( 'Triple Feature' ),
            'description'     => __( '' ),
            'category'        => 'nokbloks-prefabs',
            'mode'            => 'preview',
            'align'           => '',
            'render_callback'	=> function( $block ){
				echo 'Triple test.';
			},
            'supports' => [
                'align' => [ 'full', 'wide' ],
            ]
]);
```

<img width="932" alt="Screen Shot 2020-08-18 at 4 14 21 pm" src="https://user-images.githubusercontent.com/2296425/90477085-1993f300-e16e-11ea-82b3-b253144aa850.png">

**Comment by noknokcody** [comment]
Thanks for all your help here.

I think I got something, your theme tipped me off. I've activated the twentytwenty theme and the alignment properties are working as expected. Look like we got a lead!

![image](https://user-images.githubusercontent.com/56014932/90480315-66c69380-e173-11ea-8ced-fa16880d956b.png)

I'm using a blank theme at the moment. Maybe it could be that I'm missing a theme support flag for Guttenberg the alignment properties ( or something similar ).

I will post here if I find anything more although any ideas appreciated! :)

**Comment by noknokcody** [comment]
Problem found between chair and keyboard.

All solved, thank you
```

if ( !function_exists( '_launchpad_setup' ) ) {
	/**
	 * Sets up theme defaults and registers support for various WordPress features.
	 *
	 * Note that this function is hooked into the after_setup_theme hook, which
	 * runs before the init hook. The init hook is too late for some features, such
	 * as indicating support for post thumbnails.
	 */
	function _launchpad_setup() {
                ....

        	/** Alignment Support */
       		add_theme_support( 'align-full' );
        	add_theme_support( 'align-wide' );

                ....
	}
}
add_action( 'after_setup_theme', '_launchpad_setup' );
```
