### ISSUE TITLE
Create group subfields with REST API

### ISSUE THREAD

**Issue by henrique-voni** [AdvancedCustomFields/acf#361]
I have a group field that i would like to populate with subfields via WP Rest API (POST). However, subfields must be created if not already exist. Is it possible? 

I can provide more details of my application if needed.

Thanks!

**Comment by elliotcondon** [comment]
Hi @henrique-voni 

This question is a little outside the scope for the support we offer, but I'll be happy to point you in the right direction.

Firstly, checkout this guide for some basics around custom REST API endpoints:
https://developer.wordpress.org/rest-api/extending-the-rest-api/adding-custom-endpoints/

Next, checkout the `update_field()` function for info on updating existing fields:
https://www.advancedcustomfields.com/resources/update_field/

If you are working with a Repeater / Flexible Content field, and want to update sub field values, please checkout these additional functions:
https://www.advancedcustomfields.com/resources/have_rows/
https://www.advancedcustomfields.com/resources/update_sub_field/
https://www.advancedcustomfields.com/resources/update_row/
https://www.advancedcustomfields.com/resources/add_row/

Wishing you all the best 👍.

**Comment by henrique-voni** [comment]
Thank you very much, Elliot. I wasn't sure if custom endpoints were required, but i guess they'll do the job. 

Best,
Henrique
