### ISSUE TITLE
jQuery 3.5.1 in the admin breaks custom blocks

### ISSUE THREAD

**Issue by Zealth57** [AdvancedCustomFields/acf#363]
When using the jQuery update test plugin https://github.com/WordPress/wp-jquery-update-test developed by some core contributors and the settings of:

jQuery: 3.5.1
jQuery Migrate: enabled (or disabled both break)
jQuery UI: 1.12.1

all custom blocks after you save a page and come back to it (or any existing ones you created before activating the plugin) will say: "Your site doesn’t include support for the "acf/{block-name}" block. You can leave this block intact or remove it entirely." There are no obvious JS errors that break things, they simply don't work. 

This configuration is tentatively scheduled to be shipped with WordPress 5.6 https://make.wordpress.org/core/2020/06/29/updating-jquery-version-shipped-with-wordpress/ so not super urgent but wanted to flag this early to give you a chance to fix.

**Comment by elliotcondon** [comment]
Hi @Zealth57 

Thanks for the heads-up. I'll add this to our list and make sure everything works with the newer version of jQuery. 
Really excited about WP adopting a modern jQuery version - this will definitely lead to some performance improvements!

**Comment by canofpopcom** [comment]
Yep - same here :) - looking forward to this getting resolved and the WP Admin area UI adopting modern versions of jQuery :)

**Comment by elliotcondon** [comment]
@Zealth57 @canofpopcom - We're currently testing ACF PRO with WP 5.6-RC1 bit haven't yet seen any issues preventing block types from being registered or used within the Gutenberg editor. It may be that the issue only exists with the "wp-jquery-update-test" plugin, however, can I ask you both to test the issue once more? And also with WP 5.6-RC1?

**Comment by Zealth57** [comment]
Yep looks like with ACF 5.9.3 and 5.6-RC1 things are working as expected. Must be something wrong with the configuration I was using back then, it was a little older version of ACF, an old version of their migrate tester plugin, and WP 5.5. Seems like whatever the conflict was has since been resolved, I'll keep an eye on things and open this back up if I run into problems. For now I'd consider this resolved.
