### ISSUE TITLE
New Dashicons not working with acf_register_block_type

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#366]
Hey Elliot,

do you have any idea why the new dashicons [https://developer.wordpress.org/resource/dashicons/](https://developer.wordpress.org/resource/dashicons/) not working with acf_register_block_type?

If we use the new dashicons (e.g. `dashicons-businesswoman` or `dashicons-camera-alt`, there is nothing appears.

```
acf_register_block_type(
	array(
		'name' => '',
		'title' => '',
		'description' => '',
		'icon' => 'camera-alt',
		...
	)
);
```

**Comment by nfsarmento** [comment]
@CreativeDive remove the -alt, use only 'icon' => 'camera',

**Comment by CreativeDive** [comment]
@nfsarmento thank you, I will try this. And how I can solve this in other cases like the "businesswoman" icon?

**Comment by nfsarmento** [comment]
@CreativeDive use only  'icon' => 'businesswoman',

**Comment by CreativeDive** [comment]
@nfsarmento yes it works. It seems this was fixed by WordPress in one of the last releases.

**Comment by nfsarmento** [comment]
@CreativeDive It was always like this :)

**Comment by nfsarmento** [comment]
@CreativeDive have a look on this, https://wordpress.github.io/gutenberg/?path=/story/icons-icon--library
