### ISSUE TITLE
The Matrix control component...

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#370]
Hi Elliot,

I successfully deployed the Matrix control in one of my ACF based container block, by simply following your example. That said, the CSS class(es) that come out are different from what the Cover block generates:

So the ACF block generates as an example: is-position-center right, while the Cover block generates is-position-center-right. As you can see ACF actually shoots out 2 CSS class names, but the Cover block only one. SO,

1. Am I doing something wrong? , or
2. Was this done on purpose on your behalf? , or
3. Is there anything I can do to fix in my ACF block to display the CSS classname exactly as the Cover block? Because if I do, all I have to do is deploy the Matrix, and simply add the CSS class wp-block-cover to the main outside div, and let Gutenberg take care of the rest, and I don't have to worry about making any CSS rules myself...

As usual, thanks in advance,
Nick

**Comment by elliotcondon** [comment]
Hi @nick6352683 

The "align_content" value will return as "center right" with a space in between the y and x settings.
If you would like to use this as "center-right", please use a `str_replace()` solution or the [sanitize_title()](https://developer.wordpress.org/reference/functions/sanitize_title/) function.

**Comment by nick6352683** [comment]
Thanks for the hint, the str_replace() function should be fine...
