### ISSUE TITLE
ACF Documentation "__experimental_jsx"

### ISSUE THREAD

**Issue by kanlukasz** [AdvancedCustomFields/acf#372]
Hello

**Here you have:**
https://www.advancedcustomfields.com/resources/acf_register_block_type/#examples
![obraz](https://user-images.githubusercontent.com/30685349/91314865-4b810700-e7b7-11ea-9879-c0ae810c5fba.png)

**But here:**
https://www.advancedcustomfields.com/blog/acf-5-9-0-release-inner-blocks-ui-improvements-and-exciting-features/
![obraz](https://user-images.githubusercontent.com/30685349/91314921-5f2c6d80-e7b7-11ea-8269-c62be0837449.png)

**The documentation is probably out of date because:**
```From 5.9.0-RC1 onward, the “__experimental_jsx” flag needed for <InnerBlocks /> support is now simply “jsx”. ```

**Comment by elliotcondon** [comment]
Thanks @kanlukasz. I've just updated the documentation to remove those outdated references.
