### ISSUE TITLE
Issues with both WP 5.5.1 & Gutenberg 8.9.0

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#379]
Hi Elliot,

I always have the Gutenberg plugin active, so I'm assuming the first issue I will mention started from WP 5.5.1, but I could be wrong, it might have started from v5.5, or even before that...

1. I have a fresh WP 5.5.1 installation, and out of the box on the front end, the Additional CSS classes do not show up. This happens only for the ACF blocks. The built in blocks, as an example the Cover block is fine.

- Installing Gutenberg 8.8 solves the issue (this is the previous version from 2 weeks ago).

2. Now updating the Gutenberg plugin to v8.9, the Additional CSS classes show up (so it fixes the first issue caused by WP 5.5.1), however all the block internal CSS inside the block template files do not show up on the front end. In other words, in the block template files the following does not show up on the front end, thus rendering many block customizations utterly useless.

<style type="text/css">
...
...
</style>

- Of course, reverting back to Gutenberg 8.8 fixes the issue, and all the internal CSS found in the block template files show up again. The strange thing is that everything works fine in the editor, all the css values and ACF fields found inside the <style type="text/css"> block are fine, it's just the front end that v8.9 screws up. 

I keep forgetting, I still have to check if the anchors are working or not, and I'll report back... 

As always, thanks,
Nick.

**Comment by nick6352683** [comment]
Update: Anchors are fine, so as the alignwide and alignfull controls.

**Comment by CreativeDive** [comment]
@elliotcondon @nick6352683 yes I can confirm. All the ACF block content is empty on the frontend view, after updating to Gutenberg 8.9.0

... and the story goes on, that after every Gutenberg update something new goes wrong. Something very annoying and exhausting for a plugin author like you @elliotcondon

**Comment by nick6352683** [comment]
Today they released v8.9.1, which does absolutely nothing to fix what they broke - Some of my blocks in the editor look funny too, but with little bit of CSS I can fix those (I hope).

**Comment by elliotcondon** [comment]
Thanks team! I'll take a look into this shortly. Fingers crossed this is a simple issue to fix...

**Comment by grahammtbr** [comment]
So what I found with testing, as I have two sites with almost the exact same blocks, but one was newer and had a few updates, and the newer one didn't have the front-end rendering issue - If you have any HTML content in your block above the ACF block wrapper, `<div id="<?php echo esc_attr($id); ?>" class="<?php echo esc_attr($className); ?>">`, everything contained within the ACF block wrapper stops rendering with Gutenberg 8.9.1. This was more of an error on my end on one site that just happened to work for past 6 months.

**Comment by nick6352683** [comment]
Since ACF Blocks have issues with both the latest WP and Gutenberg versions, is there any urgency or at least some sort of priority with the ACF devs. to solve these latest issues?

**Comment by elliotcondon** [comment]
@nick6352683 Will be investigating these issues shortly.

**Comment by nick6352683** [comment]
Thanks Elliot.

**Comment by nick6352683** [comment]
UPDATE: I just realized that Gutenberg in the meantime had quietly released 2 more versions, and we are at v8.9.3.

The good news is that v8.9.3 solves both of the issues introduced with WP 5.5.1.

The tricky part for you Elliot is you have to make a decision to either instruct everyone who is on WP 5.5.1 (and I'm guessing that's the vast majority), to activate Gutenberg 8.9.3, or try to fix the issue ACF is having with WP 5.5.1 without the latest version of Gutenberg being activated. 

WP 5.6 is due in December and until then there is the potential that many who want to add custom CSS classes, won't be able to unless:

1. ACF addresses the WP 5.5.1 issue with the custom CSS classes, or
2. The latest Gutenberg plugin is also activated, or,
3. Place the ACF Blocks inside Group Blocks, and apply the custom CSS classes by using the said Group Blocks.

Ideally WP should come up with 5.5.2 and should include the fix they did in Gutenberg 8.9.3 !

**Comment by nick6352683** [comment]
I think with the latest Gutenberg plugin updates and with WP 5.6 beta1 things have been fixed by their end...
