### ISSUE TITLE
Repeater Field Add Button not appear on screen

### ISSUE THREAD

**Issue by rmaaia** [AdvancedCustomFields/acf#390]
![DE7E5260-9D7D-48D6-9222-B33BCDFE0C73](https://user-images.githubusercontent.com/61801718/94364729-e5332100-00a1-11eb-867e-3f43b1c308e9.jpeg)

Hey there,
has this happened to you?

The reapeter field add button isn`t displayed. 
All fields groups are synced.

1) This is a new install and database is new too.
2) No error on console
3) No plugins are installed

ACF PRO 5.9.1

How i can fix it?

Thanks :)

**Comment by rmaaia** [comment]
![0F8D8BB0-2C30-4AE2-B1AA-D8DF48BAE78C](https://user-images.githubusercontent.com/61801718/94367411-f9cce480-00b4-11eb-8b2a-af030c4efb8e.jpeg)

I found that the repeater subfields are not synchronizing and the parent field is empty.

**Comment by elliotcondon** [comment]
Hi @rmaaia 

Thanks for the question and follow up. Yes, it appears that your Repeater field is missing any sub field definitions. Can you import or add these in?

**Comment by rmaaia** [comment]
Hi @elliotcondon,
thanks for the answer.

So, i discorver that error comes from my theme. The script to auto sync groups not recognized the repeater subfields in json.

Got corrected :)

Thank you.

**Comment by rmaaia** [comment]
Fixed
