### ISSUE TITLE
Call to a member function register_field_type() on null on line 204 in advanced-custom-fields/includes/fields.php

### ISSUE THREAD

**Issue by djvdorp** [AdvancedCustomFields/acf#40]
**Version:** ACF Free 5.6.10
**PHP:** 7.1
**WP:** 4.9.6

While trying to preview or update a page in the WordPress admin I get an error that looks like this one:

```
Call to a member function register_field_type() on null on line 204 in TRUNCATED/wp-content/plugins/advanced-custom-fields/includes/fields.php
#0 TRUNCATED/wp-content/plugins/advanced-custom-fields/includes/fields/class-acf-field-text.php(167): acf_register_field_type('acf_field_text')
#1 TRUNCATED/wp-content/plugins/advanced-custom-fields/includes/api/api-helpers.php(397): include_once('TRUNCATED')
#2 TRUNCATED/wp-content/plugins/advanced-custom-fields/acf.php(261): acf_include('includes/fields...')
#3 TRUNCATED/wp/wp-includes/class-wp-hook.php(286): ACF->init('')
#4 TRUNCATED/wp/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#5 TRUNCATED/wp/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#6 TRUNCATED/wp/wp-settings.php(450): do_action('init')
#7 TRUNCATED/wp-config.php(27): require_once('TRUNCATED')
#8 TRUNCATED/wp/wp-load.php(42): require_once('TRUNCATED')
#9 TRUNCATED/wp/wp-admin/admin.php(31): require_once('TRUNCATED')
#10 TRUNCATED/wp/wp-admin/post.php(12): require_once('TRUNCATED')
#11 {main}
```

Relevant version information:
```
    "wpackagist-plugin/advanced-custom-fields": "5.6.10",
    "wpackagist-plugin/acf-content-analysis-for-yoast-seo": "2.0.1",
```

Let me know if I missed anything here. Would love to help getting rid of this error.

**Comment by elliotcondon** [comment]
Hi @djvdorp 

Thanks for the bug report.
I'm not able to replicate this from my end, are you able to setup a fresh WP install without an other plugins and see if the issue persists?

**Comment by djvdorp** [comment]
Hi @elliotcondon 

Sorry for the delayed reply. I haven't been able to reproduce the issue somewhere else yet, so it could potentially be related to another plugin or some setting that is off. I want to investigate this further soon!

**Comment by djvdorp** [comment]
Hi @elliotcondon 

We found out that it is likely related to a plugin we're using, [vBLink](https://vblink.apphero.in/).
Please correct me if we're wrong, but it looks like this could be what is happening:
- ACF uses a global instance of itself, which somehow gets broken when vBLink is enabled
- ACF initialize itself in 2 hooks: first when plugins are loaded and then in init
- it looks like vBLink makes ACF lose the global instance that ACF uses for itself
- what happens then is that only init is run and not initialize which causes some fields to not be there
- that results in above error

My colleague was able to find a (horrible) work-around for this, which is rather dirty but works:
```
[...]

// BEGIN VBLINK CODE
// making a backup so we can reassign values to their originals after it is loaded.
$requestSuperglobals = array($_GET, $_POST, $_REQUEST);
// END VBLINK CODE

// WORKAROUND: Ugly fix for not breaking page save due error in ACF
$saveAcf = $GLOBALS['acf'];

[...]

// BEGIN VBLINK CODE
list($_GET, $_POST, $_REQUEST) = $requestSuperglobals; <-- vBLink code
// END VBLINK CODE

// WORKAROUND: Restore ACF
$GLOBALS['acf'] = $saveAcf;

[...]
```

Since vBLink is not open source software, I can most likely not paste (all of the) the exact code, but I hope the above description makes sense to you to give you an idea what happens and what goes wrong here.

**Comment by elliotcondon** [comment]
Hi @djvdorp 

Thanks for the reply and info.

ACF does use a global variable called `$acf`, and this is initialized at the end of the main acf.php file via the function `acf();`

I'm not sure why the vBLink plugin would be causing such an issue, but this will definitely be something the developers should be aware of - can you please contact them and let them know?

Thanks
Elliot

**Comment by djvdorp** [comment]
Hi @elliotcondon 

I would love to hit up the vBlink developers and inform them about this, but I am having a very hard time reaching them currently. I mostly wanted to share the workaround here for others right now.
I am closing this issue since I don't think there is much that you (on behalf of ACF) can do about this?

**Comment by sultanboss** [comment]
After updating to latest ACF, faced same issue and thanks to @djvdorp for the tricky solution :)
