### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by justinkruit** [AdvancedCustomFields/acf#404]
I'm trying to limit a post object to a specific post type when I ran into this problem. It also happens when I press the taxonomy list.

WordPress 5.5.3, ACF PRO 5.9.2

![image](https://user-images.githubusercontent.com/1642830/97856220-4d59d000-1cfc-11eb-88cf-97ed396f6d74.png)

**Comment by elliotcondon** [comment]
Hi @justinkruit 

Thanks for the bug report and apologies for the issue. This problem has been resolved and a hotfix applied to the plugin files online. We're also hoping to release a 5.9.3 version shortly.

In the meantime, can you please redownload the ACF PRO plugin files and let me know if this fixes your problem?
- The only files that have changed are the ones inside the "assets/js" folder 👍.

**Comment by justinkruit** [comment]
Sorry, didn't have the time to test it in between. Installed 5.9.3 and the problem is solved. 

Thanks for the quick updates!

**Comment by elliotcondon** [comment]
Fantastic 🎉
