### ISSUE TITLE
ACF 5.9.3: Uncaught TypeError: acf.add_action is not a function

### ISSUE THREAD

**Issue by hirasso** [AdvancedCustomFields/acf#406]
Hi there,

I just noticed that after updating to `5.9.3` my calls to some ACF Javascript API functions are broken, e.g.:

```console
Uncaught TypeError: acf.add_action is not a function
```

I noticed the `newCompatibility` in `acf-input.js`:

```javascript
/**
*  acf (compatibility)
*
*  Compatibility layer for the acf object
*
*  @date	15/2/18
*  @since	5.6.9
*
*  @param	void
*  @return	void
*/

var _acf = acf.newCompatibility(acf, {
  
  // storage
  l10n:	{},
  o:		{},
  fields: {},
  
  // changed function names
  update:					acf.set,
  add_action:				acf.addAction,
  remove_action:			acf.removeAction,
  do_action:				acf.doAction,
  add_filter:				acf.addFilter,
  remove_filter:			acf.removeFilter,
  apply_filters:			acf.applyFilters,
  parse_args:				acf.parseArgs,
  disable_el:				acf.disable,
  disable_form:			acf.disable,
  enable_el:				acf.enable,
  enable_form:			acf.enable,
  update_user_setting:	acf.updateUserSetting,
  prepare_for_ajax:		acf.prepareForAjax,
  is_ajax_success:		acf.isAjaxSuccess,
  remove_el:				acf.remove,
  remove_tr:				acf.remove,
  str_replace:			acf.strReplace,
  render_select:			acf.renderSelect,
  get_uniqid:				acf.uniqid,
  serialize_form:			acf.serialize,
  esc_html:				acf.strEscape,
  str_sanitize:			acf.strSanitize,

});
```
How does this work?

**Comment by elliotcondon** [comment]
Hi @hirasso 

I've just tested this report, but am unable to replicate any issues accessing legacy functions such as `acf.add_filter()`.

If it's not too much to ask, can you please spin up a fresh WP site in "Local by Flywheel" and try to replicate the issue? Please keep the default theme active and edit the functions.php file with any extra logic needed.​

​​If you can replicate the issue, please export the site (from flywheel app, right click the site and click "export") and attach to your next reply. ​I'll import this and get to work replicating / testing the issue :)

**Comment by hirasso** [comment]
Hi Elliot,

after the weekend I tested it again today, but wasn't able to reproduce the issue – it seems to be a sneaky one. In my case the error was caused by 'acf-autosize', looking there, I discovered that they also have an issue for this:

https://github.com/yeah8000/acf-autosize/issues/11

...I haven't used Local by Flywheel before, but next time the error pops up I might take the time to create an export.
