### ISSUE TITLE
Custom namespace when registering ACF blocks

### ISSUE THREAD

**Issue by fabrikatdigital** [AdvancedCustomFields/acf#409]
Hey,

Thanks for the awesome block integration!

Wondering if it is somehow possible to create custom namespaces when registering blocks. Couldn't find anything in the docs.

**Comment by elliotcondon** [comment]
Hi @fabrikatdigital 

Can you please elaborate a little more on this question? ACF will currently prefix all blocks with an "acf/" namespace to comply with WP requirements, but it is also possible to "sub namespace" this by registering a block with the name "my/special-block".

**Comment by fabrikatdigital** [comment]
Hey @elliotcondon 

Thanks for the quick answer. I was wondering if it is possible to change the **acf** namespace.

The sub namespacing is what we are already doing and it's working great, but was just wondering. :-)

**Comment by elliotcondon** [comment]
Hi @fabrikatdigital. The "acf/register_block_type_args" filter will provide you with full control over the registered block args (including the full block name w namespace). It will technically be possible to modify the namespace via this filter, however, I'm not sure of any issue that may arise from doing so.

**Comment by fabrikatdigital** [comment]
We'll stick with your first suggestion, thanks @elliotcondon !
