### ISSUE TITLE
Preload blocks doesn't include acf-block-preview class

### ISSUE THREAD

**Issue by Zealth57** [AdvancedCustomFields/acf#410]
When using the preload blocks constant with true, and my blocks are in "preview" mode they all load wrapped in a <div> with no class on it. I'd expect them to load with class="acf-block-preview" on them. If I make a change to any of the data in the sidebar, it refreshes the block and does add the class because it recognizes it's in preview mode. I'm using that class in my stylesheet so that my styles only affect my block and not the ACF inputs when in edit mode.

**Comment by elliotcondon** [comment]
Hi @Zealth57 

Thanks for the bug report. I'll add this to the list and take a look shorty.

**Comment by Zealth57** [comment]
Hey @elliotcondon just noticed that 5.9.4 fixed this problem for me, but I didn't see anything referenced about the bug fix in the changelog. Was this an intentional fix and we can mark this complete? Now that it has that class I can start really using and testing the feature more to see if there's any problems. So far working great and I use a very custom setup with StencilJS web components.

**Comment by elliotcondon** [comment]
Hi @Zealth57 

Sorry about that. Yes, the bug is fixed, and was listed in the changelog under this item - which is a different UX problem but the same code issue:
```
* Fix - Fixed bug preventing preloading blocks that contain multiple parent DOM elements.
```

**Comment by Zealth57** [comment]
Ah okay great, thanks for the confirmation and great work as always!
