### ISSUE TITLE
[QUESTION] ACF And meta fields Database performance

### ISSUE THREAD

**Issue by isuke01** [AdvancedCustomFields/acf#414]
Hey,
it is more a question, that I asked myself long time ago. 
Saving data to custom DB table exclusive for ACF can improve performance significantly since WP meta table and how it works is just garbage in performance (See WooCommerce). I discovered it long time ago. Especially Repeaters. 

There are some plugins/codes that we can use today:
https://hookturn.io/downloads/acf-custom-database-tables/
https://wordpress.org/plugins/acf-fields-in-custom-table/
 But there is always commmon problem, with custom ACF fields. 

And here is my question, Is there any common hook that will allow to override default ACF save/read to DB methods, which we can hook to use some different methods to save/retrive data withot saving them to wp_post_meta?

Edit:
Dont understand, me wrong, I love ACF and ACF PRO, Im using it almost every day, that's why I would love to find way to improve it even more! <3

**Comment by nick6352683** [comment]
I could be wrong, but I don't think there is such a hook mentioned above, but again I could be completely wrong here.

I saw and downloaded the second plugin mentioned above yesterday from the wordpress.org plugin repository, but did not have a chance to test it yet. Has anyone tested it if it works? Also, be aware that both plugins are partial solutions, as they don't support the repeater field type.

I totally agree with isuke01 about loving ACF Pro and love ways to improve it. In that at mind, the ideal solution for best database "management" would be to use ACF made Gutenberg blocks, but with that we solve the data issues, but introduce 2 HUGE issues, that does not exist with Meta Fields - so we break somethings that already work with Meta Fields.

1. Impossible to do front side forms, (a half baked solution to this is to allow users to use the blocks in the back site, and of course you have to limit what they can do once they get inside the backsite - not ideal, and not very professional, but a compromise for now - Block Templates, locking, permissions, etc...).

2. Impossible to do parametric searches. With Meta fields, and for example in a Real Estate website as an example, we can query the data to display properties between $400,000  and $1 million. With the data being stored in the post content with no data structure, as the actual data and design code all mixed up in one block of code "soup" - doing anything but simple searches, like the price being $1 million, or all properties in London, is impossible. A compromise to this is to use Taxonomies and do the best you can with them to "filter" the data.

The only solution that I can think of when it comes to complex searches within ACF Blocks, is to have a hybrid data storage system, where when creating your fields ACF Blocks in ACF Pro, you would have an option to save that specific field as usual in the post content or as a Meta Field. So in this example you would save all the fields in the post content, and the price field, and any other fields you want to perform complex (parametric) searches in a Meta Box. With this of course, Elliot has to also find a solution to display those Meta Fields in the Gutenberg blocks, which right now there is no way to connect (associate) the meta fields to the ACF blocks. There is one plugin that can display Meta Fields in Gutenberg blocks, so this is possible (speaking in general), but that plugin has nothing to do with ACF...

Until they find solutions to all these issues, WordPress is a very bad solution for big sites that function as "Application sites", like classifieds, directories of any kind, collections (of books, movies, etc...), Invoicing, CRM, among others.

**Comment by elliotcondon** [comment]
Hi @isuke01 

Thanks for the question.

There are always strong opinions over the architecture of WordPress' metdata tables, however, I must disagree that the current design is non-performant or garbage. The simplicity and scalability of metadata tables are fantastic! With the right caching, any website can be lightning fast, no matter the size.

If you're looking to create custom tables for meta, look no further than https://hookturn.io/downloads/acf-custom-database-tables/ - this is a very well made plugin.

You can also run your own CRUD logic by hooking into the "pre" filters on our get, update and delete functions.
- acf/pre_load_meta
- acf/pre_update_metadata
- acf/pre_delete_metadata

Please refer to the source code for information on these filter, and good luck with your project!

**Comment by isuke01** [comment]
Hey, @elliotcondon 

Thanks for your replay! I'll definitly look into those hooks you mentioned :)
My issue with perfomrance are mostly with repeater, nested repaters etc. But after some caching etc yes everything is great. 
Again I really love to work with ACF, and I just want to try to improve some stuff :D 

Actually I have  build few bigger websites using ACF + Languages etc and with few thousand posts, many post types and logic between them, nested in repeaters, with multi option what and where to display related to some posts/categories .... and logic to display (some clients just like to have hard time to set up things xD) Page: https://svw.no/. Everything is based on ACF and Polylang. And I think speed of this page is not bad, overall could be better but TIME TIME TIME RUSH!
But point is. Yes it required a lot of caching pre build index etc and custom Queries since default WP query is ultra slow VS custom SHORTINIT amd then custom query :)
