### ISSUE TITLE
Custom Field Settings stay there when selecting another field type

### ISSUE THREAD

**Issue by hirasso** [AdvancedCustomFields/acf#418]
Hi there,

just noticed a possible bug. I am adding a custom field setting to fields of type `text` like [described here](https://www.advancedcustomfields.com/resources/adding-custom-settings-fields/):

```php
function my_render_field_settings( $field ) {

  acf_render_field_setting( $field, array(
    'label'			=> __('Translatable?'),
    'instructions'	=> '',
    'name'			=> 'is_translatable',
    'type'			=> 'true_false',
    'ui'			=> 1,
  ), true);

}
add_action("acf/render_field_settings/type=text", 'my_render_field_settings', 9);
```
The field setting works as expected, but when I select another field type, it won't be hidden. Also, if I also register the setting for another field type like e.g. `textarea`, I will have two settings after switching from `text` to `textarea`:

![image](https://user-images.githubusercontent.com/869813/101275103-6fcf8500-37a3-11eb-8908-7ceb0c1b2e22.png)

Tested with:
ACF Version 5.9.3
WP Version 5.5.3
No other plugins, an empty theme with only this functionality.

**Comment by elliotcondon** [comment]
Hi @hirasso 

The `acf_render_field_setting()` function accepts 3 parameters. The last of which is used to describe the setting as a "global" setting. With this set to `true` as you have, the setting will not be associated with the specific field type and will result in the experience you describe.

Please set this parameter to `false`, or simply remove the definition (as the default value for this param is `false`) and the setting should work as expected.

**Comment by hirasso** [comment]
Oh my... thank you @elliotcondon !
