### ISSUE TITLE
ACF Blocks issue with Gutenberg 9.6

### ISSUE THREAD

**Issue by nick6352683** [AdvancedCustomFields/acf#426]
Jut a heads up Elliot,

They released Gutenberg 9.6 earlier today. When active if you have an ACF Block in the post/page, and when saving the post/page  you get a false message that your post might not have been saved, which of course it is not true... This does not happen of your post does not contain ACF Blocks, like the core blocks...

**Comment by elliotcondon** [comment]
Thanks @nick6352683. I'll keep my eye on it.

**Comment by nick6352683** [comment]
Update: The Gutenberg 9.7 plugin that was released yesterday fixed the issue !
