### ISSUE TITLE
All "parent" parameter when registering block

### ISSUE THREAD

**Issue by JiveDig** [AdvancedCustomFields/acf#438]
My specific use-case:

I have a Custom Columns block a Custom Column block. I want to make Custom Column only allowed inside Column Columns for (hopefully) obvious reasons.

For a native block this is quite easy via https://github.com/WordPress/gutenberg/blob/wp/5.6/packages/block-library/src/column/block.json#L5-L6

This would be a great (and seemingly/hopefully) simple addition. First learned about this via https://github.com/WordPress/gutenberg/issues/12931#issuecomment-751869860

**Comment by JiveDig** [comment]
Oh geez. I reeeeallly should have tested that first. It already works! This should be documented IMO.

I added `'parent' => [ 'acf/mai-columns' ],` to my column and it was hidden unless I was adding it inside my columns container block. Perfect 👍.

**Comment by elliotcondon** [comment]
Agreed. The docs mention you can use "Any argument from the JavaScript registerBlockType() function", but we can definitely update our list to include parent 👍

**Comment by JiveDig** [comment]
Yeah definitely user error here on my part. This one might be worth adding just to spark some ideas/creativity as people are reading the docs :)
