### ISSUE TITLE
PHP 8.0 (Deprecated) function Required parameter follows optional parameter

### ISSUE THREAD

**Issue by GasparSukk** [AdvancedCustomFields/acf#442]
> Deprecated: Required parameter $field follows optional parameter $value

https://github.com/AdvancedCustomFields/acf/blob/691bae36510e138d1e464d8db3852335c286ae7f/includes/acf-value-functions.php#L164

**Comment by elliotcondon** [comment]
Thanks @GasparSukk 

Looks like we missed this one in our last update. I've added this to our list and will ensure it is resolved in the next release

**Comment by mandelaloko** [comment]
@elliotcondon is this resolved? I have same problem.

**Comment by peterbrejassou** [comment]
Any news on this problem please ?

**Comment by GasparSukk** [comment]
Looks like it has been resolved in ACF 5.9.5 - https://github.com/AdvancedCustomFields/acf/commit/89421ceb6da6cd0951f62e6fb705dd8e5a9ba853
