### ISSUE TITLE
Php error in 5.9.4 --htmlspecialchars() expects parameter 1 to be string, array given--

### ISSUE THREAD

**Issue by wpsumo** [AdvancedCustomFields/acf#445]
```
htmlspecialchars() expects parameter 1 to be string, array given

wp-includes/formatting.php:4521
htmlspecialchars()
wp-includes/formatting.php:4521
esc_textarea()
wp-content/plugins/advanced-custom-fields-pro/includes/acf-input-functions.php:229
acf_get_textarea_input()
wp-content/plugins/advanced-custom-fields-pro/includes/acf-input-functions.php:209
acf_textarea_input()
wp-content/plugins/advanced-custom-fields-pro/includes/fields/class-acf-field-textarea.php:80
acf_field_textarea->render_field()
wp-includes/class-wp-hook.php:287
do_action_ref_array('acf/render_field/type=textarea')
wp-content/plugins/advanced-custom-fields-pro/includes/acf-hook-functions.php:105
_acf_apply_hook_variations()
wp-includes/class-wp-hook.php:287
do_action('acf/render_field')
wp-content/plugins/advanced-custom-fields-pro/includes/acf-field-functions.php:784
acf_render_field()
wp-content/plugins/advanced-custom-fields-pro/includes/acf-field-functions.php:744
acf_render_field_wrap()
wp-content/plugins/advanced-custom-fields-pro/includes/acf-field-functions.php:603
acf_render_fields()
wp-content/plugins/advanced-custom-fields-pro/includes/forms/form-post.php:208
ACF_Form_Post->render_meta_box()
wp-admin/includes/template.php:1389
do_meta_boxes()
wp-admin/includes/post.php:2315
the_block_editor_meta_boxes()
wp-admin/edit-form-blocks.php:434
```

**Comment by elliotcondon** [comment]
Hi @wpsumo 

Thanks for the bug report. This error suggests that your textarea `$value` is an array, which is quite odd. Is it possible that you have previously saved an array value for this field name, and then either changed the field's type to textarea or created a new textarea field with that existing name?

**Comment by wpsumo** [comment]
@elliotcondon  Could it be that I changed URL field to text? As the URL field no longer support the relative path and must be absolute (should be a feature request for that). So until that is fixed, so we don't have to insert `protocol:://domain::tld` for URL fields once its internal ones. As we can use relative or code it in the template for a cleaner view within wp-admin and acf. Just for cleaner and structure, but until this is fixed we had to use just text fields for fetching URL paths instead.
That means:

URL field => text field = same name and key.

Other potential arrays or if you refer specifically to the textarea field I can not remember.

**Comment by wpsumo** [comment]
@elliotcondon Solved it! It was my bad.

Used `number_format();` when it shouldn't be used. On a text field and not a number field where it should be text field and `number_format();` should be removed.

Problem solved and closed. Just make sure to bump up +1 on my request for url field to support relative paths and not forced to use `protocol:://domain::tld`

**Comment by deepwaterpixel** [comment]
I just wanted to chime in and say this thread helped me narrow down the 500 error being thrown on the edit-profile page, when I had an array value stored for a field that I changed to textarea to make it easier to read (some arrays are big enough that text field is too small), but I wasn't thinking ACF could be applying additional filtering to the values.  Switching from textarea to text fixed this problem for me.
