### ISSUE TITLE
The bottommost block is partially invisible (padding: 0 important)

### ISSUE THREAD

**Issue by denkharkov77** [AdvancedCustomFields/acf#448]
Hi Elliot!
In editor, the bottommost block is partially hidden
![image](https://user-images.githubusercontent.com/61991428/106046409-e7a69580-60ea-11eb-8fe2-24ac8555779c.png)
Resolve problem - /assets/css/acf-input.css 
.acf-postbox>.inside{margin:0 !important;padding:0 0 30px 0 !important}
(padding-bottom 30px)

Your plugin is the best! )))
Best regards, Denis.

**Comment by denkharkov77** [comment]
Windows 10
1920 px screen
google chrome
ACF 5.9.4 version
WP 5.6

**Comment by elliotcondon** [comment]
Hi @denkharkov77 

Thanks for the bug report. This issue has already been flagged with the WordPress team back in December of last year. You can find more information about the bug and proposed fix here: https://core.trac.wordpress.org/ticket/51920
