### ISSUE TITLE
ACF Block HTML quote being incorrectly escaped when using AlpineJS (with example repo to reproduce)

### ISSUE THREAD

**Issue by Jamiewarb** [AdvancedCustomFields/acf#453]
Hi there,

I've been working with ACF Blocks for a while, and have now encountered a strange problem I've not seen before.

I have registered a block which has AlpineJS syntax in it. E.G.

```html
<section x-data="{query: ''}" x-init="$watch('query', (value) => console.log(this) )"></section>
```

However, after adding this block and viewing it on the frontend, the final quote mark to closing `x-init` is escaped into `&#8221;`.

I don't know if this is caused by ACF Blocks or by WordPress.

![image](https://user-images.githubusercontent.com/2754728/106381558-86fcae80-63b1-11eb-8664-b76d44c5df8e.png)

This doesn't happen when using long functions, e.g. `function(value) { console.log(this) }`. Only with arrow functions.

## Expected Outcome

```html
<section x-data="{query: ''}" x-init="$watch('query', (value) => console.log(this) )"></section>
```

## Actual Outcome

```html
<section x-data="{query: ''}" x-init="$watch('query', (value) => console.log(this) )&#8221;></section>
```

## Steps to Reproduce

I have created a repo set up to reproduce the problem here: https://github.com/hex-digital/acf-bug-example/

- Install WordPress and add the ACF Pro plugin
- Clone this repo as a theme into the wp-content/themes directory
- Activate the theme
- Create a page
- Add the block called "Test Block" to the page
- Publish page
- Go to the page in browser, and view source code
- Observe the above described bug

**Comment by elliotcondon** [comment]
Hi @Jamiewarb 

Thanks for the bug report. From what you have described, I would be leaning towards this issue being some sort of escaping / validating conflict.

The beauty of dynamic blocks is that they are rendered dynamically when needed, instead of being saved into the database as raw HTML. Because of this, we can rule out any potential DB character escaping issue and focus on why/when the `"` character is being converted to `&#8221;` on the front-end.

The part which is baffling me is why the bug can't be produced with an arrow function 🤷‍♂️. I doubt there are any PHP functions that are content-aware of JS syntax (unless you have a plugin that could be doing this), so it is very unlikely that the variable here is JS syntax. I would be more inclined to believe the variable at play is character based. Perhaps there is WP function hooked into "the_content" which is attempting to validate HTML attributes and is getting confused by the ones in your block?

I suggest working through the `the_content()` function and all the callbacks hooked into the `the_content` filter to discover when and where the `"` character gets converted to a `&#8221;`.

Let me know what you are able to find 👍.

**Comment by Jamiewarb** [comment]
Thanks @elliotcondon, will take a look. 

>why the bug **can't** be produced with an arrow function

Just to clarify this point, it is the opposite, that it is only produced with an arrow function - not with a regular function.

This leads me to think it may be something to do with the `=>` symbol.

I'll take a sweep through the content filter, but if that's the case it sounds like it's a Core WordPress bug, right? If so, do you know where I should take this bug report once I look into it a bit further? I haven't reported a bug for WP before.

**Comment by Jamiewarb** [comment]
Yep, I can confirm it is very likely to be caused by the `=>` symbol.

```html
<section x-init="=>"></section>
```

is outputted as 

```html
<section x-init="=>&#8220;></section>
```

![image](https://user-images.githubusercontent.com/2754728/106477529-28622e00-64a0-11eb-94e6-0a4aaf07c6e0.png)

**Comment by elliotcondon** [comment]
Nice work @Jamiewarb. I suspect there is a WP function hooked into the "the_content" filter which is attempting to validate / balance HTML attributes. The unescaped `=` character within an attribute value will represent a problem, I'm not sure what the solution here will be... 

Can you try using the WP escape functions to help avoid the issue?
```
<section x-data="{query: ''}" x-init="<?php echo esc_attr('$watch('query', (value) => console.log(this) )'); ?>"></section>
```

**Comment by Jamiewarb** [comment]
Thanks Elliot. Didn't have time to look yesterday, but looking today it seems that

``` // wp-includes/default-filters.php
/* L173 */ add_filter( 'the_content', 'wptexturize' );
```

is changing it from `'` to `&#8220;`.

-=-

And yes, using `esc_attr` turns it into =&gt;, and JS is happy to run that, so that solution works - thank you very much for unblocking me on that! I'm definitely in the wrong repo as it's a core problem, so thank you double for the help.

Would you say this is a bug for WP then, or expected behaviour? If the former, where do you think I should report it? Trac?

**Comment by elliotcondon** [comment]
@Jamiewarb That's a great result!

I'm so glad I was able to help. This kind of issue is a little in uncharted territory. There isn't much of a precedent for sending JS through HTML attribute values from PHP into the Gutenberg editor. I don't think this is a bug exactly, but just something that needs to be considered when using certain characters within attribute values.

Good luck with the rest of your project!

**Comment by mrkaluzny** [comment]
@elliotcondon I've found the similar issue with " being replaced by ″ in some AlpineJS expressions

```
remove_filter('the_content', 'wptexturize');
```

Seems to be the best approach, adding the top example for someone to find it faster next time ;)

**Comment by coulterpeterson** [comment]
@mrkaluzny Thank. You. So. Freaking. Much! Been losing my mind as to why my Alpine-driven PHP components were getting broken by angled double quotes when they were wrapped in something like an ACF Block or custom Gravity Forms element, and it was the wptexturize filter messing them up all along - much appreciated!
