### ISSUE TITLE
Set custom fields of a taxonomy using REST API

### ISSUE THREAD

**Issue by djoo** [AdvancedCustomFields/acf#460]
Hi,

I try to set up fields of a taxonomy by the REST API.

In the past i succeed to do it for a custom post type like this : 
Endpoint : /wp-json/wp/v2/custompost
Type : POST
```
{
    "title": "Title of the psot",
    "status": "publish",
    "featured_media": 0,
    "fields": {
      "acf_field_1": "test",
      "acf_field_2": "test"
    }
}
```
-> Works perfectly

But this doesn't work for taxonomy :
Endpoint : /wp-json/wp/v2/taxonomy
Type : POST
```
{
    "title": "Title of the taxonomy",
    "fields": {
      "acf_field_1": "test",
      "acf_field_2": "test"
    }
}
```
-> In this case the taxonomy is created, but the acf fields are empty

Any idea ?

Thanks

**Comment by elliotcondon** [comment]
Hi @djoo 

Thanks for the post. We don't yet offer a native REST API solution with ACF. This is something that is currently in the works, but not yet released. Is it possible you are using a 3rd party plugin or custom code for the REST API functionality?

**Comment by djoo** [comment]
Hi @elliotcondon,
Thanks for your quick reply.
"Is it possible you are using a 3rd party plugin or custom code for the REST API functionality?"
Do you have something to suggest that can help me to "find the way" to code this ?
I was thinking, i can maybe create a custom endpoint for my taxonomy, where i fill up the fields in php ? Make sense to do this ? (sorry i'm beginner with WP API and ACF).
THanks

**Comment by elliotcondon** [comment]
Hi @djoo. I'm not sure I will be able to assist with this question. We don't yet offer a native REST API solution with ACF, so I'm not the best person to ask for advice on registering rest fields or endpoints. I think yo would have more success posting this question on a generic WP development site - perhaps StackOverflow or Twitter?

**Comment by djoo** [comment]
Hi @elliotcondon 

Thanks for your reply. Finally i did a custom endpoint, where i get the POST parameters and handle by myself with the PHP update_fields() function.
