### ISSUE TITLE
WordPress: Inner Blocks API Changes

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#464]
Hey @elliotcondon 

I wonder if this changes are essential for the ACF innerBlocks implementation and if this changes could break the ACF innerBlocks implementation in the future?

Here you can read more:

[https://make.wordpress.org/core/2021/02/23/inner-blocks-api-changes/](https://make.wordpress.org/core/2021/02/23/inner-blocks-api-changes/)

**Comment by elliotcondon** [comment]
Hi @CreativeDive. This change looks to affect the "focus" behavior when inserting an inner block. I'll perform some testing with 5.7, but do not anticipate this being a breaking change.

**Comment by CreativeDive** [comment]
This sounds good, thank you @elliotcondon
