### ISSUE TITLE
Sidebar field header icons to be in sync with core styles

### ISSUE THREAD

**Issue by rahuladams** [AdvancedCustomFields/acf#468]
The icons used for re-ordering the field group in sidebar appears to be same as the arrow that WordPress core uses for toggling the field groups. This creates confusion when the project is handed over to a layman user. Please check the screenshot below.

<img width="771" alt="Screenshot 2021-03-05 at 12 28 23 PM" src="https://user-images.githubusercontent.com/16552397/110079449-247f3f80-7daf-11eb-8f48-c879fab3f0d3.png">

Ideally, those arrows should be different and the arrow icon that ACF uses for toggling has to look identical to what WordPress uses. Please find below an example of what I would suggest. The arrows used are in sync with the core style. 

![Solution](https://user-images.githubusercontent.com/16552397/110080037-f0f0e500-7daf-11eb-93cb-39321b86e809.jpg)

**Comment by elliotcondon** [comment]
Hi @rahuladams 

Thanks for raising this issue with a detailed ticket. I especially like your redesign of the metabox reordering icons that were added in WordPress 5.5. Unfortunately, this isn't something added by or fixable from the ACF plugin and I encourage you to submit a ticket to the WordPress core development team with regards to this improvement suggestion.

**Comment by rahuladams** [comment]
Hey @elliotcondon, sure, I shall do that.
