### ISSUE TITLE
Feature Request: Disallow a ACF block to be nested

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#469]
Hey @elliotcondon 

it's possible to set an option to acf_register_block_type() to disallow a ACF block can be nested?

In some cases this can be very helpful to set restriction for the user. Because the user is very free to add all ACF blocks as an inner block.

I my case I have builded a header block with ACF, which is always placed on the top outside of the content. But there are other cases, if disallowing to be nested can be very helpful.

Are there any ways I can do this using the Block API?

Something like that?

```
acf_register_block_type(
	array(
		'name' => 'acf-block',
		'title' => __('ACF Block', 'block'),
		'supports' => array(
			...
			'nested' => false, // We can't use this block as inner block
			...
		),
		'render_template' => my_dir( 'inc/acf-blocks/acf_template/acf_template.php' ),
	)
);
```

And also helpful can be to avoid the nesting of an ACF block to specific wrapper blocks, like this:

```
acf_register_block_type(
	array(
		'name' => 'acf-block',
		'title' => __('ACF Block', 'block'),
		'supports' => array(
			...
			'disallow_nesting' => array('core/columns', 'core/cover'), // We can't use this block as inner block for specific block types
			...
		),
		'render_template' => my_dir( 'inc/acf-blocks/acf_template/acf_template.php' ),
	)
);
```

or

```
acf_register_block_type(
	array(
		'name' => 'acf-block',
		'title' => __('ACF Block', 'block'),
		'supports' => array(
			...
			'allow_nesting' => array('core/columns', 'core/cover'), // We can use this block as inner block only for specific block types
			...
		),
		'render_template' => my_dir( 'inc/acf-blocks/acf_template/acf_template.php' ),
	)
);
```

I think the last way, should be the best way corresponding to the following filter:

`add_filter( 'allowed_block_types', 'my_function', 10, 2 );`

**Comment by elliotcondon** [comment]
Hi @CreativeDive 

Good question. After a quick look online, this may be possible by using the `parent` property: https://developer.wordpress.org/block-editor/developers/block-api/block-registration/#parent-optional

If the above doesn't work out, please have a read over [this ticket](https://github.com/WordPress/gutenberg/issues/7845) which poses a similar question to the Gutenberg team - there may be some useful solutions there.

**Comment by CreativeDive** [comment]
@elliotcondon Thank you for response. 

This `parent` property is a good solution to allow a block to be nested only in a specific parent block.

This can be also very helpful in the other way.

Is there currently any way to add this `parent` property to `acf_register_block_type()`?

Really good thinking on your linked ticket [https://github.com/WordPress/gutenberg/issues/7845](https://github.com/WordPress/gutenberg/issues/7845).

It seems this will support in the future. Will ACF stick with it to support this use case as soon as it becomes available?

**Comment by CreativeDive** [comment]
@elliotcondon the parent property really works, very nice. Thank you :-)

```
acf_register_block_type(
	array(
		'name' => 'my-block',
		'title' => __('My Block', 'wphave'),
		...
		'parent' => array('core/cover'),
		...
	)
);
```

But it seems there is no possibility to set a block for the "root" document only and to allow only specific block as inner blocks at the moment.

**Comment by Log1x** [comment]
> But it seems there is no possibility to set a block for the "root" document only and to allow only specific block as inner blocks at the moment.

```
<InnerBlocks allowedBlocks="<?php echo json_encode(['acf/my-block']); ?>" />
```

**Comment by CreativeDive** [comment]
@Log1x Thank you, yes here we can set the allowed block for a specific inner block. Thats really great.

But things like to allow a block only on the root first level is missing at the moment. But it seems this will come to Gutenberg.

My main question here, is how we can restrict a specific block in the main way on acf_register_block_type(), like this:

```
acf_register_block_type(
	array(
		'name' => 'acf-block',
		'title' => __('ACF Block', 'block'),
		'supports' => array(
			...
			'nested' => false, // We can't use this block as inner block
			...
		),
		'render_template' => my_dir( 'inc/acf-blocks/acf_template/acf_template.php' ),
	)
);
```

So we could define, this block is strictly not nestable. 

I don't know if something like that comes to Gutenberg in the future.
