### ISSUE TITLE
InnerBlocks & render_block_preview

### ISSUE THREAD

**Issue by simonseddon** [AdvancedCustomFields/acf#471]
**Pre-amble:** I have a container block (mosaic) and an items block (mosaic tile), tied to each other by parent & allowBlocks. On the frontend, the item blocks appear in a CSS grid, with each item taking up __x and __y grid columns/rows), set via. ACF fields (working great). However, this grid is proving near impossible to replacate in the editor, due to the Innerblocks being wrapped in a bunch of containers divs (the div which dictates their __x and __y dimensions via. CSS classes is buried).

Is there a way to remove container divs from `InnerBlock` in the editor? That would be the easy way. If not...

I've got a semi-working solution, which uses `render_block_preview` to check an item's class and append it to the nearest `.wp-block`. This works 🍻 (on page load it does/looks exactly as I'd want) but changes are lost the moment I hover over anything else in the editor. Is there a better action or approach, which will persist changes in the editor?

```
if (window.acf) {
    const tile_updated = ($block) => {
        const parentBlock = $block.closest('.wp-block');
        
        // grab new "tile-size-" class from buried div, to append to parent .wp-block
        const blockClasses = [...$block[0].children[0].classList].filter(c => c.startsWith('tile-size-'));
        
        // detect any classes starting with "tile-size-" already on .wp-block for removal
        const parentBlockClassesToRemove = [...parentBlock[0].classList].filter(c => c.startsWith('tile-size-'));

        parentBlock[0].classList.remove(...parentBlockClassesToRemove);
        parentBlock[0].classList.add(...blockClasses);
    }

  window.acf.addAction('render_block_preview/type=mosaic-tile', tile_updated);
}
```

**Comment by elliotcondon** [comment]
Hi @simonseddon. Thanks for the topic. I believe we have a similar issue already in conversation here (https://github.com/AdvancedCustomFields/acf/issues/471). Can you please give that a read and let me know if this can be considered a duplicate ticket?

**Comment by simonseddon** [comment]
Thanks for the response @elliotcondon. It looks like you've linked to this issue. I'll see if I can find the dupe. In the meantime I've had a think and may be able to use display:content on the surrounding divs in the editor, to get around hacking it with JS but haven't had a chance to test yet.

**Comment by elliotcondon** [comment]
Apologies for that. I mean tot reference https://github.com/AdvancedCustomFields/acf/issues/465

**Comment by simonseddon** [comment]
Thanks @elliotcondon . I was just reading that, and it is indeed the same issue.

So I've actually been able to solve my own issue much more elegantly than the hacky JS way I originally posted. This is _kind of_ particular to my own styling and doesn't solve the over-arching issue with API v2, but appreciate that will take a while to roll out.

**If your block's CSS issues are due to using child, sibling, adjacent combinators, et-al., then this method won't apply.**

I'll quickly document here in case it's useful for anyone else (this is literally the first time I've came across `display: contents` and suspect it may be new to others). It's not fully supported across browsers, yet, but in the back-end who cares right :)

Editor SCSS (obv. replace .your-block-name with whatever class you've put on your block render):

```
.your-block-name {
    > .block-editor-inner-blocks,
    > .block-editor-block-list__layout,
    > .block-editor-block-list__layout > .wp-block,
    > .block-editor-block-list__layout > .wp-block > .acf-block-body,
    > .block-editor-block-list__layout > .wp-block > .acf-block-body > div,
    > .block-editor-block-list__layout > .wp-block > .acf-block-body > div > .acf-block-preview {
        display: contents;
    }
}
```
-- and just like that, my CSS grid worked as though the InnerBlock elements were direct children of my parent block :D Screenshot for reference of ACF fields working in tandem with editor output.

![Screenshot 2021-03-05 at 23 42 47](https://user-images.githubusercontent.com/606762/110186255-8b7f1180-7e0c-11eb-8de3-ffd0d611009e.png)

**Comment by stuartcusackie** [comment]
Nice hack. Works well, except that I cannot edit inner blocks - I cannot click on the blocks anymore.

This works for me, but I guess each case is different:

```
.block-grid {
  & [data-inner-blocks],
  & .block-editor-inner-blocks,
  & .block-editor-inner-blocks > .block-editor-block-list__layout {
    display: contents;
  }
}

.block-grid {
  & .wp-block {
    width: 100%
  }
}
```
