### ISSUE TITLE
Posts not shown on Wordpress 5.7

### ISSUE THREAD

**Issue by tw1t611** [AdvancedCustomFields/acf#473]
### Error
The post entries are not shown on the latest Wordpress.
Although the entries are "there" as seen in the filter options above.
![image](https://user-images.githubusercontent.com/13353525/111135571-1b475d00-857d-11eb-924d-8635b8030de3.png)
The filtergroup is set to content-type "Transporter"

### Expected
Post entries are shown.

### Versions
Wordpress 5.7
Advanced Custom Fields 5.9.5
PHP 7.3

**Comment by elliotcondon** [comment]
Hi @tw1t611 

Sorry to hear about the issue, but I'm not understanding how this is related to the ACF plugin. Can you provide a little more information to explain how ACF is causing this issue?

**Comment by tw1t611** [comment]
Well I thought, it is the plugin, the custom post type was created with:
![grafik](https://user-images.githubusercontent.com/13353525/111280752-7a1fdb80-863c-11eb-88b2-e75061b924ba.png)
Please tell me if I got something wrong. The only thing I know, is that it worked with Wordpress 5.6 and there is no other plugin (like CTP UI) installed, which could be related to this.

**Comment by elliotcondon** [comment]
Thanks for the reply. The ACF plugin is not responsible for custom post types or post content. 

Is it possible that you have confused ACF with another plugin?

**Comment by tw1t611** [comment]
Yes its a custom created archive, ty for your help.
