### ISSUE TITLE
There is no way to check if an oEmbed is set, without the code actually processing the url into the embed.

### ISSUE THREAD

**Issue by maartenhunink** [AdvancedCustomFields/acf#486]
I have a loop with posts which checks if an oEmbed is filled in or not. Depending if it filled or not the template hides or shows certain elements.

But if I do `if(get_field('oEmbed')){ //do something}` it always processes the field and returns the oEmbed. While I don't actually need the embed, I just need to know if it's set or not. If I do this in a loop of about 30 posts, the page becomes very slow. 

I found a way around it by using get_post_meta() instead.

```
$featured_video_meta = get_post_meta(get_the_ID(), 'oEmbed');
$has_featured_video = ($featured_video_meta ? !empty($featured_video_meta[0]) : false );
```

In the documentation this isn't mentioned anywhere, it might be helpful to add? Since it's not clear at the moment that this is happening and that it could lead to a slowdown of the site. 

Thank you!!

**Comment by elliotcondon** [comment]
Hi @maartenhunink 

Thanks for the topic. Don't forget about the `$format_value` parameter available to the `get_field()` function. This will allow you to load the value in its raw format without any "oEmbed" logic applied: https://www.advancedcustomfields.com/resources/get_field/
