### ISSUE TITLE
Conflict with other plugins / themes that use Walker_Nav_Menu_Edit

### ISSUE THREAD

**Issue by AndreiIgna** [AdvancedCustomFields/acf#49]
This is a known limitation in WordPress, admin menu items are a bit tricky to work with.

At the moment, `ACF_Walker_Nav_Menu_Edit ` breaks the menu items functionality added by other plugins and themes. There's no support for multiple walkers, so if ACF walker is loaded after other plugins, it overwrites those other plugins custom's code (can happen other way around, and ACF menu item code is rendered useless as well).

Theme and plugin developers took a shared approach and now add a hook named `wp_nav_menu_item_custom_fields`, so others can extend the menu items, even without their specific Walker being used. Examples:
- https://github.com/AndreiIgna/if-menu/blob/master/src/if-menu-nav-menu-4.7.php#L170
- https://github.com/helgatheviking/Nav-Menu-Roles/blob/master/inc/class.Walker_Nav_Menu_Edit_Roles_4.7.php#L66
- and many others

Can that hook be added in `ACF_Walker_Nav_Menu_Edit`? It would be helpful for everyone, as it makes cross-plugin compatibility easier to implement.

Cheers

**Comment by AndreiIgna** [comment]
For reference, better support for this is being discussed for years https://core.trac.wordpress.org/ticket/18584 without something concrete being planned

**Comment by elliotcondon** [comment]
Hi @AndreiIgna 

Thanks for the topic and info. I like your solution (https://github.com/helgatheviking/Nav-Menu-Roles/blob/master/inc/class.Walker_Nav_Menu_Edit_Roles_4.7.php#L66) - this looks neat and tidy to me.

I've had a similar ticket on my to-do for a long time, but never got around to it. I'll make sure I look into this shortly :)

**Comment by AndreiIgna** [comment]
That's great @elliotcondon 

As a example, someone is affected by this and ACF fields are not being displayed in menu items https://wordpress.org/support/topic/acf-plugin-conflict-2/

**Comment by elliotcondon** [comment]
Hi @rico 

We fixed this issue a while ago by adopting a generic `Walker_Nav_Menu_Edit` class that uses an "wp_nav_menu_item_custom_fields" action.

May I ask which other plugin or theme is causing you the conflict issue?

**Comment by rico** [comment]
Hi @elliotcondon - ah ok, sorry, thought it is still open.

It's this Plugin: https://wordpress.org/plugins/wpfront-user-role-editor/. However, I figured out that the plugin has a somehow cryptic option called _Override Navigation Menu Permissions_ which seems to overcome the conflict.

If the option is not activated, I get a warning: _Menu walker class is overridden by a theme/plugin. Current value = ACF_Walker_Nav_Menu_Edit. Navigation menu permissions may still work._

**Comment by AndreiIgna** [comment]
@elliotcondon thanks for adding the hook in ACF. Didn't notice until now is added, tested and works fine.

@rico Looks like "WPFront User Role Editor" needs to override the Menu walker to add its own functionality, and also preserves support for other plugin to hook into it. The option "Override Navigation Menu Permissions" probably is for these use cases.
https://plugins.trac.wordpress.org/browser/wpfront-user-role-editor/trunk/classes/class-wpfront-user-role-editor-nav-menu-walker.php#L192

I will close this, as the change is made in ACF and works as expected
