### ISSUE TITLE
Feature Question/Request: Acf user field and multisite

### ISSUE THREAD

**Issue by isuke01** [AdvancedCustomFields/acf#495]
Hey, 
I noticed if you create User field for user form while on mutisite setup uses global meta function instead of per site setup. 
I understand this is intentional design choice?.  
Looks like it uses `update_user_meta(...)` function. 

For save info per site should be used  `update_user_option(...)` function which create per site user meta with naming `{wpdb_Prefix}_{blog_Id}_{option_name}` .  Only for non main websites, for main webiste it contain standard user meta notation. Similar how user capabilities are saved.

Problem with current soultion is, we use ACF user fields e.g for access to pages this will set site pages as global user meta or any user preferences per site, which make no sense.

Would be nice to have switch during creation this field that allow to choose global or per site user setting or separate type of field.

Also my question here is if any one know some hook/function to change default function save/load/read behavior for user field :)

**Comment by elliotcondon** [comment]
@isuke01 

Thanks for the topic. This is an interesting scenario that I would like to understand better. Are you able to provide some more detail on the current "scope" problem and perhaps include some screenshots to help demonstrate how ` update_user_option()` would remedy the situation?

As for a hook/function to solve the issue for now: Yes, please use the following filters to hook in before ACF runs meta functionality for the CRUD functions:

1. "acf/pre_update_metadata".
2. "acf/pre_delete_metadata".
3. "acf/pre_load_metadata".

These filters can be found within the `includes/acf-meta-functions.php` file with comments to help explain how to use them and their parameters.

**Comment by isuke01** [comment]
Just in case if some one is interested in topic, @elliotcondon  hooks solved my issue.
Below is my code: 
note: `access_level` and `access_groups` are just name of my user form field since I want to hook only those user fields as as specyfic for site/blog.
```
add_filter('acf/pre_update_metadata', 'tb_pre_update_user_metadata', 10, 5);
add_filter('acf/pre_load_metadata', 'tb_pre_load_user_metadata', 10, 4);
add_filter('acf/pre_delete_metadata', 'tb_pre_delete_user_metadata', 10, 4);


/**
 * Detalist in acf/includes/acf-meta-functions.php
 */
function tb_pre_update_user_metadata($null, $post_id, $name, $value, $hidden){
	// Decode $post_id for $type and $id.
	extract( acf_decode_post_id($post_id) );
	// Bail early if no $id (possible during new acf_form).
	if( !$id ) {
		return false;
	}
	// Hidden meta uses an underscore prefix.
	$prefix = $hidden ? '_' : '';

	if($type && $type === 'user' && ($name === 'access_level' || $name === 'access_groups' ) ){
		return update_user_option($id, "{$prefix}{$name}", $value);
	}
}

function tb_pre_load_user_metadata($null, $post_id, $name, $hidden){
	// Decode $post_id for $type and $id.
	extract( acf_decode_post_id($post_id) );
	// Bail early if no $id (possible during new acf_form).
	if( !$id ) {
		return false;
	}
	// Hidden meta uses an underscore prefix.
	$prefix = $hidden ? '_' : '';

	if($type && $type === 'user' && ($name === 'access_level' || $name === 'access_groups' )){
		return get_user_option("{$prefix}{$name}", $id );
	}

}

function tb_pre_delete_user_metadata($null, $post_id, $name, $hidden){
	extract( acf_decode_post_id($post_id) );
	// Bail early if no $id (possible during new acf_form).
	if( !$id ) {
		return false;
	}
	// Hidden meta uses an underscore prefix.
	$prefix = $hidden ? '_' : '';

	if($type && $type === 'user' && ($name === 'access_level' || $name === 'access_groups' )){
		return delete_user_option($id, "{$prefix}{$name}" );
	}
}
```
DB:
![image](https://user-images.githubusercontent.com/12289763/117783170-960dbb00-b242-11eb-942c-ecd71f1c03db.png)
