### ISSUE TITLE
update_field($selector, $value, [$post_id]);  $post_id not targeting specific post id.

### ISSUE THREAD

**Issue by kevinmancuso** [AdvancedCustomFields/acf#496]
Hi,
I noticed if you try to use update_field(); It wont specifically target only the $post_id.

Wordpress Version 5.7.1
ACF Version 5.9.5
I am using Gutenberg Editor.

Example code.
$selector = 'field_60954b6876828'; // This is a standard text field.
$value = 'Coolio'; 
$post_id = 514; // "514" is my post id, that I want to change only.
update_field($selector, $value, $post_id);

When I run this, it changes all custom-post types with "field_60954b6876828".

**Comment by elliotcondon** [comment]
Hi @kevinmancuso 

Can you please provide some context around where and when you are running this code? 

We are unaware of any issues preventing the `update_field()` function from working correctly, but will be more than happy to help diagnose and solve the issue with you. You mentioned that when you run this, it changes *all* custom post types.

Do you mean to say that it updates multiple posts meta values? If so, this is very odd behavior and most likely a result of some incorrect logic surrounding the `update_field()` call.

The more information you can provide about how you are using this function, the better. Looking forward to hearing from you.

**Comment by kevinmancuso** [comment]
Hi @elliotcondon, I'm so sorry I found the error, I accidentally made an infinity loop that kept crashing the admin editor page which is why the fields were not updating correctly.
I got rid of the glitch and fields update normal now!


Currently Im trying to create a basic visual editor.

single-merchant.php: This is where the *fake input field is.
    $m_contact = get_field('merchant_contact_first');

<div id="container" class="container">
    <div contenteditable="true" id="myContent" data-acf-name="merchant_contact_first" data-page-id="<?= get_the_ID(); ?>"><?php if($m_contact){ echo $m_contact; } ?></div>
    <button class="btn" id="save" disabled>Save Content</button>
 </div>
 
 
 main.js. For the example I just got rid of all the sanitization code.
     $('#save').click(function(){
        var clean1 = $('#myContent').text(); //.text() function will escape and display text
        var myPageId = $('#myContent').attr('data-page-id');        

        $.ajax({
            type: 'post',
            url: towerContenteditingAjax.ajaxurl,
            data: {
                myPageId: myPageId,
                mycontent: clean1,
                action: 'do_contentediting',
                nonce: towerContenteditingAjax.nonce
            },
            dataType: 'json',
            success: data => {
                jQuery('.big_wrapper').text(data.data);
            },
            error: err => {
                console.error(err);
            }
        });
    });
 
 
Ajax.php. For testing purposes I changed the post Id to a specific post 495 
// Content Editing page Ajax Functionality
add_action('wp_ajax_nopriv_do_contentediting', 'tower_ajax_do_contentediting');
add_action('wp_ajax_do_contentediting', 'tower_ajax_do_contentediting');

function tower_ajax_do_contentediting() {
    if (!wp_verify_nonce($_POST['nonce'], 'contentediting-ajax-nonce')) {
        wp_send_json_error('Security check failed', '400');
        wp_die();
    }
        // Update with new value.
        $selector = 'field_60999ff04ca1a';
        $value = $_POST['mycontent']; 
        $post_id = $_POST['myPageId'];
        update_field( $selector, $value, $post_id );

    $ajax_content = $_POST['mycontent'];
    wp_send_json_success($ajax_content);

}
