### ISSUE TITLE
Required asterisk gets escaped in field group editor after 5.9.6 update

### ISSUE THREAD

**Issue by first-wgrt** [AdvancedCustomFields/acf#502]
When marking a field as required, it is marked with an asterisk. After updating to 5.9.6, it seems the asterisk HTML is being escaped. It looks like this now:

![image](https://user-images.githubusercontent.com/55440658/118943318-cc8aba80-b953-11eb-8094-9d4ba41fd349.png)

And the markup for the asterisk is now `&lt;span class=&quot;acf-required&quot;&gt;*&lt;/span&gt;`.

Seems to have nothing to do with #500; adding/removing the `ACF_EXPERIMENTAL_ESC_HTML` constant in wp-config.php has no effect.

The issue seems to be limited to the field group editor. The fields themselves are rendered properly.

**Comment by c0deTechy** [comment]
@first-wgrt,  
Мое быстрое исправление, пока жду разработчика, Я использовал функцию PHP strip_tags () /includes/acf-field-functions.php  линия между строками 835 и 839:

`if( $field['required'] ) {
		$label .= strip_tags('<span class="acf-required">*</span>');
	}`

**Comment by elliotcondon** [comment]
Thanks @first-wgrt 

I've patched the issue and pushed a hotfix to all repositories. Please re download the plugin files when possible or refer to the above commit.

**Comment by c0deTechy** [comment]
@elliotcondon Я могу подтвердить, что теперь это работает, спасибо.

**Comment by first-wgrt** [comment]
@elliotcondon thanks for the fix, can confirm it works for me 🙂
