### ISSUE TITLE
add_menu_page has as value in position a float but needs an int. 

### ISSUE THREAD

**Issue by Joeri-Abbo** [AdvancedCustomFields/acf#506]
This has given me a notice when using WP 5.7. Could this be changed to an int?

https://github.com/AdvancedCustomFields/acf/blob/5b3f4b86eb10bd15035f66b123f9da9a134df365/includes/admin/admin.php#L48

**Comment by elliotcondon** [comment]
Hi @Joeri-Abbo 

Thanks for letting us know about the bug. I'll add this to our to-do list and investigate shortly 👍.

**Comment by elliotcondon** [comment]
Hi @Joeri-Abbo, can you please provide the full PHP notice logged? Just want to make sure I'm looking at the right line of code.
