### ISSUE TITLE
429 Too many requests / 504 error

### ISSUE THREAD

**Issue by AaronJ98** [AdvancedCustomFields/acf#524]
Hi there,

I seem to be having some issues with ACF blocks / Reusable blocks. 

I am getting a number of 429 responses when loading a few pages within the backend. This is coming from admin-ajax.php requests to load the ACF blocks.

I have monitored for a page load, with the following results:

    266     [action] => acf/ajax/fetch-block
     16     [action] => heartbeat
      8     [action] => get_post_suggestions
      4     [action] => wpil_is_outbound_links_added
      4     [action] => wp-remove-post-lock
      4     [action] => update_suggestion_display

ACF is over-requesting admin-ajax, which is limited to preserve server stability. Would you be able to look into this?

FYI the pages firing the errors are very content-heavy.

Appreciate any help you can offer on this!

Aaron

**Comment by elliotcondon** [comment]
Hi @AaronJ98 

Thanks for the bug report. May I ask how many ACF blocks exist within this Post content? Keeping in mind that ACF Blocks are *dynamic* (not static), they should be used sparingly within the Post content to avoid overwhelming server-side rendering via AJAX requests.

**Comment by AaronJ98** [comment]
Hi @elliotcondon 

Thanks for coming back to me. There are 30+ fields on the page that are producing 504 errors.

I have spoken to WPEngine support and they identified that the requests are being blocked by rate limiting on the server so they advised getting in touch with yourself. Is there a way to set a limit to the number of blocks that are rendered in 1 single second?

Removing the fields is not possible as there is a number are pages that are reliant on the fields already and changing the way content is loaded would be a considerable amount of work. How would you advise going about fixing the issue so that blocks are fully scalable going forward?

**Comment by mattgrshaw** [comment]
Closing this one since block preloading was released in ACF 5.10. Hopefully that fixed the issue for you @AaronJ98, but please let us know if you run into any further issues.
