### ISSUE TITLE
Undefined function acf_register_block_type

### ISSUE THREAD

**Issue by nhatrangnet** [AdvancedCustomFields/acf#528]
I'm in Version 5.9.8 and when I try to add a custom block I got error Call to undefined function acf_register_block_type.
Even when I use the sample code here https://www.advancedcustomfields.com/blog/acf-5-9-exciting-new-features/.
Is this a bug, or should I buy PRO version?
Thanks for your help.

**Comment by nick6352683** [comment]
I'm afraid you have to buy the Pro version... You cannot create blocks with the free version...

**Comment by nhatrangnet** [comment]
@nick6352683 ok thank you.
