### ISSUE TITLE
Unable to colorize ACF block icon background if custom icon is used

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#529]
Hey @mattgrshaw,

we have the possibility to colorize our ACF block icons like this:

```
acf_register_block_type(
	array(
		'name' => 'my-acf-block',
		...
		'icon' => array(
			'background' => $block_background,
			'foreground' => $block_foreground,
			'src' => 'text-page',
		),
		...
	)
);
```

But in a lot of cases the default dashicons are not enough. So we can use custom icons like this:

```
acf_register_block_type(
	array(
		'name' => 'my-acf-block',
		...
		'icon' => load_my_svg_icon( 'cool-icon' ),
		...
	)
);
```

In this case, we are unable to colorize the block icon background. But it would be very helpful for the user, if all block icons have the same background, if they are coming from the same plugin / theme.

Is there a way to provide the same "icon" array from the first example for custom icons?

**Comment by CreativeDive** [comment]
@lgladdy any tip for me to solve this issue with the current version?

**Comment by lgladdy** [comment]
`icon` is provided by the block editor, as detailed at https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/#icon-optional

You can pass an SVG icon in as src whilst still setting the background and foreground as shown in WordPress's example

**Comment by CreativeDive** [comment]
@lgladdy thanks for the response. Yes I have already tested this, but it's not working. Do you can confirm this?

```
'icon' => array(
				'background' => '#eef8ff',
				'foreground' => '#2271b1',
				'src' => '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path fill="none" d="M0 0h24v24H0V0z" /><path d="M19 13H5v-2h14v2z" /></svg>',
			),
```

The result: No SVG icon. The colorized icon box is empty without an icon.

Is this a WordPress or an ACF bug? Do you can test it for me on your test installation to confirm this please?

**Comment by CreativeDive** [comment]
@lgladdy do you could test the custom icon with a custom background color at the meanwhile?

**Comment by lgladdy** [comment]
@CreativeDive We're currently in dev for our next release, so a little less active on here as we'll be around betas and releases - but I've made a note to test this as part of our release testing.

I'm not sure we do anything but pass this data raw through to WordPress though so it could be an issue their end.

**Comment by CreativeDive** [comment]
@lgladdy 

I have investigated the issue further can see HTML output in the case we use a custom SVG icon in combination with the background, is wrong. This is the reason why the custom background color dosen't work in combination with the SVG icon.

```
<span class="dashicon dashicons dashicons-<svg viewBox=&quot;0 0 24 24&quot; xmlns=&quot;http://www.w3.org/2000/svg&quot;><path fill=&quot;none&quot; d=&quot;M0 0h24v24H0V0z&quot; /><path d=&quot;M19 13H5v-2h14v2z&quot; /></svg>"></span>
```
You can see the `<SVG>` tag is outputted directly inside a `<SPAN>` tag. This can't work correct.

It's possible to fix this issue shortly please?

**Comment by lgladdy** [comment]
Hey @CreativeDive. I don't believe this is an ACF issue. We pass that data through to the standard WordPress registration system, so it's likely they don't support this.

Whilst I see it's listed here: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/ that only covers blocks registered by JavaScript, and required you to pass a React SVG element.

If you look at the documentation for register_block_type, you'll see icon is required to be a string: https://developer.wordpress.org/reference/classes/wp_block_type/__construct/
