### ISSUE TITLE
ACF 5.7.3 issue with WPML: editing taxonomy makes UI disappear

### ISSUE THREAD

**Issue by luismsf-va** [AdvancedCustomFields/acf#53]
When trying to add or edit taxonomy fields all fields disappear from the interface.
I believe this happens with translated taxonomies. I deactivated WPML and the issue didn't occur.
The issue started after updating ACF to version 5.7.3

Tried with the previous version and it worked fine.

**Comment by elliotcondon** [comment]
Hi @luismsf-va 

Thanks for the bug report.

Version 5.7.3 does include some changes to our "acf.screen" logic which handles the "Refresh Metaboxes" functionality. It's very possible that we have a conflict with WPML translated taxonomies.

Can you please provide us with a simple set of instructions to replicate the issue as precisely as possible?

**Comment by joeuttaro** [comment]
@elliotcondon I also noticed a similar issue conflict with ACF 5.7.3 and WPML in which when a different template is selected (under Page Attributes), the ACFs are not refreshed, but rather are removed from the screen.

Sounds like it would likely be with the 'refresh metaboxes' functionality. I did a few hours of testing on this one- disabling WPML fixes the issue, as does downgrading to 5.7.2. Let me know if there's any more detail I can provide.

**Comment by elliotcondon** [comment]
Hi @joeuttaro 

I've had some luck debugging this issue and believe I have found a solution :)
It would be great if you could help test this out.

Please edit the file 'ACFPRO/includes/wpml.php' and change the function verify_ajax() on line 433 to:
```
	function verify_ajax() {
		
		// set the language for this AJAX request
		// this will allow get_posts to work as expected (load posts from the correct language)
		if( isset($_REQUEST['lang']) ) {
			global $sitepress;
			$sitepress->switch_lang( $_REQUEST['lang'] );
			//$sitepress->set_default_language($_REQUEST['lang']);
		}
	}
```

This should solve the issue. Please let me know if you notice any other issues with WPML afterwards such as incorrect posts/terms/users loaded in AJAX powered fields.

**Comment by joeuttaro** [comment]
@elliotcondon Just gave this a test, and it seems to have done the trick! Nice work 👍

**Comment by elliotcondon** [comment]
Thanks for the reply. I'm glad to hear this has solved the problem. I'll do some more testing here and release an update soon.

**Comment by luismsf-va** [comment]
It's working now. Thank you!
