### ISSUE TITLE
Page title with line break inside Post Object field

### ISSUE THREAD

**Issue by ArthurShlain** [AdvancedCustomFields/acf#533]
By default wordpress not prohibits to use `<br>` tag inside post title.

And how it looks inside `Post Object` field:

![image](https://user-images.githubusercontent.com/2047645/129733345-27a5d4f7-9b6b-4757-b3fa-da9ae04e7bd0.png)

```html
<span class="select2-selection__rendered" 
  id="select2-acf-field_..." 
  title="Железобетонные <br>трехслойные стеновые панели">Железобетонные <br>трехслойные стеновые панели</span>
```

**Comment by mattgrshaw** [comment]
Hey @ArthurShlain, thanks for reporting this.This should already be resolved in the next release, which is currently available as a release candidate in the  "My Account" section of https://advancedcustomfields.com/.
