### ISSUE TITLE
Concat prepended and appended text with content of text field value

### ISSUE THREAD

**Issue by Sergei8888** [AdvancedCustomFields/acf#534]
If i use a prepended text like this:
![image](https://user-images.githubusercontent.com/45688549/130357834-98cfeb0c-c213-4bde-9806-92a4b84ef2bc.png)
I want to get tel:79520621168 value in the_field() method, but i get only content of the field: +79520621168.

**Comment by lgladdy** [comment]
Hey @Sergei8888 thanks for raising this issue.

I'm going to close it here and log it in our feature request list. For obvious backwards compatibility reasons, we won't be able to enabled this behaviour by default - but we'll investigate how viable it would be to add an option on the field for this.
