### ISSUE TITLE
ACF Block BUG since the release of ACF 5.10 when copying and pasting a block

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#537]
Hey @mattgrshaw @lgladdy 

I have found a new BUG since ACF 5.10 is released :warning:.

How you can replicate this BUG?

1. Create a block with ACF
2. Change the block options
3. Duplicate this block
4. Make changes two the new duplicated block 
5. The result is, the changes apply to the original block and not to the new duplicated block :scream: :scream: :scream:

Screen recording with ACF 5.9.9

It's working like expected.

![Aug-26-2021 21-23-07](https://user-images.githubusercontent.com/31563167/131023561-d858bd1a-451b-4298-b33b-686147bbf057.gif)

Screen recording with ACF 5.10

Here you can see the unexpected behavior and the BUG.

![Aug-26-2021 21-24-56](https://user-images.githubusercontent.com/31563167/131023843-21ee37e7-c158-4172-b48f-808378e6fc39.gif)

This BUG is really annoying as I often duplicate blocks and then want to change different options.

I hope you get it fixed with the next release :-)

**Comment by mattgrshaw** [comment]
Closing since this should be resolved in 5.10.2, released today. Please let us know if you run into any further issues!

**Comment by CreativeDive** [comment]
perfect @mattgrshaw just tested with 5.10.2 and it's working like a powerful ACF block :muscle: Thank you.
