### ISSUE TITLE
ACF Pro 5.10.1 (5.10?) bug when saving a block in editor mode

### ISSUE THREAD

**Issue by ideag** [AdvancedCustomFields/acf#540]
Hi!

We ran into a bug in ACF Pro 5.10.1 this morning.

I've made a screen recording of what we see here: https://www.youtube.com/watch?v=wZ9WivtOvxc

In ACF Pro 5.10.1, if you open an ACF block to Edit it, save the post and then reload the page/open it again, it comes back broken.

It looks like ACF thinks it is in preview mode, renders the acf-block-preview div, but then renders all the editor fields inside it. 

It becomes an obvious issue if you have some custom css on the .acf-block-preview class, i.e. pointer-events:none;

But also it starts breaking down some more as you go along, ACF starts showing the "Edit" button when you are in editor view, and preview button when you are in preview screen (I haven't filmed this part yet, found it afterwards.)

I was able to replicate this on a fresh site with just WP Core 5.8 and ACF 5.10.1 so it is definitely not 'environmental'.

**Comment by mattgrshaw** [comment]
Closing this one since we've released 5.10.2 today which addresses this issue.

Please give that a try and let us know if you run into any further issues @ideag!

**Comment by ideag** [comment]
Hi. Sorry for the late reply! Yes issue seems to be fixed. Thanks for the quick work!
