### ISSUE TITLE
Firefox validation bug

### ISSUE THREAD

**Issue by elliotcondon** [AdvancedCustomFields/acf#56]
A bug in Firefox 59 and below prevents the form from submitting after ACF validation has been performed. Please find updated .js files below to place into the 'assets/js' folder
[Archive.zip](https://github.com/AdvancedCustomFields/acf/files/2347033/Archive.zip)

**Comment by despecial** [comment]
Confirmed. These files fix the bug. Thank you, Elliot!

**Comment by unitb-ore** [comment]
Now it works, thanks! (Tested with  5.7.2.)

**Comment by elliotcondon** [comment]
Great!
