### ISSUE TITLE
Subplugin with WPML and ACF detects wrong language

### ISSUE THREAD

**Issue by Sysix** [AdvancedCustomFields/acf#57]
Hello,

currently I found a little bug in my Plugin, which output my german fields on my france page. 
I'm using th newest WPML und ACF Plugin versions.

I could fix this behavior with following snippet in my theme function:
```php
add_action('wp', function() {
    global $sitepress;

    acf_update_setting('current_language', $sitepress->get_current_language());
});

```

Solution found here: https://github.com/AdvancedCustomFields/acf/blob/master/includes/wpml.php#L33

PS: I think it is not save to use `ICL_LANGUAGE_CODE` as the Identifier. Because a theme/plugin can easily switch the language programmatically with `$sitepress->switch_lang('en');`.

**Comment by elliotcondon** [comment]
Hi @Sysix 

Good point. I'll take a look at when `get_current_language()` was added. If this is a function that has been around for a while, I'm happy to make this change :)

**Comment by elliotcondon** [comment]
Hi @Sysix 

I've just spent some time refactoring the WPML code in ACF, and have added this in. Thanks again for the info, this is much better than using the `ICL_LANGUAGE_CODE` constant.
