### ISSUE TITLE
[PRO] License key definition 

### ISSUE THREAD

**Issue by sebastienserre** [AdvancedCustomFields/acf#572]
Hello,

From ACF PRO 5.11, we can defined the license key in a Constant. By default, once done we have a message in the admin saying : "Your license key is defined in wp-config.php."

If we defined the key in our code, it's in general to avoid a mistake with a final customers or user of the website. Giving the location of the Key is quiet "dangerous" IMO.

Should it be possible to change the string to "Your license key is already defined" or something like this ?

**Comment by polevaultweb** [comment]
Good call @sebastienserre - will get that in the next release.

**Comment by sebastienserre** [comment]
Thank you, the filter added in 5.11.1 is great !
