### ISSUE TITLE
Field output missing when conditional logic field has a default value 

### ISSUE THREAD

**Issue by sboerrigter** [AdvancedCustomFields/acf#578]
Hello! 👋

Since ACF 5.11, fields that have conditional logic only work when the field it depends on has a value. I would expect the field to return a value as well when the field it conditional depends has a default value, but it doesn't. You can follow these steps to understand what I mean:

**Steps to reproduce**

- Create a `text` field named "example" for a post.
- Add `the_field('example')` to the post's template.
- Create a post, add some content to the "example" field and save the post.
- Visit the post to verify that you see the content.
- Now add a "`true_false` field named "show_example" to the same fieldgroup with a default value set to `true`.
- Add conditional logic to the "example" field, so that the field is only shown when "show_example" is set to true.
- Don't save the post!

If you visit the example post in the front-end you'll see that the output from `the_field('example')` is now missing. If you visit the WordPress admin page of the same post you do see the field's value.

I understand that this is because of the security updates in ACF 5.11, but I would expect the field values to be returned when a default value is set for a field used in conditional logic. This behaviour makes it hard to add conditional logic to existing fields when there are a lot of posts in the database that don't have values for the new field yet. I hope this is clear.

**Tested with:**
ACF version: 5.11.1
WordPress version: 5.8.2

Thanks in advance for looking into this!

**Comment by lgladdy** [comment]
Hey @sboerrigter, is this issue still happening in ACF 5.11.2? We made some changes to the security updates which might solve it, but let me know if not and we'll look deeper.

**Comment by sboerrigter** [comment]
@lgladdy thanks for your response. I've tested this with ACF 5.11.2 now but the problem persisted. I've also tried to reproduce this issue on another website, but I couldn't reproduce it there. So this is probably a site specific issue for which I already found a workaround. So I'll close this issue.
