### ISSUE TITLE
ACF 5.11 breaks certain Timber functions

### ISSUE THREAD

**Issue by rmens** [AdvancedCustomFields/acf#579]
After updating to ACF 5.11 a part of our site that gets the 4 most recent uploaded videos from a json-blob stored in the postmeta didn't show any video. When downgrading to ACF 5.10 it worked again. I expected ACF 5.11.1 to point out the problem in an admin notice, but it didn't show any warning at all.

The site is built with Timber. We use Timber to read out postmeta with the `meta(` function. That works fine < ACF 5.11, but with ACF 5.11 Timber returns an empty object. The postmeta field is not an ACF field. We fixed it in https://github.com/oszuidwest/streekomroep/commit/33db540aef0fa14f0510271122f20ad23a66c5c4 with bypassing the Timber `meta(` function.

A lot sites use ACF and Timber. This is probably something you and @jarednova should discuss mutually. I suspect Timber to always use `get_field` whether it's an ACF-field or not. Maybe ACF should flash an extra warning for sites using Timber too.

**Comment by lgladdy** [comment]
@rmens Hey - thanks for the report.

We're investigating this at the moment and I'll let you know as soon as we have a workaround or fix for you!

**Comment by lgladdy** [comment]
@rmens We made some changes in 5.11.2 which should solve this issue!
