### ISSUE TITLE
Wrong language in backend

### ISSUE THREAD

**Issue by infostreams** [AdvancedCustomFields/acf#58]
Hi!

First of all, thanks for the great plugin! I've noticed an issue with the language that ACF is using in the backend, though. My site's language is German, but in my profile I've selected that the WordPress backend language should be English. However, ACF ignores the language I selected in my profile and displays everything in German. If I change the site language to English ACF displays its whole UI in English. Please adjust?

Thanks!
Ed

**Comment by infostreams** [comment]
I have ACF version 4.4.12 by the way.

**Comment by elliotcondon** [comment]
Hi @infostreams 

Thanks for the bug report. This issue has been fixed in ACF5 - soon to be released!
If you are interested in upgrading to ACF5 today, please checkout our Early Access feature here:
https://www.advancedcustomfields.com/blog/acf-5-early-access/
