### ISSUE TITLE
ACF 5.11 and Yoast SEO 17.6 Select2 styling conflict

### ISSUE THREAD

**Issue by rastitkac** [AdvancedCustomFields/acf#581]
Hi there,

I came across a styling conflict when ACF Pro 5.11 and Yoast SEO 17.6 are active in parallel.

After updating Yoast SEO from 17.5 to 17.6 appearance of Select2 fields of ACF Pro in backend is broken.
This happens only with 17.6.
I can confirm it's not an issue in 17.5 and it has been reported that it's not an issue as far as 17.3.

Original report, with some feedback: [here](https://wordpress.org/support/topic/conflict-with-acf-pro-styles-select2/)

# How can this behavior be reproduced?
1. Install and activate Yoast SEO 17.6
2. Install and activate ACF Pro 5.11
3. Create a group with a custom field that uses Select2 (like Post Object with multiple values allowed)
4. Set the field group to appear if post type is posts
5. Create new or edit existing post
6. Look and try to edit the custom field just created in step 3
7. You'll notice the style is broken: like in [this picture](https://cln.sh/EUvjjA) or in [this picture](https://prnt.sc/2012hcx)

I already reported it to Yoast and they asked that I reported to you as well: https://github.com/Yoast/wordpress-seo/issues/17681

**Comment by lgladdy** [comment]
@rastitkac Hey! Thanks for the report.

We're working on getting a fix out for this ASAP. It's a little more complicated by if you have WooCommerce installed too, that breaks the styling even further... so we're trying to get something in place to work for all possibilities!

**Comment by rastitkac** [comment]
@lgladdy thank you for your feedback

**Comment by lgladdy** [comment]
Hey @rastitkac. This should be fixed in today's 5.11.2 release. Thanks again for your report!
