### ISSUE TITLE
Enhance slugify array to prevent js errors

### ISSUE THREAD

**Issue by cmarangon** [AdvancedCustomFields/acf#585]
The helper function acf_slugify does not remove single quotes from strings.

They are usually common in french texts such as (in my case) "Heures d'ouverture". This field group title breaks the js execution because of `Syntax error, unrecognized expression: #acf-group_heures_d'ouverture`

That is why I recommend the extension of the slugify array by the character "single quote".

```
function acf_slugify( $str = '', $glue = '-' ) {
	return str_replace(array('_', '-', '/', ' ', '\''), $glue, strtolower($str));
}
```

**Comment by lgladdy** [comment]
Hey @cmarangon, we actually made some changes to this in ACF 5.11.2 which should solve the issue - we also run the string through `sanitize_title`

**Comment by cmarangon** [comment]
Thanks @lgladdy for pointing this out.
I must have somehow missed the changes, when i was checking the source code here. I switched to the newest version and lo and behold, everything runs fine now.

**Comment by lgladdy** [comment]
@cmarangon No worries! Your issue actually let me spot some inefficiencies in our code here anyway so we'll patch those in the next release too!
