### ISSUE TITLE
ACF Blocks can fail to load edit fields on init

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#605]
Hey @lgladdy @mattgrshaw 

This issue is not related to the new Beta1 5.12. It's the same in Beta1 5.12 and  the latest 5.11 version.

https://user-images.githubusercontent.com/31563167/152304249-d573b315-c6ab-4478-9231-537bdcc619ba.mov

How do you can replicate this issue?

1. Create a simple ACF block pattern
2. Insert this block pattern
3. Try to change the fields of this inserted block

You can see the result, the fields are completely missing after the block pattern has been inserted.

After saving and refreshing the editor, the fields are there for the inserted block.

**Comment by CreativeDive** [comment]
OK, I have to correct myself. This issue only occurs when I paste the pattern very quickly after opening the pattern selection. I don't think there's anything to fix that, right?

**Comment by CreativeDive** [comment]
It seems there are multiple issues if a block pattern has been included too fast.

Here another screen recording:

https://user-images.githubusercontent.com/31563167/152313945-e5c3181d-cdbe-401f-a2ad-be62d633050d.mp4

I added the same pattern three times with a very small delay between pasting.

--> In this case, the ACF field values ​​don't update when you change them.

BUT if I wait a little longer between pasting these three patterns, everything works as expected.

This issue could also cause misunderstandings and poor user experience in the future. You cannot prompt the user to interact slowly.

**Comment by CreativeDive** [comment]
And here another example, in this case I've copied a ACF block to the clipboard and paste this via keyboard to the editor.

The same here, BUT this case is a little bit different. This issue occurs only the the second pasted block, also if the delay between pasting the block is longer, interesting @lgladdy @mattgrshaw ?

https://user-images.githubusercontent.com/31563167/152320679-c92d1f88-5dc4-45a8-aa56-a108cb289b3c.mp4

**Comment by CreativeDive** [comment]
And one more example. Here I add three blocks, changing the colors and copied them all to the clipboard. After pasting this three blocks, two of the three blocks are not updating the values:

https://user-images.githubusercontent.com/31563167/152323258-74cc4179-deef-45f9-b2fc-296bd05256de.mp4

All of this makes working into a poor user experience while creating content. There are too many scenarios where ACF blocks don't work as expected after adding them.

@lgladdy @mattgrshaw Is there any hope of solving this issues?

**Comment by CreativeDive** [comment]
There is the same without using pattern. Similar issues after creating a ACF block totally new:

https://user-images.githubusercontent.com/31563167/152326883-4aac5b69-bdd3-4df1-9e75-6246bd06896e.mp4

**Comment by CreativeDive** [comment]
A new one that fails, this time nested in a core column block:

https://user-images.githubusercontent.com/31563167/152343143-87499876-460a-4fa4-aa8a-fbd1b8370db6.mp4

**Comment by CreativeDive** [comment]
@lgladdy @mattgrshaw Please understand the importance of this fix. Since unfortunately no feedback has been received so far, it seems as if these issues are not correctly classified.

I want to explain. The end user mainly works with copy and paste to build the content. The user does not always go down the route of creating a block from scratch when they need a similar one that has already been created.

As can be seen in the videos, there are many usability killers here. It's very frustrating when you copy and paste blocks, make changes to them and then they aren't saved because the correct field assignment to the block doesn't work. Or if you make changes that are then visible on the wrong block. 

All this is very frustrating for the user when working with ACF blocks.

In my opinion, these issues should have very high priority.

**Comment by CreativeDive** [comment]
@lgladdy a month has passed since I added this issue. What's the point of doing the work of reporting bugs if it's just being ignored here?

**Comment by lgladdy** [comment]
@CreativeDive Thanks for the report. We read all issues as they're created and make a quick assessment as to their importance for priority. You submitted this during out ACF 5.12 release testing and cycle. As this wasn't a bug related to that release, hasn't been reported by anyone else, and has a workaround, this issue was added to our list to investigate rather than treated as a critical issue to fix in that release.

In this particular issue, we suspect this is likely a bug in Gutenberg rather than ACF - but will confirm that when we come to this issue, and raise it with the Gutenberg team if required.

**Comment by CreativeDive** [comment]
@lgladdy Thanks for the feedback. It is important to react, to know that issues are heard.

Have you ever tried to create a page with ACF blocks without facing these issues? Imagine the end user (not the developer) creating a page with ACF blocks. Will you use the copy and paste or duplicate function if you want to add the same formatted ACF block in multiple columns? Yes you will. This misconduct is a major contributor to the frustration of working with ACF blocks.

How often do you face these issues when creating a page with blocks? Very likely that is very often the case.

That's right, there is a way around these issues by creating an ACF block from scratch. At this point, however, the user was repeatedly confronted with the issues and is therefore frustrated. Because he inserted blocks, changed field values ​​and added content that is no longer there after saving.

It is important to view this misconduct as an end user and not as a developer.

Because of this, I can't understand why these errors aren't considered Important.

It can be seen very often in the screen recording that ACF blocks are there immediately after insertion and are not loaded with AJAX as usual. So I suspect this is more of a bug related to the way ACF loads block contents and fields with AJAX.

**Comment by JiveDig** [comment]
Just adding a +1 here to say that my team and I, and our customers hit this issue on a daily/weekly basis. We have some pre-saved patterns that we like to paste in as a head start. If we paste in multiple of the same pattern then the block ID is duplicated and we get all sorts of weirdness when trying to edit each block instance separately.

To clarify, this ID doesn't change when pasting in:

![CleanShot 2022-03-07 at 10 34 06](https://user-images.githubusercontent.com/540990/157065886-a59ecb43-1016-4b88-8138-ab1c916c7b14.jpeg)

**Comment by lgladdy** [comment]
@JiveDig Yeh - for that aspect of this bug, we do have a plan to remove block IDs so they behave more independently which will solve this, but that might come as part of a bigger refactor of blocks to solve some other issues - we're currently shaping the scope of how we get to the end goal across what releases at the moment.

**Comment by CreativeDive** [comment]
> though we'll likely need to generate something to use as the id for the template, as I'd imagine many users are using `$block['id']` in their templates for things like anchors

I think this one we can / should solve by using the HTML anchor (Advanced by each block) and calling `$block['anchor']`.

**Comment by CreativeDive** [comment]
@lgladdy we can't use multiple ids. But in the case of the editor we can use the ACF block id like `id="block_617004ca10ced"` and in frontend `id="my-anchor"` instead. Because the anchor is no necessary in the case of the block editor and the ACF block id is not necessary in the case of the frontend. I can't imagine that anyone use a id like "`block_617004ca10ced`" as selector for styling a block.

**Comment by CreativeDive** [comment]
Or another workaround to use the anchor, is so set the `$block['anchor']` value inside an inner container of the parent container. In my case I do that. Because I generate a unique id for each parent block container as selector to style a unique block.

**Comment by JiveDig** [comment]
@CreativeDive that code works for officially registered patterns, but we have a snippet library offsite for copying/pasting in, so there's no ability to do that. Or times when we build one column with an icon, and we want to copy/paste or duplicate the icon to the next column so all of the settings are there but we just want to change the icon... that's when we start to see the issues.

**Comment by CreativeDive** [comment]
@JiveDig yes correct, it's a litte fix in that case only. But it's very helpful in this case :-D

> Or times when we build one column with an icon, and we want to copy/paste or duplicate the icon to the next column so all of the settings are there but we just want to change the icon... that's when we start to see the issues.

Yes, it's frustrating when you're working the end-user way, with copy & paste or duplicate ACF blocks. I hope this is viewed as an important and substantial error. Because it has been difficult for me and others to work with blocks under these conditions for a long time.

**Comment by lgladdy** [comment]
Removing Block IDs is absolutely a top priority issue for ACF blocks - but it's important to say that's not the cause of the majority of the issues reported on this issue. Issues like #478 and #308 (and likely many others!) focus specifically on the block ID issue, so I'll pick this up over there once we have more information to share!

**Comment by CreativeDive** [comment]
@lgladdy I'm pretty sure when these bugs are all fixed. Satisfaction when using ACF blocks is 99.9%.

**Comment by benupham** [comment]
Hi,

Sorry to pile on here, but we are also experiencing this issue with our headless WP site (using Gatsby/graphql). When we use the block toolbar "Copy" function to copy an ACF block from one post to another, and then update the settings on the copied block, the settings on the original block are changed to match the copy, presumably because the block_ IDs are the same. 

The issue is only apparent in the Gatsby app. Viewing the two posts in standard WP, the content is correct and not the same, but I guess on the data level (where graphql gets it) the blocks are considered the same because they have the same id. 

Is there some way to hook into the toolbar "Copy" function and clear the block ID before it is pasted?

Thanks,
Ben

**Comment by lgladdy** [comment]
@benupham Hey Ben - I think the original issue for that bug is: https://github.com/AdvancedCustomFields/acf/issues/183 - can you subscribe for updates there as we'll use that to keep you updated. Given this bug is regarding fields not appearing when a new block inserted rather than duplicated block IDs, I'm keen it doesn't get mixed up :)

**Comment by lgladdy** [comment]
Hey @JiveDig @CreativeDive, 

I've just figured out what's causing this bug and I'm happy to say we'll have a fix into the next alpha preview build either later this week or early next 🥳

**Comment by JiveDig** [comment]
Excellent!

**Comment by CreativeDive** [comment]
Wonderful!
