### ISSUE TITLE
ACF Block: Additional CSS shouldn't be added to the block wrapper

### ISSUE THREAD

**Issue by erwinyusrizal** [AdvancedCustomFields/acf#609]
I have ACF block inside:

```
- rows
---- columns
-------- column
------------- MyACFBlock
```

when I add additional css for example tailwind class w-1/2 , it's added to my block html which is I expected, but on preview mode, why the additional css added to the MyACFBlock wrapper too? it makes the layout broken, the additional css shouldn't be added to the block parents (see screenshot)

![WhatsApp Image 2022-02-09 at 9 35 22 AM](https://user-images.githubusercontent.com/3752374/153136796-2335917d-f5c1-4ee2-93fc-ddb9527533ed.jpeg)

Expected Preview

![Screenshot from 2022-02-09 09-32-01](https://user-images.githubusercontent.com/3752374/153136859-7c8dd074-9b20-42c2-b8e4-32cbc9f252e2.png)

Preview I Got:

![Screenshot from 2022-02-09 09-32-31](https://user-images.githubusercontent.com/3752374/153136894-e3bdecc5-d775-4953-a484-ba07bdf7f6b3.png)

**Comment by lgladdy** [comment]
Hey @erwinyusrizal, thanks for the report. I'll take a look at this, but I think we have no control over this, and it's a WordPress default as it expects that additional css field to be applied to the outer wrapper of the html, rather than deeper in your template.

Your best way forward here might be to add another ACF field for this class instead so it's handled only by ACF, and not the default WordPress code.

**Comment by erwinyusrizal** [comment]
Hi @lgladdy thank you for your response. 
Yes, currently I created new ACF field to handle the additional css for my template

**Comment by lgladdy** [comment]
@erwinyusrizal Yeh that makes sense. WordPress will automatically apply things like backgroundColors to the blocks outer container too. We've been trying to figure out the best way forward on this over on #569 in a way that lets us take advantage of all the default WordPress `supports` for blocks, but maintaining flexibility for users templates.

I'll close this issue for now, and will consider this as part of those changes.
