### ISSUE TITLE
[Pro] Duplicate layout with checkbox/radios

### ISSUE THREAD

**Issue by nlemoine** [AdvancedCustomFields/acf#616]
Hi there,

I have a custom field type that outputs the following HTML radio inputs:
```html
<div>
    <input type="radio" value="1" id="id1" />
    <label for="id1">1</label>
</div>
<div>
    <input type="radio" value="2" id="id2" />
    <label for="id2">2</label>
</div>
<!-- etc. -->
```

`id`s have been simplified to demonstrate the issue but i'm using the following pattern: 
```php
$id = $field['id'] . '-' . str_replace( ' ', '-', $value );
``` 
taken from the checkbox field type.

When I duplicate a layout, `input` `id`s attributes are correctly replaced. But `label`s `for` attributes are not. 

Because the logic behind duplication misbehaves on `for` attributes, lines 322-329 of `assets/build/js/pro/acf-pro-input.js`: 
```js
rename: function (name, value, search, replace) {
  // Rename id attributes from "field_1-search" to "field_1-replace".
  if (name === 'id') {
    return value.replace(fieldKey + '-' + search, fieldKey + '-' + replace); // Rename name and for attributes from "[field_1][search]" to "[field_1][replace]".
  } else {
    return value.replace(fieldKey + '][' + search, fieldKey + '][' + replace);
  }
},
```

The replacing pattern for `id` attributes isn't the same than the pattern used for other attributes such as `for` which has to match the `input` `id`. It actually should be:
```js
rename: function (name, value, search, replace) {
  // Rename id/for attributes from "field_1-search" to "field_1-replace".
  if (name === 'id' || name === 'for') {
    return value.replace(fieldKey + '-' + search, fieldKey + '-' + replace); // Rename name and for attributes from "[field_1][search]" to "[field_1][replace]".
  } else {
    return value.replace(fieldKey + '][' + search, fieldKey + '][' + replace);
  }
},
```

I'm aware I could use the `<label><input /></label>` pattern but I'm not because it prevents using the css sibling selector (`input:checked ~ label`). 

Would you agree to fix this?

**Comment by nlemoine** [comment]
Note that I'm using the latest ACF version (5.12)

**Comment by nlemoine** [comment]
@mattgrshaw Could you have a look at this legitimate issue?

**Comment by mattgrshaw** [comment]
@nlemoine yep, we'll see if we can get this in a future release. Thanks for the report and suggested fix!

**Comment by nlemoine** [comment]
Thanks! :)

**Comment by nlemoine** [comment]
Just saw the release, thanks a lot for the fast fix!
