### ISSUE TITLE
Switching Template causes to remove/hide defined acf fields via php

### ISSUE THREAD

**Issue by Sysix** [AdvancedCustomFields/acf#62]
Hey,

I think I found a bug.

## Reproducing:

1. Fill a page with ACF-Fields
2. Save the Page
3. Switch the Page-Template 
4. Look how all your Input's are missing

## Group Settings:

```
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
```

## Versions:

Browser: FireFox 63
WP: 4.9.9
ACF Pro: 5.7.1

**Comment by elliotcondon** [comment]
Hi @Sysix 

Thanks for the issue,
Elliot here - ACF dev​​​.

It is expected behavior for ACF to refresh the metaboxes displayed when changing post data such as the "page template". 

1. Is it possible that your field group location rules do not match this "page template"
2. After saving the post, does the field group appear or continue to stay hidden?
3. Can you please create a field group and export it so I may import and test the same setup.

**Comment by Sysix** [comment]
Hey Elliot,

thanks for the response.

> Is it possible that your field group location rules do not match this "page template"

No, I don't have condition which checking the page template

> After saving the post, does the field group appear or continue to stay hidden?

No it stays hidden. For all Fields.

> Can you please create a field group and export it so I may import and test the same setup.

When I create the fields via the UI, it work. It look like only PHP-Fields will not update.

Here is a simple code:


```php
add_filter('acf/location/rule_match/post_type', function ($match, $rule, $options) {
    if ($rule['operator'] == 'IN' && isset($options['post_type'])) {
        $match = in_array($options['post_type'], $rule['value'], true);
    }

    return $match;
}, 10, 3);

add_action('init', function() {

    acf_add_local_field_group([
        'key' => 'sub_headline_group',
        'title' => '&nbsp;',
        'fields' => [
            [
                'key' => 'header_size',
                'label' => 'Header Größe',
                'name' => 'header_size',
                'type' => 'select',
                'default_value' => 'default-header',
                'choices' => [
                    'default-header' => 'Schmal',
                    'big-header' => 'Groß'
                ]
            ]       
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => 'IN',
                    'value' => ['post', 'page']
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'acf_after_title',
        'style' => 'seamless',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => 1,
        'description' => '',
    ]);
});
```

**Comment by elliotcondon** [comment]
Hi @Sysix 

Thanks for the reply and code.
During the AJAX call to "refresh metaboxes", the post_type may be unknown. 
To get your code running, you will need to load the post_type using the post_id screen data.

Please take a look at the 'includes/locations/class-acf-location-post-type.php' class for some code example of how the post_type is found.

Thanks
E

**Comment by Sysix** [comment]
Can it be possible that the AJAX-Call is not using the filter `acf/location/rule_match`, only the defined rule_match from the class/object?

>  To get your code running, you will need to load the post_type using the post_id screen data.

And how I manage this, when the Plugin is making the AJAX-Call?

**Comment by elliotcondon** [comment]
Hi @Sysix 

The AJAX call is definitely triggering the "acf/location/rule_match" filter. If you have any doubt of this, please perform some debugging/logging in your function to confirm.

During the AJAX call, the `$options['post_type']` data does not exist. To find the post_type of the current post, please take a look at the 'includes/locations/class-acf-location-post-type.php' class for some code example of how the post_type is found :)

**Comment by Sysix** [comment]
After debugging and debugging I found finally the "perfect" solution for my problem.  

Herer is my new rule_match code:

```php
add_filter('acf/location/rule_match/post_type', function ($match, $rule, $options) {
    if (isset($options['ajax']) && $options['ajax'] && !isset($options['post_type'])) {
        $options['post_type'] = get_post_type($options['post_id']);
    }

    if ($rule['operator'] == 'IN' && isset($options['post_type'])) {
        $match = in_array($options['post_type'], $rule['value'], true);
    }

    return $match;
}, 10, 3);
```
