### ISSUE TITLE
BUG: ACF field value not returned in combination with do_blocks() or  apply_filters( 'the_content', '')

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#631]
Hey @lgladdy @mattgrshaw 

I am run into this frustrating issue and I can't find any solution to get this worked. On a page or post I try to get the content of an other post by using `get_post()` or `get_posts()` in combination with `do_blocks( $post_content )` or `apply_filters( 'the_content', $post_content )` inside an ACF block template.

But doing this breaks the ACF field values and the values return nothing. I tried to find a solution for hours, but it dosen't work.

Do you can confirm this is not working in your case? Maybe this is a bug?

Tested all with the latest ACF version and the latest WP version:

### Example 1 (not working):

```php
get_post(12345);
	
$post_content = isset( $post->post_content ) ? $post->post_content : '';
$post_content = apply_filters( 'the_content', $post_content );	
echo $post_content;

// This is a field of an ACF block
$acf_field = get_field('field_name');

echo $acf_field; /* <-- !! return NOTHING */
```

### Example 2 (not working):

```php
global $post;
	
$posts = get_posts( array(
	'post_type' => 'post_type_name'
) );
	
foreach( $posts as $post ) {
	setup_postdata($post);	
	$post_content = isset( $post->post_content ) ? $post->post_content : '';
	$post_content = apply_filters( 'the_content', $post_content );	
	echo $post_content;
}

wp_reset_postdata();

// This is a field of an ACF block
$acf_field = get_field('field_name');

echo $acf_field; /* <-- !! return NOTHING */
```

### Example 3 (not working):

Using `do_blocks( $post_content )` instead of `$post_content = apply_filters( 'the_content', $post_content );`:

```php
get_post(12345);
	
$post_content = isset( $post->post_content ) ? $post->post_content : '';
$post_content = do_blocks( $post_content );	
echo $post_content;

// This is a field of an ACF block
$acf_field = get_field('field_name');

echo $acf_field; /* <-- !! return NOTHING */
```

### Example 1:

If I commented out `$post_content = apply_filters( 'the_content', $post_content );` like this:

```php
get_post(12345);
	
$post_content = isset( $post->post_content ) ? $post->post_content : '';
//$post_content = apply_filters( 'the_content', $post_content );	
echo $post_content;

// This is a field of an ACF block
$acf_field = get_field('field_name');

echo $acf_field; /* <-- FIELD VALUE WILL RETURNED */
```

### Example 2:

If I commented out `$post_content = do_blocks( $post_content );`  like this:

```php
get_post(12345);
	
$post_content = isset( $post->post_content ) ? $post->post_content : '';
//$post_content = do_blocks( $post_content );	
echo $post_content;

// This is a field of an ACF block
$acf_field = get_field('field_name');

echo $acf_field; /* <-- FIELD VALUE WILL RETURNED */
```

### Example 3:

Post content as string:

```php
$post_content ='<!-- wp:heading --><h2>Owner of this website</h2><!-- /wp:heading -->';
$post_content = apply_filters( 'the_content', $post_content );	
echo $post_content;

// This is a field of an ACF block
$acf_field = get_field('field_name');

echo $acf_field; /* <-- FIELD VALUE WILL RETURNED */
```

### Summary

Each time I tried to convert the post content (block content) to HTML by using `apply_filters( 'the_content', $post_content )` or `do_blocks( $post_content )` the ACF field value returned nothing.

Only without converting the post content to HTML or without using `get_post()` or `get_posts()`, the ACF field value is successfully returned.

**Comment by lgladdy** [comment]
Hey, this isn't a bug I'm afraid, this isn't a supported use case.

`get_field` for an ACF Block's fields will only work inside an ACF block template. In all your examples, you're trying to access the fields on the post, rather than the block.

**Comment by CreativeDive** [comment]
@lgladdy please check this again:

I try to get ...

```
// This is a field of an ACF block
$acf_field = get_field('field_name');
```

... is a field of an ACF block template.

**Comment by lgladdy** [comment]
Are you saying your code is running inside an ACF Block's template, not on page or post?

**Comment by CreativeDive** [comment]
@lgladdy yes this code is running inside an ACF block. And I think all three examples should actually work.

**Comment by lgladdy** [comment]
If that is the case, then I can understand why that would be broken. You're modifying the global context, and wp_reset_postdata won't work inside a block template as that will only reset things about the post - it doesn't have an awareness of the block.

You might be able to switch back to the block's meta by using `get_field('field_name', $block['id'])` - it's a kinda reverse situation of having to use `get_the_ID()` when in a block to access fields on the post; using any kind of post setup function will make ACF lose the block context.

**Comment by CreativeDive** [comment]
@lgladdy thanks for the feedback. I will try to test it by using `get_field('field_name', $block['id'])` instead and will reporting back later this day. Thank you

**Comment by CreativeDive** [comment]
@lgladdy Thank you for your very quick feedback and help. That made my day. It works like a charm. Passing `$block['id']` is solving all my issues.

**Comment by lgladdy** [comment]
@CreativeDive No worries! I'll make sure we continue supporting that same code once we remove block IDs. Cheers.

**Comment by CreativeDive** [comment]
@lgladdy I have a question because you mentioned that the block IDs will removed. My thought was the block ID will removed inside the template output only.

I wonder which variable is usable to identify a specific block if the block ID is completely removed?

Some of my block use WP queries. To improve the loading performance, this queries will cached with transients.

To assign the saved transient to the correct block, I use the block ID like `my_transient_query_block_name_' . $block[ID] . '`.

It seems this will broken after the block IDs are removed.

Is there any other block specific identifier I can use for this?

**Comment by CreativeDive** [comment]
@lgladdy Or another use case is to get data from an API and save it with transients for loading performance reasons.

To use the "`$post_id`" is no alternative, because this dosen't work if the same block type is multiple used with different queries on the same page / post.

**Comment by lgladdy** [comment]
@CreativeDive We can pick this up on the release post once it's out; but the point of blocks is that they're supposed to be standalone, and portable. IDs fundamentally break that paradigm; as you've seen by trying to duplicate or copy things.

You could generate your own ID to be saved against the block server side if you really wanted to add it back in; but obviously that wouldn't be recommended. You'd be better off using a proper query caching system that wasn't block specific, but rather query specific - that's the data which is important to cache; what block it is in shouldn't matter!

**Comment by CreativeDive** [comment]
@lgladdy thanks for the hint. This is correct, using block ids is not future proofed.

I think to use the `$args = array(...)` for WP queries or the `request` itself for APIs could be the alternative identifier for using transients cache here.

Thank you!

**Comment by lgladdy** [comment]
@CreativeDive Yeh - this is why I'm hoping to run a longer beta where we can work with devs to figure it out in a way that doesn't break things for the majority of users.

ACF Blocks has a lot of legacy we need to modernise in order to make future WordPress changes less impactful on us; and block IDs are one of the biggest issues we have as ACF's devs, and users have trying to use new features WordPress introduces.
