### ISSUE TITLE
Filter acf/load_value broken in front-end

### ISSUE THREAD

**Issue by FeIix** [AdvancedCustomFields/acf#632]
Hi,

I noticed a bug after updating from ACF PRO 5.11.4 to 5.12.1.
I think it's a bug because I haven't found any explanation for this in changelogs :

The filter acf/load_value is not triggered anymore in frontend forms, only in admin.
It was working as expected until 5.11.4, then it suddenly broke.

Is it a bug or an undocumented breaking change ?

In this case I was using load_value to prefill a date field with the current date.
Is there another filter I could use to do this ?

**Comment by mattgrshaw** [comment]
Hi @FeIix 

Sorry to hear you ran into this - however I just tested this out myself and wasn't able to replicate the issue.

I've tested with various combinations of the `acf/load_value` filter and with/without the datefield in frontend forms, and that seems to be working even if completely logged out.

Would you be able to attach an export of the field group that you're using, as well as share the code you're using for adding that filter?

**Comment by FeIix** [comment]
Thanks for your answer.


I attached the acf-json of the field group. The problematic field is "reunion_day"

Here is the code used to prefill that field with a GET param :
```
add_filter('acf/load_value/name=reunion_day', function($value, $post_id, $field) {
    if ($value !== null) return $value;
      
    if(!empty($_GET['meeting_day'])){
        $value = $_GET['meeting_day'];
    }
    return $value;
}, 1, 3);
```

This is never called in frontend (done var_dump + die before the return)

Reverting back to ACF Pro 5.11 made it work again.


Thanks

**Comment by FeIix** [comment]
As advised by ACF support, I replaced acf/load_value by the acf/prepare_field filter and this one work, maybe this will help someone

**Comment by unetics** [comment]
Just confirming i have had issues with this same filter since the upgrade this is not an isolated bug.

**Comment by mattgrshaw** [comment]
@FeIix Glad to hear you found a workaround.  Just to confirm, are you using the frontend forms functionality included in ACF, or are you using forms created through ACF Extended?

@unetics Thanks for chiming in as well. Could you please also confirm if you're using standard ACF frontend forms or forms created through ACF Extended?

**Comment by unetics** [comment]
@mattgrshaw your right i am using ACF Extended this may be the issue.

**Comment by mattgrshaw** [comment]
Thanks @unetics. We're looking into this further on our end. In the meantime, you may be able to use the `acf/pre_load_value` as a workaround as Felix mentioned above.

**Comment by FeIix** [comment]
> @FeIix Glad to hear you found a workaround. Just to confirm, are you using the frontend forms functionality included in ACF, or are you using forms created through ACF Extended?
> 
> @unetics Thanks for chiming in as well. Could you please also confirm if you're using standard ACF frontend forms or forms created through ACF Extended?

I'm not using ACF Extended, the form is generated with the acf_form() function.

**Comment by lgladdy** [comment]
@FeIix Hey Felix, We're working on a release with a fix for the ACFE Form issues with default values - if you're interested in a beta build, can you drop us an email to support@ and ill send it over?

**Comment by FeIix** [comment]
Thanks, message sent

**Comment by FeIix** [comment]
I tested the beta build, I can confirm that the acf/prepare_field problem is solved for me !

Thanks

**Comment by mattgrshaw** [comment]
Closing this one as this should be resolved with the latest version of ACF.
