### ISSUE TITLE
Cloned clones not saving data in 5.12.1

### ISSUE THREAD

**Issue by raray** [AdvancedCustomFields/acf#633]
After updating to 5.12.1, fields that are clones of clones no longer save changes. Reverting to 5.12 returned expected functionality.

**Comment by lgladdy** [comment]
Hey @raray. Could you send us a field export of your setup so we can try to reproduce this please? Feel free to email if you'd rather not attach it publicly.

**Comment by raray** [comment]
@lgladdy Sorry I never made it back to this, but it does appear to be resolved in `15.12.2`.
