### ISSUE TITLE
PHP block registration doesn't pass all defined args

### ISSUE THREAD

**Issue by timotheemoulin** [AdvancedCustomFields/acf#637]
Hi,
When registering a new Gutenberg block in PHP all the params are not passed through the `register_block_type` function.

Here is a basic example.
```php
<?php
acf_register_block(
    [
        'name'            => 'my-block',
        'title'           => 'This is my block',
        'description'     => 'Small description',
        'render_callback' => 'some_working_php_callback',
        'category'        => 'my-custom-category',
        'icon'            => 'index-card',
        'keywords'        => [ 'custom-keyword', 'list' ],
        'mode'            => 'preview',
        'supports'        => [
            'align' => false, // disable alignment selection
            'mode'  => false, // force edition in the sidebar
        ],
    ]
);
```

When calling `WP_Block_Type_Registry::get_instance()->get_all_registered()` in a script after the registration, you can see that some values are missing.
- title
- category
- icon
- description

![image](https://user-images.githubusercontent.com/1841590/162140331-139b112c-ae4b-489b-861b-d6109857bfee.png)

All the values are correct in the Gutenberg block inserter.
![image](https://user-images.githubusercontent.com/1841590/162141024-64fb9096-d875-4936-94ae-3f7f54ffced6.png)

The error seems to come from this portion of `function acf_register_block_type`.
```php
<?php
// Register block type in WP.
if ( function_exists( 'register_block_type' ) ) {
    register_block_type(
        $block['name'],
        array(
            'attributes'      => acf_get_block_type_default_attributes( $block ),
            'uses_context'    => $block['usesContext'],
            'api_version'     => 2,
            'render_callback' => 'acf_render_block_callback',
        )
    );
}
```

When calling `register_block_type()` souldn't we pass all the given args?
IMO we sould try to keep consistency  in the block definition between PHP and JS.

**Comment by lgladdy** [comment]
This issue will be resolved in our next release, and should be fixed now in our [ACF Block Versioning Preview](https://github.com/AdvancedCustomFields/acf/issues/654) release available now.
