### ISSUE TITLE
Attachment custom fields not showing on initial load

### ISSUE THREAD

**Issue by cmargroff** [AdvancedCustomFields/acf#64]
I currently has a Credit field added for all image types with ACF.
If an image is currently set as featured and the user attempts to update the custom field it does not appear initially after clicking the featured image in the editor.
The user must first click any other image and then back to the original to see the field. It also shows the field by going directly to the attachment from the media gallery.

**Comment by elliotcondon** [comment]
Hi @cmargroff 

Please contact support for any help with the ACF plugin, thanks.
http://www.advancedcustomfields.com/contact/
