### ISSUE TITLE
All fields showing on all post editing screens, regardless of rules

### ISSUE THREAD

**Issue by jalefkowit** [AdvancedCustomFields/acf#644]
In our WP installation, which has a theme that makes heavy use of ACF Pro, we have been struggling for a while now with ACF fields showing up on all post/page editing screens, regardless of what rules are set to target where they should and should not appear. Field group metaboxes that are not ruled in for display in a particular editing screen are shown with a loading spinner that never resolves (i.e., the appropriate fields for that group are never loaded into the metabox).

![failed-metabox](https://user-images.githubusercontent.com/453235/164315052-1dcd1dcb-8bd5-4ff3-940f-60ff5b901700.png)

[Others have reported the same problem in the support forum](https://support.advancedcustomfields.com/forums/topic/fields-showing-on-all-pages-despite-field-group-location-rules/), and it was mentioned that 5.8.0 was supposed to solve it, but that version didn't solve it for us, and no update since has solved it either. We're still seeing the same behavior on ACF Pro 5.12.1.

#77 sounds similar, and the issue report says it was fixed in 5.8.0-beta2. But that issue was labeled as Gutenberg-specific, and we're using Classic Editor, so I'm not sure if the problem is the same. When I disable the Classic Editor plugin to force the editor to use Gutenberg, it still displays non-relevant field groups (though, weirdly, not some that show up under Classic Editor), so I suspect the problem lies somewhere deeper than which editor is in use.

I have periodically attempted to go spelunking through the ACF source to find where the root of the issue is, but I haven't been able to identify it on my own. If this is a known issue with a known fix or workaround, any guidance on how to resolve it would be great. 

Our WP installation is multi-site/network enabled, if that helps. Other possibly relevant info:

- WordPress: version 5.9.2
- PHP: 7.2.24-0ubuntu0.18.04.6 
- Web server: Apache
- OS: Ubuntu

**Comment by lgladdy** [comment]
@jalefkowit Hey Jason, could you raise this as a support request by email so the support team can pick it up and try to debug what's going on for you? Cheers!
