### ISSUE TITLE
BUG: No content after <InnerBlocks... is showing in the block editor

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#650]
Hey @lgladdy 

I have detected a bug in the case of <InnerBlocks ... /> is used in the block editor. If we have content after the <InnerBlocks ... /> tag. The content below is no longer there in the block editor. In the front end view everything is visible after the innerblocks.

Here an example:

```
<InnerBlocks allowedBlocks="<?php echo esc_attr( wp_json_encode( $allowed_blocks ) ); ?>" template="<?php echo esc_attr( wp_json_encode( $template ) ); ?>" />

<div>My content below</div>
```

The `<div>My content below</div>` is not outputted in the block editor.

This issue can solved by adding `</InnerBlocks>`. But should we do that?

```
<InnerBlocks allowedBlocks="<?php echo esc_attr( wp_json_encode( $allowed_blocks ) ); ?>" template="<?php echo esc_attr( wp_json_encode( $template ) ); ?>"></InnerBlocks>

<div>My content below</div>
```

Which is the correct way to solve that issue? It's a bug or the first way to use <InnerBlocks ... /> is not correct?

**Comment by CreativeDive** [comment]
@lgladdy Content that is not displayed after `<InnerBlocks ... />` only affects content that is in the same block template as the `<InnerBlocks ... />`.

**Comment by CreativeDive** [comment]
@lgladdy this could be the reason for this warning?!

<img width="1675" alt="Bildschirmfoto 2022-05-05 um 07 38 54" src="https://user-images.githubusercontent.com/31563167/166868412-71423677-5f5b-4334-9284-87b83f64f296.png">

**Comment by lgladdy** [comment]
I'm able to reproduce this, we'll try and get it fixed in our next release :)

**Comment by CreativeDive** [comment]
@lgladdy thank you!

**Comment by lgladdy** [comment]
I've got a fix ready to go for this, so pending our internal PR it should be in our upcoming block changes beta.

**Comment by lgladdy** [comment]
This issue will be resolved in our next release, and should be fixed in our [ACF Block Versioning Preview](https://github.com/AdvancedCustomFields/acf/issues/654) build.
