### ISSUE TITLE
Limit post title lenght in custom loop

### ISSUE THREAD

**Issue by andre994** [AdvancedCustomFields/acf#651]
Hi, i'm trying to limit the title lenght of my posts in the custom loops i made with Ele Custom Skin, to avoid having a messy loop layout with cards of different height.
I've tried using the following script that i found in some thread online, but to no avail:

```
function max_title_length( $title ) {
    $max = 20;

    if ( in_the_loop() && strlen( $title ) > $max ) {
        return substr( $title, 0, $max ) . ' &hellip;';
    } else {
        return $title;
    }
}
add_filter( 'the_title', 'max_title_length' )
```

What am i missing?

**Comment by lgladdy** [comment]
Hey @andre994, we use this repo for bug reports and pull requests for the Advanced Custom Fields plugin, rather than support.

Additionally, your issue isn't related to ACF and so would be better asked in a WordPress support forum! Cheers :)
