### ISSUE TITLE
ACF Block loses connection when momentarily clicked

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#657]
Hey @lgladdy,

I've noticed this issue for a long time and still with the current alpha version. I am very often confronted with this issue and I think others are too. @JiveDig Perhaps you have also had such experiences?

This issue is actually very easy to understand and to reproduce.

The point is that if you short click on an ACF block and then click on another block, you can no longer make field changes if you then go back to the previously clicked block and want to change field values.

Only when you then reload the page can you make changes to the field values ​​again.

Here the screen recording:

![May-30-2022 13-19-44](https://user-images.githubusercontent.com/31563167/170981877-a4f865f7-dd25-466a-9dca-605a92c28859.gif)

This can happen very often when creating content in the Block Editor. It happens to me personally more often.

It would be great if this problem could be fixed.

It seems that if you click on an ACF block and leave it before the fields have been loaded with AJAX, then this problem occurs.

It also seems that this issue is not due to the previously existing block IDs.

This could be related to: https://github.com/AdvancedCustomFields/acf/issues/605

**Comment by CreativeDive** [comment]
@lgladdy this is the full console log:

<img width="928" alt="Bildschirmfoto 2022-05-30 um 13 43 01" src="https://user-images.githubusercontent.com/31563167/170985396-288bffbf-71c9-4ee6-9aba-c1122838cfbd.png">

And no more. If you then go back to the ACF block and try to change field values, no new entries appear in the console.

**Comment by JiveDig** [comment]
I definitely and regularly have blocks freeze up like that. I've never pinpointed why it happens and find myself refreshing the admin page multiple times during the time I'm doing a bunch of edits to a page.

To clarify for me, I can change the settings but the preview does not update and the values do not actually save when I Update the post.

**Comment by CreativeDive** [comment]
@JiveDig Thanks for the input and good to know it happens to you just as often. I think after removing the block IDs this would be another approach to improve the user experience of ACF blocks even more.

**Comment by lgladdy** [comment]
Gunna close this one (as I don't think I can merge...) but this is the same issue as #605.

ACF isn't responsible for the application of WordPress rendered properties like background colours, so this is almost certainly Gutenberg bug. We'll raise this up to them as we deal with the issue in #605. Cheers!

**Comment by CreativeDive** [comment]
@lgladdy It would be great if there could be a solution to this issue. Because we are confronted with it very often.

**Comment by CreativeDive** [comment]
@lgladdy the same issue occurs with all the other ACF default field types.

**Comment by JiveDig** [comment]
I can confirm this happens to us on blocks that do not use native/core controls. It happens with our most used field types like select, button group, radio, checkbox, etc.

**Comment by JiveDig** [comment]
Sounds good. Already subscribing there I just wanted to clarify on this thread for anyone involved or anyone that finds it later. Thanks :)

**Comment by lgladdy** [comment]
Just to confirm we believe this issue will be resolved in the second preview build of the block changes, and will pick this up in #605 after it's release.

Changing the close status of this from completed to duplicate.
