### ISSUE TITLE
BUG: With Group fields

### ISSUE THREAD

**Issue by samjco** [AdvancedCustomFields/acf#659]
If I make ACF fields to reference my WP user_meta: first_name, last_name, etc..
They seem to work by showing the same info that is in the user default first name, etc fields!
But if I move my ACF user fields into a Group field, they do not work..

Also, If I move (drag and drop) fields out of my Group Field, remove the Group field, and the update.....
All of my fields that I've moved out will all delete as well!!!

Please fix!

**Comment by lgladdy** [comment]
Hey @samjco,

This isn't really a bug, ACF's working as designed here.

If you use a field name that clashes with a WordPress default, you'll see the data from that value.

When you move a field into a group (or out of a group) you change the key for that field, and so ACF won't see the current data - just as if you were to manually rename a field. If you want to move data around like that you also need to manually update the existing saved meta values to match the new field keys.

Thanks!
