### ISSUE TITLE
Deprecated: wp_make_content_images_responsive is deprecated since version 5.5.0!

### ISSUE THREAD

**Issue by matzocca** [AdvancedCustomFields/acf#668]
Hi, this error appears on my site (https://recooper.it/):
[Deprecated: La funzione wp_make_content_images_responsive è deprecata dalla versione 5.5.0! Utilizza al suo posto wp_filter_content_tags(). in /var/www/recooper.it/httpdocs/sito/wp-includes/functions.php on line 5379](https://recooper.it/chi-siamo/)

How can I fix it without switching to the pro version of the plugin?

Thanks in advance
Matteo

**Comment by lgladdy** [comment]
Hey @matzocca 

ACF has supported this change in WordPress for a long time.

I don't think this an an ACF bug. What version of ACF and WordPress are you running?
