### ISSUE TITLE
support composer/installers ^1.0|^2.0

### ISSUE THREAD

**Issue by drzraf** [AdvancedCustomFields/acf#670]
Please relax the constraint in the pro-version composer package.
That's what Bedrock now requires and the plugin is incompatible without this.

**Comment by lgladdy** [comment]
@drzraf Hey, we currently don't provide ACF PRO via composer. Please raise this issue with the third party plugin you're using for that.

We're hoping to bring official support for composer installs of ACF PRO in a future release, once we've made some backend changes to enable support for it.
