### ISSUE TITLE
Block assets are not loading in WP pattern inserter

### ISSUE THREAD

**Issue by JiveDig** [AdvancedCustomFields/acf#674]
I originally thought this was caused by the [developer preview](https://github.com/AdvancedCustomFields/acf/issues/654#issuecomment-1182457201) but have since found out it's not working in 5.12 either.

I have existing blocks that load styles fine in the editor and on the front end, but the pattern preview doesn't load styles at all.

The editor shows this:
![image](https://user-images.githubusercontent.com/540990/178764122-78434eba-df41-4d0b-ae77-564402ee598c.png)

While the inserter shows this (notice the icons are missing styling):
![image](https://user-images.githubusercontent.com/540990/178764202-77e57070-e81c-4d14-b992-605962c6fb65.png)

I'm using `acf_register_block_type()` to register the blocks and have tried `enqueue_style` and `enqueue_assets` with the same results.

**Comment by lgladdy** [comment]
@JiveDig Awesome! Yeh, we'll get the docs updated, but we didn't want to do a sweep on that when we need to do the block.json updates too for 6.0!

The main issue right now with the iFrames is you can't rely on third party JS libraries being available, even things like jQuery may not work, and they don't have an easy way to mark a script as something which needs to be available inside all blocks.

This is why ACF's edit mode can't work in those iframes (such as when you use the phone or tablet preview mode in the block editor) - because we aren't allowed to access things like select2 or date picker libraries inside those blocks. We're hoping the Gutenberg team will solve this before they force the desktop view to be inside an iframe too!

**Comment by JiveDig** [comment]
Good to know! I don't use any external libraries as of now, and we're 100% jQuery-free (for performance purposes) thankfully.

**Comment by CreativeDive** [comment]
> This is why ACF's edit mode can't work in those iframes (such as when you use the phone or tablet preview mode in the block editor) - because we aren't allowed to access things like select2 or date picker libraries inside those blocks. We're hoping the Gutenberg team will solve this before they force the desktop view to be inside an iframe too!

@lgladdy Does WordPress even have that in mind? I hope so too.

**Comment by JiveDig** [comment]
@lgladdy Is this "new way" only an v2 API thing? I'm testing on 5.12 now and my styles are not loaded at all, anywhere.

I've also added:
```
'api_version'       => 2,
'acf_block_version' => 2,
```
to my `acf_register_block_type()` array and that doesn't help.

**Comment by CreativeDive** [comment]
@JiveDig This has been introduced since ACF 6.0, right?

```
'api_version'       => 2,
'acf_block_version' => 2,
```

How do you load styles with 5.12 now? Why not switch to `block.json` entirely?

**Comment by lgladdy** [comment]
@JiveDig My suggestion is a code change to ACF's core code to potentially fix a bug that might be preventing it working, nothing to do with your code there!

**Comment by CreativeDive** [comment]
From my understanding, `"style"` doesn't exist for use in ACF's 5.12 `acf_register_block_type()` like in your sample code above. Following @lgladdy suggestion, this would be a possible solution. And maybe an addition of the ACF 6.0 release (?!), if it's working in your case @JiveDig.

**Comment by JiveDig** [comment]
>@JiveDig My suggestion is a code change to ACF's core code to potentially fix a bug that might be preventing it working, nothing to do with your code there!

Doh! Now I see what you meant.

First attempts through an undefined error because not all blocks had `style` defined, so I went this:
```
'style' => isset( $block['style'] ) ? $block['style'] : '',
```
and now it works. 

So it sounds like the only way to get this to work now would be to modify ACF (obviously not great) or wait for 6.0.

Any filters anywhere that you can think of that may be able to help pass this attribute in the meantime?

**Comment by JiveDig** [comment]
>Let me see if that's another way/filter or something I can think of to force this in!

Thanks. I'm digging now and not seeing it. Thankfully (as of now) our platform loads ACF for the customers so I think we could get by _for now_ by modifying ACF. Obviously not great but maybe it will get us by until 6.0.

Do you foresee any issues if I use `enqueue_style` AND `style` attributes in `acf_register_block_type` so there is a fallback incase someone loads ACF separately without the modified version?

**Comment by JiveDig** [comment]
>Do you foresee any issues if I use enqueue_style AND style attributes in acf_register_block_type

FWIW my testing is proving that this works so at least styles are loaded. If `style` is missing from `register_block_type` in ACF my styles are still loaded, and I only lose styles in the pattern inserter.

**Comment by lgladdy** [comment]
> Ah just saw that go out, you should have snuck this one in there! 😂

Ha, i'd have loved too... but we've got so many fixes ready to go in 6.0, along with so many build system updates and such that trying to back port specific issues back to the 5.12.x branch would have been a nightmare (and probably risked breaking everything...) so we stuck to the security fix only in that one!

I'm hoping it won't be too much longer until 6.0 is ready anyway... We should be moving to betas and RCs over the coming weeks.

**Comment by lgladdy** [comment]
Hey everyone,

I've been doing a little bit more work into this, this morning to try and get a way to reliably load styles (and scripts) in all cases.

As we suspected, this isn't currently possible on ACF 5.12.3, but will be in ACF 6, but you can manually edit ACF's code to enable this on 5.12.x, specifically `pro/blocks.php` we'll replace the "Register block type in WP" function which begins on line 53, with:

```php
	// Register block type in WP.
	if ( function_exists( 'register_block_type' ) ) {
		register_block_type(
			$block['name'],
			array(
				'attributes'      => acf_get_block_type_default_attributes( $block ),
				'uses_context'    => $block['usesContext'],
				'style'           => $block['style'],
				'script'          => $block['script'],
				'api_version'     => 2,
				'render_callback' => 'acf_render_block_callback',
			)
		);
	}
```

The "array" methods of style and scripts don't seem to work correctly with non block.json blocks, so you need to make sure you only specify one entry in your block registration, and use dependancies for this.

Specifically, my demo here is for a slick.js carousel block, so you can see how I load the slick css styles, the slick JS framework and my custom JS to bring it all together, which works in the iFrame previews too.

Here's the block registration PHP:

```php
<?php

add_action( 'acf/init', 'acf_init_add_blocks' );

function acf_init_add_blocks() {
	wp_register_style( 'slick', get_template_directory_uri() . '/inc/blocks/slider/slick/slick.css', array(), '1.8.1' );
	wp_register_style( 'slick-theme', get_template_directory_uri() . '/inc/blocks/slider/slick/slick-theme.css', array( 'slick' ), '1.8.1' );

	wp_register_script( 'slick', get_template_directory_uri() . '/inc/blocks/slider/slick/slick.min.js', array( 'jquery' ), '1.8.1', true );
	wp_register_script( 'slider-js', get_template_directory_uri() . '/inc/blocks/slider/slider.js', array( 'slick' ), '1.0.0', true );

	acf_register_block_type(
		array(
			'name'            => 'slider',
			'title'           => 'Slider',
			'description'     => 'A custom slider block.',
			'render_template' => __DIR__ . '/blocks/slider/slider.php',
			'style'           => 'slick-theme',
			'script'          => 'slider-js',
			'category'        => 'formatting',
			'icon'            => 'images-alt2',
			'align'           => 'full',
		)
	);
}
```

And here's a zip of the contents of `/inc/blocks/slider` - note if you're using the block a plugin, you'll need to change the `get_template_directory_uri` function accordingly.

[slider.zip](https://github.com/AdvancedCustomFields/acf/files/9132209/slider.zip)

I'll be posting a ACF6 version of this block, using block.json and the WPDefinedAsset method of including scripts, over on the [main thread for 6.0](https://github.com/AdvancedCustomFields/acf/issues/654)

**Comment by JiveDig** [comment]
Thanks for this @lgladdy. Just a reminder that the only thing I hit when adding that to ACF core was an undefined index (or similar) error for blocks registered that don't have script/style in the array.

**Comment by lgladdy** [comment]
> Thanks for this @lgladdy. Just a reminder that the only thing I hit when adding that to ACF core was an undefined index (or similar) error for blocks registered that don't have script/style in the array.

Thanks, fixed!

**Comment by lgladdy** [comment]
This issue is resolved when using the WordPress provided script and style asset loaders with ACF Blocks v2 in ACF >=6.0
