### ISSUE TITLE
Translator note requested

### ISSUE THREAD

**Issue by NekoJonez** [AdvancedCustomFields/acf#678]
https://translate.wordpress.org/projects/wp-plugins/advanced-custom-fields/stable/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7728807&filters%5Btranslation_id%5D=96297586

Can for this string, a translator note be added? For the simple reason that "Order" can mean either "Placing an order" or "The order of the numbers" and in translation to e.g. Dutch it's VERY different.

**Comment by lgladdy** [comment]
@NekoJonez Sure! I'll get this added in the next release.

**Comment by lgladdy** [comment]
Just to confirm, we've got this merged into our internal develop branch now, so our next release will contain this. Thanks again for the suggestion!
