### ISSUE TITLE
ACF numerical value... the problem ⚡

### ISSUE THREAD

**Issue by nreljed** [AdvancedCustomFields/acf#679]
Hello,
we must talk about an important point concerning the acf shortcodes and the formatting of numerical values

in my example here I'm trying to get the price and surface to be nicely formatted and the symbol and currency values to be displayed after 

but it doesn't work, my acf-options values are not showing... I  can't figure out what is going wrong...

```
// Return ACF Number Fields Formatted with Commas on the Frontend
    add_filter('acf/format_value/name=price', 'acf_number_comma_decimal_for_currency_field', 20, 3);
    
    function acf_number_comma_decimal_for_currency_field($value, $post_id, $field) {
        if(empty($value)){
        return 'Price: Contact US';
      }
      $value = number_format(floatval($value), 0) . the_field('currency', 'acf-options');
    
      return $value;
    }
    
    // Return ACF Number Fields Formatted with Commas on the Frontend
    add_filter('acf/format_value/name=surface', 'acf_number_comma_decimal_for_surface_field', 20, 3);

function acf_number_comma_decimal_for_surface_field($value, $post_id, $field) {
      $value = number_format(floatval($value), 0) . the_field('symbol', 'acf-options');
    
      return $value;
    }
```

Can we make it more simpler and see things differently? like adapting acf to elementor/gutenberg to make a special interface for numeric value like this?

 jetengine approach with numeric values
![Capture d’écran 2022-08-02 154631](https://user-images.githubusercontent.com/82481592/182405107-352ecaf6-66ed-4198-b0c1-dbdd94aa37d6.png)

ACF Modern Numeric Filed 

the idea is to add in dynamic tags the formatting options and adapt the everything shortcode policy so that I can extract and add my acf-option values
it will look something like this

![acf numeric](https://user-images.githubusercontent.com/82481592/182409209-daa144c8-e53e-43ea-8f26-fe1cba9ac819.png)

![acf numeric field](https://user-images.githubusercontent.com/82481592/182410082-dcd53ff3-3992-4e5a-9718-763d046afaa8.png)

the main thing is to have the control inside the dynamic tag

**Comment by lgladdy** [comment]
Hey, unfortunately this isn't an ACF bug. Your code would work in a native ACF field, or ACF shortcake outside of elementor

You'll need to contact elementor support for advice on how to achieve this in their plugin. Thanks!
