### ISSUE TITLE
nl_BE translation done 

### ISSUE THREAD

**Issue by NekoJonez** [AdvancedCustomFields/acf#681]
![Screenshot_20220803-232515645.jpg](https://user-images.githubusercontent.com/4569581/182715016-762238a5-898d-4444-aa62-75174d7d9291.jpg)

Is the fallback still needed? I finished the nl_BE translation yesterday

**Comment by lgladdy** [comment]
Thanks for the heads up here @NekoJonez, we'll take a look at this.

As you know our chats on the polyglots WordPress slack, we will begin importing that language from our next release. I'll duplicate the pro strings file from nl_NL to nl_BE and remove this override so we can pick up your translations from translate.wordpress.org

**Comment by lgladdy** [comment]
Hey @NekoJonez, gunna close this issue now we've got the new translation systems in place.

This override was removed from ACF 6.0.0-beta1, so you should have your new translate.w.org strings in place!
