### ISSUE TITLE
Request: Add Post Type --> ALL to fields post type location rules.

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#690]
Hey @lgladdy,

I would like to display field groups for each type of public post type, but I found that this is currently not possible.

Therefore I want to start the request for an addition to add the location rule "`Post Types: All public`".

<img width="1228" alt="Bildschirmfoto 2022-08-18 um 15 19 24" src="https://user-images.githubusercontent.com/31563167/185404915-754cfbd5-10a4-4de3-a907-161ad8b7da4f.png">

Important would be to do this for public post types only:

```php
$post_args = array(
	'public' => true, // --> Only include public post types
);

// Get post types
$post_types = get_post_types( $post_args, 'objects' );	
```

And maybe the "attachment" post type could be removed from this public post types:

```php
// Define a list of disallowed post types
$disallowed_post_types = array(
	'attachment',
);		

$results = array();

if( $post_types ) {
	foreach( $post_types as $post_type_slug => $data ) { 

		if( in_array( $post_type_slug, $disallowed_post_types) ) {
			unset( $post_types[$post_type_slug] );
			continue;
		}

		$results[$post_type_slug] = $data;		

	}
}

return $results;

```

**Comment by lgladdy** [comment]
I'll let @polevaultweb pick this one up as feature requests need to go through him for prioritisation.

We're also trying to keep GitHub to only bugs/issues for devs rather than feature requests though, so I suspect he'd prefer this stuff logged to the support email if you don't mind! Cheers :)

**Comment by polevaultweb** [comment]
@CreativeDive Thanks for the feedback. Custom rules can be added using this [doc](https://www.advancedcustomfields.com/resources/custom-location-rules/), so you could implement this yourself. We'll add your suggestion to our internal discussion tracker.
