### ISSUE TITLE
PHP 8: Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value.

### ISSUE THREAD

**Issue by philipjohn** [AdvancedCustomFields/acf#691]
When running a PHPCompatibility check for any issues with PHP I came across the following warning:

> Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter, but will instead provide the current value. The parameter \$post_id\" was used

It looks like there are [more uses of `func_get_args()`](https://github.com/AdvancedCustomFields/acf/search?q=func_get_args) too. 

I'm not sure if this is a big issue in PHP 8 yet, as I haven't seen anything going wrong in my project, but I wanted to flag it anyway.

**Comment by lgladdy** [comment]
Our use of of this function is unaffected by this change. Thanks for the heads up though! 👍
