### ISSUE TITLE
Charecters converted to Unicode inside Alpine JS components

### ISSUE THREAD

**Issue by arceoh** [AdvancedCustomFields/acf#692]
### Issue description:
When using Alpine JS a few characters get converted to Unicode Decimal Code.

`'>'` gets converted to `'>&#8216;`

So when having this in a block.php

```
<div x-data="{ foo: '>'}">
    <p x-text="foo"></p>
</div>
```
You get this in the page source
```
<div x-data="{ foo: '>&#8216;}&#8221;>
    <p x-text="foo"></p>
</div>
```

Vanilla JS like `<script>console.log('>')</script>`  works fine.

**Comment by lgladdy** [comment]
This doesn't seem to be a bug with ACF?

If we're outputting stuff fine for vanilla JS, it has to be an issue with Alpine which we wouldn't be able to support I'm afraid.
