### ISSUE TITLE
ACF 6.0 RC1 - UI Update Feedback

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#694]
@polevaultweb Thanks for the fresh UI update. It looks very good overall. However, I have noticed a few things so far.

## 1. Title should be in line

A note here because it confuses my eyes a lot. The field title should be in line with the rest.

Before:

<img width="1372" alt="Bildschirmfoto 2022-08-24 um 19 28 23" src="https://user-images.githubusercontent.com/31563167/186485200-b0fd6fda-69f4-48b6-b364-358180fbbfcf.png">

Now:

![Bildschirmfoto 2022-08-24 um 19 29](https://user-images.githubusercontent.com/31563167/186485689-bef6516c-b640-464f-b3f7-4cbf019b7180.jpg)

## 2. Icon is breaking

The key icon should not break an small screens:

https://user-images.githubusercontent.com/31563167/186487578-75876818-8982-411d-bc7c-0a588a1ce4d0.mp4

## 3. More compact

Before, everything was a bit more compact in the list view. I prefer that more. Maybe you could reduce the inner distance a bit.

https://user-images.githubusercontent.com/31563167/186489018-bc45b4ab-c692-41ad-922b-82b2dbff48dd.mp4

You can save space if you apply the horizontal padding to one side only `padding: 12px 0 12px 24px;` instead to right and left.

_Originally posted by @CreativeDive in https://github.com/AdvancedCustomFields/acf/issues/654#issuecomment-1226051614_

**Comment by CreativeDive** [comment]
## 4. Box shadow on active / focused elements

The box shadow on active / focused elements looks like it doesn't belong there. This could be solved with `box-shadow: none;`

<img width="457" alt="Bildschirmfoto 2022-08-24 um 20 01 17" src="https://user-images.githubusercontent.com/31563167/186490843-50922ca2-bff6-4471-b104-bc0ba397c5f4.png">

<img width="456" alt="Bildschirmfoto 2022-08-24 um 20 01 27" src="https://user-images.githubusercontent.com/31563167/186490853-19536ce6-bf9a-4f98-8d48-955106fd6e5a.png">

**Comment by lgladdy** [comment]
I'm gunna hi-jack the title of this thread and open this up for everyone to give feedback here so @polevaultweb has all the GitHub feedback in one place if that's okay!

**Comment by CreativeDive** [comment]
## 5. The new toggles

It looks like the new toggles have an extra outline which is not in shape if the toggle is active / focused.

<img width="71" alt="Bildschirmfoto 2022-08-24 um 20 08 10" src="https://user-images.githubusercontent.com/31563167/186492771-100ad4f9-dff8-4916-89eb-73023d82138b.png">

<img width="61" alt="Bildschirmfoto 2022-08-24 um 20 08 24" src="https://user-images.githubusercontent.com/31563167/186492776-8d15f62c-0292-4ee7-9175-cdf8fbd8b28f.png">

For all my reports, I use the latest Google Chrome browser on MacOS.

**Comment by CreativeDive** [comment]
## 6. Outer box shadow on input / select

With the new outer box shadow on input / select tags, the elements look no longer like a real input field. Using an `inset shadow` is solving that in my eyes. 

https://user-images.githubusercontent.com/31563167/186494767-70b61481-42f9-4e21-abb3-e9d053a24307.mp4

**Comment by CreativeDive** [comment]
@polevaultweb I'm surprised nothing of what I mentioned was fixed in RC2?

**Comment by polevaultweb** [comment]
Hey @CreativeDive sorry for the delay here. The UI will be continually worked on and enhanced as we hear more feedback.  RC3 will contain some of these fixes in the next couple of days.

1 - We are aware of this and our designer is working on improvements. We've tried to keep the action links on hover the same as 5.x but that has an impact on the vertical alignment of the title.
2 - This fix will make it to RC3
3 - Thanks for the feedback, we are aware of this and trying to improve for RC3
4 - This is for accessibility, although we will look to improve in a future version
5 - This is for accessibility, although we will look to improve in a future version
6 - Thanks for the feedback, we've passed on to the designer

**Comment by JiveDig** [comment]
Hey y'all. Did I miss an announcement of RC2?

**Comment by CreativeDive** [comment]
@JiveDig Right, that wasn't the case this time. But a blog entry [https://www.advancedcustomfields.com/blog/acf-pro-6-0-rc-2/](https://www.advancedcustomfields.com/blog/acf-pro-6-0-rc-2/)

**Comment by polevaultweb** [comment]
@JiveDig we didn't send an email about RC2 (my bad) but will do going forward, so signup for emails if you haven't already [here](https://www.getdrip.com/forms/864019178/submissions/new)

**Comment by polevaultweb** [comment]
RC3 has just been released with a number of these issues fixes. The others have been moved to our internal issue list. Closing this, thanks again for the feedback @CreativeDive 🙌

**Comment by cbirdsong** [comment]
Is this a good place to leave UI feedback or should I open a new issue?

**Comment by polevaultweb** [comment]
@cbirdsong new issue would be helpful, please 👍
