### ISSUE TITLE
ACF 6.0 RC1 - `Trying to get property 'labels' of non-object`

### ISSUE THREAD

**Issue by kebbet** [AdvancedCustomFields/acf#697]
Something is not working with the page title's on Tools and Updates. 

The user's locale is set to sv_SE, and the pages are missing their title's. They are present in the navigation above and in the Admin menu.

This is the pages affected by the bug.
`wp-admin/edit.php?post_type=acf-field-group&page=acf-settings-updates`
`wp-admin/edit.php?post_type=acf-field-group&page=acf-tools`

<img width="1314" alt="bild" src="https://user-images.githubusercontent.com/11491369/186708986-05bfac12-5105-4756-93f0-a83d76bf2ee0.png">

<img width="1149" alt="bild" src="https://user-images.githubusercontent.com/11491369/186709075-d21f4c1f-ccda-4f6e-92bf-ffa80b8798ce.png">

<img width="1001" alt="bild" src="https://user-images.githubusercontent.com/11491369/186709100-2c179946-3671-45fe-8c22-03aac067be8f.png">

**Comment by polevaultweb** [comment]
Thanks for the report @kebbet - we've got this fixed in RC2 coming out later today
