### ISSUE TITLE
Pagination in 6.0 RC-1 is buggy

### ISSUE THREAD

**Issue by edavies-ddc** [AdvancedCustomFields/acf#699]
The new pagination on repeaters in the 6.0 RC-1 is super buggy. In one repeater field that existed before and I added the pagination to after it wouldn't let me page through the repeaters and when I hit save I lost everything in the pages after the limit. So I had 9 items on my page, I set rows_per_page to 3, and I lost items 4-9 on save. Then on a field I added items from scratch I set the rows_per_page to 3, added 4 items and it saved all 4 but it wouldn't show anything on page 2. When I went to page 2 it was blank. It seems like this new feature is not really backwards compatible and still has a lot of testing and polishing needed.

**Comment by mattgrshaw** [comment]
Thanks for the report @edavies-ddc and sorry to hear you ran into this.

Could you please share an export of the field group that contains the repeater field that you were trying to edit?

Also, could you please confirm if you were already editing the repeater field while you had enabled the "Pagination" setting and/or the "Rows per page" setting (i.e. if you had the repeater field open and then enabled either of those settings before reloading the page containing the repeater)?

**Comment by edavies-ddc** [comment]
@mattgrshaw I define my fields in PHP so I'm not able to export them but I can provide the markup we use in PHP to define the field that gets registered with ACF. Experience 1 I've linked to a gist with the markup used for the repeater. For experience 2 I can't share the fields publicly but if you have a way for me to get you them securely I can share those with you as well.

The steps I took had 2 different experiences but both failed in different ways:

[Experience 1](https://gist.github.com/edavies-ddc/594ec8e57f1607f17761c824d4058199)
1) Add pagination = 1 and rows per page = 3 settings to my accordion ACF block
2) Create a new page and add the accordion block to the page
3) Add 4 accordion repeater items and populate each 'title' and 'wysiwyg' and save the page
4) Reload the page and observed 3 visible accordion items with an option to go to page 2. When clicking to page 2 it did not show the repeater item at all, just a grey line.

Experience 2:
1) Add pagination = 1 and rows per page = 3 settings to my pledge card block
2) Edit an existing page where the pledge card block was already setup and populated with content prior to the pagination settings being added. The existing pledge card block had 10 items.
3) Observe the block had 3 visible items, but the 'pages' were limited to 1 so I could not page through to see more. Expected to see 4 pages I could click through.
4) Saved the page and reloaded it. Still could only observe 3 items visible.
5) Removed pagination = 1 and rows per page = 3 settings from my pledge card block
6) Reloaded the page and observed the items 4-10 were gone forever, it had only saved the 3 visible items in step 4.

**Comment by FreekGille** [comment]
@mattgrshaw Has there been any update on this?

**Comment by edavies-ddc** [comment]
@FreekGille No one ever replied but I did happen to read in their release notes they likely won't be supporting pagination in ACF blocks https://www.advancedcustomfields.com/blog/acf-6-0-released/#things-to-note I guess I'll go ahead and close this. Feel free to create or re-open if you can and you feel strongly they should implement this.
