### ISSUE TITLE
Layout - Unable to access parent fields after checking `have_rows()`

### ISSUE THREAD

**Issue by digitaldesigndj** [AdvancedCustomFields/acf#7]
Here's some simplified code: 

```
<?php the_sub_field( 'tools_section_title' ); // Works Here ?>
<?php if( have_rows( 'tool_cards' ) ): ?>
    <h2><?php the_sub_field( 'tools_section_title' ); // Stops working ?></h2>
    <?php while ( have_rows( 'tool_cards' ) ) : the_row(); ?>
        <h3><?php the_sub_field( 'tool_title' ); ?></h3>
        <p><?php the_sub_field( 'tool_text' ); ?></p>
    <?php endwhile; ?>
<?php endif; ?>
```

When this appears inside a flexible layout, after checking `have_rows()` I can no longer access data from the 'parent' context. When not in a flexible layout, you would normally just use `the_field()`, but here we have a special case... perhaps we need a function like `the_parent_field()` for this special case?

Kinda hoping I've got something wrong here. Thanks for the great code Elliot! 🎊

**Comment by elliotcondon** [comment]
Hi @digitaldesigndj 

Thanks for the post.
This is expected behaviour.

The get_sub_field() functions will only work with the data available inside the current loop, not any parent loop.

If you wish to access the parent, you will need to do so like this:

```
<?php $title = get_sub_field( 'tools_section_title' ); ?>
<?php if( have_rows( 'tool_cards' ) ): ?>
    <h2><?php echo $title; ?></h2>
    <?php while ( have_rows( 'tool_cards' ) ) : the_row(); ?>
        <h3><?php the_sub_field( 'tool_title' ); ?></h3>
        <p><?php the_sub_field( 'tool_text' ); ?></p>
    <?php endwhile; ?>
<?php endif; ?>
```

**Comment by digitaldesigndj** [comment]
Thanks, that's a very good solution. Extending the API is a silly idea. 🤐 

A mention of this behavior in the docs might be a good idea. I'd be happy to help with a pull request.

**Comment by elliotcondon** [comment]
Good point. I'll update the docs!
