### ISSUE TITLE
Can we turn off ACF block edit mode entirely

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#702]
hey @lgladdy,

I wonder if we can turn off ACF block edit mode entirely? Why am I asking about this?

When working with nested blocks, inline edit mode of block fields makes no sense if we have too small block width:

<img width="1261" alt="Bildschirmfoto 2022-08-30 um 15 42 21" src="https://user-images.githubusercontent.com/31563167/187452840-f816a9f4-c773-4712-a20d-9c36096facd1.png">

Another reason I personally prefer turning edit mode off is that field styles break depending on theme styles.

EDIT: One reason more, it breaks the user experience. Since the user is used to it, adjust the fields in the sidebar.

**Comment by JiveDig** [comment]
@CreativeDive If you put mode as preview I think it does this, right?

```
"acf": {
    "mode": "preview"
}
```

**Comment by CreativeDive** [comment]
@JiveDig I use exactly the same, but the inline edit mode is still available. It seems there is currently no way to disable it.

**Comment by JiveDig** [comment]
Boooo. Have you tried false?

**Comment by CreativeDive** [comment]
@JiveDig Unfortunately not. With `false` the edit mode is always visible in the block itself. That would be even worse. You don't need this mode at all. The sidebar is perfectly adequate for the fields.

@lgladdy I think there is currently no way to do that, right?

**Comment by VoroDk** [comment]
@CreativeDive I believe this is a new issue. I'm pretty sure it didn't use to show the pencil/screen icons unless the block had `'mode' => 'auto'` set.

**Comment by dansdev** [comment]
Hey @CreativeDive are you using block.json? I managed to remove the mode selector by setting the mode to false in the Gutenberg supports, see below:

`"acf": {
        "mode": "preview"
    },
    "supports": {
        "mode": false
    },`

If you are registering via php use the below:
`acf_register_block_type(array(
 ...
 'mode'	=> 'preview',
 'supports' => array('mode' => false),
));`

**Comment by CreativeDive** [comment]
@dansdev fantastic. Exactly what I'm looking for. Thank you !!! @lgladdy a good addition for the documentation :-)
