### ISSUE TITLE
[ACF 6.0 RC1] Duplicated block <div> container ID in Gutenberg editor

### ISSUE THREAD

**Issue by aadam86** [AdvancedCustomFields/acf#706]
I created a simple block in ACF 6.0 using the block.json. 

`{
    "name": "acf/block-example-01",
    "title": "Block Example 01",
    "description": "",
    "style": "",
    "script": "",
    "category": "formatting",
    "icon": "images-alt2",
    "supports": {
        "jsx": true
    },
    "acf": {
        "mode": "preview",
        "renderTemplate": "block-example-01.php",
        "blockVersion": 2
    },
    "align": "full"
}`

In block-example-01.php file I added this code:

`<div class="block-container"><h2>This is a H2 heading</h2><h3>This is a H3 heading</h3></div> `

When I insert the custom block in Gutenberg editor and check the HTML code that is generated, I see that the block div container ID and  additional css class is duplicated. See image below. Are you aware of this? Is this an known bug?

![screen-1](https://user-images.githubusercontent.com/75834899/188111620-189fd7a4-a1cc-4f17-8934-71d2e05cfe47.jpg)

Thanks for all the effort regarding ACF 6.0 release. Great work and love the new UI!

**Comment by lgladdy** [comment]
@aadam86 This is a weird one - not one we've seen at all in our testing. What version of WordPress are you running, do you have the Gutenberg plugin installed too?

**Comment by aadam86** [comment]
WordPress 6.0.2, no Gutenberg plugin installed or any other plugin, the default Twenty Twenty One theme.

I downloaded your ACF Slider Block plugin's example ( https://gladdy.uk/blog/2022/07/24/creating-a-portable-slider-block-with-acf/ ) and created the block after it.

 I see the issue happens on the ACF Slider Block example too. Hope it helps find the issue. I'm not a developer to dig more :|

![screen-1](https://user-images.githubusercontent.com/75834899/188611535-a6face35-c6dc-4a6e-81cb-00ad6e728ddd.jpg)

**Comment by lgladdy** [comment]
Hey Adam,

Thanks for the report. I've been able to reproduce this with my slider block example there - yet weirdly it doesn't happen with every block! We'll keep digging into this and figure out what's going wrong

**Comment by lgladdy** [comment]
@aadam86 Hey again! Turns out, this was a simple one. If you add `"apiVersion": 2,` to the top level of your block.json, this issue is resolved.

We should be assuming that for block.json blocks, so a huge thanks for raising this. You've stopped a bug from shipping in 6.0! 🎉

**Comment by aadam86** [comment]
Great, it's fine now! I'm glad it wasn't something complicated :)
