### ISSUE TITLE
Advanced Custom field not showing in REST API for tags

### ISSUE THREAD

**Issue by jellesiderius** [AdvancedCustomFields/acf#713]
In the API for tags, the ACF is not showing up. Using WordPress 6.2 + ACF 5.12.3.

**Comment by mattgrshaw** [comment]
Thanks for the report @jellesiderius. I'm closing this as a dupe of #664, but this is on our radar. With ACF 6 out the door now we'll hopefully pick up some more steam with some of the REST API issues.

**Comment by salvimateus** [comment]
same problem here, latest version ACF PRO
