### ISSUE TITLE
Missing ACF block IDs after update to 6.0

### ISSUE THREAD

**Issue by kory-northrop** [AdvancedCustomFields/acf#715]
I saw the release notes about [Block ID Changes](https://www.advancedcustomfields.com/resources/whats-new-with-acf-blocks-in-acf-6/#block-id changes) right _after_ I updated ACF Pro to version 6.0. I have some of those edge cases that were mentioned whereby I use `parse_blocks()` to get the unique block ID of some custom ACF blocks saved to a post. In one of the edge cases I search through a parent page's blocks to find the existence of a specific custom ACF block and if it exists, grab the value and display it on the child page.

If I grab the blocks for a post and loop through them, I no longer see an ID value in the block attributes for my custom ACF blocks, e.g.

```
$post_id = 1234; // example post_id
$post_blocks = parse_blocks( get_the_content( '', false, $post_id ) );
foreach ( $post_blocks as $block ) {
    echo '<pre>'.print_r($block,true).'</pre>';
}
```

The block data for one of my ACF blocks looks like this:

```
[0] => Array
    (
        [blockName] => acf/name-of-our-custom-block
            [attrs] => Array
                (
                    [name] => acf/name-of-our-custom-block
                    [data] => Array
                        (
                        .......
```

Before the upgrade it had the [id] attribute like so:

```
[0] => Array
    (
        [blockName] => acf/name-of-our-custom-block
            [attrs] => Array
                (
                    [id] => block_613a81d1aec41
                    [name] => acf/name-of-our-custom-block
                    [data] => Array
                        (
                        .......
```

In the 6.0 release documentation it's mentioned that this filter can be used to set a unique ID to be used on the front-end. My question is whether this will work out-of-the-box without having to re-save/update every post that has the custom ACF blocks in the post_content.

```
add_filter(
    'acf/pre_save_block',
    function( $attributes ) {
        if ( empty( $attributes['id'] ) ) {
            $attributes['id'] = 'acf-block-' . uniqid();
        }
        return $attributes;
    }
);
```

**Comment by lgladdy** [comment]
Hey @kory-northrop,

It won't generate a new ID unless you save a page with blocks - but the block ID won't be removed either, until you save a page with blocks, so if you drop in that code you'll only need to update pages which have been updated since you upgraded to 6.0 and you dropped in the ID code.

**Comment by kory-northrop** [comment]
Thanks for the reply @lgladdy. That's good to know that the block ID won't be removed on updating to ACF 6.0. My block IDs _did_ disappear so I gotta figure out what happened.

**Comment by lgladdy** [comment]
@kory-northrop Did they disappear from all blocks, even before you updated any pages? I'm wondering if WordPress uses "known attributes" and ignores anything not in that...

But if that was the case, the `add_filter` wouldn't work either.

**Comment by kory-northrop** [comment]
@lgladdy it seems like a fluke, isolated to just a couple of posts. Not sure how to explain that, but I tested out the filter and it seems to work just fine for our purposes on those blocks that were missing an ID.

**Comment by eliawk** [comment]
@lgladdy @kory-northrop same problem here: ACF create custom block without id
this is the correct one:
```
<!-- wp:acf/counters {"id":"block_62d5311367567","name":"acf/counters",
```
and the broken one:
```
<!-- wp:acf/counters {"name":"acf/counters","data"
```

**Comment by lgladdy** [comment]
@eliawk ACF no longer uses block IDs saved to the block comment in ACF 6.0. Please see our release documentation for more info on this: https://www.advancedcustomfields.com/resources/whats-new-with-acf-blocks-in-acf-6/#block-id

**Comment by eliawk** [comment]
@lgladdy ok thanks, anyway this will cause a lot of bugs for people like me that are using acf and wpgrapqhl-gutenberg. without that id, all the data from the queries are nulls.

**Comment by lgladdy** [comment]
Hey @eliawk, could you send us a link to the ACF blocks specific GraphQL integration you're using? It should be a very simple change for them to add support for ACF 6 :)

**Comment by eliawk** [comment]
@lgladdy we are using:
- ACF
- WPGraphql - https://github.com/wp-graphql/wp-graphql
- WPGraphql ACF - https://github.com/wp-graphql/wp-graphql-acf
- WPGraphql Gutenberg - https://github.com/pristas-peter/wp-graphql-gutenberg
- WPGraphql Gutenberg ACF - https://github.com/pristas-peter/wp-graphql-gutenberg-acf

The last plugin (https://github.com/pristas-peter/wp-graphql-gutenberg-acf/blob/develop/plugin.php#L128) gets the value using the ACF id of the block.
