### ISSUE TITLE
Can not reset/remove conditional logic

### ISSUE THREAD

**Issue by merijnponzo** [AdvancedCustomFields/acf#717]
I updated to Version 6.0.0 and found a minor problem:

1. I have a radio button with some options
2. I add any field with a conditional logic to it
![Screenshot 2022-09-23 at 23 12 16](https://user-images.githubusercontent.com/23075300/192057516-750012af-5fab-4197-bf3f-92bce394607f.png)
3. Now i remove the radiobuttons (page will refresh)
4. I'm not able to change the conditional logic of my field.
![Screenshot 2022-09-23 at 23 12 39](https://user-images.githubusercontent.com/23075300/192057672-7051d8d1-8cbd-4cb0-9a29-a42a4ce99800.png)

My only way to work around it is to remove the whole field and startover

**Comment by merijnponzo** [comment]
Update, i don't have to remove my radio buttons
After any save it's showing the field key name instead of the fields label and i am not able to remove the condition

**Comment by polevaultweb** [comment]
Hey @merijnponzo thanks for the report and apologies for the inconvenience. I wasn't able to recreate this - does your Radio field have a label? Could you share an export of the field group please.

**Comment by merijnponzo** [comment]
Hello,

I forgot to mention that i also use ACF [extended](https://www.acf-extended.com/)
And https://github.com/houke/acf-icon-picker

The problem is caused by the acf-icon picker so I have to open an issue there. 
<img width="1170" alt="Screenshot 2022-09-26 at 14 25 54" src="https://user-images.githubusercontent.com/23075300/192276236-b0677b82-6cac-44b0-b4b0-4d7853c5bf91.png">

Thanks!

**Comment by polevaultweb** [comment]
Thanks for letting us know @merijnponzo
