### ISSUE TITLE
Small design inconsistencies with true/false field

### ISSUE THREAD

**Issue by Humanify-nl** [AdvancedCustomFields/acf#718]
I have found a few issues in the interface. This is with ACF 6 blocks on a default WP 6.0.2 theme.json based FSE theme.

1) True/false field in the edit-post-sidebar has incorrect border when selected. The radius overlaps with the button borders. 

![acf-truefalse-bug](https://user-images.githubusercontent.com/82579622/192136640-11988b3e-69f5-42fa-8201-809f00980902.gif)

IMHO the select field focus is properly 'signalled' to the user by its color switching. I corrected this with: 

```
.acf-field-true-false {
	.acf-true-false:focus-within {
		border: 1px solid transparent;
	}
}
```
2) The same field has some issues when opening the block settings.

![acf-truefalse-bug-block](https://user-images.githubusercontent.com/82579622/192136739-e71e175d-a148-43cc-90c8-f80d8eccbdcf.gif)

The above code helps with removing the border on the element. But there still is a flicker of the outside box, which looks quite wrong to the user. I haven't been able to fix it yet (will update).

**Comment by lgladdy** [comment]
Hey @Humanify-nl,

We've got this bug patched already :) We should have a small UI bug fixes patch out in the next few days including this fix!

**Comment by Humanify-nl** [comment]
Closing
