### ISSUE TITLE
Repeater pagination doesn't work for nested repeater.

### ISSUE THREAD

**Issue by michaelozery** [AdvancedCustomFields/acf#720]
I have a complex ACF structure, which includes a repeater within another repeater.
Unfortunately, the pagination toggle switch is only available/visible in the parent repeater.

Parent repeater:
![image](https://user-images.githubusercontent.com/41621093/192801036-223f3e51-e366-42de-8974-0be25a80219f.png)

Child repeater: 
![image](https://user-images.githubusercontent.com/41621093/192801102-7964c9e8-1941-426f-8a80-6e1e781dcc79.png)

Btw, when I turn on pagination, it caused deletion of all the values within my repeaters.

**Comment by lgladdy** [comment]
@michaelozery Hey, as noted in the release notes and blog posts, and the pagination documentation - Repeater Pagination is not yet supported in Flexible Content fields, or inside other repeaters.

We're hoping to bring support for this in an upcoming ACF release.

**Comment by michaelozery** [comment]
Thank you for the quick answer. I'll make sure to read the release notes and blog posts next time :)
