### ISSUE TITLE
ACF blocks jQuery scripts in block editor tablet/mobile preview not working after switching the preview mode

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#723]
Hey @lgladdy,

Perhaps in the future the block editor will also switch to the iframe solution for the desktop preview. It can therefore make sense to tackle issues early on.

I personally have trouble using jQuery scripts in ACF blocks when the preview mode has been changed.

### What works?

1. When I create an ACF block (an accordion block in this case), everything works fine when I do it in the default (desktop) view of the block editor.

2. If I first switch to mobile/tablet preview and then create an ACF block (an accordion block in this case), everything works in the mobile/tablet block editor view.

### What does not work?

1. When the ACF block (in this case an accordion block) exists in the default (desktop) view of the block editor and I switch to mobile/tablet preview, the scripts are corrupt and opening the accordion elements is no longer possible.

<img width="448" alt="Bildschirmfoto 2022-09-29 um 10 37 48" src="https://user-images.githubusercontent.com/31563167/192983180-587adf12-2f81-4a04-bbc7-74844816d14a.png">

If you examine the iframe, all the necessary scripts are loaded successfully.

<img width="1110" alt="Bildschirmfoto 2022-09-29 um 10 38 55" src="https://user-images.githubusercontent.com/31563167/192983645-797430d4-dca2-4532-ae1f-15245998931c.png">

Why do the scripts work when creating a block after changing the preview mode, but not when changing the preview mode after creating the block?

This script will initialized inside the ACF block template in this way:

```
<script>
	jQuery(document).ready(function($) {
		// Initialize accordion menu
		$('#<?php echo esc_html( $id ); ?>').accordionMenu();
	});
</script>
```

The fact that scripts with ACF blocks do not work in the tablet/mobile preview is not a fundamental problem. However, there seem to be issues when the script is triggered in the block template itself.

Is there a way to solve this issue? What exactly is causing this issue?

**Comment by CreativeDive** [comment]
@lgladdy I got it worked. The solution to get jQuery scripts working in each kind of preview (mobile/tablet/desktop) is to work with a block script file only!

```javascript
(function( $ ) {
	
    function accordionInit( el ) {
		
        el.each(function() {
		
            var accordion = $(this);
            var id = accordion.attr('id');

            ...

        });
		
    }

    $(document).ready(function() {
        var selector = $('.accordion-menu-block');
        accordionInit( selector );
    });

    // Adds custom JavaScript to the block HTML
    var initializeBlock = function( $block ) {
        accordionInit( $block );
    }

    // Initialize dynamic block preview (editor)
    if( window.acf ) {
        window.acf.addAction( 'render_block_preview/type=accordion', initializeBlock );
    }
            
})( jQuery );
```

But only the usage of `$(document).ready(function() {` make the script working if I switch from desktop to mobile/tablet preview.

```javascript
$(document).ready(function() {
        var selector = $('.accordion-menu-block');
        accordionInit( selector );
});
```

It seems like you should avoid initializing jQuery scripts in the ACF block template and always use a separate block script for it.

**Comment by CreativeDive** [comment]
The registered block script should use the correct dependencies `array('jquery', 'acf')`:

```php
wp_register_script( 
    $script_handle, $block_script_path, array('jquery', 'acf'), false, true
);
```

**Comment by lgladdy** [comment]
Yeh - this is "expected". inside the iframe, only JS your block is listed as needing will work.

So, that requires adding jQuery as a dependency for your code too at the moment!
