### ISSUE TITLE
Reordering fields with drag and drop does not work since 6.0.1

### ISSUE THREAD

**Issue by wiegertschouten** [AdvancedCustomFields/acf#724]
Hi there,

I love the work you guys are doing on ACF.

However, since upgrading to 6.0.1 this morning, I can no longer change the order of fields in the field group edit screen. I can reorder them visually, but the new order does not persist. It reverts to the old order after saving.

I don't get any error messages, not on my screen and not in the logs, with `WP_DEBUG` and `WP_DEBUG_DISPLAY` both set to `true`.

The issue appears on multiple sites, which makes me suspect it's a bug in ACF.

I'm running ACF PRO 6.0.1 on WordPress 6.0.2. If you need more info, just let me know.

**Comment by acf-extended** [comment]
Hello,

I just had a similar bug report, but with sub fields in the Group field. [See ticket thread](https://wordpress.org/support/topic/not-saving-the-right-order/#post-16054386).

> _When a user add a sub field to a Group field which has been already saved before, the newly added sub field is shifted to the next position._

- [Video showing the bug in ACF 6.0.1](https://www.acf-extended.com/share/fuand)
- [Video showing it working correctly in ACF 5.12.3](https://www.acf-extended.com/share/FNkVd)

Regards.

**Comment by lgladdy** [comment]
Hey everyone. We patched this issue in ACF 6.0.2 released earlier today! Sorry about this, it slipped through as part of some fixes to Flexible Content ordering.

**Comment by Phalconline** [comment]
Hi, 
Unfortunately, I can reproduce it with ACF 6.0.0, 6.0.2, 6.0.3 or 6.0.4 with ACF Extended 0.8.8.10

**Comment by Phalconline** [comment]
Unfortunately, I can reproduce it with ACF 6.0.0, 6.0.2, 6.0.3 or 6.0.4 with ACF Extended 0.8.8.7 or 0.8.8.10

**Comment by polevaultweb** [comment]
@Phalconline please could send a ticket to our support with some more details so we can investigate - thanks! https://www.advancedcustomfields.com/contact/

**Comment by Phalconline** [comment]
I'm sorry for bothering you. I found that the problem was not related to any plugins. 
I was in the next code not related to ACF:
`add_action('pre_get_posts', function ($query) {
    $query->set('order', Utilities::get_sort_param());
});`
