### ISSUE TITLE
How to set ACF as a dependancy in block.json 

### ISSUE THREAD

**Issue by dansdev** [AdvancedCustomFields/acf#728]
Hi there,

Prior to ACF using block.json, scripts could be registered in php and dependancies could be set e.g:

`function register_block_scripts() { 
wp_register_script( 'block-script', get_template_directory_uri() . '/blocks/block/block-script.js', [ 'jquery', 'acf' ] );
}
add_action( 'init', 'register_block_scripts' );`

Is it possible to set acf as a dependancy in block.json? Reason being I need to intialize a dynamic block preview via window.acf.addAction:

`if( window.acf ) {
        window.acf.addAction( 'render_block_preview/type=slider', initializeBlock );
    }`

Or is there recommended way of achieving this now? 

Cheers!

**Comment by polevaultweb** [comment]
Hey @dansdev does @CreativeDive's comment solve that for you?

**Comment by dansdev** [comment]
> Hey @dansdev does @CreativeDive's comment solve that for you?

Hi @polevaultweb,

Yeah I think @CreativeDive's answer will be the solution when WP 6.1 is released. It's due for release in Nov 1st, any chance there is a recommended work around in the meantime to get acf as a dependancy in the editor?

Cheers!
