### ISSUE TITLE
Gutenberg 4.1 - All Fieldgroups Showing Up in Post

### ISSUE THREAD

**Issue by kuse-de** [AdvancedCustomFields/acf#73]
## Bug Description
Fieldgroups are not getting filtered by Custom Taxonomy anymore in Posts with Gutenberg 4.1 activated.

## Screenshots
![screnshot1](https://user-images.githubusercontent.com/1517214/47596759-d4934100-d988-11e8-8f99-2df87edfb048.PNG)

![screenshot2](https://user-images.githubusercontent.com/1517214/47596691-415a0b80-d988-11e8-8e86-82857092cd21.PNG)
## Expected Behaviour
Fieldgroups getting Filtered by Taxonomy (Fornat)
### Plugins
Gutenberg 4.1.1
ACF Pro 5.7.7 // 5.8.0 beta1

### Last Working Setup
Gutenberg 4.0
ACF Pro 5.7.7 // 5.8.0 beta1

**Comment by elliotcondon** [comment]
Hi @kuse-de 

Thanks for the bug report. We've had a few reports of this same issue, and will be sure to have a fix shortly :)

I'll close this issue for now, please stay tuned for updates from our [twitter account](https://twitter.com/wp_acf)
