### ISSUE TITLE
Request: Why we can't add a custom class name for the accordion field type?

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#731]
Hey @mattgrshaw 

I've noticed that the custom class name is not set for the accordion field type, if I fill the input inside the field group.

![Bildschirmfoto 2022-10-10 um 10 50](https://user-images.githubusercontent.com/31563167/194830024-8b4d188b-2898-4f54-9268-897c25cee4e1.jpg)

It's possible to fix this issue with an upcoming ACF release please?

**Comment by mattgrshaw** [comment]
Hey @CreativeDive - how are you adding that class name input into the accordion field? I don't believe that "Class Name" setting is added to that field type in ACF core.

**Comment by CreativeDive** [comment]
@mattgrshaw sorry for this! The new ui played a trick on me and I confused it with the other default class field:

<img width="649" alt="Bildschirmfoto 2022-10-13 um 08 57 41" src="https://user-images.githubusercontent.com/31563167/195524640-23a190be-df38-4452-ac76-64a556e16d78.png">

The other class field is from my own implementation that I added years ago. :hear_no_evil: So it's not a bug. Rather a request how to solve it to add a class name?

**Comment by CreativeDive** [comment]
@mattgrshaw ahhh, looked to my code again and I can see we can modify `$field['wrapper']['class']` to solve this. Now I'm wondering why there isn't a class name field by default?

**Comment by CreativeDive** [comment]
@polevaultweb I will close this, because I found a solution using the `'acf/prepare_field'` filter here. But it would be nice if this request can land on your list? I know it's not a request with high priority, but it's confusing the user. Technical it's possible to set a class name for the accordion field type, but there is not field for the user to change this.
