### ISSUE TITLE
Improvement: make field Groups and fields registered via code will not be visible via “Field Groups” admin page.

### ISSUE THREAD

**Issue by ts-mz** [AdvancedCustomFields/acf#740]
Hi,

I guess I just never noticed because the pre-export field-group was still present after exporting the created code to the theme. Not being able to at least have a reference to code-created fieldgroups in the field group admin page is very confusing. Please consider to add at least some sort of indicator that such field groups are present in an installation.

Thanks for consideration.

**Comment by polevaultweb** [comment]
Thanks @ts-mz, I've added this to our internal tracker and will close it for now, but others can leave their +1 in the comments still.
