### ISSUE TITLE
Some html tags and attributes begin stripping from field instructions

### ISSUE THREAD

**Issue by nikrowell** [AdvancedCustomFields/acf#744]
I occasionally like to add HTML to field instructions or even update them with dynamic content via the `prepare_field` filter. If I'm not mistaken, it appears the 6.0 release that introduced the redesigned admin UI is stripping some html and attributes from these. It could simply be that it's this through a sanitization function, but I don't see field instructions as being a security concern given that they'd only be created by Administrators. Here are a few examples of what I've seen:

**Renders the div and label tags but removes the input entirely:**
```php
add_filter('acf/prepare_field/key=field_634585138bcd9', function($field) {
    $field['instructions'] .= <<<HTML
    <div>
        <label for="example">Label</label>
        <input id="example" type="text" value="Something the might need to be copied" readonly />
    </div>
    HTML;
    return $field;
});
```
 **Renders the div and button but removes the onclick handler:**
```php
add_filter('acf/prepare_field/key=field_634585138bcd9', function($field) {
    $field['instructions'] .= <<<HTML
    <div>
        <button type="button" onclick="console.log('click')">Click Me</button>
    </div>
    HTML;
    return $field;
});
```

**Renders a red list but removes `display: flex` from the style attribute**
```php
add_filter('acf/prepare_field/key=field_634585138bcd9', function($field) {
    $field['instructions'] .= <<<HTML
    <ul style="background-color:#F00; display: flex;">
        <li>lorem</li>
        <li>ipsum</li>
        <li>dolor</li>
    </ul>
    HTML;
    return $field;
});
```
Please let me know if I'm overlooking another reason for the sanitization (or another explanation for the issue). Thanks for maintaining one of the most important WordPress plugins!

**Comment by CreativeDive** [comment]
Hey @nikrowell maybe this is helpful for you here? [https://www.advancedcustomfields.com/resources/html-escaping/](https://www.advancedcustomfields.com/resources/html-escaping/)

**Comment by nikrowell** [comment]
@CreativeDive very helpful - thank you!
