### ISSUE TITLE
ACF Blocks how to limit blocks to specific post types

### ISSUE THREAD

**Issue by dansdev** [AdvancedCustomFields/acf#747]
Hey all,

Prior to ACF 6.0 blocks could be limited to specific post types via the [acf_register_block_type()](https://www.advancedcustomfields.com/resources/acf_register_block_type/) function. 

When registering blocks via block.json is there a way that this can still be achieved?

Cheers!

**Comment by CreativeDive** [comment]
Yes!

```json
"acf": {
        "mode": "preview",
        "renderTemplate": "index.php",
	"postTypes": [
		"my-post-type"
	]
    },
```

**Comment by dansdev** [comment]
@CreativeDive perfect! Thanks for taking the time and passing on the info 🙌 🙌
