### ISSUE TITLE
SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by jensmercedesbenz** [AdvancedCustomFields/acf#748]
Server/URL where we fetch ACF using Composer has certificate issues at the moment (blocking our deployment processes).

**Common Name (CN)**	
connect.advancedcustomfields.com
**Common Name (CN)**	
Sectigo RSA Domain Validation Secure Server CA
**Organisation (O)**
Sectigo Limited

**Issued On**
Monday, 1 November 2021 at 01:00:00
**Expires On**
**Wednesday, 2 November 2022 at 00:59:59**

**Comment by jensmercedesbenz** [comment]
It's back.

**Common Name (CN)**	
connect.advancedcustomfields.com
**Common Name (CN)**	
R3
**Organisation (O)**	
Let's Encrypt

**Issued On**
Wednesday, 2 November 2022 at 08:12:59
**Expires On**
**Tuesday, 31 January 2023 at 08:12:58**

**Comment by polevaultweb** [comment]
Thanks for the report - for future site issues, please send a message via https://www.advancedcustomfields.com/contact/
