### ISSUE TITLE
No Fields Assigned empty message

### ISSUE THREAD

**Issue by cabrailsford** [AdvancedCustomFields/acf#749]
When using the filter to remove the default message about adding fields to a custom block, I have the following code:
```add_filter( 'acf/blocks/no_fields_assigned_message', '__return_empty_string' );```

However, in the markup output by ACF, the control area includes a wrapper regardless of whether the content is empty or not. Would it be possible to check the output of the filter and not display the wrapper div if it's empty?

![acf-no-fields-message](https://user-images.githubusercontent.com/3218451/199501313-f8509ea8-f0a7-41ab-a48b-32eb7fea7693.png)

**Comment by polevaultweb** [comment]
Thanks @cabrailsford, we'll get this fixed up

**Comment by polevaultweb** [comment]
Hey @cabrailsford we just shipped a fix for this in ACF 6.0.6 🙌

**Comment by cabrailsford** [comment]
Awesome! Thanks @polevaultweb!
