### ISSUE TITLE
All Radio Button fields share the same name!? (even with select)

### ISSUE THREAD

**Issue by blaasvaer** [AdvancedCustomFields/acf#755]
I have multiple radio buttons fields, but they ALL share the same name, and therefore act as ONE GIANT radio button group. Now, HOW can I separate them. They even share name with Selects as well, making it impossible to have more than one of these field types.

**Comment by polevaultweb** [comment]
Thanks for reaching out. We are using this repository for technical bug reports only. If you have an issue you require support for or a feature request, please contact our support team who would be happy to help troubleshoot.

https://www.advancedcustomfields.com/contact/
