### ISSUE TITLE
Rev Slider Settings appears on Field Group editor

### ISSUE THREAD

**Issue by Hube2** [AdvancedCustomFields/acf#759]
Not sure it this is something that you can fix or it is something that Revolution Slider should fix, but the rev slider metabox appears on the field group editor.

![acf-ref](https://user-images.githubusercontent.com/6631975/201939974-e8925856-8d9f-40e0-a576-c5f71e47887e.jpg)

This can be corrected temporarily by adding the following code
```
add_action('do_meta_boxes', 'remove_revolution_slider_meta_boxes', 999);
function remove_revolution_slider_meta_boxes() {
  remove_meta_box('slider_revolution_metabox', 'acf-field-group', 'side');
}
```

**Comment by polevaultweb** [comment]
Thanks @Hube2, this would be something Rev Slider should fix.
