### ISSUE TITLE
$attributes variable is undefined in block templates after update to 6.0.4

### ISSUE THREAD

**Issue by mathew-crisp** [AdvancedCustomFields/acf#760]
After the update, the $attributes variable is undefined in block templates. Multiple developers at my company have encountered this issue. Reverting to 6.0.3 fixed the issue.

**Comment by lgladdy** [comment]
@mathew-crisp Hey Mathew,

`$attributes` was never supposed to be available inside a block template - it was a scoping issue that made it available. As per the documentation, `$block, $content, $is_preview, $post_id, $wp_block, $context` are the variables which are available to block templates, and only `$block` is guaranteed to have a value (the rest are optional, with false or 0 defaults)

In 6.0.4, we correctly scoped block templates so they can't modify internal ACF variables which would lead to errors.
