### ISSUE TITLE
Gutenberg 4.1 showing all ACF Group Fields

### ISSUE THREAD

**Issue by jonathanfallon** [AdvancedCustomFields/acf#77]
As described in [issue 11071](https://github.com/WordPress/gutenberg/issues/11071) on the Gutenberg repository, all Group Fields are shown in the Gutenberg editor regardless of the Rules defined in the Custom Field Location.

This happens on Posts, Pages and Custom Fields

@mcsf on [this comment](https://github.com/WordPress/gutenberg/issues/11071#issuecomment-433144388) has an interesting analysis.

### Environment

- Gutenberg 4.1
- ACF Pro 5.7.7
- Firefox 63 (Ubuntu) / Chrome 70 (Ubuntu)

### Steps to reproduce

- Create a new Group field with Location Rules to restrict display for page A
- Create a new Group field with Location Rules to restrict display for page B
- Edit page A
- Group Fields for Page A and Page B are shown

**Comment by kuse-de** [comment]
Hi  @jonathanfallon 
It's Fixed in Version 5.8.0-beta2, else downgrade to Gutenberg 4.0.
Greets

**Comment by elliotcondon** [comment]
Hi @jonathanfallon Thanks for the bug report. Yes, this has been fixed in 5.8.0-beta2
