### ISSUE TITLE
Gutenberg blocks default alignment

### ISSUE THREAD

**Issue by NewJenk** [AdvancedCustomFields/acf#78]
Disabling the alignment toolbar and choosing which alignment options are great, but can an option be added to allow a default alignment? For example, for a hero I need to disable alignment and set the default as full width (as the Hero is always going to be full width).

**Comment by elliotcondon** [comment]
Hi @NewJenk - Great idea.

Currently, it is possible to set a "default" mode by defining "mode" in the block settings. It would makes sense to do the same thing for "align".

For example:
```
acf_register_block(array(
	'name'			=> 'testimonial',
	'title'				=> __('Testimonial'),
	'mode'			=> 'preview',	
	'align'			=> 'wide',
	// ...
));
```
