### ISSUE TITLE
'Duplicate' icon no longer appears on Flexible Content fields

### ISSUE THREAD

**Issue by jmoconn** [AdvancedCustomFields/acf#782]
The latest update (6.0.6) dropped the ``content: "";`` rule from the ``.acf-icon.-duplicate:before, .acf-icon.-duplicate:after`` selector on line 440 of assets/build/css/acf-global.css. Because of this, the icon does not appear where it should on flexible content fields. Tested on a post edit screen using the classic editor plugin (did not test on a Gutenberg edit screen).

**Comment by polevaultweb** [comment]
Thanks for the report, we have the fix for this and will be shipping it in 6.0.7 very soon

**Comment by polevaultweb** [comment]
ACF PRO 6.0.7 has been released with this fix 🙌 

https://www.advancedcustomfields.com/blog/acf-6-0-7/
