### ISSUE TITLE
ACF Gutenberg blocks not showing.

### ISSUE THREAD

**Issue by zkingdesign** [AdvancedCustomFields/acf#79]
Using acf pro 4.8 beta 2.

Registered gutenberg block using documentation found here: https://www.advancedcustomfields.com/resources/acf_register_block/

But the ACF block doesn't show up when trying to add new blocks. Also created the fields, and assigned them to the block after registering.

Am I missing something? Or this is a bug?

Thanks

**Comment by elliotcondon** [comment]
Hi @zkingdesign 

Thanks for the email,
Elliot here - ACF dev​​​.

Can you please provide me the full code you are using to register the block and I'll test it out on my local install.

**Comment by zkingdesign** [comment]
Hi @elliotcondon 

Thanks for the quick response. I'm trying the code that's available in the official docs, so that means:

`
add_action('acf/init', 'my_register_blocks');
function my_register_blocks() {

	// check function exists
	if( function_exists('acf_register_block') ) {

		// register a testimonial block
		acf_register_block(array(
			'name'              => 'testimonial',
			'title'             => __('Testimonial'),
			'description'       => __('A custom testimonial block.'),
			'render_callback'   => 'my_acf_block_render_callback',
			'category'          => 'formatting',
			'icon'              => 'admin-comments',
			'mode'              => 'preview',
			'keywords'          => array( 'testimonial', 'quote' ),
            'post_'
		));
	}
}
function my_acf_block_render_callback( $block, $content = '', $is_preview = false ) {

	// get image field (array)
	$avatar = get_field('avatar');

	// create id attribute for specific styling
	$id = 'testimonial-' . $block['id'];

	// create align class ("alignwide") from block setting ("wide")
	$align_class = $block['align'] ? 'align' . $block['align'] : '';

	?>
	<blockquote id="<?php echo $id; ?>" class="testimonial <?php echo $align_class; ?>">
		<p><?php the_field('testimonial'); ?></p>
		<cite>
			<img src="<?php echo $avatar['url']; ?>" alt="<?php echo $avatar['alt']; ?>" />
			<span><?php the_field('author'); ?></span>
		</cite>
	</blockquote>
	<?php
}`


Other people are reporting same issues on acf support forums, see here: https://support.advancedcustomfields.com/forums/topic/acf-5-8-0-beta2-block-not-in-gutenberg/

Thanks,
Zoltan

**Comment by zkingdesign** [comment]
Just to let you know, as users reported in forums and just tried myself, the code works with acf 5.8 beta 1 version of the plugin, so it must be something with beta 2

**Comment by zkingdesign** [comment]
Now it works @elliotcondon . I see you've updated the plugins source code as well already. Thanks!

**Comment by marekmaurizio** [comment]
Same problem in beta3 it seems.

`  add_action('acf/init', 'lr_register_acf_blocks');
  function lr_register_acf_blocks() {
    if( function_exists('acf_register_block') ) {
      acf_register_block(array(
        'name'        => 'hero',
        'title'       => __('Hero'),
        'description'   => __('Hero Block'),
        'render_callback' => 'lr_acf_block_hero_render_callback',
        'category'      => 'common',
      ));
    }
  }`

**Comment by tweetzal** [comment]
Thanks for this @elliotcondon & @zkingdesign . 
This fix did not work with : Version 5.8.0-beta1 (Block option wasn't showing under locations in acf)
But works with : Version 5.8.0-beta4.1

One small styling glitch, thought I might highlight to help out: 
When you add the newly created block, it appears without fields until you click the pencil icon/ to edit it and then it displays the fields. See Screenshots.

Apart from that - I am a Pro user - So well done to ACF team! Great Job

Really liking how you have made all fields work within a block, what a time saver.
Best
Mo
@tweetzal
London, UK

![Screen Shot 2019-05-02 at 13 11 45](https://user-images.githubusercontent.com/2478550/57074542-215f2800-6cdc-11e9-97a9-c8e4b0da7025.png)
![Screen Shot 2019-05-02 at 13 11 54](https://user-images.githubusercontent.com/2478550/57074544-21f7be80-6cdc-11e9-942b-45af08ca37e2.png)
![Screen Shot 2019-05-02 at 13 12 01](https://user-images.githubusercontent.com/2478550/57074545-21f7be80-6cdc-11e9-83f3-b4d2471b44c4.png)
![Screen Shot 2019-05-02 at 13 12 06](https://user-images.githubusercontent.com/2478550/57074546-21f7be80-6cdc-11e9-83b3-8842d6bade36.png)

**Comment by elliotcondon** [comment]
Hi @tweetzal 

Thanks for the feedback. Be sure to read up on the "mode" setting in ACF Blocks.
What you are seeing is your "Block Preview" not displaying any HTML - perhaps due to no values yet existing.

The docs show how to implement default values here: https://www.advancedcustomfields.com/resources/blocks/

**Comment by winstonsmith1789** [comment]
I've tried all the suggestions and I still am unable to register a new ACF block. 

I am using WP 5.2.2 and ACF Pro 5.8.2, with the Testimonial sample code from https://www.advancedcustomfields.com/resources/blocks/ :

`function register_acf_block_types() {

	// register a testimonial block.
	acf_register_block_type(array(
		'name'              => 'testimonial',
		'title'             => __('Testimonial'),
		'description'       => __('A custom testimonial block.'),
		'render_template'   => 'template-parts/blocks/testimonial/testimonial.php',
		'category'          => 'formatting',
		'icon'              => 'admin-comments',
		'keywords'          => array( 'testimonial', 'quote' ),
	));
}

// Check if function exists and hook into setup.
if( function_exists('acf_register_block_type') ) {
	add_action('acf/init', 'register_acf_block_types');
}`

However, when I try to use the newly registered block, these symptoms appear:

In ACF location rules, block selector is empty:
![image](https://user-images.githubusercontent.com/47567591/61421915-3dd03100-a8d7-11e9-8250-de434f599685.png)

The page editor can't find Testimonial block to insert:
![image](https://user-images.githubusercontent.com/47567591/61421955-5f311d00-a8d7-11e9-8e45-83613ed27f3d.png)

![image](https://user-images.githubusercontent.com/47567591/61421993-9dc6d780-a8d7-11e9-8fa9-c2383c64fe77.png)

Any pointers would be much appreciated. Thank you.
