### ISSUE TITLE
Unexpected Behavior: Core block tabs attached to each ACF block

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#794]
Hey @lgladdy,

I realized that the new core block tabs (introduced in WP 6.2) are attached to each of my ACF blocks.

The first tab contains the ACF fields:

<img width="372" alt="Bildschirm­foto 2023-03-01 um 09 26 27" src="https://user-images.githubusercontent.com/31563167/222084998-56298c80-70f7-428d-a5b2-1a75f1f6f94a.png">

The second tab contains core text decoration settings:

<img width="223" alt="Bildschirm­foto 2023-03-01 um 09 29 16" src="https://user-images.githubusercontent.com/31563167/222085259-bf1092ca-21e9-4f16-8f90-7d365cd1fe72.png">

However, there should be no text decoration settings. I didn't enable this in the `block.json` file and setting typograpfy to false in block.json isn't a solution to fix that either.

Can you replicate this issue and does ACF need to be adjusted with the new core block tabs to work properly?

**Comment by lgladdy** [comment]
Hey @CreativeDive. Can you raise this with the Gutenberg team too? I suspect this bug is their side; as updates should change the behaviour. It might be worth waiting til beta4 today and go from there if it's still an issue.

**Comment by CreativeDive** [comment]
@lgladdy Good idea, I'll wait until Beta4 and then report a bug if it's still there. Only my experiences are rather bad that such issues are promptly reacted to in the Gutenberg repro.

**Comment by CreativeDive** [comment]
This behavior only occurs when the Gutenberg plugin is activated. It works correctly in the latest WP 6.2 beta without the Gutenberg plugin.
