### ISSUE TITLE
How to add fields to the default settings pages?

### ISSUE THREAD

**Issue by campusboy87** [AdvancedCustomFields/acf#8]
Hey. Can I use ACF to add fields to the settings pages created by WordPress itself, for example here /wp-admin/options-reading.php? By default, ACF does not know this, but can there be methods to overcome this constraint?

**Comment by elliotcondon** [comment]
Hi @campusboy87 

I'm sure this is possible by hooking into some core WP actions that are run during the "/wp-admin/options-reading.php" page.

You can find the code used by ACF to render form elements within the 'includes/forms/form-xxx.php' files. 

I'll leave the rest for you to dive, learn, debug and try!

P.S. This github repo is used for bug reports, not questions. Please be sure to ask any questions on the ACF support here: https://support.advancedcustomfields.com/
