### ISSUE TITLE
post_type_exists is false

### ISSUE THREAD

**Issue by caspahouzer** [AdvancedCustomFields/acf#807]
I've migrated the post_types from CPT UI to ACF.

The post_types are all active and I can create those entries in the backend.

Logging `get_post_types` gives me 
```
(
    [post] => post
    [page] => page
    [attachment] => attachment
)
```

`post_type_exists('rest_api')` is false even I have entries in the database and can see them in the backend.

Am I missing anything?

**Comment by lgladdy** [comment]
Hey @caspahouzer,

At what point are you logging and running post_type_exists? If it's before ACF has registered them, they will be false.

**Comment by caspahouzer** [comment]
Damn. That could be possible. Maybe I should hook into acf/load?

Is that the right hook?

**Comment by caspahouzer** [comment]
@lgladdy Thanks for the hint. I execute the `post_type_exists` now in the Wordpress `init` action and it shows me all activated CTP
