### ISSUE TITLE
FrontEnd: providesContext usesContext does not work

### ISSUE THREAD

**Issue by IvanPr** [AdvancedCustomFields/acf#812]
Hello and thank you for your help, if any.

I have a parent and children ACF Blocks set up with:
"providesContext": {"acf/fields": "data"}
and
"usesContext": ["acf/fields"],

The $context data is well passed to the child Blocks and I am able to get it updated in the **BackEnd** accordance with the recommendations of the:
https://www.advancedcustomfields.com/resources/whats-new-with-acf-blocks-in-acf-6/#:~:text=WordPress%20to%20share%20the%20ACF

At the same time, and using the same templet, nothing gets updated in the FrontEnd.

What could be a reason?
Please advise.
Thank you.

p.s. I am getting the data using the field_key and field_name just as it is suggested by ACF, and, again, it works great but only at the Back End:

if( !empty($context['acf/fields']['field_643c43f276d37']) ) {
  $tag = esc_html($context['acf/fields']['field_643c43f276d37']);
} elseif( !empty($context['acf/fields']['tag']) ) {
 $tag = esc_html($context['acf/fields']['tag']);
} else {
 $tag = '~';
}

**Comment by IvanPr** [comment]
Does it happening because, quote:
«Note: Block Context is not available to save.»

Source:
https://developer.wordpress.org/block-editor/reference-guides/block-api/block-context/#:~:text=Note%3A%20Block%20Context%20is%20not%20available%20to%20save.

**Comment by lgladdy** [comment]
If you `var_dump($context)` on the front-end, what do you see?

**Comment by IvanPr** [comment]
> field_643c43f276d37
Thank you for responding.

The **Backend output** when the blocks are **saved** and the page reloaded, and the Block's custom field's values are 'h5' and 'h6'

`array(1) { ["acf/fields"]=> array(6) { ["tag"]=> string(2) "h5" ["_tag"]=> string(19) "field_643c43f276d37" ["tags_class"]=> string(2) "h6" ["_tags_class"]=> string(19) "field_643c62fe37351" ["style"]=> string(0) "" ["_style"]=> string(19) "field_6436fb052e7e3" } }`

If I **change** the parent Block's fields to 'h3' and 'h4' the back-end's var_dump($context); shoots:

`array(1) { ["acf/fields"]=> array(3) { ["field_643c43f276d37"]=> string(2) "h3" ["field_643c62fe37351"]=> string(2) "h4" ["field_6436fb052e7e3"]=> string(0) "" } }`

At the same time the front-end template's var_dump($context); outputs only i:

`array(2) { [“postId”]=> int(2) [“postType”]=> string(4) “page” }`

**Comment by lgladdy** [comment]
This should work as far as I can see, but the context system is all handled by WordPress itself rather than ACF. We'll do some testing to see if we can replicate this though.

**Comment by IvanPr** [comment]
From what I understand, the Child's Block is processed prior to the Parent's 'Container' code with the child's <InnerBlocks> and it would not be possible to pass the parent's values to the <InnerBlocks>'s child in the **FrontEnd**.

**If I do an experiment, and run the following codes in the followinng set of blocks:**
<ParentBlock><child><child><child></ParentBlock>

with the following output code in:

**Parent's Block:**
if( !isset($GLOBALS['case']) ) {
  $GLOBALS['case'] = 1;
} else {
  $GLOBALS['case']++;
}
echo $GLOBALS['case'] . ' - in parent<div><InnerBlocks /></div>';

**And in every one of the three Child's Block:**
if( !isset($GLOBALS['case']) ) {
  $GLOBALS['case'] = 1;
} else {
  $GLOBALS['case']++;
}
echo $GLOBALS['case'] . ' - in child<div><InnerBlocks /></div>';

~~~~~

I get the following output in the **Backend** when **page was saved**:
4 - in parent
1 - in child
1 - in child
1 - in child [all three child blocks were rendered now and the $GLOBALS['case']++ would be output as '4' in its parent]
4 - in parent
1 - in child
1 - in child
1 - in child

But in the **Frontend** it would be:

4 – in parent
1 – in child
2 – in child
3 – in child [all three child blocks were rendered now and the $GLOBALS['case']++ would be output as '4' in its parent]
8 – in parent
5 – in child
6 – in child
7 – in child

~~~~~

I make a conclusion that all three child Blocks rendered prior to the render of its Parent Block.

**This explains why the:** 

function callback($buffer) { return (str_replace("child", "baby", $buffer)); }
ob_start("callback");
echo '<div><InnerBlocks /></div>';
ob_end_flush();

changes nothing in the Child Block.

**Comment by IvanPr** [comment]
Sorry, closed the issue as resolved by mistake.

**Comment by lgladdy** [comment]
Rendering time doesn't matter, as context isn't dependant on rendering. The attributes from the parent block are still passed down, otherwise the whole system would be kinda pointless.

I've tested this locally again and everything is working as expected for me. Could you please share both your `block.json`'s, and the block templates? Thanks.

**Comment by IvanPr** [comment]
**It works!**

I must have made a mistake somewhere.... I just recreated a simple set of test parent/child blocks and it works!

Thank you a lot!
