### ISSUE TITLE
Required fields validation ignored on sidebar

### ISSUE THREAD

**Issue by singhpaul** [AdvancedCustomFields/acf#818]
Required fields validation is completely bypassed when fields (not blocks) are positioned on the sidebar and the user clicks Publish while the Block tab is selected or if the sidebar is hidden. 

So you can quite easily end up in a situation where required fields are empty in the database.

We reported to support and they were able to replicate but haven't heard since. 

Is there a hook we can tie in to force validation? Happy to help test potential fixes. We have a production site that can't be released due to this rather serious issue.

**Comment by CreativeDive** [comment]
hey @singhpaul I think this could be not fixable. I've an similar issue, while I have rendered custom CSS in the post editor settings sidebar.

If I select a block and the post settings area is no longer visible in the sidebar, my custom CSS is no longer applied.

WordPress is removing the complete section from the DOM, so in my eyes I can't imagine that your required fields issue can be solved @lgladdy ?

**Comment by singhpaul** [comment]
Hi @CreativeDive, 

If I select some values for the ACF fields on the sidebar and then hide the sidebar before saving, those field values are saved correctly. So even if the sidebar fields are removed from the DOM when the sidebar is hidden, their data persists somewhere and is accessible to ACF. So it seems that validation hooks could be applied at that point I'd imagine.

**Comment by CreativeDive** [comment]
I can not say it exactly. It was just a guess as to why this behavior is occurring.

**Comment by singhpaul** [comment]
Hi, any updates on this please? Broken validation really wrecks havoc on data integrity and can lead to some significantly broken site functionality on our end.

**Comment by singhpaul** [comment]
Hi @lgladdy, @mattgrshaw, any updates on this please? It seems like fairly critical functionality. Thank you.

**Comment by singhpaul** [comment]
Hi, could you please provide an update or some context for the delay? Is metabox support essentially being abandoned in favor of blocks? If so it would be good for agency devs to be aware so we can consider alternatives. As it stands, this seems like a fairly significant issue that is being overlooked -- there is essentially no way to ensure data integrity of fields on the sidebar.

**Comment by lgladdy** [comment]
@singhpaul Sorry for the delay here. We'll have this fixed in our next release.

**Comment by singhpaul** [comment]
> @singhpaul Sorry for the delay here. We'll have this fixed in our next release.

That will be amazing, thank you. 

> We're also definitely not abandoning metabox support - it's a big focus of our upcoming releases;

That's wonderful news. ACF metabox functionality has always been at the core of working with WordPress as a CMS and critical to our typical workflow.

**Comment by lgladdy** [comment]
Hey folks! This was resolved in today's ACF 6.3.9 release! Please test and let me know if you have any issues!

**Comment by singhpaul** [comment]
> Hey folks! This was resolved in today's ACF 6.3.9 release! Please test and let me know if you have any issues!

Thanks for this! Very much appreciated. We've done some testing and everything looks good so far. 

One suggestion: when the sidebar is on the Block tab and the user clicks Publish, they correctly receive the "Validation Error..." message but screen focus remains on the Block tab instead. It would be helpful to switch focus automatically in this case to the Post tab since the user has elected to Publish and so would no longer be working on the Block and can then see the fields that require input.
