### ISSUE TITLE
Inner Blocks with ACF

### ISSUE THREAD

**Issue by john-freedman** [AdvancedCustomFields/acf#82]
Is there a way to use acf_register_block() to make Gutenburg blocks that support nesting? (I'm using 5.8.0-beta2) I've been looking at the documentation, trying to figure out a way to do this, but I'm beginning to think that ACF doesn't support InnerBlocks yet. Am I correct? If there is a way, could you perhaps give me a hint as to how to do it? Thanks!

**Comment by elliotcondon** [comment]
Hi @john-freedman 

Thanks for the question. You are correct, ACF Blocks do not support "InnerBlocks". This is becuase ACF Blocks are a "hybrid" between the new React JS and the old PHP api for registering custom fields.

We are in a strange "transition" period at the moment, and won't be able to provide "full" Gutenberg compatibility for quite some time.
