### ISSUE TITLE
Cannot set attachments in relationship fields after recent update

### ISSUE THREAD

**Issue by robrecord** [AdvancedCustomFields/acf#825]
Regression

Since around version 6, it is no longer possible to set an attachment in a Relationship field.

This is because the default post status for attachments, 'inherit', is no longer being recognised by ACF by default.

It's not clear to me where this bug is happening, since normally get_post_stati() does include 'inherit', but certainly by the time it's being used in ACF, several types have been weeded out of the list, included "auto-draft" and "acf-disabled".

A temporary workaround is this (in theme functions.php):

```php
add_filter('acf/get_post_stati', function ($stati) {
  $stati['inherit'] = 'inherit';
  return $stati;
});
```

This is happening on my current website; I will try to determine whether another plugin is causing this and report back if so. Still, the changes introduced do not ensure that attachments can be used in this way, and I believe ACF should ensure this.

**Comment by lgladdy** [comment]
Hey @robrecord, which version of ACF are you running?

This should have been fixed in [6.1.4 last month](https://www.advancedcustomfields.com/changelog/).
