### ISSUE TITLE
ACF calls additional post type and taxonomy database queries on the frontend

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#829]
Hey @mattgrshaw ,

I've noticed there a some new database queries on the frontend called by ACF. It seems this is coming from the brand new ACF post type and taxonomy features. Is that correct?

<img width="1916" alt="Bildschirmfoto 2023-05-11 um 13 42 43" src="https://github.com/AdvancedCustomFields/acf/assets/31563167/f598450e-0a5b-4703-850a-0ee60054e4d6">

I think these queries should not be done on the frontend for performance reasons. Is there a reason why these are not only queried in the backend?

**Comment by lgladdy** [comment]
ACF's AJAX requests will need to know about any post types and taxonomies registered, so the queries will happen anytime the WordPress stack is loaded while enabled.

If you disable ACF's post types and taxonomies feature, they shouldn't be executed anymore.

**Comment by CreativeDive** [comment]
@lgladdy Are these queries only called when we are logged in?

The post type/taxonomy feature is very useful for the most of users. Personally, I've gotten used to doing it myself in code. Therefore I will try to disable it.

**Comment by CreativeDive** [comment]
yes using:

`add_filter( 'acf/settings/enable_post_types', '__return_false' );`

... solves that in this case. Thank you @lgladdy
