### ISSUE TITLE
5.8.0-beta2 Gutenberg image field returns string instead of proper return value

### ISSUE THREAD

**Issue by Toxyc** [AdvancedCustomFields/acf#84]
Hi,

I found out that while using a custom post object as an ACF field, all data is displayed properly except for the image field. Normally you'd expect the image field to return whatever you selected in the ACF field as output. However now it always returns a string with what I assume is the ID of the image object.

``
dump(employee.image)
``
results in
``
string(2) "26"
``

**Comment by elliotcondon** [comment]
Hi @Toxyc 

Thanks for the topic. Your code example doesn't looks like standard PHP. Perhaps you are using a contemplating language such as twig? If so, can you please direct this question to the developers of that contemplating?

**Comment by Toxyc** [comment]
Hi @elliotcondon ,

I think this is more of an ACF issue. 
Normally the fields would be available within the WP_POST object if I'm not mistaken.
``
    object(WP_Post)#9512 (24) {
  ["ID"]=>
  int(117)
  ["post_author"]=>
  string(1) "1"
  ["post_date"]=>
  string(19) "2018-10-31 17:56:07"
  ["post_date_gmt"]=>
  string(19) "2018-10-31 15:56:07"
  ["post_content"]=>
  string(15) "hoi ik ben carl"
  ["post_title"]=>
  string(20) "Name"
  ["post_excerpt"]=>
  string(0) ""
  ["post_status"]=>
  string(7) "publish"
  ["comment_status"]=>
  string(6) "closed"
  ["ping_status"]=>
  string(6) "closed"
  ["post_password"]=>
  string(0) ""
  ["post_name"]=>
  string(4) "carl"
  ["to_ping"]=>
  string(0) ""
  ["pinged"]=>
  string(0) ""
  ["post_modified"]=>
  string(19) "2018-11-02 11:59:55"
  ["post_modified_gmt"]=>
  string(19) "2018-11-02 09:59:55"
  ["post_content_filtered"]=>
  string(0) ""
  ["post_parent"]=>
  int(0)
  ["guid"]=>
  string(56) "https://url.nl/?post_type=employees&p=117"
  ["menu_order"]=>
  int(0)
  ["post_type"]=>
  string(9) "employees"
  ["post_mime_type"]=>
  string(0) ""
  ["comment_count"]=>
  string(1) "0"
  ["filter"]=>
  string(3) "raw"
``

Seeing as my twig templates get the data from the ACF fields, they just format it into a Timber_Post object. Which is almost similar to WP_POST object.

There are 8 fields that should be available within this WP_POST object but they're not showing.

Maybe I'm doing something wrong but the fact remains that in my twig template the image object or array is always a string with an ID.

**Comment by elliotcondon** [comment]
Hi @Toxyc 

Thanks for the reply.
Can you please provide some more information about the "context" of your code.

Where are you running this twig code? Within a block, or within a page template?
ACF doesn't contain any specific code to modify the WP_Post object, so perhaps this is something the twig plugin is doing? It would be great if you can get in touch with the twig WP developers to discuss the issue.

**Comment by Toxyc** [comment]
Hi @elliotcondon ,

I'm using it within a page template. However I found out that I can retrieve the image using employee.get_field('image') which is the name of the field. Normally Timber would add this field as an attribute automatically hence why I was getting the ID instead of the actual response I should have.

employee being a variable rendered from the context within my page template. All other attributes work fine, just not the image object within a post object apparently. I'll reopen this issue on their github and be sure to ask them to fix it.

You can close this issue as it's Timber specific, I apologize for wasting your time.

So for anyone else running into this issue with timber you can call a .get_field('field_name') on the actual post object to get your image.

For relevance: https://github.com/timber/timber
