### ISSUE TITLE
ACF Fields not storing for mixed type - Checkbox

### ISSUE THREAD

**Issue by raguvaranrceo** [AdvancedCustomFields/acf#840]
Hi,
Checkbox field not working properly on rest API. Please find the data format.

**Option Value**
branding_marketing : Branding & Marketing
changemakers : Changemakers
Entertainment
Technology

The above option have 2 different format. One has with keys and other ones without keys. The without keys are not getting updated. Could you please check it

**Comment by raguvaranrceo** [comment]
I have raised similar issue previously 
https://github.com/AdvancedCustomFields/acf/issues/830

**Comment by lgladdy** [comment]
@raguvaranrceo This isn't supported I'm afraid, and causes errors outside of the REST API too.

You need to use either fully key choices, or not at all. A mix will only end up supporting either the values with keys.
