### ISSUE TITLE
Theme check plugin shows many warning 

### ISSUE THREAD

**Issue by latheeshvm** [AdvancedCustomFields/acf#85]
I have included the plugin in my theme . I am using pro version. The theme is rejected because of theme check plugin errors. 

Please suggest what to do . Details below

Theme check plugin shows many warning 

WARNING: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are  **acf, min**` how to fix this?

WARNING: Found remove_filter( in the file class-acf-field-wysiwyg.php. Themes should not remove core filters. Ensure this is a valid use case.
Line 269: remove_filter( 'acf_the_editor_content', 'format_for_editor', 10, 2 );
Line 270: remove_filter( 'acf_the_editor_content', 'wp_htmledit_pre', 10, 1 );
Line 271: remove_filter( 'acf_the_editor_content', 'wp_richedit_pre', 10, 1 );
WARNING: Found remove_filter( in the file api-term.php. Themes should not remove core filters. Ensure this is a valid use case.
Line 201: remove_filter('terms_clauses', '_acf_terms_clauses', 10, 3);
WARNING: Found remove_filter( in the file api-helpers.php. Themes should not remove core filters. Ensure this is a valid use case.
Line 1600: //remove_filter('query', '_acf_query_remove_post_type');
Line 1742: remove_filter('posts_orderby', '_acf_orderby_post_type', 10, 2);
Line 619: <li><a href='<?php echo esc_url( $url_home ); ?>' target='_blank'><?php echo $icon; ?> <?php _e('Website','acf'); ?></a></li>
Line 620: <li><a href='<?php echo esc_url( $url_home . '/resources/' ); ?>' target='_blank'><?php echo $icon; ?> <?php _e('Documentation','acf'); ?></a></li>
Line 621: <li><a href='<?php echo esc_url( $url_support ); ?>' target='_blank'><?php echo $icon; ?> <?php _e('Support','acf'); ?></a></li>
Line 623: <li><a href='<?php echo esc_url( $url_home . '/pro/' ); ?>' target='_blank'><?php echo $icon; ?> <?php _e('Pro','acf'); ?></a></li>
WARNING: Found echo $ in the file admin-field-group.php. Possible data validation issues found. All dynamic data must be correctly escaped for the context where it is rendered.
Line 391: $('#post-status-display').html('<?php echo $status; ?>');
WARNING: Found add_meta_boxes in the file third-party.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 36: add_action('tabify_add_meta_boxes',		array($this, 'tabify_add_meta_boxes'));
Line 110: *  tabify_add_meta_boxes
Line 122: function tabify_add_meta_boxes( $post_type ) {
WARNING: Found add_meta_boxes in the file form-comment.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 113: add_action('add_meta_boxes_comment', 	array($this, 'edit_comment'), 10, 1);
WARNING: Found add_meta_box in the file third-party.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 36: add_action('tabify_add_meta_boxes',		array($this, 'tabify_add_meta_boxes'));
Line 110: *  tabify_add_meta_boxes
Line 122: function tabify_add_meta_boxes( $post_type ) {
Line 139: add_meta_box( $id, $title, '__return_true', $post_type );
WARNING: Found add_meta_box in the file form-post.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 203: add_meta_box( $id, $title, array($this, 'render_meta_box'), $this->typenow,
Line 290: extract( $args ); // all variables from the add_meta_box function
WARNING: Found add_meta_box in the file form-comment.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 113: add_action('add_meta_boxes_comment', 	array($this, 'edit_comment'), 10, 1);
WARNING: Found add_meta_box in the file admin-tools.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 248: add_meta_box( 'acf-admin-tool-' . $tool->name, $tool->title, array($this, '
WARNING: Found add_meta_box in the file admin-options-page.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 200: add_meta_box('submitdiv', __('Publish','acf'), array($this, 'postbox_submit
Line 237: add_meta_box( $id, $title, array($this, 'postbox_acf'), 'acf_options_page',
Line 297: extract( $args ); // all variables from the add_meta_box function
WARNING: Found add_meta_box in the file admin-field-group.php. Custom meta box functions are allowed for design only. Ensure this is a valid use case.
Line 202: add_meta_box('acf-field-group-fields', __('Fields','acf'), array($this, 'mb
Line 203: add_meta_box('acf-field-group-locations', __('Location','acf'), array($this
Line 204: add_meta_box('acf-field-group-options', __('Settings','acf'), array($this, 
WARNING: Found ($_SERVER in the file api-helpers.php. PHP Global Variable found. Ensure the context is safe and reliable.
Line 3609: $url = home_url($_SERVER['REQUEST_URI']);
WARNING: fwrite was found in the file json.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 229: fwrite($f, acf_json_encode( $field_group ));
WARNING: fopen was found in the file json.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 228: $f = fopen('{$path}/{$file}', 'w');
WARNING: file_get_contents was found in the file settings-info.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 151: $readme = file_get_contents( acf_get_path('readme.txt') );
WARNING: file_get_contents was found in the file json.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 155: $json = file_get_contents('{$path}/{$file}');
WARNING: file_get_contents was found in the file class-acf-admin-tool-import.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 129: $json = file_get_contents( $file['tmp_name'] );
WARNING: fclose was found in the file json.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.
Line 230: fclose($f);
REQUIRED: Found mkdir( in the file wpml.php. mkdir() is not allowed. Use wp_mkdir_p() instead.
Line 192: mkdir($path, 0777, true);
REQUIRED: Found is_plugin_active( in the file updates.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.
Line 65: // Check if is_plugin_active() function exists. This is required on the front end of th
Line 72: if( is_plugin_active($plugin['basename']) ) {
REQUIRED: Found is_plugin_active( in the file updates.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.
Line 51: if( !acf_is_plugin_active() ) return;
REQUIRED: Found is_plugin_active( in the file html-notice-upgrade.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.
Line 8: if( is_plugin_active('acf-repeater/acf-repeater.php') ) $plugins[] = __('Repeat
Line 9: if( is_plugin_active('acf-flexible-content/acf-flexible-content.php') ) $plugin
Line 10: if( is_plugin_active('acf-gallery/acf-gallery.php') ) $plugins[] = __('Gallery'
Line 11: if( is_plugin_active('acf-options-page/acf-options-page.php') ) $plugins[] = __
REQUIRED: Found is_plugin_active( in the file api-helpers.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.
Line 4648: function acf_is_plugin_active() {
Line 4654: // ensure is_plugin_active() exists (not on frontend)
Line 4663: return is_plugin_active($basename);
REQUIRED: Found is_plugin_active( in the file admin-settings-updates.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.
Line 158: if( !acf_is_plugin_active() ) return;
REQUIRED: Found base64_encode in the file updates.php. base64_encode() is not allowed.
Line 211: $value = base64_encode(maybe_serialize($data));
REQUIRED: Found base64_encode in the file api-helpers.php. base64_encode() is not allowed.
Line 5137: if( !function_exists('openssl_encrypt') ) return base64_encode($data);
Line 5153: return base64_encode($encrypted_data . '::' . $iv);
REQUIRED: Found base64_decode in the file updates.php. base64_decode() is not allowed.
Line 134: $license = maybe_unserialize(base64_decode($license));
REQUIRED: Found base64_decode in the file api-helpers.php. base64_decode() is not allowed.
Line 5175: if( !function_exists('openssl_decrypt') ) return base64_decode($data);
Line 5183: list($encrypted_data, $iv) = explode('::', base64_decode($data), 2);
REQUIRED: Found alt="" in the file class-acf-field-gallery.php. Do not leave attributes empty.
Line 539: <img src='<?php echo $thumbnail['url']; ?>' alt='' title='<?php echo $a['title']; ?>'/>
REQUIRED: Found alt="" in the file class-acf-field-file.php. Do not leave attributes empty.
Line 134: <img data-name='icon' src='<?php echo esc_url($o['icon']); ?>' alt=''/>
REQUIRED: Found alt="" in the file api-helpers.php. Do not leave attributes empty.
Line 4376: $data['html'] = '<img src='' . $data['url'] . '' alt='' />';

**Comment by elliotcondon** [comment]
Hi @latheeshvmv

Thanks for the topi.c

It looks like these warnings are trivial, and mainly related to un-escaped variable printing.
There are cases when escaping such variables is unnecessary.

It is stange that the theme checker has found 2 text domains. Did it provide any information on where this second "min" textdomain exists in the plugin files?

**Comment by latheeshvmv** [comment]
Hello thanks for the response.  i am not sure where min is may be in these lines ?
acf\includes\fields\class-acf-field-number.php:

`// min
  235: 		if( is_numeric($field['min']) && $value < floatval($field['min'])) {
  236  			
  237: 			$valid = sprintf(__('Value must be equal to or higher than %d', 'acf'), $field['min'] );
  238  			
  239  		}`

**Comment by elliotcondon** [comment]
Thanks for the info.

**min textdomain**
I don't see any issue in these lines. The __() function is being used correctly here. Perhaps the theme checker is reporting a false positive result?

**Found base64_decode in the file updates.php. base64_decode() is not allowed.**
This is a fallback functionality if the `openssl_decrypt()` function does not exist. In 99% of servers, the `openssl_decrypt()` function will work as expected.

**Found alt="" in the file api-helpers.php. Do not leave attributes empty.**
That's true. I'll get that fixed

**Found is_plugin_active( in the file admin-settings-updates.php. is_plugin_active() is not reliable. Use function_exists() or class_exists() instead.**
Not true. The `is_plugin_active()` function is definitely included when viewing the admin dashboard.

*fclose was found in the file json.php File operations should use the WP_Filesystem methods instead of direct PHP filesystem calls.*
Fair point. I'm happy to improve this code to use the WP_Filesystem instead of PHP functions.

**Comment by latheeshvmv** [comment]
Hi any update on this

**Comment by elliotcondon** [comment]
Hi @latheeshvmv. No update on this. All attention is on the WordPress 5.0 release.

**Comment by latheeshvmv** [comment]
Hello @elliotcondon okay i am also excited for it i dont want to trouble you guys :).. is there any beta available for it ? Any plans to make the inclusion of plugin to theme as per envato standards?  Like TGM plugin did.

**Comment by elliotcondon** [comment]
Hi @latheeshvmv. Yes, 5.8.0 is available in beta: https://www.advancedcustomfields.com/blog/acf-pro-5-8-0-beta3/
