### ISSUE TITLE
Subject: Bug Report - ACF Conditional Rendering Issue

### ISSUE THREAD

**Issue by amirtabatabaei69** [AdvancedCustomFields/acf#852]
Bug Description:
I have encountered two issues with the ACF plugin. Firstly, the conditional rendering feature is causing content loss when switching between options in a select field within a flexible content layout. Secondly, when reordering the blocks, the content also gets lost.

Steps to Reproduce:

Issue 1 - Conditional Rendering:

Edit the content for "Option A" in the select field.
Save the changes and refresh the page.
Select "Option B" in the select field.
Edit the content for "Option B."
Save the changes and refresh the page.

Issue 2 - Block Reordering:

Edit the content for a block.
Attempt to reorder the blocks within the flexible content layout.
Save the changes and refresh the page.

**Comment by lgladdy** [comment]
Hey @amirtabatabaei69,

Could you confirm your ACF and WordPress Versions, Browser type and send us a JSON export of the affected field groups so we can try to reproduce? Thanks!

**Comment by amirtabatabaei69** [comment]
Hi @lgladdy ,

thank you for your response. unfortunately i dont have the fields anymore as i changed the logic to resolve the problem. i closed the issue.
