### ISSUE TITLE
Wrong CSS path generated from block.json

### ISSUE THREAD

**Issue by AlkoKod** [AdvancedCustomFields/acf#860]
Not sure if it can be related to the  ACF or Bricks child theme, but I will try to ask.

I am trying to use the ACF Blocks with Bricks Builder child theme - I am trying good, but I encountered strange errors in backend, where CSS files are not being loaded correctly.

I have found that when I register style with block with this code:
`"style": [ "file:./partners_testimonials.css" ],`

It doesn't load the style correctly. I have the structure of theme:

https://novy.spssecb.cz/wp-content/themes/bricks-child/blocks/partners_testimonials/partners_testimonials.css

But it still loads it wrong:

https://novy.spssecb.cz/wp-content/themes/bricks/-child/blocks/partners_testimonials/partners_testimonials.css

Which doesn't work. Any Ideas why it breaks the url in the theme name? or is it fine? I have a lot of blocks and I want my backend to be styled... AAAnd its completely fine on frontend.

![image](https://github.com/AdvancedCustomFields/acf/assets/52713604/50fba4a6-9ad3-4255-8390-db88f50f3719)
![image](https://github.com/AdvancedCustomFields/acf/assets/52713604/38d2c525-02bd-4c19-b6f6-533a35dde36b)

EDIT: I have found similiar question on the forum, but with other URL's being generated: https://support.advancedcustomfields.com/forums/topic/acf-blocks-with-block-json-generates-wrong-css-file-url/

**Comment by lgladdy** [comment]
@AlkoKod Heya, this is this bug in WordPress: https://core.trac.wordpress.org/ticket/59018

We actually contributed the patch to fix this, and it will be in 6.3.1! For now, you can rename your theme folder to not start the same way as the parent theme to fix it, or apply the patch manually from trac.

**Comment by AlkoKod** [comment]
> 

Damn, you are good! Thanks!
