### ISSUE TITLE
Fatal error after adding a new field group with ACF 6.2.1

### ISSUE THREAD

**Issue by CreativeDive** [AdvancedCustomFields/acf#872]
Hey,

after updating to 6.2.1 I received this fatal error after adding a new field group:

<img width="654" alt="Bildschirmfoto 2023-09-08 um 17 25 50" src="https://github.com/AdvancedCustomFields/acf/assets/31563167/1b46f3ff-3b7c-4f0b-b983-8860cf953918">

**Comment by CreativeDive** [comment]
The reason for this is because I use:
 
`add_filter( 'acf/settings/enable_options_pages_ui', '__return_false' );`

**Comment by mattgrshaw** [comment]
Thanks for the report @CreativeDive, we'll get this fixed up in the next release.

**Comment by mattgrshaw** [comment]
Thanks again @CreativeDive - we've released ACF PRO 6.2.1.1 which has a fix for this issue.
