### ISSUE TITLE
Editing field groups when Gutenberg is enabled

### ISSUE THREAD

**Issue by studioraygun** [AdvancedCustomFields/acf#88]
When browsing Field Groups each group has `Edit | Edit (classic editor)` same as posts, pages etc, but when clicking `Edit` (not the classic editor) you get a white screen of death. Presumably this is a Gutenberg-related issue.

Gutenberg 4.5
ACF Pro 5.7.7

**Comment by nick6352683** [comment]
It is... I reported it here - https://wordpress.org/support/topic/gut-4-5-needs-to-add-a-fallback-for-cpts-that-do-not-have-rest-api-activated/#post-10902098

and Elliot here - https://github.com/WordPress/gutenberg/issues/12148

**Comment by nick6352683** [comment]
Update: Issue fixed with Gutenberg 4.5.1 emergency patch...
