### ISSUE TITLE
Presence of fields on a post type breaks iframe editor, even when fields are positioned to the side

### ISSUE THREAD

**Issue by ericestes** [AdvancedCustomFields/acf#892]
The requirements for the iframe editor are all registered blocks use API v3 and no classic metaboxes sit below the editor. But even when this is the case, having an ACF field group attached to a post type still breaks the iframe editor. This occurs even when those fields are configured to be positioned to the side of the editor, not below.

**Comment by lgladdy** [comment]
Hey there,

This is a decision by WordPress - when any legacy meta boxes are used, the iframe editor is disabled.

We have a longer-term project planned to replace our use of the legacy meta box, but we're still very early in conversation with the Gutenberg devs to build a place for content too wide for the sidebar to live.

I'm going to close this issue this isn't an ACF bug, but thanks for raising it!
