### ISSUE TITLE
Block fields now show in the right hand side panel

### ISSUE THREAD

**Issue by mikebhart** [AdvancedCustomFields/acf#899]
**Describe the bug**
I used to be able to edit fields in the block.  Now all the block fields are listed in the right hand side panel.

**To Reproduce**
Go to edit page and select a block.

**Screenshots or Video**
<img width="1783" alt="image" src="https://github.com/AdvancedCustomFields/acf/assets/19751493/4a562bc8-75cb-4925-b50a-8db2a021dee2">

reproduce the issue.

**Version Information:**
 - WordPress Version Version 6.5-beta2
 - PHP Version 8.2
 - ACF Version ACF PRO 6.2.1
 - Browser Chrome Version 121.0.6167.189 (Official Build) (64-bit)

**Comment by lgladdy** [comment]
Hey @mikebhart,

We're aware of this issue and it will be fixed shortly. It's an upstream bug in WordPress we're hoping they'll merge before beta 3 tomorrow: https://github.com/WordPress/gutenberg/pull/59105

Thanks!
Liam
