### ISSUE TITLE
ACF 6.3.0 update breaks "No fields assigned" filter with empty string

### ISSUE THREAD

**Issue by cabrailsford** [AdvancedCustomFields/acf#910]
**Describe the bug**
When updating to 6.3.0, I selected an existing ACF block that has no fields assigned to it. I am using the `no_fields_assigned_message` filter to return an empty string, which simply output nothing below the title & description before the update. Now it shows a constant spinner, and an error in the console of `Cannot read properties of undefined (reading 'data')`.

**To Reproduce**
1. Assign `add_filter( 'acf/blocks/no_fields_assigned_message', '__return_empty_string' );` in theme/plugin.
2. Go to any post or page with an ACF block that has no fields.
3. Click on the block to select it.
4. Check the block sidebar under the title.
5. See the spinner.
6. Open the web inspector console.
7. See error.

**Expected behavior**
Using the `acf/blocks/no_fields_assigned_message` filter with `__return_empty_string` should not show anything under the block title/description, nor produce errors in the console.

**Screenshots or Video**
Here is a [video](https://share.zight.com/o0uLq4Yq) showcasing 2 identical blocks, one of which has a custom field assigned to it, while the other does not.

**Code**
[block.json](https://github.com/AdvancedCustomFields/acf/files/15437428/block.json)

render.php
```<?php
/**
 * ACF Test Block 2
 *
 * @package ACFTest
 **/

echo '<div>This is a test block 2</div>';
```
functions.php
```
add_filter( 'acf/blocks/no_fields_assigned_message', '__return_empty_string' );
```

**Version Information:**
 - WordPress Version: 6.5.3
 - PHP Version: 8.1.23
 - ACF Version: ACF Pro 6.3.0.1
 - Browser: Chrome 124

**Comment by cabrailsford** [comment]
@lgladdy @polevaultweb Following up on this, it appears the changes you pushed for 6.3.1 resolved the issue above. 

The only request I have now is if it would be feasible to remove the padding and border applied to the empty fields section, as shown in [this screenshot](https://share.zight.com/E0uej1zG). Thanks!

**Comment by lgladdy** [comment]
Hey @cabrailsford,

Turns out, we had to ship a 6.3.1.2 tonight for a bug with blocks on widgets, so I was able to slip this fix in there too.

Can you confirm that's good for you now?

**Comment by cabrailsford** [comment]
@lgladdy That seems to have done the trick! Thanks for all the hard work, it's greatly appreciate
