### ISSUE TITLE
Can't add ACF licence key

### ISSUE THREAD

**Issue by LoriWJ** [AdvancedCustomFields/acf#911]
**Describe the bug**
Can't add a new ACF licence key so am unable to run the plugin update.

**To Reproduce**
1. Add a new ACF licence key to the field in the ACF updates area.
2. Select “Activate Licence”.
3. An error message is displayed saying, “Error. Could not connect to update server.”

**Expected behavior**
The licence should be activated.

**Version Information:**
 - WordPress 6.5.3
 - PHP 7.4
 - ACF PRO 5.5.8
 - Chrome 125.0.6422.112

**Comment by lgladdy** [comment]
Hey Lori,

Because you're on such an old version of ACF, you'll need to go ahead and manually download the plugin from your account and manually upgrade.

Please contact our support team, support@advancedcustomfields.com if you need any further help.

Thanks!
Liam
