### ISSUE TITLE
update_field() not working as expected in this scenario

### ISSUE THREAD

**Issue by alexsoluweb** [AdvancedCustomFields/acf#913]
### Issue Description

**Steps to Reproduce:**
1. Create two identical field groups with the same names and fields embedded in groups.
2. Assign each field group to a different taxonomy within a post type.
3. For example, let's have a group named `foo` and a subfield named `bar` with the field key `field_12345`.

**Expected Behavior:**
- When calling `update_field('foo_bar', $value, $postId, $field_group_key)`, the function should accept a extra parameter to update the field in the appropriate group.
- When calling `update_field('field_12345', $value, $postId)`, the function should correctly identify and update the right meta key.

**Actual Behavior:**
- The call `update_field('foo_bar', $value, $postId)` updates the first field group it finds.
- The call `update_field('field_12345', $value, $postId)` does not work as expected. It triggers `wp_update_meta('post', $post_id, 'bar', $value)` instead of the correct meta key, causing an update to the wrong meta key.

**Detailed Description:**

When creating two field groups with identical names and fields, but different display conditions based on taxonomies, the `update_field` function exhibits unexpected behavior. Specifically, using the field key to update a field results in an incorrect meta key update. This issue seems to stem from the way `update_field` resolves field keys and meta keys.

Also, there is a lack to specify the right fields group in this circumsistence.

### Steps to Reproduce Code Example

1. Create two field groups:
   - Group 1: `foo` with a subfield `bar` (key: `field_12345`) assigned to Taxonomy A.
   - Group 2: `foo` with a subfield `bar` (key: `field_12345`) assigned to Taxonomy B.

2. Use the following code to update the field values:
   ```php
   // This should have an option to specify which field_group we want to save
   update_field('foo_bar', $value, $postId);
   
   // This should update the field with the field key
   update_field('field_12345', $value, $postId);

### Observed Issue

- `update_field('foo_bar', $value, $postId)` updates the first matching group correctly.
- `update_field('field_12345', $value, $postId)` incorrectly triggers `wp_update_meta('post', $post_id, 'bar', $value)`, leading to an update with the wrong meta key.

### Suggested Solution

Review and refine the logic within `update_field` to ensure it correctly resolves field keys to the appropriate meta keys, considering the field group option.

### Environment

- WordPress Version: 6.5.3
- ACF Version: 6.3.0.1
- PHP Version: 7.4

Thank you for your attention to this issue. Looking forward to your response and potential resolution.

**Comment by lgladdy** [comment]
Hey there,

Updating sub fields via update_field is not supported. You'll need to update the parent field with a full array of the sub fields.

Alternatively, if you're looking to loop over each sub field to update it you can use update_sub_field inside an ACF loop.

If you'd like to raise a feature request for a new function or additional parameter to update_field, your best bet for that is to use our feedback board at https://www.advancedcustomfields.com/feedback - as that's where we collate upvotes which influences our product roadmap.

Cheers!
Liam

**Comment by alexsoluweb** [comment]
The acf_form output is wrong when outputting both fields group, 1 form will get the field_key of the other... There is actually something wrong going on.
