### ISSUE TITLE
Group: image subfield n°10 not working

### ISSUE THREAD

**Issue by eur2** [AdvancedCustomFields/acf#918]
I have a Group field with 10 image subfields:
<img width="1142" alt="Capture d’écran 2024-06-18 à 11 20 15" src="https://github.com/AdvancedCustomFields/acf/assets/28712725/f73d3d8d-598f-4946-b3d9-28da2d34abc7">

The image subfield number 10 is not working. When I add the image and update the post, the post is published but this field remains with no image selected:
<img width="141" alt="Capture d’écran 2024-06-18 à 11 26 27" src="https://github.com/AdvancedCustomFields/acf/assets/28712725/f5311a5f-3faa-47df-a3b6-f610540f14d2">

**Version Information:**
 - WordPress Version 6.5.4
 - PHP Version 8.3.0
 - ACF Free 6.3.1
 - Browser Chrome 126

**Additional context**

**Comment by lgladdy** [comment]
Hey there,

For reports like this, please contact our support team - support@advancedcustomfields.com, they'll work with you to understand the issue and if necessary raise a technical bug report to us.

Thanks!
Liam
