### ISSUE TITLE
PLEASE ADD A DISCLAIMER THAT SHORTCODES HAVE TO BE ENABLED NOW

### ISSUE THREAD

**Issue by hugo749** [AdvancedCustomFields/acf#919]
PLEASE ADD A DISCLAIMER THAT SHORTCODES HAVE TO BE ENABLED NOW

Would be great, like this other people not spend 1h to try to understand why nothing is working. We've been using ACF for years then a new "feature" is released without any disclaimer or something.

Thank you.

**Comment by lgladdy** [comment]
Hey Hugo,

We've added this to all our documentation and the release notes, it's also present in ACF's section in Site Health.

That said, please raise this request on our [feedback board](https://www.advancedcustomfields.com/feedback). This GitHub repo is only for technical bug reports.

Thanks,
Liam
