### ISSUE TITLE
Field not saved in ACF 5.8.0-beta3 in Gutenberg editor

### ISSUE THREAD

**Issue by briggySmalls** [AdvancedCustomFields/acf#93]
The new ACF beta release (5.8.0-beta3) seems to have introduced a regression when compared with v5.8.0-beta2). ACF fields positioned to "Side" cannot be saved in the Gutenberg editor. The field will work as expected if any of the following are changed:

- Position is set to 'below content'
- Editor is switched to 'classic'

Note: if the field is already populated from a previous assignment then it is displayed unchanged.

Steps to reproduce:
- Install Gutenberg
- Install ACF 5.8.0-beta3
- Create custom fields for a post, and position in Side
- Observe how field is not saved for a new post
- Replace ACF with v5.8.0-beta2
- Observe how field _is_ saved on a new post

I have seen the same behaviour with the following setup:
- Wordpress 4.9.8
- Gutenberg 4.5.1

Issue originally created from an issue in an [ACF forum thread](https://support.advancedcustomfields.com/forums/topic/acf-not-saving-fields-with-gutenberg/#post-73377). The key information is:

> Update: In my case it successfully saves the page when you place the ACF fields after content. Saving fails only when you place ACF fields aside the content.
> That helps a lot, so I can at least continue with my project. But placing ACF aside would be way more comfortable to use…
> So I´m really looking forward for a solution

**Comment by briggySmalls** [comment]
Apologies to anyone who may have been reviewing/working on this. I mistakenly thought this was to do with `mu-plugin` vs `plugin`, as this was a difference between my dev/staging environments (one worked the other didn't).

However it turns out that once I upgraded my one environment to beta3 it behaved the same as the other. It doesn't matter whether it is a must-use plugin or not.

**Comment by marianfeiler** [comment]
Any news in this case?

**Comment by Novalis80** [comment]
i have the same bug on wp 5.0.2 and acf 5.7.9. i am not sure if it was introduced with wp or acf, since i updated at same time.

**Comment by Novalis80** [comment]
i did a rollback to 5.7.8 and it works again.

**Comment by elliotcondon** [comment]
Hi @Novalis80 

Can you please spin up a fresh WP 5.0.2 install with ACF and try to replicate the issue?

**Comment by Novalis80** [comment]
i happily put it on my todo list. i am not sure if i find time this week.

**Comment by sito** [comment]
I'm facing the same problem using WP 5.0.3 and ACF 5.7.9.
Tried to downgrade ACF and also to change the placement (as suggested fix) but none has worked.

**Comment by elliotcondon** [comment]
Hi @sito 

Thanks for the +1.
Can you please provide the exact steps to replicate the issue? 
This will help me find the problem as fast as possible.

**Comment by gio00** [comment]
Same problem here:
ACF Version 5.7.10
Gutenberg 4.9.0
Wordpress 5.0.3

Using a simple text field visible only in pages, appears at the bottom after the Gutenberg editor. Saving the page doesn't seem to save the field.

**Comment by elliotcondon** [comment]
Hi @gio00 

Thanks for the reply. You mentioned that you have the Gutenberg plugin installed and also WP 5.0.3.
Please note that WP 5.0+ includes the new Gutenberg editor, so perhaps you have a conflict by including the plugin also? Can you please confirm this?

**Comment by dekode-rasmus** [comment]
This seems to be fixed in version 5.7.10 according to the changelog: https://www.advancedcustomfields.com/blog/acf-5-7-10-release/

**Comment by briggySmalls** [comment]
After a long hiatus, I've returned to my wordpress project and done some upgrading. With:

- Wordpress 5.1.1
- ACF Pro 5.8.0-RC2

The issue is fixed for me.

**Comment by dekode-rasmus** [comment]
Still there in 5.7.13. We just got a ticket from a client reporting this exact issue.

**Comment by Novalis80** [comment]
i believe it is totally an upgrade failure. on a clean install it seams to work.

**Comment by briggySmalls** [comment]
> so perhaps you have a conflict by including the plugin also? Can you please confirm this?

I had this issue come back and it was indeed because I had an old version of Gutenberg installed.

**Comment by manuel-84** [comment]
same issue with latest gutenberg plugin and acf

**Comment by nick6352683** [comment]
@manuel-84 - I am getting the message that is not saved too, but if I view my page on the frontend, the block fields are actually saved. So, it's a false message. With the latest Gutenberg version, this happens to not only ACF created blocks, but even with the core blocks. To stop the messages, ACF Pro must be deactivated, which of course, is not an option...

**Comment by manuel-84** [comment]
In my case the first save works but after this the interface (update
button) is freezed into updating state and you need to reload the page to
save again, and this is bad

Il sab 31 ago 2019, 19:45 Nick DerAvedissian <notifications@github.com> ha
scritto:

**Comment by nick6352683** [comment]
@manuel-84 - I had opened a new issue as this is actually a closed one, 3 days ago, but Elliot has not responded yet... I feel sorry for him, Gutenberg constantly throws all sorts of things at him, almost constantly - https://github.com/AdvancedCustomFields/acf/issues/218 - and to be honest, I'm not sure if this is easily fixable with ACF, or the Gutenberg plugin has to patched up...

**Comment by bublick** [comment]
I have same problems only in production. And this is really worse.
