### ISSUE TITLE
Wordpress 5.0 Update - Fieldgroups Bug again

### ISSUE THREAD

**Issue by kuse-de** [AdvancedCustomFields/acf#95]
Hi Elliot,

the Fieldgroups are not showing up correctly again after upgrading to 5.0:

- My Fieldgroups are all Connected to different Taxonomys (Layouts) and should show up when  the Taxonomy is selected
- Some Fieldgroups are shown when the Taxonomy is selected, some are not 
- Assigning it to Post directly doesnt work too
- Different Settings like "show after titel or after content" dont affect it
- Activating the Gutenberg Plugin in WP 5.0 will lead to other fieldgroups show up and some others dont
- Rollback to 4.9 isnt resolving the issue i guess its because of Database changes
- Tested Versions (Recent, Beta2, Beta3)

Only chance atm was to go back to a clean 4.9 installation if you need more Information / Screenshots let me know. Would be great if you could post a hotfix if you dont plan to release a new fixed beta version i got all my pages on Auto Major Upgrade and it would be very nice if i can hotfix them within next week

Greetings
Pierre

Edit: Ive seen your post in the Gutenberg Repo, is it possible to downgrade the Gutenberg Plugin inside WP 5.0 to make it work again? And if yes which version would u suggest? Thanks for help :)

**Comment by elliotcondon** [comment]
Hi Pierre

Thanks for posting, but please know this is not the place for support. Please contact our support team here and they will be able to provide help: https://www.advancedcustomfields.com/contact/
