### ISSUE TITLE
Wordpress 5.0 + Q-Translate: Fields not updating and not showing in Front-end

### ISSUE THREAD

**Issue by oieusouamiguel** [AdvancedCustomFields/acf#97]
## Description

- The first is that fields don't save in Wordpress admin. I make the changes in the Wysiwyg editor within the page that I created, I give Update and the changes don't appear when reloading the editing of the page in the admin. I thought it would be a problem with the Database, but there are more than 10,000 fields entries with the same names that I put in each of the fields (152 fields) in DS.

- Another problem is that I created a new group of fields and some fields of the same don't reflect on the Front-end. In the database, the old fields are as `'laboral-table-row-1-text-1'` and the new fields as `'lab-table-row-1-text-1'`.

I tried to find something that fixes this on the internet, but I didn't find anything about it.

## I'm using:

- Wordpress: 5.0
- ACF Pro: 5.7.7
- QTranslate-X: 3.4.6.8

**Comment by elliotcondon** [comment]
Hi @oieusouamiguel

Thanks for the bug report. Please note this GitHub repository is not the pace for bug reports.
If you can, please submit a ticket to our support team here: https://www.advancedcustomfields.com/contact/
