### ISSUE TITLE
Wordpress 5.0 + Q-Translate-X: Wysiwyg editor bug

### ISSUE THREAD

**Issue by oieusouamiguel** [AdvancedCustomFields/acf#98]
## Description
-  Wysiwyg editor isn't working. When I try to edit something in Visual mode, the tab does not work to switch the preview from Text to Visual.

![hello](https://user-images.githubusercontent.com/20358128/49703990-edcc1600-fbf3-11e8-813f-514fdf08bcf3.gif)

## I'm using:

- Wordpress: 5.0
- ACF Pro: 5.7.7
- QTranslate-X: 3.4.6.8

**Comment by elliotcondon** [comment]
Hi @oieusouamiguel 

Thanks for the bug report. Please note this GitHub repository is not the pace for bug reports.
If you can, please submit a ticket to our support team here: https://www.advancedcustomfields.com/contact/

**Comment by arku31** [comment]
Hi @elliotcondon 
First, thanks for the really awesome plugin but your answer is not really community friendly. What's the state of the bug? Does it even on ACF side?
